opengisch/QField

- src/coordinatetransform.cpp
- src/distancearea.cpp
Read: the method has been removed.
> QgsDatumTransform no longer needs to be initialized

- src/qml/editorwidgets/ValueMap.qml
Instead of QMap because it's stored since 3.0 as QList in config('map').
Means it needed another loop to get all the data for the checkbox and some changes because the structure is slightly different. 
This change only makes sense when this is merged: https://github.com/qgis/QGIS/pull/6091
Possible that we could make some parts more elegant. I was not sure about everything but it works now perfectly with QGIS 2.18 and QGIS 3.00 projects.
> Open the valuemap data as QList

- android/src/ch/opengis/qfield/QFieldActivity.java
- src/androidplatformutilities.cpp
- src/androidplatformutilities.h
- src/main.cpp
That's where our srs.db should be... hopefully...
fix #192
> Set package path based on unzip path

- src/qml/editorwidgets/TextEdit.qml
> Fix 0 representation in TextEdit widget

- src/qml/DigitizingToolbar.qml
- src/qml/qgismobileapp.qml
- src/rubberband.cpp
- src/rubberband.h
- src/rubberbandmodel.cpp
- src/rubberbandmodel.h
- src/sgrubberband.cpp
- src/snappingutils.cpp
* saving does not add a point
* freeze rubber band while form is open
> digitizing improvements

- src/qgsquickmapcanvasmap.cpp
- src/qgsquickmapcanvasmap.h
only cosmetic before integrating deeper changes
> format MapCanvas along with QgsQuick

- src/qml/qgismobileapp.qml
> Attribute form as a drawer

- src/coordinatetransformer.cpp
- src/coordinatetransformer.h
- src/qml/PositionInformationView.qml
- src/qml/TransformedPositionSource.qml
>  format CoordinateTransformer along with QgsQuick

- android/AndroidManifest.xml
> Update targetSdkVersion to 26

- src/main.cpp
> Fix package data path for srs.db

- i18n/qfield_fr.ts
> Update French translation

- .travis.yml
> Update SDK for setuid free qca

- src/core/qgismobileapp.cpp
- src/qml/PositionInformationView.qml
- src/qml/TransformedPositionSource.qml
missing import of Utils
fix Position Information View (using GeoPosition)
register missing transform context
> [fix #379] fix broken GPS

- android/AndroidManifest.xml
- android/build.gradle
- src/core/androidplatformutilities.cpp
- src/core/androidplatformutilities.h
- src/core/platformutilities.cpp
- src/core/platformutilities.h
- src/qml/editorwidgets/ExternalResource.qml
- src/qml/qgismobileapp.qml
- test/test.pro
- test/test_vertexmodel.cpp
Fix #304
Request permissions at runtime if they are not granted but required.
> Update target sdk to version 26

- android/src/ch/opengis/qfield/FileUtils.java
- android/src/ch/opengis/qfield/QFieldActivity.java
- android/src/ch/opengis/qfield/QgsDocumentsProvider.java
- Scan every external root dir to generate Qgs file provider list
- Use a better way to guess real file path from documents provider uri
> File selector sd-card

- qfield.pri
- src/core/featureslocatorfilter.cpp
- src/core/featureslocatorfilter.h
porting of https://github.com/qgis/QGIS/pull/8650
> avoid freeze when searching over too many layers

- src/qml/OverlayFeatureFormDrawer.qml
- src/qml/qgismobileapp.qml
> [fix #407] feature form not correctly set on second time 

- .travis.yml
- src/core/featureslocatorfilter.cpp
- src/core/locatormodelsuperbridge.cpp
- src/core/locatormodelsuperbridge.h
- src/core/qgismobileapp.cpp
- src/qml/DigitizingToolbar.qml
- src/qml/LocatorItem.qml
- src/qml/NavigationBar.qml
- src/qml/qgismobileapp.qml
depends on https://github.com/qgis/QGIS/pull/8667
> fixes for geometry less layers

- src/qml/DashBoard.qml
- src/qml/qgismobileapp.qml
also move QML code into specific file to avoid overwhelming main QML
> put DashBoard on top of of search item

- src/qml/PositionInformationView.qml
- src/qml/ScaleBar.qml
- src/qml/qgismobileapp.qml
> Redesign of scale bar and info window

- src/qml/PositionInformationView.qml
> Unify font size

- .travis.yml
with `RUN yes | sdkmanager --licenses && sdkmanager --verbose "platforms;android-21" "build-tools;28.0.2" tools platform-tools` to the Dockerfile
> try with accepted license for SDK 21

- src/qml/OverlayFeatureFormDrawer.qml
- src/qml/qgismobileapp.qml
it doesn't solve my issue, but at least removes a warning.
> fix bad connection to reset

- android/src/ch/opengis/qfield/FileUtils.java
Improves the file selector by adding more possibilities to deduce the correct path of the qgs project.
References #390
> Add ways to deduce qgs file

- src/app/main.cpp
fixes #447
Not sure if this is the right place to make that.
> Deactivate WAL for Geopackages

- src/core/attributeformmodelbase.cpp
- src/qml/editorwidgets/DateTime.qml
or any provider with a QDate field
actually it would be fixing for postgres too (has date field)
> fix editing of date fields for shapefiles

- src/qml/LocatorItem.qml
also simplify a bit the code by removing animations
> add frame to search results

- src/core/featureslocatorfilter.cpp
- src/core/locatormodelsuperbridge.cpp
- src/core/locatormodelsuperbridge.h
- src/qml/LocatorItem.qml
- src/qml/QFieldSettings.qml
replicate QGIS alg to scale depending on layer density
also add an option so one could deactivate scaling when searhcing (pan only)
> optimize scale when searching points

- src/qml/LocatorItem.qml
but what is the use case?
waiting for feedback
> allow to copy text from clipboard in search bar

- src/qml/editorwidgets/TextEdit.qml
Fix #368 
@Emic37 and @nicpitsch can you test this branch (download link should be here in 15 minutes)
> Respect DPI in multiline fontsize

- android/res/layout/list_separator.xml
- android/res/values/strings.xml
- android/src/ch/opengis/qfield/QFieldProjectActivity.java
- android/src/ch/opengis/qfield/QFieldProjectListAdapter.java
- android/src/ch/opengis/qfield/QFieldProjectListItem.java
Add two sections on the root of the file selector with the last 3 used directories and the last 5 used projects.
> Recent projects and directories in file selector

- src/qml/DashBoard.qml
- src/qml/FeatureForm.qml
- src/qml/Legend.qml
- src/qml/QFieldSettings.qml
- src/qml/editorwidgets/DateTime.qml
- src/qml/editorwidgets/TextEdit.qml
- src/qml/qgismobileapp.qml
Fixes a number of QML warnings
> Fix QML warning

- android/res/layout/list_project_item.xml
- android/res/values/strings.xml
- android/src/ch/opengis/qfield/QFieldProjectActivity.java
- remove recent directories
- use ripple effect in file selector
> Remove recent directories and use ripple effect in file selector

- android/res/layout/list_projects.xml
- android/res/values/strings.xml
- android/src/ch/opengis/qfield/QFieldProjectActivity.java
- android/src/ch/opengis/qfield/QFieldProjectListItem.java
Add a section in file selection first activity with the favorite directories. 
To add a directory to the favorites, do a long click on the directory. 
To remove a directory from the favorites do a long click on the entry in the favorites section.
> Favorite directories in file selector

- src/core/linepolygonhighlight.cpp
- src/core/qgsgeometrywrapper.cpp
- src/core/qgsgeometrywrapper.h
- src/qml/FeatureListSelectionHighlight.qml
- src/qml/GeometryHighlighter.qml
- src/qml/GeometryRenderer.qml
- src/qml/LocatorItem.qml
fixes #435 
Search had issues:
- the geometry wrapper was not corrected when geometry changed, the item has to be reset first
- the timer was not correctly set
> Fix search

- android/src/ch/opengis/qfield/QFieldActivity.java
Apparently on some devices the unzipping of individual files sometimes
fails for unknown reasons and without exception.
This introduces a check that the unzipped files exist and in case they
don't it restarts the unzipping process.
The unzip code itself was also improved for more performance.
> Restart unzipping if not successful

- android/res/values/strings.xml
- android/src/ch/opengis/qfield/QFieldProjectActivity.java
- android/src/ch/opengis/qfield/QFieldProjectListItem.java
> SD-Card warning and read only entry

- src/qml/FeatureForm.qml
- src/qml/editorwidgets/CheckBox.qml
just to find the issue of invisible checkboxes
> test with checkboxes

- android/src/ch/opengis/qfield/QFieldAppRaterActivity.java
Wait 30 days AND 10 launches to show popup "rate this app" dialog
> Set definitive popup rate rules

- src/core/attributeformmodelbase.cpp
@signedav do you see a problem with this?
> Fix setting attributes from NULL to 0 and similar

- src/core/attributeformmodelbase.cpp
- src/core/identifytool.cpp
- src/core/layertreemapcanvasbridge.cpp
- src/core/qgismobileapp.cpp
- src/core/qgssggeometry.cpp
- src/core/rubberbandmodel.cpp
- src/core/sgrubberband.cpp
- src/qgsquick/qgsquickmapcanvasmap.cpp
- src/qgsquick/qgsquickmapsettings.cpp
> No more Q_FOREACH

- src/qml/FeatureListSelectionHighlight.qml
- src/qml/GeometryHighlighter.qml
- src/qml/GeometryRenderer.qml
> fix highlighting features on identify

- src/core/identifytool.cpp
- src/core/identifytool.h
- src/core/rubberbandmodel.cpp
- src/core/rubberbandmodel.h
- src/qml/DashBoard.qml
- src/qml/DigitizingToolbar.qml
- src/qml/qgismobileapp.qml
Based on digitizing rubberband.
(Pink button is only for test - no worries)
The digitizing rubberband and the measure rubberband are seperated, means you can continue with the digitizing after you did a measurement.
> Measure tool

- qfield.pri
Fix #583
@cgaldini-datek22 can you test the apk when it's there, thank you.
> Deploy virtual layer provider

- src/core/expressioncontextutils.cpp
- src/core/expressioncontextutils.h
- src/core/featuremodel.cpp
- src/core/featuremodel.h
- src/core/rubberbandmodel.cpp
- src/core/snappingresult.cpp
- src/core/snappingresult.h
- src/core/snappingutils.cpp
- src/core/snappingutils.h
- src/qml/CoordinateLocator.qml
- src/qml/qgismobileapp.qml
- Providing Snapping Results
- Providing Z and M values
- pushing the snapping result into the feature model
- fill up map tool capture scope in expression context
Solves #575 and #592
> @snapping_result integration and z values

- src/core/qgismobileapp.cpp
Maybe it has been to easy that it can be true.
Let's see what the fairy brings to us...
> Use documents location to share printing PDF

- resources/demo_projects/offline_bees.qgs
- resources/demo_projects/online_survey.qgs
Two small demo project fixes:
- on the online demo, avoid empty feature display name
- on the offline demo, do not make the country polygon identifiable, covers the canvas with yellow
> Two small demo project fixes

- src/qml/qgismobileapp.qml
Oupsi, my bad, I forgot to update the variables when re-structure the referred commit.
> Followup 81197de: use the right variables (doh)

- android/res/values/libs.xml
> Revert "add missing libraries"

- src/qml/editorwidgets/DateTime.qml
- src/qml/qgismobileapp.qml
- src/qml/ui/LayerTreeItemProperties.ui.qml
First PR, let's see if that'll pass tests.
> A few fixes for the feature form date widget, the layer tree pop up, and file picker

- images/qtquickcontrols2.conf
- src/qml/ui/LayerTreeItemProperties.ui.qml
Layer properties popup cleanup:
- Use Theme fonts
- Avoid mixture of white / light gray background
> Layer properties popup cleanup

- src/qml/CoordinateLocator.qml
- src/qml/DigitizingToolbar.qml
> Measurement tool UI/UX fixes

- src/qml/LayerLoginDialog.qml
Fixes warnings and removes leftovers.
> Layer login dialog cleanup

- src/core/attributeformmodelbase.cpp
- src/core/attributeformmodelbase.h
> Autodetect Widgettype

- src/qml/About.qml
Makes the about dialog usable in protrait mode
> Revamp the about dialog

- src/qml/NavigationBar.qml
> do not display "zoom to" button when identifying geometry less features

- scripts/ci/travis_build.sh
- scripts/docker-build.sh
- src/qml/imports/Theme/Theme.qml
Based on https://twitter.com/timlinux/status/1193777205706448896
Fix #710
> Increase font size

- src/qml/MessageLog.qml
> Improved layout in log screen

- android/res/values-eu/strings.xml
- i18n/qfield_eu.ts
- i18n/qfield_pt_BR.ts
- i18n/translations.qrc
Brazilian portuguese and Turkish
Fix #708
> Add more translations

- src/core/qgismobileapp.cpp
> Use current extent in print to PDF

- src/core/layertreemodel.cpp
- src/core/layertreemodel.h
configuration is to be done InvisibleLayersAndGroups Qgis Plug-in
Supersedes #578
> Allow hiding legend nodes

- src/qml/ScaleBar.qml
> Improve readability of scale bar on dark background

- src/qml/FeatureListForm.qml
- src/qml/qgismobileapp.qml
- Give more space to the locator item for landscape screens
- Slightly increase width of the feature list side panel for landscape screens
> A few landscape screen improvements

- src/qml/qgismobileapp.qml
Title says it all. UX issue discovered while adding a today button to the datetime edit widget.
> Toast messages shouldn't grab clicks / touches

- src/qml/MessageLog.qml
- src/qml/qgismobileapp.qml
Because while users might never hit this part of QField, those who do shouldn't feel disoriented.
> Improve the message logs page

- android/build.gradle
To show details in the log about deprecated classes and methods
> Compile java code with -Xlint:deprecation

- android/AndroidManifest.xml
- android/res/layout/unpacking_dialog.xml
- android/res/values/strings.xml
- android/src/ch/opengis/qfield/QFieldActivity.java
- Change unpacking message after 60%
- Use a custom dialog with a ProgressBar instead of the deprecated ProgressDialog class
- Use sensor orientation to launch Android's activity
> New unpacking progress dialog

- src/qml/BadLayerItem.qml
- src/qml/LayerLoginDialog.qml
- src/qml/QFieldSettings.qml
A net minus 134 lines of code, in exchange for insuring QField will have harmonized looks.
> Page header migration to template

- src/qml/DashBoard.qml
- src/qml/qgismobileapp.qml
@m-kuhn , small welcome page fix for 1.4.1.
> Disable dashboard drawer on welcome screen

- scripts/deploy.sh
according to https://developers.google.com/android-publisher/tracks the track is called only internal
> fix track name to internal

- android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
- android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
(DCIM) if not exists fixes #571
> create image dir 

- src/core/androidpicturesource.cpp
- src/qml/editorwidgets/ExternalResource.qml
> Do not store empty image path on cancel

- src/qml/editorwidgets/Range.qml
Small follow up to initial range widget implementation.
> [range widget] Don't display 0 when value is null in slider mode

- src/core/qgismobileapp.cpp
- src/core/qgismobileapp.h
This will avoid writing repetitive code in the source file
> use C Macro to register singletons

- src/qml/FeatureForm.qml
> Fix color on valid constraints

- qfield.pri
> Load libexiv2 lib to fix crash on android platform

- .travis.yml
- scripts/ci/travis_build.sh
- scripts/deploy.sh
remove all git log based calculations since they might not be available on Travis
> use date instead of commits count to determine version code

- src/qml/FeatureForm.qml
@mbernasocchi , your wish is my command :wink:
> Fix broken vertical alignment of feature form tab label

- src/qml/editorwidgets/Range.qml
> Fix tiny slider handle on hidpi screens

- src/qml/QFieldSettings.qml
> Fix storing new variables

- src/qml/imports/Theme/Theme.qml
- src/qml/qgismobileapp.qml
@mbernasocchi , as discussed in the hive group.
> Improve location information text placement and size

- src/qml/QFieldSettings.qml
Fix storing new variables
Backport of #862
> [backport] Fix storing variables

- src/qml/EmbeddedFeatureForm.qml
- src/qml/editorwidgets/RelationEditor.qml
- src/qml/qml.qrc
For reuse.
Excluded from Relation Editor.
Can be done as well in Relation Reference.
> Extract Embedded Feature Form

- src/core/vertexmodel.cpp
we currently do not support editing of multi geometry and rings
> fix discarding rings in vertex model

- src/qml/editorwidgets/ExternalResource.qml
I've overseen that on the last implementation...
> Fix external resource widget on add new

- src/qml/qgismobileapp.qml
On activating of the position we visualize what is happening over the icons.
Since it can be a little confusing the toast messages help the user that it's searching for the position and received it.
> Message for the status while getting the position

- src/qml/qgismobileapp.qml
> Do not show toasts on welcome screen

- src/qml/FeatureForm.qml
Fix constraint description height
Fix position of remember box on constraint description 
fixes #908
Looks like this:
> Fix constraint description height

- src/qml/FeatureForm.qml
Backport of #910 
* fix constraintDescriptionLabel height
fix position of remembercheckpos on constraintDescriptionLabel visible
* set fontsize of constraint description label 2/3 of the field label
> [Backport release-1_5] Fix constraint description height (#910)

- src/qml/Button.qml
> Update Buttons to QtQuick.Controls 2

- src/qml/qgismobileapp.qml
> [Backport release-1_5] Fix center GPS over menu

- src/core/appinterface.h
- src/core/attributeformmodel.h
- src/core/attributeformmodelbase.h
- src/core/badlayerhandler.h
- src/core/distancearea.h
- src/core/featurelistmodel.h
- src/core/featuremodel.h
- src/core/geometry.h
- src/core/identifytool.h
- src/core/layertreemodel.h
- src/core/legendimageprovider.h
- src/core/messagelogmodel.h
- src/core/modelhelper.h
- src/core/printlayoutlistmodel.h
- src/core/qgismobileapp.h
- src/core/qgsgpkgflusher.h
- src/core/rubberbandmodel.h
- src/core/snappingresult.h
- src/core/snappingutils.h
- src/core/submodel.h
- src/qml/geometry_editors/FillRingToolBar.qml
- src/qml/geometry_editors/GeometryEditorsToolbar.qml
Fixes a crash with the fill ring tool
> Initialize values

- src/core/appinterface.h
- src/core/attributeformmodel.h
- src/core/attributeformmodelbase.h
- src/core/badlayerhandler.h
- src/core/distancearea.h
- src/core/featurelistmodel.h
- src/core/featuremodel.h
- src/core/geometry.h
- src/core/identifytool.h
- src/core/layertreemodel.h
- src/core/legendimageprovider.h
- src/core/messagelogmodel.h
- src/core/modelhelper.h
- src/core/printlayoutlistmodel.h
- src/core/qgismobileapp.h
- src/core/qgsgpkgflusher.h
- src/core/rubberbandmodel.h
- src/core/snappingresult.h
- src/core/snappingutils.h
- src/core/submodel.h
- src/qml/geometry_editors/FillRingToolBar.qml
- src/qml/geometry_editors/GeometryEditorsToolbar.qml
> Backport  Initialize values

- .clang-format
- .gitignore
Brings the clang format style closer to our existing code style.
This does not yet enforce anything
> Adjust clang style

- src/qml/LocatorItem.qml
- src/qml/qgismobileapp.qml
otherwise, the virtual keyboard is shown when you close the dash board
> leave focus of search bar

- src/qml/editorwidgets/CheckBox.qml
> remove aliases

- src/qml/Button.qml
@m-kuhn , reverting the button change makes it easier to work on UI.
> Revert Button change (for now)

- src/qgsquick/qgsquickutils.cpp
this is no big deal for us since we don't use this code for now.
see upstream https://github.com/qgis/QGIS/pull/32708
> fix deprecated warnings

- sdk.conf
- src/core/featuremodel.cpp
The last mile, we're here.
This won't work until we have an updated SDK.
> Improve avoid intersections/overlaps by respecting newly-introduced avoidance mode

- src/qml/QFieldSettings.qml
- src/qml/imports/Theme/Theme.qml
I also added some gray color for the descriptions
> use a model to display the settings

- src/core/vertexmodel.cpp
- src/core/vertexmodel.h
with the fill ring tools, it is required to support rings when using the vertex tool
> support rings in vertex model

- src/app/main.cpp
This greatly, greatly helps debugging stuff on Android via adb.
> Forward Qt info/debug console (as well as qml console.log) messages to android's logcat

- src/core/featurechecklistmodel.cpp
- src/core/featurechecklistmodel.h
- src/core/featurelistmodel.cpp
- src/core/featurelistmodel.h
- src/qml/editorwidgets/ValueRelation.qml
> fix display field not shown in value relation

- src/core/appinterface.cpp
- src/core/appinterface.h
- src/core/qgismobileapp.cpp
- src/core/qgismobileapp.h
- src/qml/WelcomeScreen.qml
> Add way to remove project from recent projects list (addresses #966)

- src/core/qgismobileapp.cpp
- src/core/rubberband.cpp
- src/core/rubberbandmodel.cpp
- src/core/rubberbandmodel.h
- src/core/vertexmodel.cpp
- src/core/vertexmodel.h
- src/qml/CoordinateLocator.qml
- src/qml/DigitizingToolbar.qml
- src/qml/MapCanvas.qml
- src/qml/QFieldSettings.qml
- src/qml/QuestionDialog.qml
- src/qml/geometry_editors/FillRingToolBar.qml
- src/qml/geometry_editors/GeometryEditorsToolbar.qml
- src/qml/geometry_editors/SplitFeatureToolbar.qml
- src/qml/geometry_editors/VertexEditorToolbar.qml
- src/qml/qgismobileapp.qml
- test/test_vertexmodel.cpp
Useful for digitizing with a pen
> Handle inputs from stylus

- src/qml/NavigationBar.qml
Refs https://github.com/opengisch/QField/issues/987
> Make string translatable

- src/qml/BadLayerItem.qml
- src/qml/FeatureForm.qml
- src/qml/MapCanvas.qml
- src/qml/QFieldSettings.qml
- src/qml/Tracking.qml
@m-kuhn , long handing fruits.
> More QtQuick 1 extermination

- src/core/expressionvariablemodel.cpp
- src/qml/Button.qml
- src/qml/FeatureListForm.qml
- src/qml/QFieldCamera.qml
- src/qml/QFieldSettings.qml
- src/qml/VariableEditor.qml
- src/qml/editorwidgets/DateTime.qml
- src/qml/imports/Theme/QfButton.qml
- src/qml/imports/Theme/qmldir
- src/qml/qml.qrc
The last use of QtQuick 1's TreeView is gone:
> Again, more QtQuick 1 extermination: revamped variable editor

- src/qgsquick/qgsquickmapsettings.cpp
- src/qgsquick/qgsquickmapsettings.h
- src/qgsquick/qgsquickmaptransform.cpp
- src/qml/LocationMarker.qml
- src/qml/ScaleBar.qml
That fixes rubber band display on HiDPI screens.
> Take scale ratio into account in map transform

- src/qml/Button.qml
- src/qml/DashBoard.qml
- src/qml/WelcomeScreen.qml
Woupidou, back to proper button size on hidpi auto up-scaled mode.
> Proper auto scale of QField buttons

- src/qml/qgismobileapp.qml
@m-kuhn , as discussed on WhatsApp.
> Fix busy indicator overlapping topological editing button

- src/qml/qgismobileapp.qml
@3nids , spotted this while doing some field testing of QField master yesterday.
> Make the measure tool work for stylus and mouse not acting as touch

- src/qml/editorwidgets/ExternalResource.qml
No more 1/6th of the photo covered by a pixelated icon, wouhou!
> Thanks to hidpi autoscaling, we can have a properly sized location indicator

- src/qml/MapCanvas.qml
@3nids , other problem discussed in WhatsApp.
I haven't tested it yet, waiting for travis to give us an apk, but I'm pretty sure it was the oldScale not resetting to 1.0 that was problematic.
> Fix pinch zoom, hopefully

- src/qml/qgismobileapp.qml
@3nids , this fixes one of the two issues I sent you videos of on WhatsApp.
> Fix locator moving on screen touch when mouse not treated as touch screen

- resources/demo_projects/advanced_bee_farming.qgs
A slider for the percentage resolves this #844
> Slider in Demoproject

- src/qgsquick/qgsquickcoordinatetransformer.h
- src/qml/PositionInformationView.qml
- src/qml/PositioningSettingsPopup.qml
The text should be parsed to assign to the float (real) and not the other way around.
The `mDeltaZ` is protected instead of private.
Fixes #1027
> Antenna height float fix

- src/core/layertreemodel.cpp
- src/core/layertreemodel.h
- src/qgsquick/qgsquickmapsettings.cpp
- src/qgsquick/qgsquickmapsettings.h
- src/qml/LayerTreeItemProperties.qml
- src/qml/ui/LayerTreeItemProperties.qml
I often get lost in the map and I cannot find an easy way to center back to the project area.
> Zoom to layer

- src/core/expressionvariablemodel.cpp
- src/qml/FeatureForm.qml
- src/qml/FeatureListForm.qml
- src/qml/LayerTreeItemProperties.qml
- src/qml/QFieldSettings.qml
- src/qml/VariableEditor.qml
> QML warning hunt

- src/qml/VertexRubberband.qml
- src/qml/geometry_editors/GeometryEditorsToolbar.qml
- src/qml/geometry_editors/VertexEditorToolbar.qml
> do not show vertex rubberband by default in map tools

- src/core/linepolygonhighlight.cpp
- src/qml/BadLayerItem.qml
- src/qml/CoordinateLocator.qml
- src/qml/FeatureForm.qml
- src/qml/LayerTreeItemProperties.qml
- src/qml/OverlayFeatureFormDrawer.qml
- src/qml/qgismobileapp.qml
Second iteration of warning hunt, at least those from the start screen are massacred. 
There are a couple more that I have investigated, but I am not advanced enough to find a stable solution. Next time :)
> Warning hunt

- src/app/CMakeLists.txt
> Add QtQuick Compiler

- src/qgsquick/qgsquickcoordinatetransformer.h
since there is no problem mention here https://github.com/opengisch/QField/issues/1027#issuecomment-636013838 and here https://github.com/opengisch/QField/pull/1038#issuecomment-638127267 anymore since update of the Qt
> make mDeltaZ private again 

- src/app/CMakeLists.txt
QtCreator now knows Theme etc.
> Add qml import paths to cmake

- src/core/featuremodel.cpp
> Fix show attribute form forced on

- src/qml/qgismobileapp.qml
> Toggle button no longer needs to handle clicks

- src/qml/qgismobileapp.qml
Fixes https://github.com/opengisch/QField/issues/1095
> Apply default values also with suppressed feature form

- src/qml/FeatureForm.qml
- src/qml/FeatureListSelectionHighlight.qml
@m-kuhn , quick multi select translation fix.
> Make multi edit value applied / value skipped translatable

- CMakeLists.txt
- sdk.conf
> Switch to android libz

- src/core/multifeaturelistmodelbase.cpp
FIX https://github.com/opengisch/QField/issues/1113
> FIX 1113 Fix double deletion of the same feature

- src/qml/DigitizingToolbar.qml
long press should be used instead
> do not show validation button when digitizing with pen

- src/core/layertreemapcanvasbridge.cpp
- src/core/layertreemodel.cpp
- src/qml/LayerTreeItemProperties.qml
- src/qml/Legend.qml
A couple of legend fixes for 1.6.1
> [Manual Backport 1_6] Legend fixes

- src/core/attributeformmodelbase.cpp
- src/qml/FeatureForm.qml
- src/qml/editorwidgets/ExternalResource.qml
- src/qml/editorwidgets/RelationEditor.qml
- src/qml/editorwidgets/TextEdit.qml
- src/qml/editorwidgets/ValueRelation.qml
> [Manual Backport 1_6] Fix Feature Form problems depending on isEnabled and AttributeAllowEdit

- src/core/snappingutils.cpp
Regression from use enabling Qt's HiDPI auto scaling.
> Fix snapping on HiDPI screens

- src/core/snappingutils.cpp
> [backport] Fix snapping on HiDPI screens

- .github/workflows/translations.yml
> Add tx into path and add forgotten CI_* env vars

- src/qml/RelationCombobox.qml
- src/qml/editorwidgets/ValueRelation.qml
|before|after|
|---------|------|
| ![image](https://user-images.githubusercontent.com/2820439/88158398-ad78aa80-cc14-11ea-8532-50d40ba6b19b.png)  | ![image](https://user-images.githubusercontent.com/2820439/88158247-7a361b80-cc14-11ea-8fdf-298763565729.png)|
> Polish ValueRelationWidget

- src/qml/qgismobileapp.qml
I often identify much more than desired.
Let's see if this version is more precise.
Fixes #858
> Reduce map identify radius

- src/qml/LayerTreeItemProperties.qml
> Layer properties popup fixes and improvements

- src/qml/Legend.qml
Small fix to silent one more warning.
> Set vector layer to null to address QML warning

- android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
- android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
> Fix DCIM folder not showing up

- src/qml/FeatureListForm.qml
> Re-focus on feature list form item after dialog is closed

- android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
- android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
Fix DCIM folder not showing up
> Backport "Fix DCIM folder not showing up" to release 1.6

- src/qml/qgismobileapp.qml
GIF:
@mbernasocchi , as discussed over hive.
> Further tweak message toaster style

- .docker/testing/Dockerfile
- .docker/testing/build-test.sh
- .docker/testing/docker-compose-ci.yml
- .github/workflows/continuous_integration.yml
- .travis.yml
- sdk.conf
- src/core/layertreemodel.cpp
- src/core/vertexmodel.cpp
- src/qml/Legend.qml
- src/qml/qgismobileapp.qml
- test/test_vertexmodel.cpp
This is exactly the same qgis version as osgeo4a and other dependencies are newer than qgis/qgis at the time of writing.
Will need to be restarted when the docker is ready.
> Use a custom docker image for testing

- resources/demo_projects/advanced_bee_farming.qgs
Results are out: this reduces the APK by slightly more than 5MB.
> Reduce APK by roughly 6MB by removing countries.gpkg

- src/core/gotolocatorfilter.h
- src/core/locatormodelsuperbridge.cpp
@m-kuhn , that should make the goto locator blazingly fast even when QField has access to only one thread.
> Flag the goto locator filter as a fast one, will fetch in the main thread

- src/qml/LocatorItem.qml
- src/qml/qgismobileapp.qml
This focus one of the last in-your-face focus issue I've spotted in QField. :tada:
> Fix focus issues when closing the search bar

- images/images.qrc
- images/themes/qfield/nodpi/ic_error_outline_24dp.svg
- src/core/layertreemodel.cpp
- src/core/layertreemodel.h
- src/qml/LayerTreeItemProperties.qml
- src/qml/Legend.qml
- src/qml/qgismobileapp.qml
> Prevent from editing invalid layers

- src/qml/LocatorItem.qml
@3nids , can you confirm search is fixed for you when the APKs pop up? Thanks
> Fix search only triggered when hitting space

- src/qml/Legend.qml
Note to the world: there's a risk someone ends up updating the SDK on the release-1_6 branch, which would trigger this regression there. Let us all be aware! :wink:
> isValid is a property these days

- src/qml/Changelog.qml
- src/qml/FeatureForm.qml
- src/qml/Legend.qml
- src/qml/WelcomeScreen.qml
- src/qml/editorwidgets/DateTime.qml
- src/qml/imports/Theme/QfToolButton.qml
As far as I can see, not used anymore since we moved to QtQucik 2-only.
> Remove unused imports

- src/core/multifeaturelistmodelbase.cpp
Fixes #1228 and similar issues on 1.6.
Regression caused by conflict resolution prior to merging multi selection branch.
> Fix broken feature deletion

- src/core/layertreemodel.cpp
Finally managed to narrow down a crasher that had been haunting me. Not sure why it doesn't systematically happen (which made it harder to debug). In any case, nailed!
> Fix a QField crash when opening a second project in a single session

- cmake/AndroidManifest.xml.in
> Replace app id everywhere

- cmake/AndroidManifest.xml.in
https://www.google.com/appserve/mkt/vib/AD-FnExPEblL99YjNRDbwejbe0L99U7No_OISqiap1Ow5Vyx9tVme29CY9ZbrQI_AR407n74_tLAHsU8WWNJ2TcvfSN1bsaZk2Ioh6meEvYojkZAaramZTlCfOsNWncrPhvo6OfQLQNQHgobPLFvE-3RmOKH9wY8QSy7Fb9_yXDcg5aOmfHwZoZHAUO5AOUqVqiRoBI
> Bump Android target sdk to 29 (Android 10)

- src/qml/NavigationBar.qml
Broken since multiselection model was introduced.
|----------|--------|
| ![image](https://user-images.githubusercontent.com/2820439/91550648-8444eb80-e931-11ea-906a-be436bb6f6c0.png)  | ![image](https://user-images.githubusercontent.com/2820439/91550541-5cee1e80-e931-11ea-91da-3e48e2f0452f.png) |
> Fix missing feature name when edit form is opened

- src/qml/About.qml
- src/qml/Changelog.qml
- src/qml/NavigationBar.qml
- src/qml/qgismobileapp.qml
Check https://github.com/opengisch/QField/pull/1274
> [Backport release-1_7] Changelog improvements

- src/qml/Legend.qml
| - | - |
| ![image](https://user-images.githubusercontent.com/2820439/91721551-a17ff100-eba1-11ea-9f5a-217ea5de0998.png) | ![image](https://user-images.githubusercontent.com/2820439/91722435-e8bab180-eba2-11ea-97b5-fd750281b6b3.png) |
> Show invalid layer indicator only on layer Legend items

- src/qml/FeatureForm.qml
> keep relation editor widget enabled in embedded forms

- .github/workflows/translations.yml
- scripts/ci/update-translations.sh
- scripts/docker-build.sh
By installing qt5-default in advance.
> Fix translation with lupdate

- .github/workflows/translations.yml
- scripts/ci/update-translations.sh
> fix translation backport

- src/core/attributeformmodel.h
- src/core/attributeformmodelbase.cpp
- src/core/attributeformmodelbase.h
- src/qml/FeatureForm.qml
> Hide webview items as much as possible, z-index unfriendly on Android

- src/core/attributeformmodel.h
- src/core/attributeformmodelbase.cpp
- src/core/attributeformmodelbase.h
- src/qml/FeatureForm.qml
Hide webview items as much as possible, z-index unfriendly on Android
> Backport #1294 to release 1 7

- src/qml/FeatureForm.qml
Set no sub models if the form has no tabs
> Backport #1288 to release 1 7

- images/images.qrc
- images/themes/qfield/nodpi/ic_group_18dp.svg
- images/themes/qfield/nodpi/ic_legend_collapsed_state_14dp.svg
- src/core/layertreemodel.cpp
- src/core/layertreemodel.h
- src/qml/LayerTreeItemProperties.qml
- src/qml/Legend.qml
> Backport #1295 to release 1 7

- src/qml/LayerTreeItemProperties.qml
Pass visibility state on tracking start
> Backport #1309 to release 1 7

- images/icons/qfield_logo.svg
- images/icons/qfield_logo_beta.svg
- images/icons/qfield_logo_pr.svg
To have the new logo in the 1.7.2 then...
> Refresh QField logo (#1311)

- src/qml/FeatureListForm.qml
> Let go of transitions, it unfortunately doesn't work well alongside section-enabled listviews

- src/qml/geometry_editors/GeometryEditorsToolbar.qml
- src/qml/qgismobileapp.qml
@signedav , this should fix your other issue reported today.
> Prevent geometry editor toolbar from 'eating' map canvas event when not visible

- src/qml/editorwidgets/ValueRelation.qml
Manual backport of https://github.com/opengisch/QField/pull/1324
> [Manual backport release-1_7] Make cascading dependencies work since the init phase

- src/qgsquick/qgsquickmapsettings.cpp
@m-kuhn , this should fix your issue.
> Avoid broken project state when a project file doesn't contain a mapcanvas element

- src/qml/qgismobileapp.qml
> [backport release 1.7] Fix topological editing

- images/icons/qfield_logo.svg
- images/icons/qfield_logo_beta.svg
- images/icons/qfield_logo_pr.svg
> Revert "Refresh QField logo (#1311)"

- sdk.conf
(Once tested, I'll do a proper OSGeo4A tagged release, just want to make sure I'm not introducing regressions first)
> Update SDK to get a couple of important QGIS fixes

- src/core/featuremodel.cpp
- src/qml/DigitizingToolbar.qml
When hitting the [ check/accept ] button in the digitize toolbar, make sure the last position is kept as a vertex.
@m-kuhn , as discussed.
> When hitting the [ check/accept ] button in the digitize toolbar, make sure the last position is kept as a vertex

- src/qgsquick/qgsquickmapsettings.cpp
1.7 backport of important projection fix.
> Fix QField _always_ ignoring project transformation settings

- .github/workflows/continuous_integration.yml
- cmake/AndroidManifest.xml.in
- scripts/ci/build.sh
> Backport 17: targetSdkVersion 29 upgrade

- src/app/main.cpp
- src/qml/FeatureForm.qml
... actually, it's worse than the title says, we never initialized qt webview on android.
> Move QtWebView::initalize so it happens _before_ QgsApplication app on android

- sdk.conf
This will, among other things, fix issue #1218.
> Update SDK to catch QGIS 3.16 final and GDAL 3.2

- src/core/qgismobileapp.cpp
- src/core/qgsgpkgflusher.cpp
- src/core/qgsgpkgflusher.h
Useful when manipulating the gpkgs of the currently opened project.
> Add option to stop/start the gpkg flusher

- scripts/ci/env_gh.sh
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
> set-env is disabled

- scripts/ci/env_gh.sh
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
> [backport release 1.7] set-env is disabled

- src/core/layertreemodel.cpp
- src/core/layertreemodel.h
- src/qml/Legend.qml
It'd probably be good to backport these fixes to our 1.7 release branch.
> [backport release-1_7] Legend speed fixes

- src/core/featuremodel.cpp
Should fix #1422 and similar issues.
> Respect feature defaults when creating a new feature

- .github/workflows/continuous_integration.yml
> Add a link to the pr commit in the apks comment

- .github/workflows/continuous_integration.yml
- scripts/basic_upload_apks_service_account.py
A successful run from a different branch:
https://github.com/opengisch/QField/runs/1491226409?check_suite_focus=true
> Publish dev builds to play store

- src/qml/FeatureListForm.qml
- src/qml/NavigationBar.qml
> Swipe up and down to show the feature form in fullscreen

- src/core/multifeaturelistmodel.cpp
- src/core/multifeaturelistmodel.h
- src/core/multifeaturelistmodelbase.cpp
- src/qml/LayerTreeItemProperties.qml
Now we can browse the non spatial layers too.
> Add "Show all features" button

- src/qml/NavigationBar.qml
This should be applied for the feature list and the new relation editor in future PRs.
> Fit the feature name in the navigation bar

- src/qml/LayerTreeItemProperties.qml
> Don't show zoom to layer on non-spatial layers

- src/qml/LayerTreeItemProperties.qml
- src/qml/NavigationBar.qml
A few bugfixes, warning hunt and fix broken merge.
> Improve the usability of the recent additions to the legend item props

- .github/workflows/continuous_integration.yml
> Hide outdated fairy comments

- src/qml/Changelog.qml
- src/qml/FeatureForm.qml
- src/qml/FeatureListForm.qml
- src/qml/MessageLog.qml
- src/qml/PageHeader.qml
- src/qml/editorwidgets/DateTime.qml
- src/qml/editorwidgets/ExternalResource.qml
- src/qml/editorwidgets/Range.qml
- src/qml/editorwidgets/RelationEditor.qml
Well, there are zero warnings when using QField.
> Eliminate the next portion of warnings

- CMakeLists.txt
> remove inexisting directory in Osgeo4a

- src/qml/imports/Theme/QfButton.qml
> Add ripple effect to QfButton

- src/qml/QFieldSettings.qml
> Swipe the settings

- src/qml/imports/Theme/QfButton.qml
```
QfButton {
text: qsTr( "Settings" )
icon.source: Theme.getThemeIcon( "ic_settings_white_24dp" )
icon.color: 'white'
}
```
> Support icons in buttons

- src/qml/LayerTreeItemProperties.qml
> Shorten "geometry locked" and "read only" texts on layer properties

- src/core/layertreemodel.cpp
- src/core/layertreemodel.h
- src/qml/LayerTreeItemProperties.qml
Needs a new sdk to be tested
Fixes #163 
Fixes #665
> Add reload data button

- images/images.qrc
- images/themes/qfield/nodpi/ic_legend_collapsed_state_white_14dp.svg
- src/qml/Legend.qml
> Supergreen legend

- src/core/attributeformmodelbase.cpp
Fixes #1480
The not null constraint checks where failing since https://github.com/qgis/QGIS/pull/39388
> Fix not null constraint checks where default values are available

- src/core/attributeformmodelbase.cpp
…ue_checks
Fix not null constraint checks where default values are available
> Backport Fix not null constraint checks where default values are available

- src/app/main.cpp
> Try to adjust paths

- src/qml/editorwidgets/TextEdit.qml
Wrap the text input contents when its too long
let
> [backport release 1.8]  Wrap the text input contents when its too long 

- .github/release_drafter.yml
- .github/workflows/release_drafter.yml
Will help us prepare the changelog
https://github.com/release-drafter/release-drafter
Thanks to @DelazJ
> Release Drafter

- src/qml/LayerTreeItemProperties.qml
> Fix capitalization

- src/qml/LayerTreeItemProperties.qml
- src/qml/QFieldSettings.qml
> Simply talk about "map" instead of "map canvas"

- src/qml/LocatorItem.qml
This fixes an issue with virtual keyboards and the search bar not clearing text when hitting the X clear button.
While testing on my smartphone, my large fingers didn't play well with the relatively small "hit" area, so I've tried to improve that on behalf of all large finger users.
Fixes #1512
> Fix search bar x clear action on virtual keyboards, increase hit area

- src/qml/imports/Theme/QfToolButton.qml
> Merry holiday and happy rippling

- src/core/rubberband.h
- src/qml/geometry_editors/FillRingToolBar.qml
> Improve rubberband visibility

- src/qml/qgismobileapp.qml
Sorry for the noise, should I caught this one in the original PR.
> Align the zoom in and zoom out buttons

- src/core/platformutilities.cpp
- src/qml/qgismobileapp.qml
Print to PDF improvements:
- when a single layout is present, skip the submenu and simply print that one
- when printing, throw a message to the user
- delay the printing for some milliseconds to show UI feedback
The single layout improvement was a(nother) good suggestion from @nyalldawson.
> Print to PDF improvements

- src/qml/MapCanvas.qml
- src/qml/qgismobileapp.qml
> MapCanvas cleanup + resurrection of mouse wheel and touble tap zoom in

- src/qml/MapCanvas.qml
> Handlers are ethernal struggles, fix double tap zoom regression

- src/qml/qgismobileapp.qml
> Fix broken condition when checking for editable layers

- src/core/bluetoothdevicemodel.cpp
- src/core/gnsspositioninformation.h
- src/qml/PositioningSettings.qml
- src/qml/QFieldSettings.qml
- src/qml/qgismobileapp.qml
@signedav , as discussed with you yesterday.
> NMEA followup

- sdk.conf
- src/qml/NavigationBar.qml
Fix https://github.com/opengisch/QField/issues/1460
> Use supportsEditing flag to determine whether to show the edit button

- src/qml/imports/Theme/QfTextField.qml
To set and get text - fixes Login Dialog
> Proxy alias text QfTextField

- src/qml/CoordinateLocator.qml
- src/qml/DigitizingToolbar.qml
- src/qml/PositioningSettings.qml
- src/qml/QFieldSettings.qml
- src/qml/imports/Theme/Theme.qml
- src/qml/qgismobileapp.qml
That should allow us to release 1.8.1 :partying_face:
> [Backport release-1_8] Accuracy indicator & requirement

- src/core/attributeformmodel.h
- src/core/attributeformmodelbase.cpp
- src/core/attributeformmodelbase.h
- src/qml/FeatureForm.qml
Christmas is over, but New Year not yet here.
Here comes another QField :gift: 
Say hello to support for group container colors
> Support for colors in attribute forms 🎨

- src/qml/Tracking.qml
> Avoid start tracking without definitions

- src/core/CMakeLists.txt
- src/core/androidplatformutilities.cpp
- src/core/feedback.cpp
- src/core/feedback.h
- src/core/qgismobileapp.cpp
- src/core/utils/fileutils.cpp
- src/core/utils/fileutils.h
- src/qml/SystemLoader.qml
- src/qml/qml.qrc
> Add system loader dialog

- .github/workflows/code_layout.yml
- sdk.conf
> Revert to Qt 5.14.2

- android/src/ch/opengis/qfield/QFieldActivity.java
- cmake/AndroidManifest.xml.in
- src/core/qgismobileapp.cpp
... the day has finally come ... we are now blank screen free :partying_face: :tada:
> Fix the blank screen on resume issue while greatly simplifying manifest & QFieldActivity java class

- src/core/expressioncontextutils.cpp
- src/core/gnsspositioninformation.cpp
- src/core/gnsspositioninformation.h
> Add position_3d_accuracy for 3DRMS

- src/core/qgsquick/qgsquickmapcanvasmap.cpp
By 'nice' I mean *huge* speed boost here. It comes at no visual cost whatsoever too. Woupidou.
> Nice speed boost for complex vector layers by enabling rendering optimization 

- src/qml/qgismobileapp.qml
> Do nothing if the new state is the same as the old one

- src/core/featuremodel.cpp
- src/core/featuremodel.h
- src/qml/OverlayFeatureFormDrawer.qml
- src/qml/qgismobileapp.qml
@LindaOPENGIS , this should fix the two freehand issues you reported. Both issues were actually impacting non-freehand digitizing too, so well spotted! :)
> Freehand fixes

- src/core/linepolygonhighlight.cpp
- src/core/linepolygonhighlight.h
- src/core/qgssggeometry.cpp
- src/core/qgssggeometry.h
- src/core/rubberband.cpp
- src/core/rubberband.h
- src/qml/GeometryRenderer.qml
- src/qml/qgismobileapp.qml
This PR fixes rubber band drawing issues / precision when digitizing on small areas with CRSes having a large number of pre-decimals digits. It fixes #1626 (and likely a few more).
Before:
https://user-images.githubusercontent.com/1728657/106092400-ced8c700-6160-11eb-8e75-067ab713a2e2.mp4
PR:
https://user-images.githubusercontent.com/1728657/106092554-18291680-6161-11eb-9911-25e4a3e080fe.mp4
Since QField can be as precise as 1mm via NMEA devices, we might as well make sure our rubber bands can too :wink:
> Fix rubber band drawing precision issues

- src/qml/RelationCombobox.qml
> Fix pixelated clear button in the relation combobox popup

- sdk.conf
> Update SDK to gain NMEA patch

- .github/workflows/continuous_integration.yml
- src/core/attributeformmodelbase.cpp
The android build use a patched 3.16.3 version, the qgis-linux build for testing
doesn't have this patch (todo for osgeo4a -- apply patches when building qgis docker images)
Instead use master which also contains this patch
> Use a QGIS master build for testing

- src/core/featurechecklistmodel.cpp
- src/core/qfieldappauthrequesthandler.cpp
- src/core/qfieldappauthrequesthandler.h
- src/core/qgismobileapp.cpp
- src/core/qgismobileapp.h
- src/qml/FeatureForm.qml
Random stuff  stumbled upon and thought it'd be good to cleanup.
> It's friday, code cleanup

- src/core/qgismobileapp.cpp
@mbernasocchi , thanks for the testing, there was indeed an issue with the code loading a dataset containing multiple layers with different CRSes.
You can enjoy viewing your safari now :wink:
> Fix broken loading of multi-layer dataset containing mixed CRSes

- src/qml/FeatureForm.qml
> Get rid of some warnings

- android/res/layout/list_project_item.xml
- android/src/ch/opengis/qfield/QFieldProjectActivity.java
> Fixes to the java file browser

- src/qml/RelationCombobox.qml
- src/qml/editorwidgets/RelationEditor.qml
@signedav , this should fix #1664.
> Fix stacking of relation combobox embedded forms

- src/qml/QFieldSettings.qml
Attempt to fix https://github.com/opengisch/QField/issues/1667
> Use C locale to validate doubles

- src/core/featuremodel.cpp
- src/qml/editorwidgets/Range.qml
This is probably bad enough to warrant a 1.8.4 ASAP.
> [Backport release-1_8] Fix remembered values regression

- src/qml/qgismobileapp.qml
> Apply geometry before calculating default values

- src/qml/RelationCombobox.qml
Should fix the issue in this comment https://github.com/opengisch/QField/issues/1579#issuecomment-767514279  .
> Enable selection of scrolled items in relations

- src/core/featurelistmodel.cpp
Fix #1707 and a regression introduced by https://github.com/opengisch/QField/commit/34d0891134dc53ef3e8cc5e9842a1587bf44d9e8?branch=34d0891134dc53ef3e8cc5e9842a1587bf44d9e8 .
> Fixed a regression not showing the display string in value relation

- scripts/build.sh
Fixes https://github.com/opengisch/QField/issues/1706
> Mount source with proper selinux permissions

- src/qml/QFieldSettings.qml
> Fix out-of-sync bar / swipeview when manually setting index

- android/src/ch/opengis/qfield/QFieldProjectActivity.java
- cmake/AndroidManifest.xml.in
- src/core/qgismobileapp.cpp
- src/core/qgismobileapp.h
> Allow QField to open individual datasets within ZIP archives

- src/core/qgismobileapp.cpp
I guess this should go into a platformutilities `initEnvironment()` method?
> Only override pgsysconfdir on Android

- resources/demo_projects/advanced_bee_farming.qgs
- resources/demo_projects/simple_bee_farming.qgs
I made them quickly to test #1731
They could be improved - still it would already be fine for the demo projects.
How I made them...
https://user-images.githubusercontent.com/28384354/109514637-8afe1800-7aa6-11eb-871e-e9dce9943a4e.mp4
> Demoprojects with Atlas Printlayout

- sdk.conf
In preparation for the 1.9 release, update the SDK to catch a bunch of QGIS fixes.
> Update SDK to catch a bunch of QGIS fixes

- src/core/snappingutils.cpp
- src/core/submodel.cpp
- src/core/submodel.h
- src/qml/editorwidgets/TextEdit.qml
There's no saying how many obscure bugs this might have caused.
> SubModel fundamentally broken, fix it!

- src/qml/editorwidgets/DateTime.qml
> Fix date widget not liking date-as-string value

- src/qml/geometry_editors/SplitFeatureToolbar.qml
> Reset rubberband after use

- cmake/GetGitRevisionDescription.cmake
- cmake/GetGitRevisionDescription.cmake.in
to work with worktrees
copied files from https://github.com/rpavlik/cmake-modules/blob/main/GetGitRevisionDescription.cmake
> fix cmake get git head rev

- .github/workflows/continuous_integration.yml
Whoops, there were few specific things that are no longer needed.
> Restore the previous continuous integration configuration

- src/qml/QFieldCloudDownloadProjectErrorsPopup.qml
- src/qml/QFieldCloudScreen.qml
Turns out delegate within a delegate does not work properly. This PR temporarily disables the "public" tab until I find a better sollution.
> Fixed the projects list download feedback

- src/core/qgismobileapp.cpp
> No map? Let's not crash

- src/qml/FeatureListForm.qml
- src/qml/NavigationBar.qml
@signedav , yep, this is truly meant for you :wink: this PR fixes a series feature list navigation bar issues we discussed.
> Navigation bar fixes

- src/core/qfieldcloudprojectsmodel.cpp
- src/core/qfieldcloudprojectsmodel.h
- src/qml/QFieldCloudScreen.qml
Quite handy if you accidentally download a project with a few GB of tiffs
> Add a way to abort project download

- src/core/featuremodel.cpp
- src/qml/CoordinateLocator.qml
- src/qml/DigitizingToolbar.qml
- src/qml/EmbeddedFeatureForm.qml
- src/qml/OverlayFeatureFormDrawer.qml
- src/qml/qgismobileapp.qml
This PR should fix missing positioning information @variables when adding new features (#1640), as well as respect minimum accuracy requirements when set by the user (#1804).
> A couple of position fixes

- src/core/featuremodel.cpp
- src/core/featuremodel.h
> [backport release-1_9] Fix and improve remembered values

- src/core/qgismobileapp.cpp
- src/core/qgsquick/qgsquickmapcanvasmap.cpp
> Catch transform errors

- src/core/qgismobileapp.cpp
- src/core/qgsquick/qgsquickmapcanvasmap.cpp
> Backport transform crash fix

- src/core/qfieldcloudconnection.cpp
- src/core/qfieldcloudconnection.h
- src/qml/QFieldCloudLogin.qml
- src/qml/QFieldCloudPopup.qml
- src/qml/QFieldCloudScreen.qml
Yes, the most crucial feature has landed in QField, avatar image!
> QField should reflect the avatar of the logged in cloud user

- src/qml/editorwidgets/ExternalResource.qml
This fixes the issue raised in #1816 with regards to document hyperlinks not always working. In doing so, I've made our widget respect some of the storage path settings. That said, some work should be done in qfieldsync so we don't always hard-code a project path prefix (users can select so in the config anyways).
The bigger picture in issue #1816 is more of a feature request for the external resource widget to handle non-image contexts.
> Improvement and fixes to the external resource/attachment widget

- src/core/qfieldcloudconnection.cpp
- src/core/qfieldcloudprojectsmodel.cpp
- src/core/qfieldcloudprojectsmodel.h
- src/qml/QFieldCloudPopup.qml
- src/qml/QFieldCloudScreen.qml
@suricactus , as discussed earlier.
This PR handles all the UI/UX issues I stumbled with invalidated tokens.
> QField should register and deal with expired/invalidated tokens

- src/qml/NavigationBar.qml
- src/qml/qgismobileapp.qml
@suricactus , two follow ups to the permissions work committed earlier this week.
> Permissions follow ups

- src/qml/editorwidgets/ExternalResource.qml
- src/qml/editorwidgets/RelationEditor.qml
@mrtwister3142 , this should fix the issue you reported. Can you try APKs in this PR to confirm? Thanks
> Fix camera popup under feature form panels (fixes #1851)

- src/qml/QFieldCloudPopup.qml
Hm, that wasn't meant to be part of the rate us revamp PR :) 
@suricactus , reverting an accidental line deletion.
> Revert accidental line delete

- src/qml/FeatureForm.qml
> [backport release-1_9] Fix ListView going broken when resetting feature form

- src/core/featurechecklistmodel.cpp
- src/core/qgismobileapp.cpp
- src/qml/RelationCombobox.qml
This PR primarily fixes #1788 , but also improves the UI/UX of the combobox (and therefore its paired editor widget) so the widget doesn't look out of place in the overall feature form.
> Relation combobox fixes and improvements

- src/qml/editorwidgets/DateTime.qml
- src/qml/editorwidgets/ValueMap.qml
> [Backport release-1_9] More editor widget improvements

- src/qml/editorwidgets/CheckBox.qml
- src/qml/imports/Theme/QfSwitch.qml
> [Backport release-1_9] Improvements to the checkbox editor widget

- src/qml/FeatureListForm.qml
- src/qml/NavigationBar.qml
- src/qml/imports/Theme/QfToolButton.qml
- src/qml/qgismobileapp.qml
> [Backport release-1_9] Focus improvements all around

- src/qml/TransformedPositionSource.qml
https://github.com/opengisch/QField/pull/1899 forgot to change this line here
> Fix coordinate to point

- src/qml/FeatureListForm.qml
> When exiting the multi selection mode via the back key, clear selection

- src/qml/FeatureForm.qml
- src/qml/NavigationBar.qml
- src/qml/Tracking.qml
> [Backport release-1_9] Always show the iOS and cancel/delete button in the add feature form

- src/qml/DigitizingToolbar.qml
> [Backport release-1_9] Allow 2-vertex line and 3-vertex polygons

- src/qml/FeatureForm.qml
> [Backport release-1_9] Fix feature addition

- src/core/snappingutils.cpp
> [Backport release-1_9] Fix snapping to segment

- src/qml/FeatureForm.qml
- src/qml/qgismobileapp.qml
> [Backport release-1_9] Fix double feature creation when adding points in fast editing mode

- src/core/layertreemodel.cpp
> [Backport release-1_9] One more legend corner scenario: insertion of rows with pre-existing children

- src/qml/FeatureForm.qml
- src/qml/editorwidgets/DateTime.qml
- src/qml/qgismobileapp.qml
|----------|--------|
| ![Peek 2021-06-02 11-13](https://user-images.githubusercontent.com/2820439/120448015-cd7c0d00-c393-11eb-918b-172211295a77.gif) | ![Peek 2021-06-02 11-11](https://user-images.githubusercontent.com/2820439/120448019-cead3a00-c393-11eb-8ca3-8b8d4b4ab9eb.gif) |
> Improve embedded forms feedback

- src/qml/FeatureForm.qml
- src/qml/editorwidgets/DateTime.qml
- src/qml/qgismobileapp.qml
> [Backport release-1_9] Improve embedded forms feedback

- src/core/deltafilewrapper.cpp
- src/core/layerobserver.cpp
- src/core/qfieldcloudprojectsmodel.cpp
- src/core/qgismobileapp.cpp
- src/core/qgismobileapp.h
- src/core/utils/qfieldcloudutils.cpp
- src/core/utils/qfieldcloudutils.h
- src/qml/DashBoard.qml
- src/qml/QFieldCloudPopup.qml
- src/qml/imports/Theme/QfToolButton.qml
- src/qml/qgismobileapp.qml
- Show the username in bold in the greeting
- UI show be no longer frozen after finished sync (fix #1914)
- Fit nonrectangular avatars to look like the ones on the web
- Add QfToolButton indicator support to show the number of local changes to be synced
- Show relative time when changes synced in the last 60 minutes
- Fix broken animation on the QFC popup while syncing
- Animate the toolbar cloud icon when downloading/uploading
- Hide the sync error once one successfull operation is finished (fix #1928)
> Cloud UI improvements

- src/core/qgismobileapp.cpp
This allows packaging of a _whole_ project within a single file (provided the vector layers are all within the same geopackage or remote). It's a nice little feature to support for users who are relying on this in their QGIS environments.
Note: this will not handle multiple projects saved within a single geopackage. The code will load the first project found in the geopackage.
> Support loading of QGIS projects saved inside geopackage files

- src/core/qgismobileapp.cpp
- src/qml/WelcomeScreen.qml
Follow up to #1963 -- make it work... :)
@xBcai , this should do it, thanks for testing.
> Fix setting base map project via welcome screen

- ios/Info.plist.in
> [Backport release-2_0] Add a description why bluetooth is required

- src/qml/editorwidgets/ValueRelation.qml
> Allow text wrapping for value relation widget

- src/qml/editorwidgets/TextEdit.qml
> [Backport release-2_0] Until we support those, prevent text editing of JSON / list fields

- src/core/changelogcontents.cpp
I know you were going to do it anyway, I just wanted to save you from some additional work @signedav .
EDIT: @nirvn saved the changelog
> Fix the changelog listening to QNetworkAccessManager

- src/core/featuremodel.cpp
- src/core/featuremodel.h
- src/qml/EmbeddedFeatureForm.qml
- src/qml/FeatureListForm.qml
- src/qml/OverlayFeatureFormDrawer.qml
- src/qml/Tracking.qml
- src/qml/qgismobileapp.qml
> Use a project property instead of QgsProject::instance in feature model

- src/core/utils/geometryutils.cpp
> [Backport release-2_0] Fix reshape tool handling of geometry operation return values

- src/core/bluetoothreceiver.cpp
> [Backport release-2_0] Identify NMEA position information source

- src/qml/editorwidgets/TextEdit.qml
@lindacamathias , can you test these APKs when our diligent fairy delivers?
> Fix text edit widget editable's logic

- src/qml/editorwidgets/TextEdit.qml
> [Backport release-2_0] Fix text edit widget editable's logic

- .github/workflows/ios.yml
Automatically create from qfield-sdk release https://github.com/opengisch/qfield-sdk/releases/tag/96
> Update QField SDK

- images/images.qrc
- images/themes/qfield/nodpi/ic_chevron_down.svg
- images/themes/qfield/nodpi/ic_chevron_up.svg
- src/core/CMakeLists.txt
- src/core/attributeformmodel.h
- src/core/attributeformmodelbase.cpp
- src/core/featuremodel.cpp
- src/core/featuremodel.h
- src/core/orderedrelationmodel.cpp
- src/core/orderedrelationmodel.h
- src/core/qgismobileapp.cpp
- src/core/referencingfeaturelistmodel.cpp
- src/core/referencingfeaturelistmodel.h
- src/qml/EmbeddedFeatureForm.qml
- src/qml/FeatureForm.qml
- src/qml/RelationCombobox.qml
- src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
- src/qml/editorwidgets/relationeditors/relation_editor.qml
- src/qml/qml.qrc
- test/CMakeLists.txt
- test/test_orderedrelationmodel.cpp
Like normal relation widget, but supports ordering. QField implementation of https://github.com/opengisch/qgis-ordered-relation-editor .
> Ordered relation widget

- src/core/qgsquick/qgsquickmapcanvasmap.cpp
- src/core/qgsquick/qgsquickmapsettings.cpp
This takes care of the "invalid map settings" message in QField 2.0 beta.
> A couple of qgsquick fixes

- images/images.qrc
- images/themes/qfield/nodpi/ic_arrow_left_white_24dp.svg
- src/qml/DashBoard.qml
- src/qml/PageHeader.qml
- src/qml/imports/Theme/QfToolButton.qml
A small test to get rid of the almost black buttons.
Let me know what you think
> Less obtrusive buttons

- src/core/identifytool.cpp
> Add all expression scopes when identifying

- src/qml/FeatureForm.qml
Follow up on the recent work by @m-kuhn to enhance looks of our navigation bar.
> Silence an harmless warning in FeatureForm.qml

- .github/workflows/ios.yml
- .github/workflows/windows.yml
- scripts/ci/env_gh.sh
for [ios](https://github.com/opengisch/QField/runs/2817661054?check_suite_focus=true#step:9:26) and [windows](https://github.com/opengisch/QField/runs/2914465844?check_suite_focus=true#step:15:59)
> Fix release scripts

- src/core/featuremodel.h
> Alert, uninitiated pointer spotted

- src/core/qgsquick/qgsquickmapsettings.cpp
> Fix qgsquickmapsettings typo

- src/core/qgismobileapp.cpp
- src/core/utils/geometryutils.cpp
- src/core/utils/geometryutils.h
- src/qml/editorwidgets/Range.qml
- test/test_geometryutils.cpp
This PR fixes #2074 . Bonus included: QField compiles against QGIS master again.
> Fix range edit widget slider mode

- .github/workflows/astyle.yml
- .github/workflows/ios.yml
- .github/workflows/vcpkg.yml
- CMakeLists.txt
- src/core/deltafilewrapper.cpp
- src/core/deltafilewrapper.h
- src/core/qgsquick/qgsquickmapcanvasmap.cpp
- src/core/utils/qfieldcloudutils.cpp
- src/core/utils/qfieldcloudutils.h
- src/core/vertexmodel.cpp
- src/core/vertexmodel.h
- test/CMakeLists.txt
- test/catch2.h
- test/test_attributeformmodel.cpp
- test/test_deltafilewrapper.cpp
- test/test_digitizinglogger.cpp
- test/test_featureutils.cpp
- test/test_fileutils.cpp
- test/test_geometryutils.cpp
- test/test_layerobserver.cpp
- test/test_stringutils.cpp
- test/test_urlutils.cpp
- test/test_vertexmodel.cpp
- vcpkg.json
It's cleaner and offers better output
> Switch some tests to the catch2 framework

- src/qml/editorwidgets/RelationReference.qml
- src/qml/editorwidgets/ValueRelation.qml
Hopefully this is the last regression from the much needed signal confusion fix applied some days ago.
> Fix relation reference / value relation editor widgets not updating values

- src/core/featurelistmodel.cpp
… when preparing a new one.
This fixes #2090 on my machine, and I suspect a bunch more. @m-kuhn , you mentioned a postgis crash too, was there an open issue?
> Fix feature list model crashes by gracefully handling pre-existing running gatherer

- src/qml/editorwidgets/ExternalResource.qml
This has been on my list of things to improve for a *long time*. This PR (greatly) improves the external resource widget's image mode UI/UX. First, screencast:
https://user-images.githubusercontent.com/1728657/130169624-c95e2fdb-b337-4ec0-be3c-95d01ccf067a.mp4
Improvements above include:
- a fixed height to better handled mixed landscape/portrait images
- an auto expand images to fit as much of the available space as possible (i.e., no more fixed 220 width), this looks _especially good_ for landscape images
- center displayed image
- in edit mode, move action buttons to sit at the top of the widget, preventing needless scrolls to reach those actions
- action buttons now show an animation when pressed
> Further improvements to the external resource's image mode UI/UX

- resources/demo_projects/advanced_bee_farming.qgs
- resources/demo_projects/live_qfield_users_survey.qgs
- resources/demo_projects/simple_bee_farming.qgs
> Use the most generic font and get rid of yellow annoyance saying font is not available

- src/core/layertreemodel.cpp
- src/qml/LayerTreeItemProperties.qml
@lindacamathias , this fixes the issue you reported (#1961).
> Insure that the show feature count works under all scenarios

- sdk.conf
A run of APKs to test things out.
> Major SDK update (QGIS, GDAL, PROJ, sqlite, etc.)

- src/core/utils/layerutils.cpp
Fix #2111 . @nirvn thanks for the detailed report.
> Fix delete the selected single feature

- sdk.conf
This seems to be a nice pair of libraries to land on for QField 2.0 final. Both non .0 solid releases.
> Update SDK (gdal 3.3.2, PROJ 8.1.1)

- src/core/qgsquick/qgsquickmapcanvasmap.cpp
> Unlock rendering of projects' main annotation layer onto the canvas

- src/core/qfieldcloudprojectsmodel.cpp
@m-kuhn from your commit in PR #2143
> add missing const

- .github/workflows/ios.yml
- cmake/FindQGIS.cmake
this brings Qt 5.15 + QGIS closer to master with auth methods
> upgrade SDK on iOS

- .github/workflows/ios.yml
- cmake/FindQGIS.cmake
> Revert "upgrade SDK on iOS"

- .github/workflows/ios.yml
this should fix the current failing jobs on CI
> revert to Release on iOS CI

- src/app/main.cpp
@suricactus , this fixes the issue I was mentioning in chat
> Avoid double loading of translation assets

- .github/workflows/ios.yml
thanks to having translations handled in build
> no more need to install Qt on iOS

- .github/workflows/vcpkg.yml
> Pull translation _before_ executing cmake

- CMakeLists.txt
> Fix missing providers, add authmethod plugins

- src/qml/editorwidgets/ExternalResource.qml
@m-kuhn , part 1 or hopefully 1 part ;)
> If we can't do native, don't do native ;)

- src/core/deltafilewrapper.cpp
- test/test_deltafilewrapper.cpp
Better be explicit than implicit. Also rename it using the boolean convention with is_ prefix.
It makes the validation on the server side easier too.
> Add the snapshot flag to the "new" in the deltafile too

- src/qml/editorwidgets/ExternalResource.qml
> [Backport release-1_10] Fix non-native camera button MIA in 1.10 (fixes #2262)

- .github/workflows/ios.yml
- src/core/feedback.cpp
- src/core/feedback.h
- src/core/platforms/android/androidplatformutilities.cpp
- src/core/utils/fileutils.cpp
> [Backport release-1_10] Only mark copying of assets to the share folder as done when we know it was successful

- sdk.conf
> [Backport release-1_10] Update OSGeo4A to fix a spatialite views regression

- src/core/layertreemapcanvasbridge.cpp
- src/core/projectinfo.cpp
- src/qml/DashBoard.qml
- src/qml/LayerTreeItemProperties.qml
> [Backport release-1_10] When manually hiding/showing layers, set map theme to none

- .github/workflows/android.yml
- platform/android/AndroidManifest.xml.in
- platform/android/res/values/strings.xml
- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- platform/android/src/ch/opengis/qfield/QFieldProjectListItem.java
Expect failures before success...
> Android 11+ storage handling

- .github/workflows/android.yml
> Add missing arches APKs from automated fairy commit message

- CMakeLists.txt
> Bump cmake minimum version to 3.15

- src/qml/qgismobileapp.qml
This fixes https://github.com/opengisch/QField/issues/2276 , thanks for reporting @lp-dj.
> Fix freehand digitizing not available when adding child geometries

- src/core/attributeformmodelbase.cpp
This fixes https://github.com/opengisch/QField/issues/2268 .
> Respect relation label configuration

- .github/workflows/vcpkg.yml
- vcpkg/overlay/qca/vcpkg.json
- vcpkg/overlay_system_qt/qtkeychain/CONTROL
Fix stylus on ~windows~ linux anc macos
> Qt version 5.14.2

- .github/workflows/vcpkg.yml
- src/app/CMakeLists.txt
- test/spix/conftest.py
This will make sure the released binaries do not have an open port with remote control functionality
> Separate spix test

- .github/workflows/android.yml
- .github/workflows/vcpkg.yml
- CMakeLists.txt
- cmake/NuGet.Config.in
- cmake/VcpkgToolchain.cmake
- src/app/CMakeLists.txt
- vcpkg/overlay/qca/vcpkg.json
- vcpkg/overlay_system_qt/proj4/vcpkg.json
Encapsulates nuget logic and overlay logic inside cmake
Credits to @Hoikas
> Create a dedicated vcpkg toolchain

- CMakeLists.txt
- remove osgeo4a leftovers
- only include required Quick parts of QtMultiMedia
> Cleanup CMake

- src/qml/QFieldCloudPopup.qml
This error persisted across projects. No longer the case.
> Fix errors happened in the previous project being still visible if when a a new project is opened

- src/core/qfieldcloudprojectsmodel.cpp
- src/qml/QFieldCloudPopup.qml
- src/qml/QFieldCloudScreen.qml
> Remove cloud project from the recent projects when removed from the cloud projects list

- .github/workflows/code_layout.yml
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
> Fix favorite folders name

- src/core/attributeformmodelbase.cpp
@lucienicolier , this should fix the issue we discussed on clickup.
> Do not make fields with 'live' default values on update read only, some scenarios require editing

- src/qml/DigitizingToolbar.qml
> Don't make a big deal of cancelling a measurement

- src/core/CMakeLists.txt
- src/core/locator/bookmarklocatorfilter.cpp
- src/core/locator/bookmarklocatorfilter.h
- src/core/locator/locatormodelsuperbridge.cpp
- src/core/locator/locatormodelsuperbridge.h
- src/qml/LocatorItem.qml
Part 2 of the bookmark support implementation in QField:
> Add bookmark locator filter to QField's search bar

- src/qml/qgismobileapp.qml
> Ensure window is on screen

- src/qml/LayerTreeItemProperties.qml
Until now clicking the button does not show anything and feels broken.
> If a layer is empty and pressing feature list display should notify the layer is empty

- platform/android/AndroidManifest.xml.in
- platform/android/src/ch/opengis/qfield/QFieldActivity.java
Unlocks importing of data from Google Hangout / Google Meet et al.
> Add support for importing datasets/archived projects via ACTION_SEND

- .github/workflows/vcpkg.yml
- src/core/qgssggeometry.cpp
> Safety check for nullpointer

- platform/android/res/values/strings.xml
- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
Fix ~~a~~two crashers reported on sentry (:heart:)
> Fix when attempting to get absolute path of disconnected external storage

- .pre-commit-config.yaml
- .zenodo.json
I added everyone with more than 50 commits to the list.
@nirvn @3nids @mbernasocchi @signedav @suricactus if you also want an orcid, you can get one here: https://orcid.org/
> Add .zenodo.json

- .github/workflows/android.yml
- src/core/platforms/android/androidplatformutilities.cpp
- src/core/platforms/android/androidplatformutilities.h
- src/core/platforms/ios/iosplatformutilities.h
- src/core/platforms/ios/iosplatformutilities.mm
- src/core/platforms/platformutilities.cpp
- src/core/platforms/platformutilities.h
- src/qml/MessageLog.qml
> Do not build sentry on production APKs & hide UI element

- .github/workflows/ios.yml
> Add missing quotes in the iOS workflow yml

- .github/workflows/android.yml
- .github/workflows/desktop.yml
This reverts commit 5faf3863c0517d88917a7a2a891e1ec0936fdeb1, reversing
changes made to fa0972adee6ef75abbe45a7f081f6346edbb0717.
Let's see.
> Revert "Merge pull request #2442 from opengisch/fix_macos_release"

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
> Fix QField crash when trying to open an extensionless file

- .github/workflows/android.yml
- platform/android/CPackAndroidDeployQt.cmake.in
- scripts/build-vcpkg.sh
Move from ci workflow into cmake
We shouldn't have to do that in every build pipeline
> Bandaid for https://bugreports.qt.io/browse/QTBUG-84302

- src/core/qfieldcloudconnection.cpp
Prevent this kind of fun :)
|-|-|
| ![image](https://user-images.githubusercontent.com/2820439/153709709-6665e6be-ef0c-4503-b724-8f899428717b.png) | ![image](https://user-images.githubusercontent.com/2820439/153709761-de5f1dac-ef50-4768-aafc-99959cecbf3c.png) |
> Strip HTML from HTTP response

- cmake/Package.cmake
References https://github.com/opengisch/QField/issues/2492
> Link to /usr/bin

- platform/android/AndroidManifest.xml.in
- platform/android/build.gradle.in
- platform/android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
> Update camera for Android 11

- src/qml/QFieldCloudPopup.qml
> Show that the QFieldCloud project has no connection if currently logged in with another user

- src/qml/qgismobileapp.qml
@suricactus , a small follow up to the cloud PR I merged earlier today. I accidentally broke editing and feature addition on all non-cloud projects :fearful:
> Fix missing edit / insert actions on non-cloud projects

- src/qml/qgismobileapp.qml
@bettellam , this should fix the regression you spotted, thanks for testing.
> Fix missing digitizing toolbar when... digitizing

- src/qml/QFieldCloudPopup.qml
This fixes the following:
@suricactus , ping.
> Fix glitch in the QFieldCloud project panel

- src/qml/QFieldCloudLogin.qml
@suricactus , release-2_0 backport of the login -> sign in commit
> Harmonize the sign in button label across all qfieldcloud tools, QField part

- src/core/screendimmer.cpp
> [Backport release-2_0] Avoid dimming when moving mouse / pen around the screen

- src/core/qgismobileapp.cpp
- src/core/qgismobileapp.h
Small fix for the initial bookmark implementation shipped in 2.0
> Use QgsApplication bookmark manager

- images/images.qrc
- images/themes/qfield/nodpi/ic_place_white_24dp.svg
- src/qml/BookmarkRenderer.qml
> [Backport release-2_0] Improve bookmark marker by using a Shape item instead of an SVG

- src/qml/qgismobileapp.qml
> [Backport release-2_0] Fix longstanding regression whereas length/area information is missing when digitizing features

- src/core/qgismobileapp.cpp
Backport #2609
**Authored by:** @signedav
> [Backport release-2_0] Print pdfs to the project folder

- src/qml/TemporalProperties.qml
- src/qml/imports/Theme/QfTextField.qml
Do the Right Ting (TM) and use the QfTextField item in the temporal properties panel.
> Tiny improvements to QfTextField, use it in the temporal properties panel

- index.html
to the documentation.
this PR depends on https://github.com/opengisch/QField-docs/pull/184/
> move contribute section

- .tx/config
- i18n/qfield_bg.ts
- i18n/qfield_bs.ts
- i18n/qfield_en.ts
- i18n/qfield_es.ts
- i18n/qfield_fi.ts
- i18n/qfield_fr.ts
- i18n/qfield_gl.ts
- i18n/qfield_hu.ts
- i18n/qfield_ja.ts
- i18n/qfield_pl.ts
- i18n/qfield_pt.ts
- i18n/qfield_pt_BR.ts
- i18n/qfield_ru.ts
- i18n/qfield_tr.ts
- i18n/qfield_uk.ts
- i18n/qfield_zh.ts
Manual backport of up-to-date translations from transifex for the 2.0 final release.
> Update translations for 2.0 release

- .github/workflows/android.yml
- CMakeLists.txt
- platform/android/AndroidManifest.xml.in
- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- src/app/CMakeLists.txt
- src/app/main.cpp
- src/core/CMakeLists.txt
- src/core/platforms/android/androidplatformutilities.cpp
- src/core/platforms/android/androidplatformutilities.h
- src/core/platforms/platformutilities.cpp
- src/core/platforms/platformutilities.h
- src/qml/MessageLog.qml
- src/qml/QFieldSettings.qml
- src/qml/WelcomeScreen.qml
This PR implements a UI to opt out of sentry anonymized crash reports.
> Sentry opt-out implementation

- src/core/qgismobileapp.cpp
Likely fix https://github.com/opengisch/QField/discussions/2235 .
> Test both existance and readability of the QField (root) data dir

- src/core/qgismobileapp.cpp
Makes no sense to assert a pointer validity _after_ using it :)
> Move assert to its righteous place

- src/core/qgismobileapp.cpp
> [Backport release-2_0] Move assert to its righteous place

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- platform/android/src/ch/opengis/qfield/QFieldUtils.java
> [Backport release-2_0] Fix java crasher seen on sentry

- .github/workflows/desktop.yml
- .github/workflows/ios.yml
> Fix macos builds

- .github/workflows/desktop.yml
- .github/workflows/ios.yml
> [Backport release-2_0] Fix macos builds

- src/qml/LocationMarker.qml
- src/qml/NavigationRenderer.qml
Small PR to insure various overlay markers (navigation and location related) are properly antialiased and their stroke not cropped off. We want how arrows to look sharp and great.
> Improve various overlay antialiasing and ensure stroke not cropped

- src/qml/geometry_editors/FillRingToolBar.qml
@signedav , that should fix the ring tool issue you reported. Thanks for spotting it.
> Reset rubber band upon a failed ring operation (fixes #2567)

- src/qml/geometry_editors/FillRingToolBar.qml
> [Backport release-2_0] Reset rubber band upon a failed ring operation (fixes #2567)

- src/core/linepolygonhighlight.cpp
- src/qml/GeometryRenderer.qml
- src/qml/NavigationHighlight.qml
This simplifies things a lot, avoids us forgetting it in the future, and is really just The Right Thing To Do (TM).
> Move devicePixelRatio logic out of QML into the LinePolygonHighlight class

- src/qml/Legend.qml
Because we :heart: being touch screen friendly :wink:
> Add some {top,bottom} padding to legend items to slightly increase the hit area for long presses

- src/qml/RelationCombobox.qml
- src/qml/editorwidgets/RelationReference.qml
- src/qml/editorwidgets/ValueRelation.qml
> [Backport release-2_0] Do not double-compile value relation feature lists

- src/qml/BookmarkProperties.qml
> Improve and harmonize bookmark properties panel looks

- src/core/qgssggeometry.cpp
- src/core/sgrubberband.cpp
This is a regression that appeared when we moved our code to use the QgsTessellator class.
This now displays properly again:
Same fix applied to polygon highlights:
@m-kuhn , I think this fixes something you'd mentioned to me forever ago.
> Fix broken rubberband / highlight with self-intersecting polygon geometry

- src/core/qgssggeometry.cpp
- src/core/sgrubberband.cpp
> [Backport release-2_0] Fix broken rubberband / highlight with self-intersecting polygon geometry

- .pre-commit-config.yaml
> [Backport release-2_0] Bump black version

- vcpkg/triplets/arm-android.cmake
- vcpkg/triplets/arm64-android.cmake
- vcpkg/triplets/x64-android.cmake
- vcpkg/triplets/x86-android.cmake
Extracting lessons learned from the ongoing asan adventure.
> Add stack protector strong

- src/qml/About.qml
- src/qml/WelcomeScreen.qml
- src/qml/imports/Theme/QfButton.qml
- src/qml/qgismobileapp.qml
> [Backport release-2_0] Further improve the metrics popup, re-asks to get a clear(er) answer

- src/core/platforms/android/androidplatformutilities.cpp
- src/qml/SystemLoader.qml
> [Backport release-2_0] Remove crash prone feedback connection in the system loader scene

- platform/android/src/ch/opengis/qfield/QFieldUtils.java
> [Backport release-2_0] Avoid crashing when parsing a DownloadsProvider URI with a non-numerical ID

- src/core/qgsquick/qgsquickcoordinatetransformer.cpp
> [Backport release-2_0] Fix broken vertical grid adjustment regression

- src/qml/BookmarkHighlight.qml
- src/qml/QFieldSettings.qml
> Add a setting to disable display of bookmarks on the map

- src/qml/BookmarkHighlight.qml
- src/qml/QFieldSettings.qml
> [Backport release-2_0] Add a setting to disable display of bookmarks on the map

- platform/android/res/menu/project_folder_menu.xml
- platform/android/res/menu/project_item_menu.xml
- platform/android/res/values/strings.xml
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
- platform/android/src/ch/opengis/qfield/QFieldProjectListAdapter.java
- platform/android/src/ch/opengis/qfield/QFieldUtils.java
> [Backport release-2_0] Implement send compressed folder and export project folder [to folder] functionality

- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
> [Backport release-2_0] Add a up/back button in the open local project/dataset activity navigation bar

- src/qml/WelcomeScreen.qml
> OK -> I agree

- src/qml/WelcomeScreen.qml
> [Backport release-2_0] OK -> I agree

- src/qml/NavigationBar.qml
> Fix focused feature issue when running out of features hitting previous/next buttons

- platform/android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
- platform/android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
Code de-duplication, best practices learn on the storage front applied here, and reliance on QFieldUtils to copy documents/files.
> Improve and cleanup camera and gallery activities

- src/qml/NavigationBar.qml
> [Backport release-2_0] Fix focused feature issue when running out of features hitting previous/next buttons

- src/core/rubberband.cpp
- src/core/rubberband.h
- src/core/sgrubberband.cpp
- src/core/sgrubberband.h
- src/qml/qgismobileapp.qml
> [Backport release-2_0] Insure that our rubber bands take device pixel ratio into account to harmonize rendering on all screen densities

- platform/android/AndroidManifest.xml.in
- platform/android/build.gradle.in
- platform/android/res/values/colors.xml
- platform/android/res/values/strings.xml
- platform/android/res/values/styles.xml
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
> [Backport release-2_0] Storage help

- src/qml/qgismobileapp.qml
> Implement a fullscreen mode on desktop, toggled via F11

- src/qml/imports/Theme/QfButton.qml
@suricactus , thanks for spotting this one.
> Fix QfButton disabled state's border color

- platform/android/res/values/strings.xml
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
> [Backport release-2_0] Cleanups

- src/qml/imports/Theme/QfButton.qml
> [Backport release-2_0] Fix QfButton disabled state's border color

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
- platform/android/src/ch/opengis/qfield/QFieldUtils.java
> [Backport release-2_0] Fix QField unable to import project from a number of ZIP files, rename functions

- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
> [Backport release-2_0] Fix back button following migration to AppCompatActivity

- src/core/changelogcontents.cpp
- if the current changelog candidates consist only "prereleases", then show only the prereleases
- if the current changelog candidates consist at least one "release" (no pre-), then show releases
and the order can be controlled whether we are updating from patch or minor version:
- patch - newest first
- minor - oldest first
| from 1.10.0 to 2.0.16 | from 2.0.15 to 2.0.16 |
|-|-|
| ![image](https://user-images.githubusercontent.com/2820439/164590660-1c899dea-b2fd-4bbd-9bf7-b7495b07a58d.png) | ![image](https://user-images.githubusercontent.com/2820439/164591145-2caeee8a-6d48-4da6-af5a-544803dcafc7.png) |
> Changelog ordering improvements

- src/core/changelogcontents.cpp
> [Backport release-2_0] Changelog ordering improvements

- src/core/changelogcontents.cpp
> [Backport release-2_1] Changelog ordering improvements

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- src/core/platforms/android/androidplatformutilities.cpp
- src/core/utils/fileutils.cpp
- src/core/utils/fileutils.h
> [Backport release-2_1] Fix virtual keyboard not opening when first launching QField on Android platform

- src/core/qgismobileapp.cpp
- src/qml/About.qml
- src/qml/QFieldCloudLogin.qml
- src/qml/QFieldCloudPopup.qml
- src/qml/QFieldSettings.qml
> [Backport release-2_1] Set a nice QField-green default app-wide hyperlink color

- src/core/qgismobileapp.cpp
> [Backport release-2_1] Improve .pg_service.conf logic, prioritize the more secure location

- platform/android/AndroidManifest.xml.in
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
- src/core/qgismobileapp.h
> Add missing handling of .tiff extension

- platform/android/AndroidManifest.xml.in
- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
- src/core/qgismobileapp.h
> [Backport release-2_1] Add missing handling of .tiff extension

- src/qml/QFieldCloudLogin.qml
- src/qml/qgismobileapp.qml
And also a bit of log/sign in/out harmonization.
> Hide the "New user?" registration link if already signed in

- src/qml/QFieldCloudLogin.qml
- src/qml/qgismobileapp.qml
> [Backport release-2_1] Hide the "New user?" registration link if already signed in

- src/qml/Changelog.qml
> [Backport release-2_1] Always show the changelog once per version update

- src/qml/qgismobileapp.qml
> [Backport release-2_1] Append CRS informatio when copying map canvas point/position  location to the clipboard

- src/qml/QFieldSettings.qml
- src/qml/RelationCombobox.qml
- src/qml/Tracking.qml
- src/qml/VariableEditor.qml
- src/qml/editorwidgets/CheckBox.qml
- src/qml/editorwidgets/DateTime.qml
- src/qml/editorwidgets/ExternalResource.qml
- src/qml/editorwidgets/Range.qml
- src/qml/editorwidgets/TextEdit.qml
- src/qml/editorwidgets/UuidGenerator.qml
- src/qml/editorwidgets/ValueMap.qml
- src/qml/imports/Theme/QfTextField.qml
- src/qml/imports/Theme/Theme.qml
> [Backport release-2_1] User proper accentLightColor for the image frame

- .github/ISSUE_TEMPLATE.md
I have updated the issue template to match the challanges of modern times, such as mobile OS name, QFieldCloud additional info etc.
> Update the issue template with additional information

- src/core/multifeaturelistmodelbase.cpp
- src/qml/Legend.qml
- src/qml/NavigationBar.qml
- src/qml/qgismobileapp.qml
Also consistency with hiding menu items if they are disabled.
> Make sure the "Locked Geometry" setting is respected when adding/deleting/duplicating/moving features

- src/core/multifeaturelistmodelbase.cpp
- src/qml/Legend.qml
- src/qml/NavigationBar.qml
- src/qml/qgismobileapp.qml
> [Backport release-2_1] Make sure the "Locked Geometry" setting is respected when adding/deleting/duplicating/moving features

- src/qml/editorwidgets/RelationReference.qml
This should fix https://github.com/opengisch/QField/issues/2833 -- my bad.
> Fix broken view relation feature button regression

- src/qml/editorwidgets/RelationReference.qml
> [Backport release-2_1] Fix broken view relation feature button regression

- README.md
> Fix sponsorship link

- CMakeLists.txt
- platform/android/src/ch/opengis/qfield/QFieldProjectListAdapter.java
- src/core/platforms/android/androidplatformutilities.cpp
Screencast:
https://user-images.githubusercontent.com/1728657/166442966-8a7ac369-bc23-40f8-9b5d-bd8893617b70.mp4
Can be quite useful when trying to find back a dataset that was imported a while back, or even look for specific image attachment(s) within a project folder.
> Display {jpg,png,tif,webp,pdf} thumbnails in the project/dataset picker activity

- platform/android/src/ch/opengis/qfield/QFieldUtils.java
> [Backport release-2_1] Guard from a ZIP path traversal attack

- src/core/qgismobileapp.cpp
This fixes the following regression reported in a comment (https://github.com/opengisch/QField/pull/2808#issuecomment-1120751553).
> Fix PGSYSCONFIGDIR handling

- src/core/qgismobileapp.cpp
> [Backport release-2_1] Fix PGSYSCONFIGDIR handling

- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
- src/core/qgismobileapp.h
> Add missing handling of .jpeg extension

- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
- src/core/qgismobileapp.h
> [Backport release-2_1] Add missing handling of .jpeg extension

- platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
> [Backport release-2_1] Slightly improve handling of removal (sd card) storage in the project dataset picker

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- src/core/platforms/android/androidplatformutilities.cpp
- src/core/platforms/android/androidplatformutilities.h
- src/core/platforms/platformutilities.cpp
- src/core/platforms/platformutilities.h
- src/core/qgismobileapp.cpp
- src/core/qgsquick/qgsquickcoordinatetransformer.cpp
- src/qml/About.qml
> [Backport release-2_1] Handle _all_ external dirs as potential QField data dirs

- src/core/bookmarkmodel.cpp
- src/core/bookmarkmodel.h
- src/qml/BookmarkProperties.qml
- src/qml/imports/Theme/Theme.qml
> [Backport release-2_1] Allow copying bookmark details to clipboard, plus usuability improvements

- README.md
> Homogenize badges

- src/app/main.cpp
> [Backport release-2_1] Do *not* use qgis data directory as profile directory

- src/qml/LocationMarker.qml
> Fix compass on rotated screen

- src/qml/LocationMarker.qml
> [Backport release-2_1] Fix compass on rotated screen

- src/qml/LocatorItem.qml
Most of the time, that's most wanted :)
> When triggering a search result action (i.e. right-end buttons), close the search result

- src/core/qgismobileapp.cpp
Well, that went unnoticed for a while, and I'm the guilty soul.
> Fix versions-old regression on project file fonts loading

- src/core/qgismobileapp.cpp
> [Backport release-2_1] Fix versions-old regression on project file fonts loading

- src/qml/LocatorItem.qml
… with features gone missing, map CRS changed, etc.
> Clear any search bar results when a new project is loaded to avoid issues

- src/qml/LocatorItem.qml
> [Backport release-2_1] Clear any search bar results when a new project is loaded to avoid issues

- src/core/layertreemodel.cpp
- src/qml/LayerTreeItemProperties.qml
@suricactus , follow up on your feature.
> Fix zoom to layer/group not using proper index, not working on layer symbol legend items

- src/qml/BookmarkProperties.qml
- src/qml/DigitizingToolbar.qml
- src/qml/PageHeader.qml
- src/qml/QFieldLocalDataPickerScreen.qml
- src/qml/qgismobileapp.qml
@marioba , as discussed yesterday evening.
> Averaged position follow up

- src/core/localfilesimageprovider.cpp
- src/core/localfilesimageprovider.h
- src/core/localfilesmodel.cpp
- src/core/localfilesmodel.h
- src/qml/QFieldLocalDataPickerScreen.qml
- PDF, unlocked
- JP2, unlocked
:heart:
> Use gdal to produce raster thumbnails

- .github/workflows/android.yml
This causes an interactive progress bar to be shown on many hundred lines in the log
> Declutter logs

- src/core/featurelistextentcontroller.cpp
- src/qml/LayerTreeItemProperties.qml
This should fix https://github.com/opengisch/QField/issues/2973
> Fix broken map canvas when hitting show features list with table layers

- src/qml/editorwidgets/Range.qml
- src/qml/editorwidgets/TextEdit.qml
This PR fixes #2972 as well as #2531 and #2936 (the latter both being the same issue).
> A couple of editor widget fixes

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
Follow up to https://github.com/opengisch/QField/pull/2978 , missed one alert dialog creation instance.
> Missed on android alert dialog in need of modern layout

- src/qml/QFieldLocalDataPickerScreen.qml
- src/qml/WelcomeScreen.qml
- src/qml/qgismobileapp.qml
Our good old friend mr focus at it again.
> Fix a couple of focus issues (yes, again) with the local data picker screen

- src/qml/qgismobileapp.qml
Fix regression caused by https://github.com/opengisch/QField/commit/735f0ac712c80bda8703a416a89a6fc7bb5aa5ba
> Fix message log model typo

- src/core/appinterface.cpp
- src/core/appinterface.h
- src/qml/imports/Theme/QfToolButton.qml
It's useful for debugging, especially when trying to help people remotely, to have a method to send log messages from within QML via iface.logMessage('blah').
> Add an iface function to print log messages

- src/qml/qgismobileapp.qml
A couple of tweaks on UI bits of the precise view feature. 
(This first commit also fixes a string formatting issue raised by one of our translator @phidrho , thanks to him for his report on transifex.)
> Precise view follow up tweaks

- src/qml/qgismobileapp.qml
> Fix long press add vertex's averaged position issue with touch screens

- src/core/qgsquick/qgsquickmapsettings.cpp
> Add safeguards to insure the map canvas' extent never gets to weird/broken values

- src/core/positioning/internalgnssreceiver.cpp
- src/core/positioning/internalgnssreceiver.h
> [Backport release-2_2] QField :heart: satellites

- src/core/positioning/internalgnssreceiver.cpp
A couple of fixes that came to me while asleep :wink:
> Satellites follow up

- vcpkg/triplets/arm-android.cmake
- vcpkg/triplets/arm-neon-android.cmake
Let's produce some APKs to see if we can do that without regressing.
> Switch CRT linkage back to dynamic on arm platform

- src/core/positioning/internalgnssreceiver.cpp
> [Backport release-2_2] Satellites follow up

- src/core/featuremodel.cpp
> [Backport release-2_2] Avoid crashing by checking whether there's a geometry to constGet

- .gitignore
- cmake/Package.cmake
no idea why but I have these files added when I build for iOS....???
create mode 100644 platform/android/AndroidManifest.xml
create mode 100644 platform/android/build.gradle
create mode 100644 platform/android/generated.xml
easy fix in .gitignore
> fix .gitignore

- src/qml/editorwidgets/TextEdit.qml
Discovered while preparing the animated project demo.
> Harmonize read-only gray text for multi line and single line text editor widget

- src/core/qgsquick/qgsquickmapcanvasmap.cpp
> [Backport release-2_2] [qgsquick] Fix silent refresh not sticking until the end of a refresh cycle

- src/qml/editorwidgets/TextEdit.qml
> [Backport release-2_2] Harmonize read-only gray text for multi line and single line text editor widget

- src/qml/BluetoothDeviceChooser.qml
> Fix string issue in the QML bluetooth device chooser item

- src/core/localfilesmodel.cpp
> Match suffix against suffix when building the local files model

- src/core/localfilesmodel.cpp
> [Backport release-2_2] Match suffix against suffix when building the local files model

- src/core/localfilesmodel.cpp
> [Backport release-2_2] Use the complete base name string for project files and datasets

- src/qml/CMakeLists.txt
Fixes https://github.com/opengisch/QField/issues/3062
> Fix static lib with Debug build

- src/app/CMakeLists.txt
- src/app/main.cpp
Fixes https://github.com/opengisch/QField/issues/3074
> Set proj path via api

- src/app/main.cpp
Quick follow up on the proj path update committed yesterday.
> Fix linux builds against system proj

- src/app/CMakeLists.txt
- vcpkg/overlay/qgis/vcpkg.json
Unrelated change: set the qgis version to "current" because no one ever thought of updating this to keep it in sync.
> Fix svg images on ios

- src/core/positioning/internalgnssreceiver.cpp
@m-kuhn , backport of your fix.
> Fix posioning crash on devices with missing satellite information capabilities

- src/core/vertexmodel.cpp
- src/core/vertexmodel.h
- test/test_vertexmodel.cpp
> [Backport release-2_2] Fix serious brokenness with vertex editor mishandling ZM geometries

- src/core/platforms/platformutilities.cpp
- src/core/platforms/platformutilities.h
Who knows, might come in handy sooner than you'd think! ;)
> Add a platform utilities function to retrieve text from the system clipboard

- src/qml/editorwidgets/TextEdit.qml
> QField has for too long auto-detected HTML irrespective of the settings, let's continue

- src/qml/editorwidgets/TextEdit.qml
> [Backport release-2_2] QField has for too long auto-detected HTML irrespective of the settings, let's continue

- src/core/multifeaturelistmodelbase.cpp
> [Backport release-2_2] Harden the selected feature check in the multi feature list model

- .github/workflows/ios.yml
> Fix ios dev builds from branches

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
Fixes https://sentry.io/organizations/opengisch/issues/3409948078/?project=6119013&query=is%3Aunresolved+release%3A%22ch.opengis.qfield%402.2.1+-+Coordinated+Capybara%2B2020199%2A%22&sort=freq&statsPeriod=7d
> Fix a java top 10 crasher reported on sentry

- src/core/qgssggeometry.cpp
- src/core/sgrubberband.cpp
> Add some debug output to catch crashy polygon WKT strings

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
> [Backport release-2_2] Fix a java top 10 crasher reported on sentry

- src/core/layertreemodel.cpp
> [Backport release-2_2] Insure that private layers are not added to the legend (fixes #3154)

- src/core/qgismobileapp.cpp
- src/core/qgismobileapp.h
Hopefully fixes a crash or two at exit
> Call exitQgis to properly exit

- src/qml/qgismobileapp.qml
> [Backport release-2_2] Fix resetting attributes on creation issue

- .github/workflows/sync-translations.yml
- scripts/ci/pull_translations.sh
> Remove line numbers from translations

- .github/workflows/sync-translations.yml
- scripts/ci/pull_translations.sh
Pulling translations was broken because of a wrong base path
> Fix translation path

- .github/workflows/code_layout.yml
Some deps fail to install in the cpanverse
> Disable failing test

- CMakeLists.txt
- src/app/main.cpp
- src/core/platforms/platformutilities.cpp
- src/qml/qgismobileapp.qml
This fixes install path for proj data on windows (and I assume OSX). No regression on the Android front.
> A round of windows fixes

- src/qml/DashBoard.qml
> Fix main menu position failing to take scene margin into account

- src/qml/WelcomeScreen.qml
... until we have something that works
> Disable local data picker on ios

- platform/android/AndroidManifest.xml.in
Try to make Google happy according to: https://stackoverflow.com/questions/61635589/permission-review-google-play-for-access-to-background-location
> remove android.permission.ACCESS_BACKGROUND_LOCATION

- src/qml/NavigationBar.qml
Otherwise you end up with glitches like this on Qt6 builds:
> Don't merely make buttons' width 0, hide them too

- src/core/linepolygonhighlight.cpp
- src/core/linepolygonhighlight.h
- src/core/rubberband.cpp
- src/core/rubberband.h
- src/qml/GeometryRenderer.qml
- src/qml/MeasuringTool.qml
- src/qml/NavigationHighlight.qml
- src/qml/Tracking.qml
- src/qml/qgismobileapp.qml
Why did this ever not create big problems I do not know :) 
On top of doing the right thing, this fixes rubber band and geometry highlight line width in QField.
> Do _not_ use a reserver quick item function name, thanks Qt6

- src/qml/FeatureListForm.qml
- src/qml/MapCanvas.qml
- src/qml/NavigationBar.qml
- src/qml/OverlayFeatureFormDrawer.qml
- src/qml/QFieldCloudScreen.qml
- src/qml/QFieldLocalDataPickerScreen.qml
- src/qml/QFieldSettings.qml
- src/qml/qgismobileapp.qml
It's also so clearly The Right Thing To Do (TM).
> Declare parameters for Qt6 compatibility

- src/qml/BadLayerItem.qml
- src/qml/MessageLog.qml
- src/qml/qgismobileapp.qml
@suricactus , thanks for pointing this out.
> Add a couple of scene top margin values missing

- src/core/recentprojectlistmodel.cpp
@suricactus , that'll fix your issue.
> Fix sample projects .qgs opened in linux/windows not showing up in recent projects list

- src/core/layertreemodel.cpp
Instead of calling mapToSource a dozen times and failing to check its validity half of the time, let's just do it once and safeguard from invalid source index for good.
This will fix a bunch of crashers seen on sentry (e.g. https://sentry.io/organizations/opengisch/issues/3289047312/?project=6119013)
> Always guard against invalid source index in the flat layer tree

- doc/dev.md
Because guessing them is not so fun.
> Add the Ubuntu packages that one has to guess each time

- src/core/digitizinglogger.cpp
- src/core/digitizinglogger.h
- src/core/featuremodel.cpp
- src/core/featuremodel.h
- src/core/layertreemodel.cpp
- src/core/qfieldcloudprojectsmodel.h
No more warnings when building QField. One fix was innocent, but the invalid property warning fix - I assume - was important :)
> Silence compilation warning

- src/qml/LayerTreeItemProperties.qml
The main UI difference is that the values is shown on the right.
Also, fix double feature count shown in layer properties panel.
> Make the slider opacity use the new QfSlider widget

- CONTRIBUTING.md
This is a contributing,md file I made after compiling similar files in several OSGeo projects. Big influence from the QGIS `CONTRIBUTING.md`.
@mbernasocchi @marioba @m-kuhn should be good enough.
> Added contents of CONTRIBUTING.md

- src/app/CMakeLists.txt
- src/qml/CMakeLists.txt
- src/qml/imports/QFieldControls/qmldir
- test/CMakeLists.txt
- test/qml/tst_editorwidgets.qml
Backport #3283
Fixes https://github.com/opengisch/QField/issues/3121
> [Backport release-2_3] Add a DateTime editor widget qml test

- platform/android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
@mbernasocchi , should fix your issue.
> Allow all types of image to by selected on Android's gallery

- platform/android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
> [Backport release-2_3] Allow all types of image to by selected on Android's gallery

- .github/workflows/ios.yml
> [Backport release-2_3] Disable bluetooth support on iOS, that's simply not supported by Qt

- src/app/main.cpp
> [Backport release-2_3] Move the setPkgDataPath call around so it doesn't get overwritten by initQgis

- doc/dev.md
- src/core/deltafilewrapper.cpp
- test/CMakeLists.txt
- test/test_deltafilewrapper.cpp
> [Backport release-2_3] Fix delta generation on NULL and 0

- README.md
> Images are worth a thousand words

- src/core/qfieldcloudprojectsmodel.cpp
> [Backport release-2_3] Prevent random sorting of the cloud projects

- src/qml/QFieldCloudScreen.qml
> Give a hint that the projects list is empty

- src/qml/QFieldCloudScreen.qml
> [Backport release-2_3] Give a hint that the projects list is empty

- src/core/layertreemodel.cpp
> [Backport release-2_3] Fix crash when the layer is invalid

- src/app/CMakeLists.txt
- src/app/main.cpp
- vcpkg/overlay/qca/portfile.cmake
- vcpkg/overlay/qgis-qt6/vcpkg-cmake-wrapper.cmake
- vcpkg/overlay/qgis/vcpkg-cmake-wrapper.cmake
> [Backport release-2_3] Handle static link to QCA ossl plugin on static builds

- src/qml/DashBoard.qml
> [Backport release-2_3] Fix dashboard buttons glitch on iOS

- .github/workflows/macos.yml
- .github/workflows/qt6.yml
Fixes https://github.com/opengisch/QField/issues/3315
> Switch to macos-11 runners

- .github/workflows/desktop.yml
- .github/workflows/qt6.yml
> Macos 11 for 2.3

- platform/ios/Info.plist.in
- src/core/platforms/ios/iosplatformutilities.h
- src/core/platforms/ios/iosplatformutilities.mm
- src/qml/WelcomeScreen.qml
> [Backport release-2_3] Implement basic iOS local files / project support

- src/core/qfieldcloudprojectsmodel.cpp
- src/core/qfieldcloudprojectsmodel.h
- src/qml/QFieldCloudScreen.qml
> [Backport release-2_3] Fetch public projects with a separate request

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- src/core/platforms/android/androidplatformutilities.cpp
> [Backport release-2_3] Fix status bar margin on a number of devices

- .github/workflows/ios.yml
> [Backport release-2_3] Update appstore certs

- src/qml/QFieldSettings.qml
Less noise in the console, happier world.
> Silence a QField shutdown QML error

- .github/workflows/ios.yml
> [Backport release-2_3] [ios] deploy on release

- .github/workflows/android.yml
- .github/workflows/ios.yml
- scripts/ci/env_gh.sh
> Fix event type to upload to {app|play}store

- .github/workflows/macos.yml
- src/core/platforms/platformutilities.cpp
Ultimately hoping this'll give us antialiased spix screensots.
> Enable tests (spix et cie) on OSX

- src/core/deltafilewrapper.cpp
- src/core/deltafilewrapper.h
Tested the fix locally against a Qt6 build, all green.
> Important Qt6-specific delta file wrapper fix

- src/core/layertreemodel.cpp
Identified while revamping the bees demo.
> Add safeguard for serious legend crasher (top list in sentry)

- src/core/layertreemodel.cpp
> [Backport release-2_3] Add safeguard for serious legend crasher (top list in sentry)

- platform/android/src/ch/opengis/qfield/QFieldActivity.java
- platform/android/src/ch/opengis/qfield/QFieldUtils.java
- src/core/platforms/android/androidplatformutilities.cpp
Java failures expected, local docker builds not setup yet.
> When sending/exporting datasets, insure all sidecars are taken into account

- src/qml/qgismobileapp.qml
> Permanently show freehand toggle button as soon as the screen has been hovered once

- src/qml/LocatorItem.qml
- src/qml/Nyuki.qml
- src/qml/qgismobileapp.qml
- src/qml/qml.qrc
Say hello to nyuki, he'll watch over you.
> Add regular Nyuki checks

- src/qml/qgismobileapp.qml
> [Backport release-2_4] Auto-dismiss changelog popup when project is loading (aka fix failing spix test on release page)

- src/core/positioning/abstractgnssreceiver.h
- src/core/positioning/bluetoothreceiver.cpp
- src/core/positioning/bluetoothreceiver.h
- src/core/positioning/positioning.cpp
- src/qml/BluetoothDeviceChooser.qml
- src/qml/qgismobileapp.qml
> [Backport release-2_4] Insure that the bluetooth combobox has the right item selected

- platform/ios/Info.plist.in
> [Backport release-2_4] Add more details on purpose and uses of the location permission

- .github/workflows/android.yml
- .github/workflows/ios.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/qt6.yml
- .github/workflows/windows.yml
Followup https://github.com/opengisch/QField/pull/3456, paths have changed
> Fix log path

- src/core/locator/featureslocatorfilter.cpp
> [Backport release-2_4] Fix search bar's go to point feature partially broken when layer CRS != project CRS

- src/qml/DashBoard.qml
- src/qml/FeatureListForm.qml
- src/qml/NavigationBar.qml
> Easing.OutQuart gives a much better impression of snappiness than Easing.InQuart

- src/core/qgismobileapp.cpp
I'm on tears on this one. Fixes #3471.
> Fix non-atlas printing to PDF

- src/core/qgismobileapp.cpp
> [Backport release-2_4] Fix non-atlas printing to PDF

- src/core/attributeformmodelbase.cpp
- src/core/attributeformmodelbase.h
Should address part of #3473 (the crasher).
> Avoid falling into an endless loop of default value updates

- src/core/attributeformmodelbase.cpp
- src/core/attributeformmodelbase.h
> [Backport release-2_4] Avoid falling into an endless loop of default value updates

- src/core/positioning/bluetoothreceiver.cpp
Fixes https://github.com/opengisch/QField/issues/3357
> Group NMEA updates by timestamp

- get_latest/index.html
@marioba , @m-kuhn , that's a possibility.
> By the power of javascript, I grant you the latest windows release

- cmake/FindQGIS.cmake
- src/app/main.cpp
- src/core/positioning/bluetoothdevicemodel.cpp
- src/core/qgsquick/qgsquickmapsettings.cpp
Regarding the need for gdal include when building main.cpp, see https://github.com/qgis/QGIS/commit/d51d1365ebe507e0663e708f0fe5a198fd5adddd
> Fix for building against QGIS master (3.29)

- src/core/attributeformmodelbase.cpp
> [Backport release-2_4] Update default values when editing a new feature to match QGIS behavior

- CMakeLists.txt
- platform/linux/qfield.metainfo.xml
> Appstream metainfo

- src/qml/ScreenLocker.qml
> Double screen unlocking drag threshold

- src/qml/qgismobileapp.qml
> Add a lock screen item in the map canvas menu for easy of access

- src/qml/MapCanvas.qml
- src/qml/ScreenLocker.qml
- src/qml/qgismobileapp.qml
This fixes https://github.com/opengisch/QField/issues/3534.
> Add missing PinchHandler grab in the screen locker, add interactive property to MapCanvas

- src/qml/BluetoothDeviceChooser.qml
- src/qml/BookmarkProperties.qml
- src/qml/DigitizingToolbar.qml
- src/qml/FeatureForm.qml
- src/qml/FeatureListForm.qml
- src/qml/LayerSelector.qml
- src/qml/Legend.qml
- src/qml/QFieldCloudPackageLayersFeedback.qml
- src/qml/QFieldCloudPopup.qml
- src/qml/QFieldSettings.qml
- src/qml/RelationCombobox.qml
- src/qml/editorwidgets/ValueMap.qml
- src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
- src/qml/editorwidgets/relationeditors/relation_editor.qml
- src/qml/geometry_editors/FillRingToolBar.qml
- src/qml/imports/Theme/Theme.qml
A few lessons learning while trying to have QField respect system's default font size are worth merging now.
> Cleaning up Theme handling
