opengisch/QField

src/qml/WelcomeScreen.qml

This is a tiny fix that will improve users' first impressions of the app. Bug caused by literal string concatenation without whitespace.

Insert missing spaces into Welcome Screen message

---

.gitmodules

Using public https:// instead of private git@ enables everyone to clone --recursive / submodule update. Even if they have configured a public key for github but don't have that key registered to the submodules.
Previously, "git submodule update" would try to authenticate with my public key and deny access.

changed URL to submodule repositories

---

src/qml/editorwidgets/CheckBox.qml

Because the value can be int or string - the config-states are strings.
To avoid problems with int values we cannot use strict comparison operators to get the checked value.
Fix #118

Not using strict comparison operators in js

---

src/attributeformmodelbase.cpp
src/attributeformmodelbase.h

instead of concatinating all visibilityexpression of the same level in attributeform what leaded misbehaviour
Fix #125

multilevel visibilityexpressions concatinate

---

src/attributeformmodelbase.cpp

On every change of any field ALL constraints had to be evaluated. because the constraint can depend on different fields. So I removed the check to evaluate only on the current field.
It's a fix for #87 
It looks now like this (Contraint is: "EinsS"+"ZweiS"+"DreiS"=100)

Evaluate all the field constraints on every change

---

src/qml/qgismobileapp.qml

Removed this Menu Item part, because usually a mobile app has not the functionality to quit.
When there is a "quit" the user expects something different than when pressing the back key.

Removed quit option in setting

---

src/layertreemodel.cpp

Functionality to set to visible / invisible and get the visible status for legend nodes - means in categorized etc. layers.
This avoids the crash and is a fix for #199 and mentioning in #181 and let's us display the subcategory as well. And set them visible and invisible like on QGIS.

Care about legend nodes

---

src/qml/qgismobileapp.qml

Closing in two steps. when closing the toast appears with the message, that with another closing command (back key) the project will be closed. Regarding #217 that the user does not close it accidentally.
Tested it in the debug mode:
On the app it will be the "back" key... I will test the feeling when apk is created.

On close - wait for second input

---

src/geometry.cpp
src/rubberbandmodel.cpp
src/rubberbandmodel.h

Apparently some dataproviders will refuse to save anything at all when they only have X/Y data and are provided with X,Y,Z data. Looking at you, spatialite.
Fix #233
Fix #146
Fix #135

Add/Drop Z value based on dataprovider

---

src/qgsquickmapcanvasmap.cpp
src/qgsquickmapcanvasmap.h

the internal previous approach caused crashes when called too quickly (during navigation).

Use QgsMapRendererJob::cancelWithoutBlocking

---

src/platformutilities.cpp
src/platformutilities.h
src/qml/editorwidgets/TextEdit.qml

The new approach is based on the field type. The previous approach relied on precision which was reported differently, in particular ogr and spatialite would happily return 0 precision for double values.
Fix #197

Allow entering decimals in all double fields

---

src/platformutilities.cpp
src/platformutilities.h
src/qml/FeatureForm.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/qgismobileapp.qml

1. Photos are now named in the format YYYYMMDDHHmmSSsss.jpg and in the relative path DCIM/<imagename> Fix #256 
2. The settings for the native camera are read directly and are not looped over featureforms.
3. Fix of small bug when using native camera that in the background the new camera implementation appeared.

Photo path improvements and camera fixes

---

src/main.cpp

Then Qt handles the whole background with path, prefix and conf-file.
Issue was, that the settings haven't been stored and read. This leaded to the issue, that the project cannot be opened automatically again on reactivate QField from standby mode. With the NativeFormat instead of IniFormat it says in the [QSettings](http://doc.qt.io/qt-5/qsettings.html) specification.
> On Unix, NativeFormat and IniFormat mean the same thing, except that the file extension is different (.conf for NativeFormat, .ini for IniFormat).
And with NativeFormat there is no problem with the prefix path and so the issue #254 should be fixed.

Set QSettings format to NativeFormat

---

src/focusstack.cpp
src/focusstack.h
src/qgismobileapp.cpp
src/qgismobileapp.h
src/qml/FeatureListForm.qml
src/qml/qgismobileapp.qml
src/src.pro

The focusstack is a QList() implementation that handles the items requesting a focus in a stack.
On creation the items "register" by `focusstack.addFocusTaker( this ))`
When an item looses the focus because another one get's it, it's still in the stack.
In case the item looses the focus because it's closed (by "back" key), it removes itself from the stack and forces the focus to the last item in the stack. Looks like this (dashboard on the left, featureform on the right, keyhandler is the mainlevel):
(Without the display messages of course)
Additionally if the featureform is open and the user presses "back" key, not the feature-sidebar closes like before, but it goes back to the list of features. This is changed, because I belief this is what a user expects. See the demonstration:
Still …

Focusstack implementation

---

src/qml/DigitizingToolbar.qml

I'd like to propose these changes for digitizing to make it more coherent with desktop but also within the app: merge it with the "+" icon.
The button has the same effect as the add vertex button and I find current mode a bit confusing.
[![screencast](https://img.youtube.com/vi/CeVu2Y64cww/0.jpg)](https://www.youtube.com/watch?v=CeVu2Y64cww "screencast")

[digitizing] remove pen icon

---

src/mapsettings.cpp
src/mapsettings.h
src/qml/ScaleBar.qml

Fix of #273 
But I request for feedback if it's solved at the correct place.
Originally it would call in `scalebar.qml`:
```
UnitTypes.toAbbreviatedString(mapSettings.destinationCrs.mapUnits)
```
But because QML cannot handle the enumeration types it just passes 0 as integer.
So it does not call `QString toAbbreviatedString( QgsUnitTypes::DistanceUnit unit )` but `QString toAbbreviatedString( QgsUnitTypes::LayoutUnit unit )` instead.
The Function to return the string is implemented in c++.
Is `mapsettings.cpp` the correct place, or should I create a `scalebar.cpp`?
Or is it even possible to make kind of typecast in QML to call the correct function?
Edit:
My problem is that only the `QgsUnitTypes` is registered where I can use the enumeration values (e.g. `QgsUnitTypes.DistanceMeters`. But …

Correct DistanceUnit in Scalebar

---

src/qml/QFieldSettings.qml
src/qml/Switch.qml
src/qml/qml.qrc

Made an own Switch.qml overwriting the Controls.Switch to set the sizes depending on the dpi.
On the Galaxy S6 mobile phone:
Fix of: #333

Small sized icons in settings

---

src/qml/FeatureForm.qml

After reporting of weird display of the buttons I replaced the `ToolButton` with the Buttons we use usually.
Could confirm the misplaced issue on my tablet and the width with my mobile.
Looks now like this:

Buttons in the feature form

---

src/qml/QFieldSettings.qml

Function has been lost on my last GUI implementations.
Saves variables on back event. Other possibility would be the save on every text change, but then there would be a lot more unneeded calls.
Fix: #354

Save variables in settings by back

---

scripts/docker-build.sh

Fix #352
@signedav after this pull request it should finally be possible to release with a single click from the release page.
This will replace the version with the information from the git tag (assuming it to be formatted `release-MAJOR.MINOR.FIX`)
One open question is what to put into the version.pri on the repository, would it be ok to tag dev-versions as 0.0.0? Or will that somehow complicate installing test releases on the device?

Use version number from tag

---

src/qml/editorwidgets/DateTime.qml

... and still not saving it. 
Additionally there has been a cross when entering a date that has been unluckily placed exactly on the RememberValue box. So it's placed correctly now, because it's **a clear-cross to erase the date-value (if allowNull)**...
Looks like this:
The other thing has been, on "Add Feature" the date of the last edited feature was always displayed - though not saved. So this is fixed now as well.
fix #369
fix #360
fix #319
Would be nice, if you could test that @gnerred @saemiw :slightly_smiling_face: Thanks.

Fix of remembering wrongly date

---

src/qml/editorwidgets/TextEdit.qml

this enables line wrap on the multiline text edit (TextArea). Otherwise, there is a new line only when there is a carriage returns.

wrap line for multi-line edit

---

src/qml/qgismobileapp.qml

move the busy indicator to the center of the map
it is not that much obtrusive

avoid overlap of busy indicator and search icon

---

src/core/featurelistmodel.cpp
src/qml/editorwidgets/RelationReference.qml

fixes #432 
I am not sure this is the correct fix (i.e. is there an issue hidden behind) but it does prevent the crash.
My wild guess is that with the project in the issue report (QGEP), rendering takes more time than the timer (100ms) so everything is not correctly set when the timer ends, but I didn't look further.
@m-kuhn thoughts?

fix crash in feature list model

---

.travis.yml
src/core/attributeformmodel.h
src/core/attributeformmodelbase.cpp
src/core/featuremodel.cpp
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/qml/FeatureForm.qml
src/qml/editorwidgets/DateTime.qml

these formats are defined in QGIS and can differ from each other
more over, the type of value from the field can be either a date or a string
by correctly constructing a date/time object when getting/setting the value from
the widget, the same behavior than in QGIS is allowed
also:
* do not open calendar when option is not checked in QGIS project
* define inputMask whenever easily possible
fix #9
fix #215
fix #371 
supersedes #404

correctly convert date/time format to respect field and display formats

---

src/core/layertreemapcanvasbridge.cpp
src/core/layertreemapcanvasbridge.h
src/core/layertreemodel.cpp
src/core/qgismobileapp.cpp

this synchronize QField bridge with the one from QGIS core (see also https://github.com/qgis/QGIS/pull/9050 )
this removes some unused code 
* for custom layer order (moved to core https://github.com/qgis/QGIS/commit/f33aabd90aab071d8b1f8f163e6cbed8869110c3#diff-48da0c3b55429da1f86f5f0d2f4e1f8e)
* for map themes (became useless since dc492ce6acf6a11c5a288605dcd3c249a3669aba)

Fix layer order

---

android/src/ch/opengis/qfield/QgsDocumentsProvider.java

Avoid `QgsDocumentsProvider` freezing by catching exceptions if an `externalFilesDir` returned by Android is not valid. Also improve speed, by avoiding the scan of some directories that can be very large and where it is unlikely to find .qgs projects (e.g. Music, Pictures, DCIM)

Improve Qgs Documents Provider

---

.travis.yml
qfield.pri
scripts/docker-build.sh
src/core/expressionvariablemodel.cpp
src/core/featureslocatorfilter.cpp
src/core/identifytool.cpp
src/core/multifeaturelistmodel.cpp
src/qgsquick/qgsquickmapcanvasmap.cpp

And a shiny new build chain without crystax

Update to Qt 5.12.1

---

src/qml/FeatureForm.qml

a crash was hapenning when switching between layers having tabbed and non-tabbbed attribute form
there was a count mismatch between swipe view and tab bar
fixes #474
fixes #477 
kudos to @m-kuhn for digging into this nasty crash
and thanks to reporters with sample projects!

fix crash when switching layer

---

src/qml/editorwidgets/DateTime.qml

@saemiw this should fix the issue of leaving an invalid date/time after the widget loses focus.
Works for you?

clear value in date/time if invalid when losing focus

---

version.pri

we might consider changing the versionCode schema
if we keep on shipping multiple apks
see:
https://developer.android.com/google/play/publishing/multiple-apks.html#VersionCodes

update ANDROID_TARGET_ARCH suffix as short time solution

---

src/qml/DashBoard.qml

I did the same like it's done already on the widgets `ValueMap` and `RelationReference`:
Could still use some beautification. Eg:

hidpi fixes on map themes combo

---

android/src/ch/opengis/qfield/QFieldActivity.java

- Refactor unzip assets
- Fix unzip progression percent that now goes up to 100% and not only 92%
- Add a sleep before unzip to allow old devices to be ready before files are written

Refactor unzip assets

---

src/qml/QFieldSettings.qml

Add padding and vertical align to the settings dialog

---

src/qml/editorwidgets/CheckBox.qml

Checkbox has been not working for Boolean fields (only for other fields used as checkbox) I believe this issue existed since we used QGIS 3.0.
Because since then the widget needs to decide if the value is a boolean or we use a representing value.
This is done in the QGIS widget here: https://github.com/qgis/QGIS/blob/master/src/gui/editorwidgets/qgscheckboxwidgetwrapper.cpp#L29-L35
I did it now in the Checkbox widget here as well. 
Since I guess I'm not able to request a type in QML I did it like this. Another possibility would be to request the value over the model, but probably that would be an overkill as well. What do you think  @m-kuhn ?

Checkbox widget with boolean fields

---

src/qml/FeatureListForm.qml

Be aware, if you are in the middle of editing a feature, this edits are lost. There is a error message in the log.
But IMO this is not a bad way of work. In case someone opens a project during editing a feature I guess he doesn't need to save that. And he get's informed as well...

Close featurelist (featureform) drawer on opening new project

---

src/qml/editorwidgets/DateTime.qml

When we selected a day, it stored one day before. This because the time is set to 0:00:00.
Now with adding a day we have the correct date.
Not sure if this is the correct way to solve the issue. What do you think @3nids ?

Add day when it sets time back

---

src/qml/CoordinateLocator.qml

QField/src/qml/CoordinateLocator.qml:25:8: error: Expected token `:'
if ( !!overrideLocation )
^
/home/travis/build/opengisch/QField/src/qml/CoordinateLocator.qml:26:7: error: Expected token `}'
return overrideLocation
^

Fix warning

---

.travis.yml
src/core/attributeformmodel.cpp
src/core/attributeformmodel.h
src/core/attributeformmodelbase.cpp
src/core/attributeformmodelbase.h
src/core/core.pro
src/core/featuremodel.cpp
src/core/featuremodel.h
src/core/multifeaturelistmodel.cpp
src/core/referencingfeaturelistmodel.cpp
src/core/referencingfeaturelistmodel.h
src/qml/FeatureForm.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/editorwidgets/RelationEditor.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/qml.qrc

(only opened to have the apks built)
- Display relations as widgets
- Pass to the widget the parent feature and the relation id
- Delete child feature
- Delete childs when parent is deleted
- Link parent feature to child - use the parents pk on adding as fk and hide this attribute
- "Buffer" parent when adding child and delete buffered feature on cancel
- Pass to the widget the associated relation id

Relation editor widget

---

.travis.yml
scripts/ci/android-5.patch
scripts/deploy.sh
scripts/upload-artifacts.sh

Directly build Android 5 versions from the same travis infrastructure as anything else.
This applies a patch to use the old SDK.
Note: This does not actually solve our Android 5 issues, it just automates the workaround.
Mid-term we will still have to either retire Android 5 or find a sustainable way of deploying openssl to Android 5.

Android 5 builds

---

src/core/identifytool.cpp

On state change (e.g. navigate to edit) the model of the identify tool has been cleared. That's why QField crashed, when it still wanted to continue with this model data (e.g. zoom to feature or edit geometry).
Since this happens on state change:
```
State {
name: "digitize"
PropertyChanges { target: identifyTool; deactivated: false }
[...]
```
First commit avoids the clear if `deactivated` is `false`. Then it's working like that:
Still you can see that the edit button is enabled in navigate-mode but edit geometry is not. I set it now to invisible, so it's the same for both. I think it's better understandable for a user when it's like that. But I'm not sure, if @m-kuhn agrees.
Another possibility would be that both keys are visible, but then we would need to change the edit-tools that …

Do not clear model on not deactivating identify tool

---

src/qml/editorwidgets/ExternalResource.qml

Because it seems the binding is brocken somewhere. Possibly when the image status turns to `Image.Error` because if there has been an image already, everything worked fine.

Handle display taken photo without bindings

---

src/qml/FeatureForm.qml
src/qml/editorwidgets/CheckBox.qml

- Because of comparison of the integer value with the value in the config, it did not work. It's fixed with the conversation to string
- The binding of checked has been broken by this workaround function. On creating a new feature with a bool value it did not initiate the checked state correctly

Fix Checkbox

---

src/core/messagelogmodel.cpp
src/core/messagelogmodel.h
src/qml/MessageLog.qml

I did that because I needed it to debug the WFS/WMS stuff, to have a better log visualization.
Because it's not a life without timestamps :-)
Looks now like this. If you agree we can take the changes:

Nicer Log Visualization with timestamp

---

src/qml/ScaleBar.qml

- Better font size on highdpi screen
- Add a small margin between text and ticks
- Most importantly, avoid the text overflowing beyond screen
Regarding the text overflowing beyond screen, this is what it looked like:
With the PR, things look much nicer:

Improve scale bar widget

---

src/qml/qgismobileapp.qml

Fix overlapping search and notification buttons

---

src/qml/DashBoard.qml

One thing I had a hard time with when first exploring the map was the dashboard navigation vs. editing toggle. The light blue and light green colors were looking to me like both "activated" colors, and kept confusing whether green meant active or blue meant active.
This PR improves the UI/UX situation by removing the light blue color, and instead use a semi-transparent version of QField's dark gray used elsewhere. I've also made the inactive mode's logo semi-transparent. IMHO, it does a much better job at telling which mode is active.
On top of that, a little toggling animation was added to be more pleasing to the eye:

Dashboard navigate/edit toggle improvements

---

src/qml/DigitizingToolbar.qml
src/qml/qgismobileapp.qml

Here's a before vs. PR shot first:
On the GPS toolbar front, biggest change here is the relocation of the toolbar to sit at the bottom right corner of the screen. This is favorable for a couple of reasons:
- It'll likely come as a more 'natural' position for most users since a large number of mapping apps places the button in that area;
- More importantly, the GPS toolbar has strong relation to digitizing, it therefore makes sense to have it close to the digitizing toolbar;
- In its former position, below the hamburger menu button, it felt odd to see it moving when the dashboard expanded while the hamburger button didn't;
- On narrow screens, with the dashboard expanded, the GPS button was going beyond the right edge of the screen.
The commit also changes the background color of the …

GPS and digitize toolbars improvements

---

src/qml/MapCanvas.qml
src/qml/qgismobileapp.qml

Here's one huge UX issue fixed: when double tapping on the screen, QField used to both zoom into the canvas (good, standard UX on smartphones and tablets) _as well as_ launching the identify too (bad).
This PR insures that the identify tool is only launched on single tap onto the screen.

Do not running the identify tool when double tapping on map canvas

---

src/qml/FeatureListForm.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/qgismobileapp.qml

On my smartphone, browsing features while the screen is in portrait mode isn't ideal (the navigation bar's widgets are overlapping each other, the form itself is too narrow, etc.):
This PR implements an alternative drawer position for portrait oriented screens, which opens at the bottom of the screen:
It's a nice UX win for smartphone users too as it insures  widgets are more easily reached by reducing the distance between thumb and widgets.

On a portrait oriented screen, use the bottom part of the screen to display the feature (list) form drawer

---

src/qgsquick/qgsquickmapsettings.cpp
src/qgsquick/qgsquickmapsettings.h
src/qml/MapCanvas.qml
src/qml/qgismobileapp.qml

Title says it all; QField would always draw the canvas with a white background, irrespective of what was set by the opened project. This PR fixes this issue. 
Previously (broken) vs. PR:

Fix project canvas background color not respected

---

src/qml/DashBoard.qml
src/qml/qgismobileapp.qml

One major UX issue I had when first testing QField was the absence of a edge swipe gesture to open the dashboard, which has come to be a pretty standard behavior these days.
This PR implements that by upgrading the dashboard to become a drawer. The result is pleasing to the thumb:
As the above GIF indicates, this move makes the dashboard modal, whereas once opened, other parts of QField are blocked until the dashboard is closed. IMHO, this is actually a nice change as it insures that there are no overlap between several drawers (identify feature list drawer comes to mind). 
Would anyone object to this new modal behavior?
There *is* a way to make drawers non modal, but AFAIK, you also need to set those drawers as non interactive and that means losing the edge swipe (which brings us back to …

Upgrade dashboard to a Drawer to enable edge swipe to open

---

src/qml/BadLayerItem.qml

Here's a before vs. PR:
Changes include:
- The bad layer dialog was upgraded to be a Page
- The top bar was moved into the page header and its look harmonized with other parts of QField (i.e. green background, white text, close button at right-end of header, etc.)
- The heavy text at the top was broken into two parts, with the help tip relocated to the bottom of the page
- The table view was styled as to avoid mini row height on smartphones

Bad layers UI improvements

---

src/qml/qgismobileapp.qml

On my phone, the busy indicator (crucial feedback to users when remote content like XYZ tiles is being fetched) is tiny, _tiny. In fact, I thought it was simply missing.
This PR tries to fix the tiny size by using the controls 2.4 element (instead of 1.X), and enlarge the indicator to take more of the screen.

Try to fix tiny-tiny busy indicator

---

src/qml/qgismobileapp.qml

Following the PR improving QField's a busy indicator to have it scale properly, this PR relocates the busy indicator to sit below the main menu button. Reasons include:
- It's less obnoxious, yet still visible
- It prevents busy indicator overlap with the identified features indicator
- It also plays better when panning while digitizing features
Here's how it looks:

Better placement for the canvas rendering busy indicator

---

src/qml/qgismobileapp.qml

This PR improves the digitizing / measurement information overlayed onto the canvas. It does so by:
- Adding a keyword for each printed value for a quicker reading/understanding of data shown
- Splitting the coordinates into two lines to avoid text overflowing beyond screen on portrait oriented smartphones
- Use X / Y or Lat / Lon to identify whether coordinates are geometric, or not (a useful visual queue for those who aren't so familiar with GPS programs)
- Add more decimals for lat/lon coordinates, and less for meter (et cie) based units
Here's how it looks like:
There's nothing like a long field trip to discover those little tweaks that make a big difference.

Improved digitizing/measurement information strings

---

src/qml/QFieldSettings.qml
src/qml/imports/Theme/Theme.qml

A screenshot worth a thousand words:
Improvements include:
- Harmonize looks to match what QField has adopted across other panels
- Use SwitchDelegate controls to gain support for right-ended placement of toggles (a standard on Android et cie)
- Avoid chopped off labels on portrait oriented screens
- Rely on Theme font size

Large number of UI/UX improvements to QField's settings panel

---

src/qml/QFieldSettings.qml

This is a follow up to #670 to address issue with text wrap. Long story short, the SwitchDelegate doesn't handle text wrapping well; the way around that is to use labels and associate those with switch-only items.
@m-kuhn , this PR also silence the warning you noted last week.

Further improvements to the settings dialog

---

src/qml/DashBoard.qml
src/qml/qgismobileapp.qml

@m-kuhn , looking into the focus issue reported by @Emic37 , I found out one source of broken focus state happens when closing the updated dashboard popup menu in an area that'll also close the dashboard itself.
One way to fix this is to force the focus onto the desired control whenever we can. This PR does that. It's a pretty important fix.

Fix focus issues

---

.github/label-actions.yml

Having the top level labels:
- BUG 
- ENHANCEMENT
- SUPPORT 
(and as well INPUT and QUESTION)
to have a visual mark for it's priority over e.g "feedback" etc...

Capslock Labels

---

src/core/qgsgpkgflusher.cpp

and not shp. Because otherwise it would print errors.
@m-kuhn I'm not that familiar with what storage types we need a flush and with what we don't. For example `MBTiles` need it as well, right?

Do only flush on gpkg or sqlite files 

---

src/core/qgismobileapp.cpp

Instead of setting it to persist the size of the map on the layout.
Fixes: https://github.com/opengisch/QField/pull/723#issuecomment-557760055

Print to PDF: zoom to extent

---

.travis.yml
sdk.conf

Separate the currently used osgeo4a version from .travis.yml

Move osgeo4a version to txt

---

src/qml/ScaleBar.qml

The scale bar wasn't behaving in a friendly way for projects with a CRS in degree units. You'd only get 2 degrees, 1 degree, and 0 degree (which is not ideal :) )
This PR adds some decimals for degrees. Much, much more useful information.

Improve scale bar for degree units

---

src/qgsquick/qgsquickutils.cpp
src/qgsquick/qgsquickutils.h
src/qml/LocationMarker.qml
src/qml/TransformedPositionSource.qml
src/qml/qgismobileapp.qml

While field testing QField, I've noticed an unfulfilled expectation: an on-canvas visual representation of my GPS accuracy. It's there on many popular mapping apps (google maps to name one :) ), and can be quite useful to get a quick sense of how accurate data entry will be, and how that accuracy is reflected onto the map (i.e., what overlays within that estimated accuracy area).
This PR implements just that. Here's how it looks:

Improve LocationMarker UX by adding on-canvas visual accuracy representation

---

scripts/docker-build.sh
src/qgsquick/CMakeLists.txt
src/qgsquick/qgsquickcoordinatetransformer.cpp
src/qgsquick/qgsquickcoordinatetransformer.h
src/qml/MapCanvas.qml
src/qml/PageHeader.qml
src/qml/PositionInformationView.qml
src/qml/PositioningSettings.qml
src/qml/QFieldSettings.qml
src/qml/TransformedPositionSource.qml
src/qml/imports/Theme/QfSwitch.qml
src/qml/imports/Theme/qmldir
src/qml/qgismobileapp.qml
src/qml/qml.qrc

This can be used to compensate measured Z values for an antenna height.
It can also be abused to compensate for anything else like geoid differences.

Add a configurable antenna height option

---

src/qml/DigitizingToolbar.qml
src/qml/qgismobileapp.qml

Popular demand is overruling my "muscle memory" argument, seems most people are happier seeing the GPS anchored to the bottom right side of the screen when the measurement / digitizing toolbar isn't active. It actually has grown on me, and I think it's likely the best behavior here:
I've also gotten rid of the floppy disk icon in favor of a check icon in the digitizing toolbar (seen in the GIF above), matches what we've established elsewhere (e.g. the page header).

A couple of GPS / digitize buttons improvements

---

src/qml/RelationCombobox.qml

Stumbled on an ugly situation with the relation combobox (supersized + button with an unwanted white background, as well as a padded popup header, which we got rid of when harmonizing looks). This PR fixes that.

Improve relation combobox looks

---

src/core/layertreemodel.cpp
src/qml/DashBoard.qml

`LayerTreeModel::updateCurrentMapTheme()` failed to clear the map theme string when checking for a map theme match upon project load, which could lead to an out-of-sync combo box.

Fix map theme combobox out of sync when loading project

---

src/qml/editorwidgets/ExternalResource.qml

When edit is **_not_** toggled.
Before:
Now:

Camera: Only display buttons on edit mode

---

src/qml/QFieldSettings.qml

And to go back to the handcrafted stuck-in-Madeira-with-fish-and-bananas-QML-cam you have to disable it. 
I did not change the setting that disabled is native cam and enabled banana cam. It's still like before, just with default on. 
And changed the description...

Enable native camera on default

---

src/qgsquick/qgsquickutils.cpp
src/qml/editorwidgets/Range.qml
src/qml/qml.qrc

This PR implements a dedicated range editor widget. Other than the benefit of cleaning numeric-specific code away from the text edit widget, the range widget now supports sliders (I was burying the lead here :wink:)
In action:
In addition, the range widget's integer and double validator will now validate the number being entered to make sure it stays within the min/max numerical values stated in the range widget configuration.

Implement a dedicated range editor widget

---

src/qml/qgismobileapp.qml

Improvements are:
- Reflow text when it goes beyond window width
- Fix background (follow up to warnings removal PR)
Looks much better on narrow screen width:
This also (finally?) unlocks the possibility of pushing longer, more informative messages to the toast pop up. Woupidou.

Toaster improvements

---

.github/workflows/backport.yml

I took the original backport bot without the token trick.
This means no security matters but no backport from forks...which is very acceptable for now.

add backport bot

---

scripts/ci/travis_build.sh
scripts/deploy.sh
src/qml/About.qml

we will build APKs for master and stable but only master ones are pushed to play store
also increase version code for PR builds so we won't need to uninstall all the time before installing new APK

adapt deploy scripts to stable/master branches

---

resources/demo_projects/advanced_bee_farming.qgs
resources/demo_projects/simple_bee_farming.qgs

Because it deserves exposure and promotion, let's use sliders in the QField demo projects:

Showcase range widget's slider mode in bee demos

---

src/core/androidplatformutilities.cpp
src/qml/qgismobileapp.qml

After the activation of the positioning (setting first time) the position updates, means the marker does not stay anymore in the top left corner until the next restart.
By setting the `preferredPositioningMethods` this works. Not really sure about what Qt Positioning does in the background but I think it's because if it starts without any positioning methods that work it does not retry with them. On setting them it tries it again.
The activation is now done over the checked state of the gpsMenu. This to avoid confusion with the binding. 
The settings are stored now to be reused after next restart.

Fix positioning after activation

---

sdk.conf
src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/qml/geometry_editors/SplitFeatureToolbar.qml

it is not working anymore with Qt 5.14+
in this case the QgsPointSequence was transformed to a vector, but when sent back to cpp, it's not seen as it should/would/could

avoid passing variables in JS

---

src/core/androidplatformutilities.cpp
src/qml/qgismobileapp.qml

set the preferredPositioningMethods on position source to receive updated position after the activation of the signal or after giving permission the first time
control activation of positioning over the checked state in the gpsMenu to avoid confusion and binding issues
store in settings if the positioning is activated
use existing functionality

Fix positioning after activation (#878)

---

src/qml/editorwidgets/RelationEditor.qml

and implement it directly in the widget. But kept the original implementation to bring it back as soon as we found out the reason for the assumed crash.

Remove embedded feature form in the Relation Editor

---

android/AndroidManifest.xml

To avoid to have the activity restarted by android.
This fixes #888
When the configuration changes, it calls directly `onConfigurationChanged` of the parent Activity class since we do not need to do anything.
Thanks @marioba for the help.

Handle the config changes by the activity

---

resources/demo_projects/advanced_bee_farming.qgs
resources/demo_projects/simple_bee_farming.qgs
src/core/androidplatformutilities.cpp
src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

I thought it's a bug, but apparently it has not been implemented before.
Now Not Null and Unique Constraints are supported.
The descriptionmessage is the list of all the messages including the ones generated for not null and unique. They are not separated by it's strength. This could be improved but is actually how QGIS behaves as well.

Not Null and Unique Constraints

---

src/qml/qgismobileapp.qml

use the positionSource.projectedPosition to center position (like we do on symbol click).
fixes #895
I didn't made research why the old functionality does not work.

Fix center GPS over menu

---

src/core/featurelistmodel.h
src/qml/FeatureForm.qml
src/qml/RelationCombobox.qml
src/qml/editorwidgets/CheckBox.qml
src/qml/editorwidgets/ValueRelation.qml

this fixes value relation widget
also, going through JS with C++ variables is not supported anymore
for instance:
var modelIndex = myModel.index(row, col, ...)
var data = myModel.data(modelIndex, role)
is not working while
var data = myModel.data(myModel.index(row, col, ...), role)
is working. But, Qt emits a warning:
Passing incompatible arguments to C++ functions from JavaScript is dangerous and deprecated.
This will throw a JavaScript TypeError in future releases of Qt!
therefore, it is advised to create helpers in the C++ classes directly:
QVariant MyModel::dataFromRow(row, role)

follow up upgrade to Qt 5.13+

---

src/qml/editorwidgets/ValueMap.qml

same that for ComboBox, Qt added the currentValue property in 5.13.
Property has been removed and taken to the top level.

fix value map

---

src/core/featuremodel.cpp
src/core/featuremodel.h
src/core/geometry.cpp
src/core/geometry.h
src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h
src/core/vertexmodel.cpp
src/core/vertexmodel.h
src/qml/qgismobileapp.qml

With these commits, QField now behaves properly in topological editing mode. Shared nodes are treated as such when moving / deleting vertices, and additional vertices are added on nodes overlapping segments.
Here's a lovely screencast:
There's no UI to toggle topological editing on/off yet, but that's the easy part. 
@m-kuhn , @3nids , your reviews are appreciated.
@signedav , I've opened this now (instead of waiting for the UI to be added) as I think this needs consideration vis-a-vis auto save.

QField 💖 Topology

---

src/qml/editorwidgets/ValueRelation.qml

`config['AllowMulti']` was returning `"0"`, which translates to `true`.
I am a bit surprised to stumble on this only now, and I would expect the same issue in other places.
Is this something related to newer versions of Qt???

fix allow mutli mode for value relation

---

scripts/ci/prepare-release.sh

I guess it's because there is no master branch on the local remote so you need to provide the destination branch
successfully tested in the release process of 1.5.1 (see https://github.com/opengisch/QField/commit/528e0ed9db3d81d9ebcd9a0e87df32f00014c7e8)

fix fetching of master when preparing a release

---

src/core/distancearea.cpp

when running on the desktop, I always had a crash on exit.
this happens at the deletion of the project (mProject = 0)

fix crash on exit

---

src/core/featurechecklistmodel.cpp
src/core/featurechecklistmodel.h
src/core/featurelistmodel.cpp
src/core/featurelistmodel.h
src/qml/editorwidgets/ValueRelation.qml

the display field was not part of the fetched attributes, hence the list remained empty.
this also fixes the initialization of inherited classes
I run clang-format on the second commit, so better inspect changes of the first commit

fix display field not shown in value relation

---

src/core/qgismobileapp.cpp

When the project title was derived from the project filename, QField was trimming on first dot when multiple dots were present. This PR fixes that. Proof:

Fix wrong trimming of project filenames having many dots (fixes #969)

---

src/qml/LayerTreeItemProperties.qml
src/qml/ui/LayerTreeItemProperties.qml

Before:
PR:
@signedav , I've led go of the start / stop custom colors in favor of QField's green. I think the Start / stop tracking conditional label in the button suffice here.

Improve visual look of layer properties tracking button

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/qml/Legend.qml

Two legend improvements that appear to have been eaten away by the large amount of rebasing that was needed last week:
- have the flat layer tree proxy handle dataChanged signal to make sure we show proper feature count in legend
- have the legend item respect legend symbols' ratio.

Legend follow-ups

---

images/themes/qfield/nodpi/ic_topology_green_24dp.svg
images/themes/qfield/nodpi/ic_topology_white_24dp.svg

This was missing from my original PR adding a topology button to QField. 
It's not used ATM, but it's nice for the project to keep vector version of icons if edits are required in the future, or derived icons are needed.

Add missing vector topology icons

---

src/qml/CloseTool.qml

Without this, the X icon isn't as sharp and way oversized.

Fix close tool button's image size on hidpi scaled screens

---

src/qml/QFieldSettings.qml

@3nids , just noticed we lost some padding on the right edge of the settings list, making the switch touch the edge of the window / device. This PR fixes that visual regression.

Add a bit of margin area at the right edge of the settings list

---

src/core/layertreemodel.cpp
src/qml/Legend.qml

Say hello to the tracker indicator in the new legend item:
I've located it along the right edge of the legend area, I find that aesthetically a bit nicer, and it links to our big brother QGIS' indicator UI/UX.

Revive tracker indicator in new legend item

---

src/qml/editorwidgets/TextEdit.qml

The validation of fields has been removed on the implementation of the nice functionalities on the range widget.
I think it should be still on the text edit widget, because otherwise customers have to reconfigure all of their text edits using numbers. 
resolves #1026
Or if we decide to have it not anymore in the textedit, it would need the information in the documentation.

Validate numeric fields on TextEdit widget

---

src/qml/editorwidgets/ExternalResource.qml

Fixes https://github.com/opengisch/QField/issues/1019
NOTE: in QField only the filename is shown, unlike QGIS, where the whole path is visualized
https://github.com/opengisch/QField/pull/1029/files#diff-bacb7c98c9810cffdfedd42311433719R71

Respect hyperlink attachments

---

src/core/multifeaturelistmodel.cpp
src/qml/FeatureListForm.qml

When deleting a feature from the feature list model, the number of features in the header remains the old one. For example, if we have selected the first item fron a list of three features, the header shows 1/3. If we delete the first one, the header remains showing 1/3, even though there are only two features left.
What is more, when we delete all features, there is a blank feature list form on the screen. In this PR, if there are no more features, the list is closed.
|before|after|
|--------|------|
| ![Peek 2020-05-14 18-03](https://user-images.githubusercontent.com/2820439/81951011-50a5b600-960d-11ea-93e4-a7c710e3d15e.gif) | ![Peek 2020-05-14 17-59](https://user-images.githubusercontent.com/2820439/81950604-d07f5080-960c-11ea-81f7-0f18d1a88b0b.gif) |

Fix feature count when deleting a feature

---

src/core/multifeaturelistmodel.cpp

|before|after|
|--------|------|
| ![image](https://user-images.githubusercontent.com/2820439/81837727-e37f1b80-954d-11ea-9d73-1a1f72ac9560.png) | ![image](https://user-images.githubusercontent.com/2820439/81837516-a581f780-954d-11ea-91af-0cbaafac1b7e.png)|

Show at least the feature ID, if the display expression evaluates to an empty string

---

src/core/layertreemodel.cpp
src/core/legendimageprovider.cpp

This PR both fixes and improve the legend image provider by setting the layer tree model to show legend items as tree instead of a flattened fake tree. 
With the QgsLayerTreeModel::ShowLegendAsTree flag, we avoid the fake tree hackery in the layer model icon creation whereas indent spacing is added _within_ the pixmap itself. This created tiny, non-centered icons in the legend. See how beautiful things are now:
_Before, the rule-based children rules to parent ones would show tiny, tiny icons_
In addition, getting the proper parent / children structure allows for a more accurate matching of legend IDs and their respective preview images. Since we're doing string matching (first match being returned), we ended up sometimes serving wrong legend icon. For e.g., take this rule-based symbol …

Improve legend icon matching and fix unwanted indent

---

src/core/androidpicturesource.cpp
src/core/androidpicturesource.h
src/core/picturesource.cpp
src/core/picturesource.h
src/core/platformutilities.cpp
src/qml/editorwidgets/ExternalResource.qml

Clicking on the gallery button opens a standard qt file dialog, instead of silently ignoring it.

Add option to change attachments on desktop build

---

src/core/expressionvariablemodel.cpp

This is a follow up to the global variable editor's upgrade done as part of the QtQuick2 upgrade work. 
In the old variable editor, the last row/item was used to add a new variable and therefore had to be skipped. This is not the case anymore, we need to save that last item.
@3nids , @m-kuhn , this will need backporting to 1.6.

Fix last user-added global variable not saved

---

src/qml/qgismobileapp.qml

the clicked point instead of the snapped point was used
the original code was introduced at the time when we had a timer to detect double taps, which is no longer used

fix snapping when digitizing with pen

---

src/qml/editorwidgets/TextEdit.qml

Fix text edit widget clipped text issue for complex scripts

---

src/qml/editorwidgets/DateTime.qml

One of the last blurry icons I could spot in QField QtQuick2-only :tada:

Fix blurry images for the datetime widget

---

src/core/CMakeLists.txt
src/core/core.pro
src/core/platformutilities.cpp
src/core/platformutilities.h
src/core/qgismobileapp.cpp
src/core/utils/stringutils.cpp
src/core/utils/stringutils.h
src/core/utils/urlutils.cpp
src/core/utils/urlutils.h
src/qml/FeatureForm.qml
src/qml/editorwidgets/CheckBox.qml
src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/Range.qml
src/qml/editorwidgets/RelationEditor.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/TextEdit.qml
src/qml/editorwidgets/ValueMap.qml
src/qml/editorwidgets/ValueRelation.qml
test/CMakeLists.txt
test/test.pro
test/test_featureutils.cpp
test/test_fileutils.cpp
test/test_geometryutils.cpp
test/test_stringutils.cpp
test/test_urlutils.cpp

When `TextEdit` or `ExternalAttachment` contains a web URL, convert it to an anchor via `QStringUtils::insertLinks` and display it. 
There is a need of aditional Text QML element, because links in TextEdit do not open on Android and it's quite dirty to automatically convert to RichText format.
|before|after|
|---------|------|
|![image](https://user-images.githubusercontent.com/2820439/85294124-ed7a2f80-b4a6-11ea-9613-176a8f604a89.png)|![image](https://user-images.githubusercontent.com/2820439/85293872-9bd1a500-b4a6-11ea-9945-838a43a0b273.png)|

Make fields with web links open externally

---

src/core/CMakeLists.txt
src/core/attributeformmodel.h
src/core/attributeformmodelbase.cpp
src/core/core.pro
src/core/featurelistextentcontroller.cpp
src/core/featurelistmodelselection.cpp
src/core/featurelistmodelselection.h
src/core/featuremodel.cpp
src/core/featuremodel.h
src/core/featureslocatorfilter.cpp
src/core/identifytool.cpp
src/core/multifeaturelistmodel.cpp
src/core/multifeaturelistmodel.h
src/core/multifeaturelistmodelbase.cpp
src/core/multifeaturelistmodelbase.h
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/FeatureListSelectionHighlight.qml
src/qml/NavigationBar.qml
src/qml/editorwidgets/Range.qml
src/qml/qgismobileapp.qml

@m-kuhn , part A.
This PR adds a  multi-selection capability to the feature list form. It is activated by a long press over a list item. Long pressing the item will select that item and enable the multi-selection behavior, whereas subsequent clicks to other list items will toggle the selection state. If all items are deselected, the list goes back to normal behavior (i.e. a click opens the feature form).
When multi-selection behavior is enabled, the feature list is filtered to _only_ show features from the layer within which features are being selected. This is a needed restriction to use this feature to unlock multi-feature editing (aka part B).
Selected features (and the filter layer) are remember when clicking on the canvas to identify features, which allows users to go through a …

Add multi-selection capability to the feature list form

---

src/qml/qgismobileapp.qml

I don't like timers for workarounds.
But since there has been so much time lost already in finding clean solutions, why not for once do it.

Add workaround for synthesized touch events

---

scripts/spell_check/spelling.dat
src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/qml/LayerTreeItemProperties.qml
src/qml/geometry_editors/FillRingToolBar.qml
src/qml/geometry_editors/SplitFeatureToolbar.qml
src/qml/qgismobileapp.qml
test/test_geometryutils.cpp

Make sure all occurrences of `Rubberband` is written with a single capital, not `RubberBand`.
Seems that Rubberband is much more popular in the codebase, even though QGIS spelling is `QgsRubberBand`
```
$ rg RubberBand | wc -l
14
$ rg Rubberband | wc -l
237
```
Not the most important fix in the world, but consistency is good.
I am cheap on PRs and fixed a warning too, that I have introduced with geometry locking.

Rename occurrances of RubberBand to Rubberband

---

src/core/layertreemapcanvasbridge.cpp
src/core/layertreemodel.cpp
src/qml/LayerTreeItemProperties.qml
src/qml/Legend.qml

This fixes #1109 , #1111 , as well as an unreported crasher when using the zoom to layer button on a group.
I've also taken the time to further cleanup the layer tree item properties QML some more (follow up to the removal of the dual qml file for that item).

New legend widget post public release fixes

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/RelationEditor.qml
src/qml/editorwidgets/TextEdit.qml
src/qml/editorwidgets/ValueRelation.qml

**Fix Relation Editor** 
Has been always disabled because of the `AttributeAllowEdit`. Now `AttributeAllowEdit` on the `ElementType` relation is always true, but on multi edit the relation editor widget is disabled.
**Clean up isEnabled vs ReadOnly** 
Since the enable state of the feature (with special cases on relation editor, value relation and external ressource) has been handled by two values, what can be done by one.
**Color or Text Editor** 
Fixing the color on TextEditor widget (has been always black before - is now gray on not edit state).
fixes #1123

Fix Feature Form problems depending on isEnabled and AttributeAllowEdit

---

src/qml/NavigationBar.qml

Use the recently renamed `focusedLayer` instead of `selectedLayer`
Fixes #1119

Fix #1119 Button to edit geometry no longer available

---

src/qml/CoordinateLocator.qml
src/qml/DashBoard.qml
src/qml/DigitizingToolbar.qml
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/GeometryHighlighter.qml
src/qml/GeometryRenderer.qml
src/qml/LocationMarker.qml
src/qml/MessageLog.qml
src/qml/NavigationBar.qml
src/qml/qgismobileapp.qml

Reverts opengisch/QField#1079
Should work stable on anyting between 5.12 and 5.15. 5.15 shows deprecation warnings.
Let's re-evaluate when Qt 6 is here and/or 5.12 is legacy.

Revert "fix QML Connections: Implicitly defined onFoo properties in Connections are deprecated"

---

src/core/multifeaturelistmodel.cpp
src/core/multifeaturelistmodel.h
src/core/multifeaturelistmodelbase.cpp
src/core/multifeaturelistmodelbase.h
src/core/trackingmodel.cpp
src/core/trackingmodel.h
src/qml/FeatureListForm.qml
src/qml/NavigationBar.qml

This PR updates QField's feature deletion UI/UX by relying on multi-selection. A GIF:
There as several advantages to this:
- obvious one: we can delete more than one feature at a time :tada: 
- reduces accidental deletion triggering by putting this behind a long press action
- reduces the visual clutteredness of the list by avoiding a repetition of the delete button
- makes the UI/UX matches what has become the normal on smartphones (i.e. long press to activate selection and deletion)

Use the new multi-select feature to offer a better feature deletion UI/UX

---

src/qml/qgismobileapp.qml

Increase the touch-only hoverhandler timer to avoid location marker jumping around when slowly dragging finger on the screen.
@m-kuhn , as discussed.

Increase the touch-only hoverhandler timer to avoid location marker jumping around

---

scripts/ci/build.sh

Current calculation:
It takes the last digit of the current year (Y) = 0
It takes the day of the year (DDD) = 202
It takes the hour of the day (HH) = 12
It takes the minutes of the hour (MM) = 22
It takes the arch nr = 1
equals 020212221 - that's bad.
Since we have today the 202 day of the year the check to be lower than 20000000 blocked the build (because we don't want to come too close to the maximum 2100000000)
It's not so good to use the date as version, so in this PR it replaces it with the number of the masters commits: 2523
Current version number is 019309501
I suggest to go on with 0193 2523 1
So we have the abstract number 0193 then the commit number and then the arch number.

Calculate APP_VERSION_CODE with number of commits instead of datetime

---

src/core/featuremodel.cpp
src/core/multifeaturelistmodel.cpp
src/core/multifeaturelistmodel.h
src/core/multifeaturelistmodelbase.cpp
src/core/multifeaturelistmodelbase.h
src/qml/FeatureListForm.qml
src/qml/NavigationBar.qml

This PR further refines the UI/UX of the feature list's multi selection mode. First, zhe GIF:
- When feature(s) is/are selected, tap on the canvas to identify additional features will have those newly identified features selected by default
- When feature(s) is/are selected, a new 'clear selection' button appears in the left end of the navigation bar, allows someone to exit the multi selection mode without having to uncheck all features
The PR also fixes a crasher.

Multi selection UI/UX improvements

---

src/qml/qgismobileapp.qml

The PR avoids what was triggering a series of warning when loading a second project that didn't have layouts when the first loaded project in QField had some.

Silence more warnings

---

sdk.conf
src/core/CMakeLists.txt
src/core/core.pro
src/core/featureslocatorfilter.h
src/core/gotolocatorfilter.cpp
src/core/gotolocatorfilter.h
src/core/locatormodelsuperbridge.cpp

GIF time:
This PR adds the capability to type and go to a given coordinate through QField's search bar. Accepted coordinates:
- a pair of longitude and latitude decimals
- a pair of degree minute second coordinates
- a pair of x y project CRS coordinates 
The parsing of numbers is locale aware, allowing users to use their language's decimal and thousand separators.

Add go to coordinate feature to search bar

---

src/qml/FeatureListForm.qml
src/qml/LocatorItem.qml
src/qml/qgismobileapp.qml

This PR further improves the search bar experience by:
- Tweaking the clear button so that it will _only_ clear the search bar text input if that has text entered vs. clear and closing bar at the same time. If the user click on the X when there is no text entered, the search bar will then close.
- Super nice animation on bar _closing_ (we were only animating the bar showing).
GIF of animation on search bar closing:

More search bar UI/UX improvements

---

src/core/featurelistmodel.cpp
src/core/featurelistmodel.h
src/qml/FeatureForm.qml
src/qml/editorwidgets/ValueRelation.qml

Value relations now support filtering the values with filter expression. What is more, cascading dependencies (e.g. using `current_value('attr1')` are also supported.
Fixes https://github.com/opengisch/QField/issues/436

Add support for filtering in value relations + cascading dependency support

---

src/qml/editorwidgets/TextEdit.qml

Fixes #1212
While the single line edit is replace with a label in r/o mode, the multiline one is is just not editable.

Show multiline widget also in r/o mode

---

src/qml/RelationCombobox.qml
src/qml/editorwidgets/ValueRelation.qml

This backport slipped through the cracks
This fixes an issue in 1.6 where comboboxes are editable even when the attribute form is not in edit mode
See #1154

Value Relation Polishing

---

src/core/rubberbandmodel.cpp
src/qgsquick/qgsquickcoordinatetransformer.cpp

Catching all exceptions instead of only `QgsCsException`.
Occured most possibly because of missing gsb file on device. this has not been integrated with proj4

Fix crash on coordinate transform

---

src/qml/FeatureListForm.qml
src/qml/Tracking.qml
src/qml/editorwidgets/RelationEditor.qml
src/qml/qgismobileapp.qml

Those QtQuick2 dialogs look much, _much_ nicer:
Old dialog (left) vs. QtQuick2 dialog (right):

Update dialogs to QtQuick 2 Dialog items

---

android/src/ch/opengis/qfield/QFieldActivity.java
src/core/androidplatformutilities.cpp
src/core/androidplatformutilities.h
src/core/platformutilities.cpp
src/core/platformutilities.h
src/core/qgismobileapp.cpp

This PR implements a localized data paths for QField, and adds a static data path (root_external_storage/QField/basemaps/) on the android platform. 
The implementation envisions the possibility of passing on multiple data paths via a string using semicolon as separator.

Add support for loading of datasets stored in a localized data path (i.e. 'basemaps')

---

src/qml/LayerTreeItemProperties.qml

It also closes the drawer, I assume the user is lost on the map and want to recenter, so they no longer need the drawer. Closes #1226

When zoom to layer is clicked, layer properties should close

---

src/core/layertreemodel.cpp

TIL moment: QGIS' layer tree removes and re-inserts layer tree items for layers with [x] show feature count active.
Which means QField has to listen and re-build the legend when layers are added (which I thought was not possible within QField other than through project load.

Listen for and rebuild legend proxy model when source layer tree rows are inserted

---

CMakeLists.txt
sdk.conf
src/app/app.pro
src/app/main.cpp
src/core/CMakeLists.txt
src/core/attributeformmodel.h
src/core/attributeformmodelbase.cpp
src/core/attributeformmodelbase.h
src/core/featuremodel.cpp
src/core/featuremodel.h
src/qml/FeatureForm.qml

This PR implements QML widget support in the feature form. An obligatory GIF:
As the above screencast demonstrates, the current implementation QField supports expression.evaluate(...). The method I've settled on to do it (i.e. string substitution in the QML source string) was the most appropriate solution I could come up with. On the plus side, the general idea behind it can easily be used to come up with an HTML widget support (via the WebView item).

QField 💖 QML & HTML

---

.tx/config
src/qml/About.qml
src/qml/Changelog.qml
src/qml/qgismobileapp.qml

Implements the feature request in #1192 . This PR uses the Markdown instead of HTML (the gif in the issue). The changelog is loaded once on startup and cached until the app is restarted. Please write stricter markdown in the release notes, all the newlines matter.

Prepare and show changelog

---

cmake/AndroidManifest.xml.in

To be able to use function getExternalStorageDirectory again.
Talked with @m-kuhn about it. The prio to upgrade is not that high. So we can find a proper solution for this #1269

Revert "Bump Android target sdk to 29 (Android 10)"

---

src/qml/About.qml
src/qml/Changelog.qml
src/qml/NavigationBar.qml
src/qml/qgismobileapp.qml

- Don't reappear the changelog once it was closed via button click, back button tapping on the modal background
- Refresh changelog if failed to load last time - previosly the changelog was showing "failed to fetch" until the app is relaunched.
One unrelated change I have forgot when fixing the `NavigationBar` : there was unused property `currentName`, that remained after the multiselect implementation.

Changelog improvements

---

src/qml/NavigationBar.qml

I think showing 1/1 brings extra noise in the overall UX without any additional information to the user.
| before | after | but still |
|----------|----------|----------|
| ![image](https://user-images.githubusercontent.com/2820439/92635813-1b6d5400-f2df-11ea-9e20-36a276fae8f5.png) | ![image](https://user-images.githubusercontent.com/2820439/92635648-da753f80-f2de-11ea-8d14-a89406a11330.png)  | ![image](https://user-images.githubusercontent.com/2820439/92635611-cd585080-f2de-11ea-854a-8f2aca8792a7.png) |

Shows navbar position prefix only when more than 1 listed feat

---

src/qml/CoordinateLocator.qml
src/qml/DashBoard.qml
src/qml/DigitizingToolbar.qml
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/GeometryHighlighter.qml
src/qml/GeometryRenderer.qml
src/qml/LocationMarker.qml
src/qml/MessageLog.qml
src/qml/NavigationBar.qml
src/qml/qgismobileapp.qml

Attempts to fix:
> fix QML Connections: Implicitly defined onFoo properties in Connections are deprecated
This was already attempted a few weeks ago https://github.com/opengisch/QField/pull/1079, but it was reverted https://github.com/opengisch/QField/pull/1134 . Hopefully the change will work this time or the needed changes should be applied.

Qml callback warning

---

src/qml/FeatureForm.qml

fixes #1283
This was avoided when introducing relation editor widgets because there has been crashes with nested relations. 
I'm pretty confident that this crash cause is resolved meanwhile because there are apparently no problems anymore.

Keep relation editor widget enabled in embedded forms

---

src/qml/FeatureForm.qml
src/qml/qgismobileapp.qml

@signedav , this fixes unwanted overlay of dashboard drawer, welcome screen, et cie.
We now have to cross fingers for Qt 6 gives us a better WebView item (or an equivalent alternative).

Only show feature form HTML widgets when the form is focused

---

src/qml/FeatureForm.qml

Set the form.model instead of sub model when it has no tabs.
Fixes #1255

Set no sub models if the form has no tabs

---

src/qml/LayerTreeItemProperties.qml

Since this has been removed here 7cd89195625c3418a2cb7abe39c09ef89aeace1c
```
property alias itemVisible: itemVisibleCheckBox.checked
``` 
tracking could not been started.
Now we get the `itemVisibile` state from the checkbox directly. Needs less code and I don't see any risks in getting it from the checkbox instead getting it from the alias...

Pass visibility state on tracking start

---

src/qml/editorwidgets/ValueRelation.qml

The current feature was invalid in the init phase, which skips the application of the filter expression. Fix https://github.com/opengisch/QField/issues/1323

Make cascading dependencies work since the init phase

---

src/qml/editorwidgets/ExternalResource.qml
src/qml/imports/Theme/Theme.qml

Tries to prevent #1213 , #1284 and other issue reports due to misconfiguration. Now it should "No Value" when there is no value. Since there are two words separated by space and different color, it's quite hard to be confused filename in my opinion.
The wording in QGIS:
> Use hyperlink for document path (read-only)
However "No Document Path Value" does not sound ok to me, as we work only with pics. "No File Path", "No Attachment Path Value", "NULL"... I am quite open for the wording here.

Show "No Value" when there is no value in attachments

---

src/qgsquick/qgsquickmapsettings.cpp

_This should probably make its way into 1.7_
The QgsQuickMapSettings::setCenterToLayer() function didn't handle layers with a CRS that's not that of the project, leading to pain and tears. This fixes it.

Fix zoom to layer extent broken on reprojected layers

---

src/core/featurelistmodel.cpp

Set QVariant() as NULL for any kind of type to avoid that for integer values 0 has been set as NULL.
Return the first index (0) if the value has not been found (because NULL is not NULL) but allowNull is active.
fixes #1337 (leet)

Do not use 0 for NULL in value relation widgets

---

src/qml/Changelog.qml

Unfortunately, there is no reliable way to get the version number on the beta channel without changing the green title after successful fetch from the github API. So the only changing thing will be the release number in bold. 
Fix https://github.com/opengisch/QField/issues/1341

Added an indication that there is a new minor release

---

src/core/geometry.cpp
src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h

When confirming a new feature, the previewed geometry would disappear off the map due to the rubber band previewing the geometry not handling project vs layer projection difference in setDataFromGeometry.
While it'd be nice to have as a fix in the 1.7 branch, I don't think it's as needed as #1342.

Fix rubber band geometry not reprojected (when needed) in setDataFromGeometry

---

src/qml/DigitizingToolbar.qml
src/qml/qgismobileapp.qml

The long press on canvas to validate a new line/polygon is really hard to discover. Let's keep the ok/check button for users to touch / click on it to confirm the geometry.
@3nids , is that OK with you? I've tested this some more with freehand digitizing and I really thing we're better keeping the button here.

Keep the digitizing ok/check button even when stylus is hovering the screen

---

src/core/layertreemapcanvasbridge.cpp
src/core/layertreemapcanvasbridge.h
src/core/legendimageprovider.cpp
src/core/qgismobileapp.cpp

This and https://github.com/qgis/QGIS/pull/39341 fix blurry QField legend preview images on HiDPI screens.

Make sure legend images are drawn at device dpi, avoid blur and size issue

---

src/qml/editorwidgets/Range.qml

Bug introduced by "Fix: editorwidgets/Range.qml:76:7: Unable to assign [undefined] to double"
https://github.com/opengisch/QField/commit/ee45e74db93e85790ac34959bbbab4d782b3bd21
When the range editor is clicked, it initialy resets to 0 and then goes to the current value.

Fix crippled range editor

---

src/core/attributeformmodelbase.cpp
src/core/attributeformmodelbase.h
src/qml/FeatureForm.qml

Feature form tabs now reflect the status of failing soft/hard constraints by changing the color of the tab title:
I took the time to improve other aspects of the feature form along the way.

Feature form container/tab constraints handling & general improvements

---

src/qml/FeatureForm.qml

The feature form's section delegate had a fixed height, which means multiline strings would end up overlapping outside of the section rectangle, for e.g.:
The PR fixes that:

Fix multiline section header, revisit padding

---

src/qml/Changelog.qml

After this comment https://github.com/opengisch/QField/issues/1327#issuecomment-716383921 it seems it's something with the new implementation of the changelog. 
Maybe it's some kind of sandboxing on Galaxies on external resources?  That's why I wrapped `new XMLHttpRequest` in a try/catch.

Fix crashes on "What's new"

---

src/qml/editorwidgets/Range.qml

This is how the config looks in QGIS:
But in QField one is not allowed to write more than a single digit.
See https://github.com/opengisch/QField/commit/0ba58d9febb30d6cc6f68b96e11ba35c8927159d#r43834696

Copy the QGIS behavior when min/max/step are not set

---

src/qgsquick/qgsquickmapsettings.cpp

Went deep down the rabbit whole to figure this one out. A good example of the number of lines not being so representative of the amount of energy spent figure things out :wink:

Fix QField _always_ ignoring project transformation settings

---

src/qml/editorwidgets/Range.qml

If the value is a digit, the typeof value is 'number', not 'numeric'. Not exactly sure what numeric vs number entails. But without this fix, our range slider is broken.

Fix range editor widget not assigning slider value properly

---

.github/workflows/continuous_integration.yml
android/build.gradle
cmake/AndroidManifest.xml.in
scripts/ci/build.sh

**_Remember, remember the 2nd of November_**
https://developer.android.com/distribute/best-practices/develop/target-sdk
Easy. But on targetSdkVersion 29 the function used in opening the main storage of android is deprecated: [Environment.getExternalStorageDirectory()](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory())
**There are two possiblities:**
1. Implement the file opener etc. with functions and ways that are supported with 29 (see https://developer.android.com/training/data-storage#filesExternal)
2. If time runs out I think this commit here would make it as well to support the [legacy function](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage): ab091f421716ba47edf8cf5beae6b075ddab945c 
But I think the …

targetSdkVersion 29 upgrade and `getExternalStorageDirectory()`

---

.github/workflows/continuous_integration.yml
scripts/ci/pull_translations.sh
scripts/ci/setup_signing_key.sh

There is one last use of `CI_SECURE_ENV_VARS`, but I don't know whether these secrets are present in GitHub:
$encrypted_c158cd588669_key -iv $encrypted_c158cd588669_iv 
They are used in this script:
https://github.com/opengisch/QField/blob/a7e4e95cb4e652763a4baddd7119b5400984e877/scripts/ci/setup_signing_key.sh#L4-L6
Which is called from here:
https://github.com/opengisch/QField/blob/a7e4e95cb4e652763a4baddd7119b5400984e877/.github/workflows/continuous_integration.yml#L21
@m-kuhn help?
Fixes https://github.com/opengisch/QField/issues/1381

Set TX_TOKEN in github workflow and assume it's set in pull_translations

---

android/src/ch/opengis/qfield/QFieldActivity.java
src/core/androidplatformutilities.cpp
src/core/androidplatformutilities.h
src/core/platformutilities.cpp
src/core/platformutilities.h
src/core/qgismobileapp.cpp

This PR enables QField users to define postgresql services via a pg_service.conf file inside their mobile device's <external_drive>/QField/ directory.
Note that <external_drive> is NOT the sd card but the internal storage.
For the non-geek users, this means adding a QField directory in the root of the external drive you see popping up on your laptop/workstation when connecting the mobile device via a USB cable.
Services are defined as follow in the pg_service.conf file:
```
[qfield_db]
host=demo.qfield.org
port=8080
dbname=qfielddemo
user=qfielduser
password=qfielduser
sslmode=disable
```
You can add as many of those as you want. Lastly, you have to make sure your postgresql layers are using the service (vs. manually defining the host,port,dbname, etc.) for those to rely on the service …

Allow users to define postgresql services in a pg_service.conf on their devices

---

src/qml/BadLayerItem.qml

Fix text being clipped and, while at it, add a little bit of padding around elements:

Fix text clipped in the missing layer(s) panel

---

src/core/attributeformmodelbase.cpp

This PR fixes #1326 . Thanks to @9ls1 for having provided a test project. His form configuration is a pretty good stress test for QField :smile: 
The bug being fixed here is that until now, QField - contrary to QGIS - would block feature form submission when hidden attributes wouldn't match their constraints. It makes no sense since those attributes can't be edited to begin with.

Fields that aren't visible should always return valid constraints

---

src/qml/FeatureForm.qml

As @m-kuhn mentioned, there's no real need for the current extra click needed to enable attribute editing when in multi-edit mode. This PR fixes that.

Remove need for extra click when in multi edit mode (fixes #1256)

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h

This PR further optimizes the flat tree model by avoiding (as much as possible) model resets when rows are inserted and removed from the source model.
I was hoping we could avoid adding this level of complexity, but it turns out force rebuilding the proxy model on all row insertion deletion creates bad speed regressions.
For e.g., @RatInTheField reported a regression whereas adding a feature freezes QField for ~15 seconds. The reason why that is is that the layers he's using to add new features have [x] show feature count enabled, which in turn triggers _three_ pair of rows removed / inserted (the layer tree removes and re-add the layer's legend children to repopulate the count).
So, here we are.
Handling insertion of rows isn't too complex.  But for rows being deleted, it's slightly more …

Further reduce number of scenarios where we force rebuild the flat tree

---

src/core/featurelistmodel.cpp

Steps to reproduce:
1) open a project
2) start editing a feature with relation editor widget
3) load a new project without closing the editing form
4) crash!

Fix crash on reloading project while editing feature with value relation editor widget

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/qml/Legend.qml

So, it turns out that setting a large number of listview items to visible: false & height: 0 can lead to serious application freeze when the number of hidden items is very large (i.e. > 1,000 items). This becomes a problem for QField's legend when a project contains a number of layers with a large number of legend items (e.g. paletted/unique value rasters with 255 values each).
The solution is to do-the-right-thing(tm) and add a filter proxy model. This PR does that. 
The speed regression was spotted and reported by @monticola2 about a week ago.

Add a filter proxy to the flat legend model to avoid freeze when hundreds of legend items are hidden

---

src/core/CMakeLists.txt
src/core/changelogcontents.cpp
src/core/changelogcontents.h
src/core/qgismobileapp.cpp
src/qml/Changelog.qml
src/qml/qgismobileapp.qml

This is an attempt to revive the changelog removed in https://github.com/opengisch/QField/pull/1375 , due to crashes on some devices, as described in https://github.com/opengisch/QField/issues/1327 and https://github.com/opengisch/QField/issues/1369 .
Now the implementation uses `QgsNetworkAccessManager` to connect to the outside world, after the lessons learned by making network requests from QML. 
sudo fairy make-apks

Implement the changelog request and parsing in C++

---

src/core/referencingfeaturelistmodel.cpp
src/core/referencingfeaturelistmodel.h
src/qml/editorwidgets/RelationEditor.qml

All of these should be gone:
```
qrc:/qml/FeatureForm.qml:578:3: QML ToolBar (parent or ancestor of Material): Binding loop detected for property "foreground"
QQmlExpression: Expression qrc:/qml/editorwidgets/RelationEditor.qml:25:9 depends on non-NOTIFYable properties:
QgsProject::relationManager
qrc:/qml/editorwidgets/RelationEditor.qml:56:11: QML QQuickText: Cannot anchor to an item that isn't a parent or sibling.
QQmlExpression: Expression qrc:/qml/editorwidgets/RelationEditor.qml:26:9 depends on non-NOTIFYable properties:
QgsProject::relationManager
qrc:/qml/FeatureForm.qml:446:11: QML Connections: Detected function "onValueChanged" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name. …
```

Fix number of warnings and errors in the RelationEditor

---

src/core/qgismobileapp.cpp

Our QField external storage data directory (i.e. /QField/) now has an additional use: registering extra fonts users might need in their projects. 
Users can simply copy TTF and OTF font files into <external storage>/QField/fonts for QField to register those on app startup. Beautiful project rendering ensues.

Allow QField to register extra fonts from external storage

---

src/core/valuemapmodel.cpp

TIL 
```
/**
* Will be saved in the configuration when a value is NULL.
* It's the magic UUID {2839923C-8B7D-419E-B84B-CA2FE9B80EC7}
*/
const QString QgsValueMapFieldFormatter::NULL_VALUE = QStringLiteral( "{2839923C-8B7D-419E-B84B-CA2FE9B80EC7}" );
```
Should fix #605

Respect the null value in the value map widget

---

android/src/ch/opengis/qfield/QFieldActivity.java
android/src/ch/opengis/qfield/QFieldUtils.java
cmake/AndroidManifest.xml.in
src/core/qgismobileapp.cpp

@signedav , @m-kuhn , this PR resurrects QGIS project file association for QField on Android. It allows QField to be launched & open a given project from a file manager such as Amaze again.
Fixing file association stuff opens the door for other interesting possibilities, such as opening of GeoPDFs, vector datasets like KML, etc.

Resurrect QGIS project file association on Android

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/qml/LayerTreeItemProperties.qml

This is only valid for layer properties, the legend rendering remains the same. It renders the number of features the same way as it is from QGIS in square brackets.

Always show feature count in layer properties popup

---

src/core/qgismobileapp.cpp
src/core/recentprojectlistmodel.cpp

With the new approach for demo projects, it is impossible to use them during development, since their path is always reset to unusable path on desktop. So in that case, if the demo project file cannot be found, just don't add it at all.

Fix usability issues with demo projects on desktop

---

CMakeLists.txt
scripts/docker-build.sh
sdk.conf

My local build crashes with this. But so does `codex` built locally as well and the APK built on PR #1439 is fine.
So with this PR I want to check if it's just my local environment that does not work properly.
The `latest` image of the SDK is named like this because the tag 5.15.1 was invalid.
It contains:
- Qt 5.15.2 (2!)
- Changes for the codex (like the 20201126)
- qtconnectivity (to use QBluetooth stuff)

Qt Version 5.15.2 / more codecs / qtconnectivity

---

CMakeLists.txt
android/src/ch/opengis/qfield/QFieldActivity.java
src/app/main.cpp
src/core/androidplatformutilities.cpp
src/core/androidplatformutilities.h
src/core/platformutilities.cpp
src/core/platformutilities.h
src/core/recentprojectlistmodel.cpp
src/core/utils/fileutils.cpp
src/core/utils/fileutils.h
src/qml/About.qml

This is a major change regarding
- java bootstrap code
- asset deployment
Almost all the initialization java code is gone. Java now does:
- Creating the /QField/basemaps, /QField/proj, /QField/fonts directories
- Obtaining some intent data for opening qgz files (to be tested)
- Setting intent data for the app itself (version information, project file to open)
Assets are no longer zipped, they are delivered as files. They are copied from the original path to some user writable location on first run and when the version changes.

Shorten java code

---

images/images.qrc
images/themes/qfield/nodpi/ic_hide_green_48dp.svg
images/themes/qfield/nodpi/ic_show_green_48dp.svg
src/qml/LayerLoginDialog.qml
src/qml/imports/Theme/QfTextField.qml
src/qml/imports/Theme/qmldir
src/qml/qml.qrc

As soon as the password field loses focus, the password is hidden.
Also, by adding a `QfTextField`, we can further easily modify text looks of the fields across QField.

Add the ability to see the password you entered

---

src/qml/editorwidgets/RelationEditor.qml

Currently the grey area of the new row in the relation editor is not active. Most of the time I end up clicking on it, since it is the biggest element in the widget. Now clicking on it or on the button has the same effect. Clickable gray area is already a thing for the the relation reference widget.

Make the whole grey area of the relation editor clickable

---

src/qml/editorwidgets/TextEdit.qml

There are few complaints that QField is quite inconvinient when the screen is not as wide as the text input contents. It is very hard to edit those attributes.
`TextField` supports wrap mode, so all should be good. I have remove the text input height, which was modified to support alphabets with very high characters, but it seems QML calculates the height automatically well enough.

Wrap the text input contents when its too long

---

src/qml/TransformedPositionSource.qml

Everything works just fine with Qt 5.14 too, and that allows me to code QField again :wink:

Lower QtBluetooth import to 5.14

---

src/qml/qgismobileapp.qml

This addresses the suggestion in #1515 to re-order the main menu so project-specific actions appear at the top:
The Print to PDF sub-menu now appears at a better location and will adjust its width to fit the longest print layout name. In addition, a disabled menu item was added to provide some advice to the user (a shortcut to address #1514):
The GPS menu got some attention too. I've regrouped the checkbox-enabled menu items together to improve the left alignment feel to the menu:
_No more label clipping!!_

Improvement to ordering, location, and width of main menu and GPS menu

---

src/qml/qgismobileapp.qml

This fixes a UX issue I've heard by many people trying QField (from beginners all the way to pros). It goes like this: "Hey, I opened the demo bees project, toggled edit mode on, and I couldn't see any changes in the interface".
The PR adds a function to auto-select the first _editable_ layer when toggling digitizing on if no layer is selected or if the selected layer is locked (read-only or geometry locked). It's a _huge_ UX improvement. 
GIF:

When toggling digitizing on, insure an editable layer is selected

---

src/core/featuremodel.cpp

Digitizing on mobile devices isn't always as precise or error free as on a workstation. Sometimes, users end up creating invalid polygon intersections as they are drawing/entering their polygon. The chances of that has increased now that QField supports stylus freehand drawing.
This PR aims at auto-fixing such issues in a non-destructive way. Example through GIF:
It's pretty important to end up with a valid polygon as otherwise it fails to properly handle overlap interdiction and topology insertion.

When applying a digitized geometry, insure invalid intersections are removed

---

src/qml/geometry_editors/FillRingToolBar.qml

While working on the reshape tool, it gave me the opportunity to look into the ring fill tool and do some UI/UX improvements.
The PR does the following:
- Let go of the question dialog in favor of a nicer looking Dialog item (which we use elsewhere)
- Decomplexify the question asked to the user after creating a ring in the feature being edited by a/ removing the [ cancel ] option (since the digitizing toolbar allows us to cancel), and b/ since we _always_ create a ring, merely ask whether the user wants to fill the created ring with a new polygon or not
- Allow for multiple rings to be crafted without the need to re-open the feature and re-edit the geometry (that's straight from doing some reshape testing)
How it looks now:
The whole question dialog revamp is IMHO needed as I will freely …

Improve UI/UX of the fill ring tool

---

src/core/featuremodel.cpp
src/core/featuremodel.h
src/qml/geometry_editors/GeometryEditorsToolbar.qml
src/qml/geometry_editors/ReshapeToolBar.qml

Without this, the red rubber band highlighting the feature doesn't get updated and is misleading to users.

Refresh the vertex model when as feature is being reshaped

---

src/core/bluetoothreceiver.cpp
src/core/bluetoothreceiver.h

Introduced in 1.8.0, we were destroying a destroyed QBluetoothSocket.

Fix QField crashing on exit (fixes #1505)

---

src/core/bluetoothreceiver.cpp
src/qml/TransformedPositionSource.qml

QML already triggers a connection via the onActiveChanged trigger (https://github.com/opengisch/QField/blob/master/src/qml/TransformedPositionSource.qml#L55) -- it increases the chance of a successful connect on app launch and avoid a duplicate connection call.

Let QML trigger the connection

---

src/qml/CoordinateLocator.qml
src/qml/DigitizingToolbar.qml
src/qml/PositioningSettings.qml
src/qml/QFieldSettings.qml
src/qml/imports/Theme/Theme.qml
src/qml/qgismobileapp.qml

This PR adds a new accuracy indicator features as well as an accuracy requirement enforcement mechanism when digitizing features. 
When the accuracy indicator is enabled, a badge is attached to the location button and colored red if the accuracy value is below bad, yellow if it falls short of excellent, or green. The badge is subtle as to avoid obscuring the map area:
In addition, an accuracy requirement mode can be toggled on alongside the indicator. The mode is active when the coordinate cursor to be locked to the GPS/NMEA position and prohibits vertex addition when the position accuracy value is below the bad accuracy value threshold. A toaster message is displayed for the user to understand he/she needs to wait for the device to gain a better accuracy:
All of the above can be  toggled …

Positioning accuracy indicator and digitizing accuracy requirement

---

android/src/ch/opengis/qfield/QFieldActivity.java

@m-kuhn , while slaying this blank screen issue, I stumbled on an android permission problem: while we now rely on a bunch of QField/sub-folders on the external storage to fetch additional projection grids, fonts, etc., that's all inactive/inaccessible until the user triggers an external storage permission request when manually opening a local project file using the welcome page button. 
This PR fixes that by checking and asking for the permission whenever we launch QField. 
This'll also have the effect of having the directory creation part of the QFieldActivity.java work on first launch.

Request external storage permission early

---

src/core/CMakeLists.txt
src/core/layerresolver.cpp
src/core/layerresolver.h
src/core/qgismobileapp.cpp
src/qml/editorwidgets/ValueRelation.qml

For reasons, layer ids configured in value relations do not always match with the id of the layer they refer to.
In these cases QGIS resorts to advanced detection techniques to resolve the layer anyway.
Let's do the same with a nice declarative approach.

Add layer resolver

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp

QField should respect the project's labeling engine settings.

Respect project labeling engine settings when rendering canvas

---

src/qml/FeatureForm.qml

This "attacked" me while testing the geometry addition child feature PR:
_Left, white line, right, fixed_

Fix white line in feature form

---

src/core/expressioncontextutils.cpp
src/core/expressioncontextutils.h
src/core/featuremodel.cpp
src/core/featuremodel.h
src/qml/qgismobileapp.qml

The position variables are only set when the digitizing crosshair is locked to the current positioning device location.
The gnss variables are always set.
The `position_source_name` will be set to `manual` when digitizing features with the position not locked
Fixes https://github.com/opengisch/QField/issues/1607

Add new gnss_* variables next to position_* variables

---

src/core/featuremodel.cpp
src/qml/DigitizingToolbar.qml
src/qml/EmbeddedFeatureForm.qml
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/RelationCombobox.qml
src/qml/editorwidgets/CheckBox.qml
src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/EditorWidgetBase.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/Range.qml
src/qml/editorwidgets/RelationEditor.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/TextEdit.qml
src/qml/editorwidgets/ValueMap.qml
src/qml/editorwidgets/ValueRelation.qml
src/qml/geometry_editors/GeometryEditorsToolbar.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

When adding a feature via the relation editor, if the referenced relation layer has a geometry, the user will jump into digitizing mode to add his/her point/line/polygon.
How it looks:

Support for geometry digitizing when adding a child feature via relation editor

---

src/core/rubberband.cpp
src/core/rubberband.h

This fixes a regression  from the rubber band precision work done and merged yesterday. For 'static' rubber band (i.e. those who don't have a moving vertex following the location indicator), we need to listen to visible extent change to update the SGRubberband.

For 'static' rubber band, we need to listen to extent change

---

src/core/CMakeLists.txt
src/core/featurelistmodel.cpp
src/core/featurelistmodel.h
src/core/fieldexpressionvaluesgatherer.h

This PR moves fetching of features for the feature list model _off_ the main thread to avoid UI hangs. This fixes a crash when WFS layers are used in value relation widgets.

Fetch feature list model off the main thread

---

src/core/appinterface.cpp
src/core/appinterface.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/qml/WelcomeScreen.qml
src/qml/qgismobileapp.qml

A screencast worth a thousand words:
https://user-images.githubusercontent.com/1728657/106242968-1cc1fd80-623b-11eb-8925-9bc1f494b620.mp4
Because UI feedback > UI freeze. The MP4 doesn't render the fade in / out loading screen that well, but it's there, and it makes for a really nice transition.
~~@m-kuhn , I did just use processEvents here literally 48 hours after you said "NOOOOOOOOOOOO" :) I however think this specific use is actually safe here. It merely allows for the QML scene to reflect the changes done in the signal onLoadProjectStarted signal. Without it, the loading items randomly fail to show.~~ 
@m-kuhn , you will be happy to know no processEvents were used in the production of this feature :wink:

Improve project loading feedback

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/qml/LayerTreeItemProperties.qml

On slow WFS servers, opening the layer properties panel (to refresh the data for e.g.) can hang QField for dozens of seconds while it's waiting a server reply on the main thread.
This PR improves the layer tree model feature count by relying on the countSymbolFeatures function whenever possible, and (for now) disable feature count on WFS layers.

Avoid UI hang/freeze when opening the layer properties panel due to slow feature count

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/core/qgsquick/qgsquickmapcanvasmap.h
src/qml/QFieldSettings.qml
src/qml/qgismobileapp.qml

This PR improves progressive rendering by:
- adding a map renderer cache, which in used by raster layers to _greatly_ improve intermediate rendering by using a transformed cache image as temporary placeholder during progressive rendering
- switching the RenderPartialOutput on when progressive rendering is on
The end result is a much, much smoother progressive rendering experience:
_Note the raster topo basemap here has its old image cache transformed and rendered onto the canvas prior to its new image being rendered_
**UPDATE** With @nyalldawson 's fantastic follow up work adding smart labels and vector caching, the progressive rendering looks _even better_:
The updated SDK on QField master also contains the recent tile download manager work, which also speeds up progressive rendering of …

Smarter progressive rendering

---

src/core/layertreemodel.cpp
src/qml/qgismobileapp.qml

This fixes a couple of corner case crashers.

Additional safeguards to avoid crash when loading a project with a project already opened

---

src/qml/editorwidgets/DateTime.qml

This will likely fix #1630 . I stumbled on a project file (shared in #1575) which had broken datetime widgets due to configuration missing in the saved QGIS project file.
This PR allows QField to survive this situation and offer a functional datetime widget.

Survive broken datetime widget configuration

---

android/res/values/strings.xml
android/src/ch/opengis/qfield/QFieldProjectActivity.java
src/core/appinterface.cpp
src/core/appinterface.h
src/core/platformutilities.cpp
src/core/platformutilities.h
src/core/projectsource.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/core/qgsquick/qgsquickmapsettings.cpp
src/core/qgsquick/qgsquickmapsettings.h
src/core/utils/featureutils.cpp
src/core/utils/featureutils.h
src/qml/WelcomeScreen.qml
src/qml/qgismobileapp.qml

This PR adds support for opening individual vector / raster datasets in QField without the need for a QGIS project file. Opening such a file in QField will automatically create a temporary project to display the dataset. If the dataset supports writing, users can use the great QField digitizing tools to add and save features into the dataset.
Here's how it looks:
https://user-images.githubusercontent.com/1728657/106351430-af7f9c80-630e-11eb-9903-c206cf78a707.mp4
Off the box, when opening individual datasets, QField will automatically add a openstreetmap layer as basemap on top of which the dataset is displayed. Users can add a custom basemap.qgs (or basemap.qgz) QGIS project file in their device's <storage>/QField/ directory to customize the layer(s) that will be used as basemap.
E.g. of …

Support for opening individual vector/raster dataset in QField

---

CMakeLists.txt
sdk.conf

This PR updates the OSGeo4A SDK to catch a couple of _exciting_ updates:
- An updated GDAL build with its PDF driver enabled (georeferenced PDFs, GeoPDFs)
- An updated QGIS build with rendering speed improvements and fixes

SDK update to gain georeferenced PDF support as well as rendering speed gains

---

cmake/AndroidManifest.xml.in

Before we allowed on QtActivity the orientation change  and on QFieldActivity we locket the orientation  Meanwhile QFieldActivity extends QtActivity and the orientation is locked and allowed in the changes for the  same activity. This leaded to the issue, that the screen does not rotate anymore.

Remove locked from screenOrientation in QFieldActivity.

---

src/core/qgismobileapp.cpp

Instant gratification:
- Exported PDFs will have project metadata added (a few clients should be happy about that)
- Georeferenced PDFs out of the box (possible since the addition of the PDF driver to the OSGeo4A GDAL library)
- Geometry simplification for smaller file sizes
It's also future-proof and far more tested in QGIS than its old QPrinter alternative.

Use QgsLayoutExporter's exportToPdf instead of a QPrinter

---

sdk.conf

Without enabling one JPG decoder in poppler, GDAL ended up only rendering the vector elements. 
We can get away with enabling poppler's internal jpg decoder and get proper rendering. Sweet.

Enable some form of jpg support to poppler to anvoid blank pages

---

src/core/featuremodel.cpp
src/qml/editorwidgets/Range.qml

@m-kuhn , as  discussed.
While debugging this, I've spotted another issue whereas _range_ widgets (i.e. numbers) don't reset values across feature addition when values are set to _not_ be remembered. 
Couldn't figure out why that is happening. The underlying model properly resets the value.

Fix remembered values regression (fixes #1673)

---

src/core/appinterface.cpp
src/core/appinterface.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/qml/qgismobileapp.qml

Title says it all. With this PR, QField will restore the last viewed map extent when re-loading a project that was previously opened by QField. This improves quality of life by a lot.
The implementation is cloud-stored project friendly as it doesn't save the project itself but rather store the extent in the user settings. This means a large cloud-stored project can have many users focused on their own specific extents, remember those without interfering with others.
There's a project/dataset file size check here to reset extent whenever the file size has changed. That's to avoid restore an extent that would have been invalidated by changes to project/dataset.

When re-loadind a project, restore last viewed extent

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp

When the map canvas is frozen (when zooming / panning), any ongoing rendering job should be stopped to prevent "jaggy" panning / zooming of map. Thanks to the recent work by @nyalldawson , we can now do that without losing any of the progressively rendered layers' cache. 
The end result is a smooth panning without any visual cost.

When freezing the map canvas, stop any rendering job in progress

---

src/core/CMakeLists.txt
src/core/appinterface.cpp
src/core/appinterface.h
src/core/projectinfo.cpp
src/core/projectinfo.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/qml/qgismobileapp.qml

@m-kuhn , OK, I give up, I'll do the right thing (tm) :wink: and while doing so, add restore last used map theme when reloading project :tada: 
Note: I'm using a pointer to the layer tree property here (instead of say a map theme string) as it unlocks more doors for the future, e.g. saving / restoring visibility of individual layers. Full disclosure: I'm not going to go there now, just stating it as a possibility for the future.

Improve project extent saving and add map theme saving

---

src/qml/RelationCombobox.qml

The trouble of selecting values under the android keyboard should be gone and fix #1579. If one tries to scroll, the keyboard disappears.

Hide keyboard on list view move started

---

android/src/ch/opengis/qfield/QFieldActivity.java
scripts/docker-build.sh
src/core/androidplatformutilities.cpp
src/core/appinterface.cpp
src/core/appinterface.h
src/core/qgismobileapp.cpp

If QField is already running, opening a QGIS project file via file association would bring QField in the foreground but fail to actually load the file.
This PR adds file association handling against a running QField instance :partying_face: .

Support file association against _running_ QField instance

---

src/core/qgismobileapp.cpp

@signedav , here, you'll be able to view your favorite recipe PDFs within QField without an pointless OSM basemap showing up :wink:

Only add a base map/project to dataset opening when a valid CRS is present

---

src/core/qgismobileapp.cpp
src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/core/utils/geometryutils.cpp
src/core/vertexmodel.cpp

This PR applies datasets' default style (i.e., embedded into a gpkg database or served through a side .qml file) when present. This means not only symbology but also customized feature form, etc.
https://user-images.githubusercontent.com/1728657/109104224-2ff2bb00-775e-11eb-8916-168b74d0b11c.mp4

Make use of dataset's default styles if present

---

src/core/qgismobileapp.cpp

Unless GDAL is compiled against libkml, it doesn't support the opening of KMZ files. We can however "trick" GDAL in doing so by using the /vsizip/ virtual file system. Clever workaround @nyalldawson came up with.
This fixes #1715.

Workaround GDAL's internal KML driver lack of KMZ support

---

src/core/qgismobileapp.cpp

@m-kuhn , I pushed the merge button a bit too quickly here.
The PR is changing ZIP handling so we can open both vector and raster datasets. The actual vector / raster dataset opening is _only indent changes_, the part added is line 606 to 630 (which has been tested in QGIS's browser panel for ages (see QgsZipItem class).

Proper way to handle ZIP container, unlock mixed vector / raster dataset loading

---

src/core/messagelogmodel.cpp
src/core/messagelogmodel.h
src/qml/MessageLog.qml
src/qml/qgismobileapp.qml

- Button to clear the message log
- Button in the main menu to open the message log on demand
- Click on message log entry will copy the text
Fixes #1723

Message log improvements

---

src/core/linepolygonhighlight.cpp

@m-kuhn , I think this might fix / help avoid the crash you were witnessing yesterday.

Avoid transforming empty geometry in LinePolygonHighlight

---

src/qml/editorwidgets/TextEdit.qml

This PR fixes several textedit editor widget regressions that slipped into QField since 1.6:
- missing bottom border line when not in edit mode in non-multiline mode
- wrong bottom border line color when in multiline mode for both edit and non-edit mode
- overlapping text + textarea when editing in multiline mode
Not sure how we missed the missing bottom border line for so long. When noticed, it can't be unseen.
Before vs. PR in read mode:
Overlapping text + textarea in edit mode (there's no vs. after, it's just fixed :) )

Fix several textedit editor widget regressions

---

src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/ValueMap.qml

This PR (dramatically?) improvements the looks of the picture-mode external resources editor widget by:
- avoiding a super-sized missing/broken image icon and making that icon semi-opaque
- aligning various icons on an invisible horizontal plane
- enlarging the tiny action buttons in edit mode
I've also fixed the value map editor widget's bottom border line in read mode:

Editor widgets improvements

---

sdk.conf

In preparation for 1.9 beta release, update libs.

Update OSGeo4A SDK to grab latest GEOS and OpenSSL libs

---

src/core/attributeformmodelbase.cpp

@signedav , while testing your client's parcel demo prototype (GCK-Rto), I noticed a confusing part of our UI/UX, whereas one field would keep being red even though I had fulfilled the constraints _QField was showing me_ (namely non NULL and unique). Turns out the field also had an expression constraint with an empty description.
This PR reduces the confusion by adding a default "Expression constraint" when no description is available, to let users know why a field would remain red.

When an expression constraint lacks a description, add a generic tip to users

---

src/qml/editorwidgets/TextEdit.qml

Another UI/UX issue spotted while testing @suricactus client's project file: QField's text edit widget doesn't reflect the maximum length set by the field. If a field has a text has maximum length of 5 [characters], QField would allow entering more than 5 characters, only to silently chop its value when saving (and not immediately reflect the change in the UI).
This PR fixes that by setting the maximumLength property of the text edit widget's TextField to match that of the field.

Respect maximum length in text edit widget

---

src/core/finlandlocatorfilter.cpp
src/core/locatormodelsuperbridge.cpp
src/core/qgismobileapp.cpp

Hopefully fixes issue #1754.
@m-kuhn , as you hinted, it seems QObject::tr() doesn't work out in providing translatable strings here. The hopeful part is me hoping QCoreApplication::translate() will work better :smile:

Fix missing translations

---

src/qml/qgismobileapp.qml

Once upon a time, QField's "toast" message container was an item which could be clicked through. That had to change to a popup to insure the message was displayed on top of everything else. However, it also led to clicks being blocked over that message area for the duration of the text (see e.g. #1611).
This PR tries to improve the situation by dismissing the message [popup] immediately when a click is detected. It's not perfect, but at least people can get rid of it before the 3 second timer runs out.

Dismiss toast message when clicking on it

---

src/core/CMakeLists.txt
src/core/platformutilities.h
src/core/qgismobileapp.h
src/core/qgsquick/qgsquickmapsettings.h
src/core/referencingfeaturelistmodel.h
src/core/rubberbandmodel.h
src/core/utils/featureutils.h
src/core/utils/fileutils.h
src/core/utils/geometryutils.h
src/core/utils/stringutils.h
src/core/utils/urlutils.h
src/core/vertexmodel.h

Properly define attribute visibility / dllexport the symbols needed by qfield app from qfield core.
@3nids in order to not mess too much with your current work, please let me know if you prefer to postpone this after the build chain work you are doing.

Generate export headers for qfield_core

---

.github/workflows/continuous_integration.yml
src/qml/MapCanvas.qml
src/qml/qgismobileapp.qml

This PR improves the deactivation of the map canvas's follow location mode by not only listening to manual panning of the map via finger gesture but also deactivating the mode whenever a user uses to search bar to go to a X,Y location, or uses the search result's shortcut to jump to feature location, etc. etc.
This is what the bug looks like:
https://user-images.githubusercontent.com/1728657/111453897-a293fc80-8746-11eb-9f96-53f97bc4d629.mp4

Fix canvas follow location interfering with jump to feature / go to coordinate

---

src/core/attributeformmodelbase.cpp
src/core/deltafilewrapper.cpp
src/core/featurechecklistmodel.cpp
src/core/featuremodel.cpp
src/core/featureslocatorfilter.cpp
src/core/fieldexpressionvaluesgatherer.h
src/core/identifytool.cpp
src/core/multifeaturelistmodelbase.cpp
src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/core/utils/fileutils.cpp
src/core/vertexmodel.cpp
test/test_layerobserver.cpp

Because it's the right thing to do, and because QGIS is getting rid of qgis::as_const.

qgis::as_const -> std::as_const

---

sdk.conf
src/core/attributeformmodelbase.cpp
src/core/bluetoothdevicemodel.cpp
src/core/featurelistmodel.cpp
src/core/gotolocatorfilter.cpp
src/core/qgismobileapp.cpp
src/core/qgsgpkgflusher.cpp

Needed to backport QGIS fixes to 1.9, including fixing feature addition on a CSV layer.

[backport release-1_9] OSGeo4A SDK update to QGIS 3.18.1 final

---

src/core/qfieldcloudconnection.cpp
src/core/qfieldcloudprojectsmodel.cpp

Makes the error responses a bit more beautiful (no double URL).
Show "Server error" when the HTTP status code == 400.
Fix double reading the response payload (second time empty).

Fix error response feedback

---

src/core/attributeformmodelbase.cpp
src/core/featuremodel.cpp
src/qml/FeatureForm.qml

This PR partially fixes #1624 -- a fix is also needed in QGIS, which I will submit in a minute.
This was caused by the following commit in QGIS (https://github.com/qgis/QGIS/commit/b078be618520f925e07e40599036f00f806fbc3e), which modified null values from OGR provider datasets (see this line https://github.com/qgis/QGIS/commit/b078be618520f925e07e40599036f00f806fbc3e#diff-e49c5ac0cde677bf01e13a0838f8f37ea2dffe73c4b8def4f9f7679d920984a0R326).
This caused two issues in QField itself:
- QML models don't handle QVariant( QVariant::Type ) properly, and shows the default value while ignoring the fact that the QVariant itself is set to null
- Also - and somewhat stupidly? - QVariant( 0 ) == QVariant( QVariant::Int ), which let to feature model not updating when switching from null to zero and …

Fix empty numeric fields saved as 0 instead of NULL

---

src/core/featuremodel.cpp
src/core/featuremodel.h

This fixes (at least) #1817 and #1823.
In addition to fixing the regression, there's a nice improvement buried in there: the remembrance settings are now shared across multiple feature forms (i.e. overlay feature form, embedded feature form, etc.).

Fix and improve remembered values

---

src/qml/FeatureListForm.qml

@lindacamathias , that fixes the UX issue you spotted.

Automatically close the features list when none are lefft after feature(s) deletion

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/core/qgismobileapp.cpp
src/qml/QFieldCloudScreen.qml

The cloud community tab is back in force.
A GIF worth a 100 word description:
Some food for thoughts while I was implementing this:
- _Not for 2.0_, but eventually, we'll need to break down this mammoth QFieldCloudProjectsModel into a QFieldCloudProjects vs a leaner model class that doesn't act as a swiss army knife.
- I'm not entirely sure what will go int the community tab, but if the list expands beyond a dozen curated (and maybe geofensed?) projects, we should avoid fetching a large public list when the user logs in and instead only to that whenever he/she clicks on the community tab

 Say hello to QFieldCloud's community projects 

---

src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/QFieldCloudScreen.qml
src/qml/imports/Theme/Theme.qml

Having a redundant string prefix in the project titles makes it much harder to skip through a long list, and eats up valuable horizontal space. Let's make use of QML ListView's nifty section headers.
GIF:

Avoid prefixing the owner to the title of each cloud projects, use ListView section headers

---

src/core/platformutilities.cpp
src/core/qfield.h
src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/qml/QFieldCloudPopup.qml

@suricactus , as discussed yesterday, this PR fixes and improves attachment uploads to the cloud.
First, there's a UI feedback informing people that attachments are being uploaded in the background:
_Feedback at the bottom of the cloud project panel_
Behind the scene, attachments uploads can be cancelled and resumed as well as new attachments appended during a session. If an attachment upload fails (network error, device gone offline, etc.), the failed attachment is keep in the list of attachments to upload and QField will retry the next time the user hits the [ Push changes ] button.
What's left to do is making that list of attachments 'permanent' across QField shutdown and restart.

Improvement on handling of attachments uploads to the cloud

---

src/core/qgsquick/qgsquickmapsettings.cpp

This fixes #1854, whereas rendering  SVG and raster markers / fills symbol layers with relative paths (data defined or otherwise) resulted in broken renderings on QField.

Fix use of relative paths by symbol layers during map canvas rendering

---

src/core/qfieldcloudconnection.cpp
src/core/qfieldcloudconnection.h
src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/qml/DashBoard.qml
src/qml/NavigationBar.qml
src/qml/qgismobileapp.qml

@suricactus , as discussed over the chat, here comes the next piece: permissions handling.
It was a bit more involved than I initially thought it'd be as I had to do some logic updates for QField to remember the last successfully logged in user to unlock proper cloud project models reload while offline (or while connecting). This was working way back last year but along the way as we added more components and refined logics, we lost offline project list loading. All good now.

QField should respect QFieldCloud permissions model

---

src/core/CMakeLists.txt
src/core/deltalistmodel.cpp
src/core/deltalistmodel.h
src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/core/qgismobileapp.cpp
src/qml/LocatorSettings.qml
src/qml/QFieldCloudDeltaHistory.qml
src/qml/QFieldCloudPopup.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

This PR adds a push history popup panel for cloud projects. The history gives a list of deltas pushed with a status:
One thing that jumped at me while doing this: for projects edited by multiple users, we would definitively gain showing the user info alongside date and status.
The UI is not entirely finished (currently the panel is accessible via a hidden click on the 'no change pushed yet/last changed pushed on XXX' label, and there's a missing [X] to close the panel (you can do so by clicking on margins).
@suricactus , I renamed a class and a few members / structs to try and make things clearer, hope I achieved this.

Add a push history popup panel for cloud projects

---

src/core/referencingfeaturelistmodel.cpp
src/core/referencingfeaturelistmodel.h
src/qml/EmbeddedFeatureForm.qml
src/qml/FeatureForm.qml
src/qml/editorwidgets/RelationEditor.qml
test/test_referencingfeaturelistmodel.cpp

Aimed at fixing #1850 .
Here's how it looks in real style:
Edit style:
I've used a custom scroll bar and our QField green to have it pop out a bit more.

Relation editor widget UI/UX improvements

---

src/core/deltafilewrapper.cpp
src/core/deltafilewrapper.h
src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/qml/QFieldCloudPopup.qml
src/qml/qgismobileapp.qml

While we should aim at it being a one in a million chance to occur, we should still provide an helpful UI/UX for those who might end up with a broken local deltas file (phone crashed, etc. etc.). This PR does that.
Now, when a broken deltas file is detected upon loading a project, the cloud project popup will automatically appear with a customized UI to inform the user about his bad luck:

Improve UI/UX and user awareness of a broken local deltas file situation

---

src/qml/EmbeddedFeatureForm.qml
src/qml/OverlayFeatureFormDrawer.qml

This PR fixes #1871 , whereas the @snapping_results variable was not properly populated when adding features.

Fix missing @snapping_results variable content (fixes #1871)

---

src/qml/FeatureForm.qml

This PR fixes #1884 . The long story short here is that when the feature form contained items with conditional visibility and items' visibility would change between the time you closed a feature form and re-opened it, the ListView would go broken. Reason for it going :boom: is our use _against documentation warning_ of ListView.contentY = 0. That led to worlds colliding, Thanos snapping our form out of existence, etc.etc.

Fix ListView going broken when resetting feature form

---

src/qml/editorwidgets/CheckBox.qml
src/qml/imports/Theme/QfSwitch.qml

This PR revamps the checkbox editor widget. Obligatory GIF:
Improvements include:
- Most importantly, we have a string representation of the state (true/false) in the form of a label, which is _very_ good as quite a few people out there don't know what a label-less empty square means :)
- Much nicer looks relying on our QfSwitch style
- Adjusted spacing/padding and added a bottom green line to harmonize with other editor widgets
- A nicer "hit area"
Because the widget now has a label, we can support QGIS' stored value display settings configuration. Second GIF:
That option is in QGIS' checkbox widget configuration panel:
It also fixes an issue whereas cancelling form change wouldn't have modified checkboxes sync back to the original value.

Improvements to the checkbox editor widget

---

src/qml/FeatureListForm.qml
src/qml/NavigationBar.qml
src/qml/imports/Theme/QfToolButton.qml
src/qml/qgismobileapp.qml

This fixes #1883 as well as a bunch of other focus-related issues with tool buttons (e.g. zoom in / out) stealing focus and breaking our back / escape hardware key handling.
The PR also adds a permanent 'back' button to the feature list / form panel, which should please QField users on iOS.

Focus improvements all around

---

src/qml/TransformedPositionSource.qml

qrc:/qml/TransformedPositionSource.qml:18: Error: Unable to determine callable overload.  Candidates are:
formatDistance(double,int,QgsUnitTypes::DistanceUnit)
formatDistance(double,int,QgsUnitTypes::DistanceUnit,bool)

Fix Error: Unable to determine callable overload. formatDistance

---

src/qml/FeatureForm.qml
src/qml/NavigationBar.qml
src/qml/Tracking.qml

As discussed, to help UI/UX on iOS where it lacks a hardware back button, this PR insures that the OK and cancel/delete button is always visible in the add feature form, irrespective of whether fast editing is on or off.

Always show the iOS and cancel/delete button in the add feature form

---

src/qml/FeatureListForm.qml

[Backport release-1_9] When exiting the multi selection mode via the back key, clear selection

---

src/qml/TransformedPositionSource.qml

This fixes a regression introduced this commit (https://github.com/opengisch/QField/commit/50587695f6790e24add031797a30f5579b116b15#diff-d0554b120b4c49e85d8747da005f129cd59618a977ac7b3032c48c9722c5194b).
@m-kuhn , this wasn't backported to 1.9 right?

Fix accuracy radius indicator gone missing

---

src/core/snappingutils.cpp

The code for adding Z/M from snapping results always took the closest vertex to force the snapping result.
This code is now disabled for segments and area, we only take the 2D results in these cases.
Note: we don't do any interpolation of Z/M, this differs from QGIS which assumes a linear interpolation of Z/M along line segments.
Fixes #1929

Fix snapping to segment

---

src/qml/FeatureForm.qml
src/qml/qgismobileapp.qml

While fixing the feature addition yesterday, I noticed a pretty bad bug with fast editing mode, whereas addition of points leading to double / triple feature creation follow by a bunch of message log errors thrown at the user and a broken UI.
The long story short here is that when we call feature form's create(), it leads to a values changed signal (e.g. fid value changes, etc.), which in turn triggers the fast editing's auto save on value changes. This would lead to worlds colliding, and end up with multiple points created and a broken UI (i.e. feature form drawer open without a navigation bar, etc.)

Fix double feature creation when adding points in fast editing mode

---

src/core/layertreemodel.cpp

So, turns out an abstract item model can insert row items with pre-existing children. In our legend context, it can happen when a layer has a multi-level rule-based renderer with feature count on. The source layer tree model deletes and re-inserts the root items of the rule-based renderer, with children attached to those parent items.
Practical example: the advanced bees demo's apiary layer.
I didn't know this was possible, I had (wrongly) assumed that inserted items would always be called individually. By not having handled the above scenario, we'd end up losing legend items (e.g., with the advanced bees demo, if you add a point, the individual disease marker legend items disappear).
The solution is to trigger the more costly model re-building when we detect this scenario (we do …

One more legend corner scenario: insertion of rows with pre-existing children

---

src/core/layertreemodel.cpp
src/core/legendimageprovider.cpp

Instead of using symbol legend display name (those aren't guaranteed to be unique, and lead to issues like #1913), use the layer tree model indexes' internal ID to build legend item symbol strings.
@lindacamathias , this should fix your issue.

Fix legend showing wrong symbol for layer sub items with same name

---

src/core/layertreemodel.cpp
src/core/legendimageprovider.cpp

[Backport release-1_9] Fix legend showing wrong symbol for layer sub items with same name

---

src/core/androidplatformutilities.cpp
src/core/androidplatformutilities.h
src/core/platformutilities.cpp
src/core/platformutilities.h
src/qml/QFieldSettings.qml

It doesn't make sense to show a setting without effect

Disable native camera on non android devices

---

src/core/qgismobileapp.cpp
src/qml/WelcomeScreen.qml

This comes in quite handy when people want to temporarily or permanently set a specific project as the one used as 'basemap' when opening individual datasets. 
It's *especially* useful for QField users who would want to make use of a QFieldCloud project, entirely removing the need to go through a USB cable file transfer.
The action is found in the menu that pops up when long-pressing a project in the recent projects list:
Note: I first add the menu item text be "set as file associated project", and wasn't satisfied with it. I've settled for "set as default project", which isn't ideal but is less obscure.
@xBcai , the feature request you filed doesn't quite match this PR but hopefully it'll meet you half way there :wink:
Edit: as of this PR, the 'basemap' logic when opening an individual …

Allow users (via the welcome screen) to specify the default project to use when opening individual datasets

---

.github/workflows/publiccode.yml
publiccode.yml

This PR contains a proposal for a publiccode.yml file for QField.
The presence of a publiccode.yml file enables the listing of an open source project in the Italian Government FOSS catalogue (https://developers.italia.it/it/search?type=software_open&sort_by=relevance&page=0 ), which showcases FOSS software which can be useful for Public Administrations (as an example, it contains Libreoffice, too).
The publiccode.yml is also being proposed as an international standard for documenting FOSS software.

Add publiccode.yml

---

src/qml/editorwidgets/ExternalResource.qml

Because on windows it's tempting to use the other one which leads to weird results

Replace \ with / in image paths

---

src/qml/editorwidgets/TextEdit.qml

QField does not (yet?) support JSON and list field types. ATM, it defaults to using the text editor widget, which displays a string representation of those objects in read view just fine, _but_ throws an empty edit field when editing features, which is set to a blank value and can't really be edited.
Until further notice, just show the string representation whether we're in edit mode or not. Showing that instead of a blank important edit field makes us look a lot better ;-P

Until we support those, prevent text editing of JSON / list fields

---

src/core/featuremodel.cpp
src/core/featuremodel.h

This PR alters how QField behaves when topological editing is on to consider _all_ editable (i.e. non read-only) vector layers as part of the overall project topology. This means that if I move a vertex from a currently selected / active line layer, it will not only insure that overlapping vertices within the line layer are moved too, it'll also do so for all other editable layers.
Makes topological editing that much more useful in QField. We'll need to add a note in the documentation so people are aware of this behavior, since it diverges from what QGIS does. Our big brother applies topological changes only to layers with edit state toggled on, which isn't appropriate for the QField environment.

Consider all writable vector layers as part of topology when editing

---

src/qml/geometry_editors/FillRingToolBar.qml
src/qml/geometry_editors/ReshapeToolBar.qml
src/qml/geometry_editors/SplitFeatureToolbar.qml
src/qml/qgismobileapp.qml

While developing the digitizing logger feature, I realized the geometry editor vertex digitizing didn't align with the main digitizing toolbar (i.e. feature attention). Long story short here is that it removed the last vertex (mimicking QGIS instead of QField). 
This PR fixes that, as well as apply an important related fix  on handling of hovering pen when entering geometry editors' digizing toolbar area.

Important fix to geometry editor handling of vertex digitizing

---

src/core/utils/geometryutils.cpp

Simplify and fixing handling of geometry's avoid intersection operation return value (i.e., just rely on empty geometry check to see if something went wrong).

Fix reshape tool handling of geometry operation return values

---

src/core/changelogcontents.cpp

[Backport release-2_0] Fix the changelog listening to QNetworkAccessManager

---

src/core/bluetoothreceiver.cpp

@geckeau , this will fix the absence of @{gnss,position}_source_name content when using a GNSS device through bluetooth.
As for the other variables you mentioned:
- @position_vertical_speed is not something that's broadcasted/available via NMEA, there seems to be little we can do about this one
- @position_magnetic_variation is something NMEA covers but QGIS hasn't implemented yet.
- @position_used_satellites should work, but I don't have an NMEA device at hand to test ATM

Identify NMEA position information source

---

android/src/ch/opengis/qfield/QFieldActivity.java
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/qgismobileapp.cpp
src/qml/EmbeddedFeatureForm.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/QFieldSettings.qml
src/qml/qgismobileapp.qml

QField now dims screen brightness when idling. It's a default behavior which can be turned off via a setting toggle:
This should make field users _very_ happy as it can result in much, much longer battery life when keeping QField on to do tracing et cie.

QField ❤️ 🔋 and now dims screen brightness when idling

---

src/core/settings.cpp
src/core/settings.h
src/qml/Changelog.qml
src/qml/QFieldCloudLogin.qml

@m-kuhn @signedav as discussed
If loading the changelog from the internet is dangerous, let the user do it.
Notify the user they need to change their device.

Add a flag when the device crashes on request and disable QFC if needed

---

src/core/deltafilewrapper.cpp
src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/core/utils/qfieldcloudutils.cpp
src/core/utils/qfieldcloudutils.h
src/qml/QFieldCloudPopup.qml
test/test_deltafilewrapper.cpp

This way we can identify deltas on the server side that are comming from the same device and/or the same export. For privacy reasons of our users, we recreate the `clientId` after each successful export.
The `exportId` will not be directly used for now, but it is a good statistic for future use.

Add exportId and clientId in the delta data

---

src/app/main.cpp
src/core/CMakeLists.txt
src/core/appinterface.cpp
src/core/appinterface.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/core/screendimmer.cpp
src/core/screendimmer.h
src/qml/EmbeddedFeatureForm.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/qgismobileapp.qml

Screen brightness dimmer, take 2.
I've gotten rid of QML to detect mouse events in favor of good old C++ by plugging in an event filter with the application itself. The benefits are:
- it detects key strokes (both from hardware keyboards as well as virtual ones), which takes care of the issue @suricactus raised that had us temporarily bump timeout to 60sec
- we now listen to the application being suspended / resumed, and restore brightness when resuming the app (it'd otherwise timeout in the background, not great)
- gets rid of hacky QML setup which wasn't working with dashboard overlays et cie (and had us disable the dimmer as a workaround the QML limitation)

Rework screen dimmer, react to all keys, touches, and mouses

---

src/qml/NavigationBar.qml

Fix navigation bar's back button gone missing

---

src/core/attributeformmodel.h
src/core/attributeformmodelbase.cpp
src/core/attributeformmodelbase.h
src/core/featuremodel.cpp
test/CMakeLists.txt
test/test_attributeformmodel.cpp

This PR adds support for 'live' updating of default attribute values when editing features. While this was 'accidentally' working when fast-editing mode was turned on, the PR makes it working reliably all the time. 
In this screencast, you can see the "int" attribute value change makes the "blah2" attribute default value update:
https://user-images.githubusercontent.com/1728657/126150187-e1ea7d8a-1226-4db2-864b-18439e33332b.mp4
I've also taken the liberty to mark attribute fields with default values that are modified on feature update 'read-only'. It makes little sense to have those fields editable as whatever value is entered by the user will ultimately be overwritten. 
Linked issues:
Fixes #1741
Fixes #1193
Fixes #1127
Fixes #914 
and likely more.

Support for 'live' default value updates when editing features 

---

src/core/utils/stringutils.cpp
src/core/utils/stringutils.h
src/qml/FeatureForm.qml
src/qml/RelationCombobox.qml
src/qml/editorwidgets/CheckBox.qml
src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/EditorWidgetBase.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/Range.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/TextEdit.qml
src/qml/editorwidgets/UuidGenerator.qml
src/qml/editorwidgets/ValueMap.qml
src/qml/qml.qrc

Because it's about time. Implements enhancement request #1661.
I took the time to rename the very confusing valueChanged( value, isnull ) editor widget signal to _changeValue( value, isnull )_.  IMHO, this is much better as a/ nobody can then confuse this with an onValueChanged signal emitted when the value property (which we pass around quite a lot) change, and also avoids duplicating an valueChanged signal in the attribute form item itself.

Support UUID generator editor widget

---

src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/ExternalResource.qml

So even if the user have set `'DCIM\\IMG_' + $id + '.jpg'`, we store it correctly.

Force using posix paths

---

src/core/featuremodel.cpp
src/core/layerobserver.cpp
src/core/multifeaturelistmodelbase.cpp
src/core/utils/layerutils.cpp
src/core/utils/layerutils.h

Allows deleting more than 1 level of children in relations. 
Currently it will delete the child features in L2, but leave the features in L3. With this PR it will cascade delete all the related features using the native QGIS cascading delete feature.
```
L1|    a
R1|   /  \
L2|  b   c
R2| / \
L3| d e 
```

Cascading delete related features

---

src/core/qfieldcloudprojectsmodel.cpp
src/qml/QFieldCloudExportLayersFeedback.qml
src/qml/qgismobileapp.qml

@suricactus , @lindacamathias , this PR fixes an issue raised in the chat room a while back, whereas the green attachment upload label would appear and stick forever.

Fix green attachment upload message never going away, fix count

---

src/qml/editorwidgets/CheckBox.qml
src/qml/editorwidgets/Range.qml

Two fixes:
- Never rely on empty label strings for the checkbox widget (fixes #2062)
- Fix QML errors with the range editor widget

Fixes for checkbox and range editor widgets

---

src/qml/LayerTreeItemProperties.qml
src/qml/PageHeader.qml
src/qml/PositioningSettings.qml
src/qml/Tracking.qml

First,a before vs. PR screenshot:
The big enhancement here is that all of the tracking settings will be remembered across sessions. This should really help out users out there who might grow tired of re-entering the same values again and again.
While visiting this part of QField, I've taken the opportunity to revamp the UI a bit so it feels more integrated into the rest of the app. Improvements there include:
- the settings is now parented to a scrollable area so people can reach settings that are outside of the current view (it'd happen if you open the tracking popup while your phone is in landscape mode for e.g.)
- the slightly confusing reliance on the page header's :heavy_check_mark: accept button has been replaced with the use of a full-width button with text,which will do a better …

Remember tracking settings values, revamp UI

---

src/core/featurelistmodel.cpp
src/core/featurelistmodel.h
src/qml/RelationCombobox.qml
src/qml/editorwidgets/RelationReference.qml

This PR adds a brand new autocomplete as you type mode to the relation combobox, used with the value relation editor widget when the user has the widget's [x] use completer settings turned on.
When switched on, the editor widget allows users to type in characters in an edit field, with instant matching against display name values:
https://user-images.githubusercontent.com/1728657/129692609-db73c810-2a3c-4d3b-8f81-c0cf8cb32d84.mp4
When the user hits enter (or 'done' on virtual keyboard), the currently displayed auto-completed value will be selected as attribute value. 
Similarly, if a user moves away from the edit field, the attribute value will be automatically set to the auto-completed value. If the entered characters don't match, the widget will revert to the last valid value.
The …

Add a complete-as-you-type mode to the relation combobox

---

src/core/tracker.cpp
src/core/tracker.h
src/core/trackingmodel.cpp

This PR modifies the tracker code to allow sub-meter (and sub-second) time and distance constraints :tada: 
@bladnor , good feedback.

Allow sub-second, sub-meter tracking constraints

---

src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/ValueMap.qml

This PR fixes this kind of UI glitch:
_Note the badly located value applied (click to toggle) label for the fk attribute_

Fix issues with editor widgets' height

---

src/core/attributeformmodel.cpp
src/core/attributeformmodelbase.cpp
src/core/submodel.cpp
src/qml/editorwidgets/TextEdit.qml

Update: happy to report the root cause of submodel falling into an out of sync situation has been identified and fixing. This means no costly model reset needed to fix feature form tab visibility :tada: 
---
OK, this is a pretty crucial fix, and one that was pretty hard to dissect. 
@3nids identified a serious issue whereas feature form tabs would get out of sync when tabs had expression-based visibility. It was difficult to diagnose what's wrong here but it boils down to the FeatureForm.qml's SubModel (line 226-230) getting out of sync when the parent Repeater item has filter changes in its model. 
The solution fixes this serious issue. However, the model reset signal has one downside: it forces all feature form tabs to re-build, which means that for e.g. value relation and relation …

Fix group visibility change leading to out of sync feature form tabs

---

src/qml/qgismobileapp.qml

@lp-dj , this should fix digitizing of child feature geometries in QField using the stylus. Thanks for the reporting.

Fix broken child feature digitizing with stylus (fixes #2079)

---

src/core/featurelistextentcontroller.cpp

This PR safeguards from attempting to auto zoom into a non-feature scenario which results in accessing a null pointer.
@lp-dj , this PR fixes #2050 . Whenever you can, please test APKs and confirm the crash is gone on your device.

Fix crash when auto-zoom on feature settings is on and focus is taken away from an open feature form

---

src/core/identifytool.cpp

This PR fixes a serious data corruption when multi editing features. The problem was that identifying additional features in the canvas while in multi editing mode would identify features from _all_ layers, and silently check/select them as part of the group of features being edited. It slipped through our (well, my :wink:) watchful eyes as the initial implementation did not auto select identified features.
The solution is to refine the identification of features to _only append features from the layer within which features are selected_. 
@lp-dj , this fixes #2082 . Feel free to test and confirm things are working as expected for you with these APKs.

Fix data corruption when multi editing

---

src/core/featurelistmodel.cpp

This PR avoids needless (and possibly quite costly) feature fetching for value relation edit widgets by restricting the feature fetch triggering upon updating the current form feature _only_ when it actually matters (that is to say, only when a filter expression is used that relies on the feature form).
I've also slightly increased the reload timer to 200ms to decrease chance of double fetching whenever multiple properties are set at the same time.
Hoping this will help #2057.

Reduce feature list model stress by increasing timer and avoiding needless gathers

---

src/qml/FeatureListForm.qml

1) select a single feature
2) open the feature form
3) attempt to delete
```
Could not convert argument 1 at onDeleteClicked@qrc:/qml…/FeatureListForm.qml:424
```

Fix warning when attempting to delete a feature

---

src/qml/RelationCombobox.qml

This fixes one of the increasingly small number of visual inconsistencies with the feature form. We're getting there.

Fix relation combobox's bad black text color for null values in read mode

---

src/core/attributeformmodelbase.cpp
src/qml/RelationCombobox.qml
src/qml/editorwidgets/RelationReference.qml

I *finally* found the scenario under which a relation reference edit widget breaks down and shows a red "invalid relation" label.
Long story short, we were failing to properly setup config-less fields linked to a child relation pair.
@lindacamathias , the test project you shared with me had a couple of these broken relations.

Fix broken config-less field relation reference edit widget

---

src/qml/FeatureForm.qml

Another feature form papercut: when the feature form is in edit mode but a field is read-only, keep the field label grayed out. It improves UX _a lot_, you don't need to wonder whether your field is broken vs. read-only :)
Looks:
Without graying out the field label, read-only fields such as _Karbonatgrenze_ have a misleading looks, leaving user unsure whether it's a text field that's somewhat broken.

Always keep field label color to gray when not editable

---

CMakeLists.txt

we only need the qml module
@hieu-van this is a partial revert, this is actually an overkill as it installs the complete QtCharts module (and not just the qml part)

QtCharts is not a build dep

---

src/core/qgismobileapp.cpp
src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/qml/geometry_editors/FillRingToolBar.qml
src/qml/geometry_editors/ReshapeToolBar.qml
src/qml/geometry_editors/SplitFeatureToolbar.qml
test/test_geometryutils.cpp

This fixes #2131 -- a while back, I added a GeometryOperationResult enum compatibility workaround to support QField compilation against QGIS 3.22 and pre 3.22. That enum used to live in QgsGeometry pre 3.22, and is now in Qgis. My compatibility workaround was :hankey: , this fixes things.

Fix geometry operation result enum compatibility workaround

---

src/core/utils/fileutils.cpp
src/core/utils/fileutils.h

@m-kuhn , this is needed for people who would update from QField 1.9 to QField 2.0. Since QGIS 3.22 renamed its provider plugins, not wiping the share folder means we'd end up with users having a share/plugins directory containing provider plugins from both QGIS 3.20 and 3.22. I assume this can lead to crashes.

When copying share assets on update, wipe pre-existing share folder

---

src/app/main.cpp

so the `qgis_platform` variable is defined and can be used to distinguish qgis vs qfield

define application name to "mobile"

---

src/core/utils/qfieldcloudutils.cpp

on iOS the settings dir is not writable, use QStandardPaths::writableLocation( QStandardPaths::AppDataLocation ) instead

fix cloud projects location

---

src/qml/QFieldCloudPopup.qml
src/qml/qgismobileapp.qml

Ouch, we were duplicating toast messages by having us react to a signal for every instance of QFieldCloudLogin object (not part of the fix in the title, just glad I caught that).
Also fixed an issue where narrow strings displayed in the toast message overlay would overflow to two lines instead of one (eg 'Logged out' would be 'Logged\nout').

Fix 'logged out' showing when failing to log in

---

src/qml/QFieldCloudLogin.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml

Doing a couple of things here: a/ trying to increase vertical height to allow scrolling the panel when the virtual keyboard is open, and b/ moving the about label to sit _below_ the user/password/log in button widgets.

Improve login screen on small vertical screen space

---

src/core/qfieldcloudconnection.cpp
src/qml/QFieldCloudPopup.qml
src/qml/imports/Theme/QfCollapsibleMessage.qml
src/qml/imports/Theme/qmldir
src/qml/qml.qrc

In action:
https://user-images.githubusercontent.com/1728657/135615807-726492d9-09d4-4d75-81af-3ee2967d2d49.mp4
This PR hides the advanced error strings behind a click on the error label. By default, a friendlier, more generic error is shown. Advanced errors are a/ scary, b/ not helpful for the avg. user, and c/ mostly there for debugging. By hiding those behind a click, we're still able to do remote debugging / help, while looking friendlier by default.

 Friendlier cloud project synchronization error

---

src/qml/FeatureListForm.qml

This fixes the bang! reported by @suricactus in #2178. Good catch.

Fix crash when activating multiselect with a focused item leading to mixed layer scenario

---

src/qml/EmbeddedFeatureForm.qml
src/qml/FeatureListForm.qml

This PR fixes #2106 by ensuring that escape and back button events are passed on to visible application overlay widgets when their presence are detected.

Make the feature list form be a good citizen by not always taking over escapes and back button events

---

src/qml/QFieldSettings.qml

A couple of follow up tweaks to the custom language feature.
@suricactus , I've tweaked things so we are adding a translatable system language item to the list of supported languages vs. embedding it in, it'll make it easier to switch to a dynamically generated list of supported languages down the road.

Make 'System language' translatable, add bottom margins to settings scroll views

---

.github/workflows/vcpkg.yml
scripts/ci/pull_translations.sh

I switched to xargs to actually get an error if lrelease or the command fails.
If lrelease is not available on vcpkg CI for now, let's just not pull the translations instead of silently failing.

revert to xargs to avoid failing without error

---

src/core/appinterface.cpp
src/core/appinterface.h
src/qml/qgismobileapp.qml

Because it's 2021 and QField handles non-project files the days. Super handy on Windows and linux platforms.

Allow drag and dropping of supported vector and raster datasets

---

resources/demo_projects/advanced_bee_farming.qgs
resources/demo_projects/simple_bee_farming.qgs

People often use these demo projects as _starting point_ to do experiments, and having a bunch of layers with offline editing custom properties (from source/remote sources that aren't available) creates a bunch of conflicts and leads to worlds colliding.
This PR deletes those custom properties.
@lucienicolier , as discussed a while back when we were preparing for the FOSS4G.

Remove offline editing custom properties from demo projects

---

src/qml/editorwidgets/ExternalResource.qml

Simplifying the conditions here to something more readable and less prone to failure. 
(Note: that probably warrant a 1.10.1 alone, but I'd like to see if we can dissect why people upgrading end up with 3.18 and 3.22 provider libraries)

Fix non-native camera button MIA in 1.10 (fixes #2262)

---

sdk.conf

This PR takes on an updated SDK that downgrades sqlite to 3.35.5 to provide time for GIS users out there to a/ be aware of a change in sqlite 3.36.0 that can lead to broken views (eg https://github.com/opengisch/QField/issues/2260), b/ adapt their syntax.
That's likely the right thing to do for QField 1
10.

Update OSGeo4A to fix a spatialite views regression

---

src/core/layertreemapcanvasbridge.cpp
src/core/projectinfo.cpp
src/qml/DashBoard.qml
src/qml/LayerTreeItemProperties.qml

This (mostly) fixes https://github.com/opengisch/QField/issues/2277 by setting the map theme to none when manually toggling individual layer visibility. When I say _mostly_, I'm referring to the absence of auto map theme matching when users would toggle individual layer visibility to match a given map theme setting. No plan to implement that behavior, I think we can save the CPU cycles on QField and avoid this.
Doing so allows for users to quickly reset the map theme via combobox.
There's also a small fix to avoid remembering an empty map theme string across project load sessions.

When manually hiding/showing layers, set map theme to none

---

platform/android/AndroidManifest.xml.in
platform/android/res/values/strings.xml
platform/android/src/ch/opengis/qfield/QFieldActivity.java
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
platform/android/src/ch/opengis/qfield/QFieldProjectListItem.java

This PR further adjusts permission handling based on recent work we've done.
In addition, it slightly reworks the file picker activity to behave better and be more informative to users in environments where permissions are not fully granted.
The long story short is that we present the app's external files directory as a location than can be used to drop content via USB cable while still warning of data loss if the app is uninstalled. Wordings have been adjusted all around. The ~~warning~~ information note looks like this:
As a nice little extra, this fixes the addition of the demo projects folder in the favorites when first launching QField (broken since forever ago).

Adjust file picker behavior based on permissions

---

src/app/CMakeLists.txt

Before vs. PR:
@m-kuhn , this fixes a regression introduced by the new packaging platform.

Fix missing welcome screen / about logo on non-Android platforms

---

platform/android/src/ch/opengis/qfield/QFieldOpenExternallyActivity.java
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/android/androidviewstatus.cpp
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/viewstatus.h
src/qml/editorwidgets/ExternalResource.qml

This PR implements an editing mode to images (and other resources) through the external resource editor widget.
The implementation basically takes on what @m-kuhn did in 2020, but instead of hard-coding ACTION_EDIT, I've made it so we use ACTION_VIEW when the feature form isn't in edit mode. I think it makes a lot of sense, allows users to set a default app for viewing vs default app for editing. That takes care of Samsung Gallery gone missing when we only use ACTION_EDIT.
Edit: the PR now also handles scenarios where the app returns a file that's not the one we attached to the intent, which unlocks a bunch of apps that don't overwrite file (success not guaranteed if saved image is in a location within which permission isn't granted).
Video of editing in action: …

Implement an image/resource editing mode to the image/external resource widget

---

src/qml/DashBoard.qml
src/qml/Legend.qml

This PR fixes https://github.com/opengisch/QField/issues/2286 by deferring the rendering of legend icons only when a user has opened the dashboard. It's essentially a bit of a work around QGIS layer tree model which doesn't emit a signal when changing legend node icon sizes (which happens after project load when getting the overall project context et al).
By waiting until the user expands the dashboard, we insure that the icon size when legend icons are drawn have the proper context.
It's also a nice micro optimization.

Only display legend icons when the drawer is expended as a workaround catching the right icon size

---

src/qml/qgismobileapp.qml

This PR fixes a big accidental data loss risk by disabling map canvas feature identification when a feature form is being edited. Without the fix, any accidental tap on the map canvas forces the feature form to shut down and any modification gets lost.
Fixes https://github.com/opengisch/QField/issues/2267.

Prevent accidental data loss when editing a feature form

---

platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
scripts/ci/pull_translations.sh
src/core/qgismobileapp.h

Formats are: GML, MapInfo MIF, FlatGeobuf (fixes #2341), spatialite [.db, .sqlite], and virtual vector/raster files (.vrt).

Add a couple more gdal-supported vector/raster formats

---

.clang-format
src/core/attributeformmodelbase.cpp
src/core/deltafilewrapper.cpp
src/core/featurelistmodel.cpp
src/core/locator/featureslocatorfilter.cpp
src/core/locator/locatormodelsuperbridge.cpp
src/core/orderedrelationmodel.cpp
src/core/platforms/android/androidplatformutilities.cpp
src/core/qfieldappauthrequesthandler.cpp
src/core/qfieldcloudconnection.cpp
src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/core/recentprojectlistmodel.cpp
src/core/scalebarmeasurement.cpp
src/core/utils/qfieldcloudutils.cpp
src/core/utils/stringutils.cpp
test/test_deltafilewrapper.cpp

Fixes weird situations like:
before:
```
NetworkReply *deltasCloudReply = mCloudConnection->post(
QStringLiteral( "/api/v1/deltas/%1/" ).arg( projectId ),
QVariantMap(),
QStringList() );
```
after
```
NetworkReply *deltasCloudReply = mCloudConnection->post(
QStringLiteral( "/api/v1/deltas/%1/" ).arg( projectId ),
QVariantMap(),
QStringList() );
```
==================
before
```
QJsonObject delta(
{
{ "localPk", oldFeature.attribute( localPkAttrName ).toString() },
} );
```
after
```
QJsonObject delta(
{
{ "localPk", oldFeature.attribute( localPkAttrName ).toString() },
} );
```

Improve formatted code readability for multiline objects/function calls

---

src/qml/FeatureForm.qml

The final bit after https://github.com/opengisch/QField/pull/2033 .
Also, the 1px on the top was driving me crazy.
before/after

Remove last leftovers from the black buttons in the header bar in QField forms

---

images/images.qrc
images/themes/qfield/nodpi/ic_place_white_24dp.svg
src/core/CMakeLists.txt
src/core/bookmarkmodel.cpp
src/core/bookmarkmodel.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/qml/BookmarkHighlight.qml
src/qml/BookmarkRenderer.qml
src/qml/GeometryRenderer.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

This PR implements basic bookmarks display framework for QField. In action:
https://user-images.githubusercontent.com/1728657/145700930-9ae95f3b-0409-4b51-a1c6-eaf044a69331.mp4
The framework displays both project bookmarks (see in the screencast) as well as app-wide bookmarks (UI to be implemented in a different PR).
This is cool for a couple of reasons:
a/ the bookmarks are rendered as QML items, so it is always shown and not bound to canvas rendering
b/ the app-wide bookmarks will be saved across projects
A single click/tap on the bookmark throws a toaster message with the bookmark name. A double click/tap sets the map canvas extent to the bookmark extent:
https://user-images.githubusercontent.com/1728657/145706411-f90aa4da-0bd9-4114-a1af-abc1d664eeea.mp4

Bookmark basics

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h

It's easier to handle and check if the project has been found. Also might fix vckpg problems as observed on #2303 .

Store cloud projects as struct pointers

---

platform/android/AndroidManifest.xml.in
platform/android/src/ch/opengis/qfield/QFieldActivity.java
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/qgismobileapp.cpp
src/qml/About.qml
src/qml/imports/Theme/Theme.qml

Winter might be coming... 
Edit: I've added an helper label in QField's about panel to provider users with strings of QField storage-wide and app directories:
If storage-wide and app are the same, the latter is skipped (i.e. windows, linux)

Implement the QField _app_ directory concept (vs. storage-wide QField directory)

---

src/qml/FeatureListForm.qml
src/qml/qgismobileapp.qml

Fix https://github.com/opengisch/QField/issues/2386
The feature is centered if:
1) you move feature from the feature form
2) there is only one feature selected in the multiselect
The features are not selected if there are more than one selected feature.

When moving a single feature, first center the map to that feature

---

src/core/multifeaturelistmodelbase.cpp

Quite annoying problem mentioned by @ipickedausername in https://github.com/opengisch/QField/issues/2387#issuecomment-1008302114 and also confirmed by me.
Here is what was fixed:

Fix feature selection after it was duplicated from the attribute form

---

platform/android/AndroidManifest.xml.in
platform/android/build.gradle
platform/android/res/values/strings.xml
platform/android/src/ch/opengis/qfield/QFieldActivity.java
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
platform/android/src/ch/opengis/qfield/QFieldUtils.java

This PR introduces a mechanism to import datasets into QField when opening of associated file datasets (via the "Open with QField" action in other apps) that are either a/ not a file path based content, or b/ not in a permission state that allows us to do in-place editing.
This is pretty cool as it allows us to _directly open in QField_ Gmail email attachments, Google Drive files, {WhatsApp, Telegram, Signal, etc} documents, and more.
The imported datasets are stored in the QField app's external files storage location, under a new "Imported datasets" directory. The directory is created and managed by QField, and is added by default in the favorites for easy access.
The PR also cleans up and improves pre-existing file association related functionalities.
_Note: the imported projects isn't …

Introduce mechanism to import associated files/datasets into QField

---

src/qml/editorwidgets/Range.qml

Two changes:
- Use the proper way to check for Infinity in JS, since it checks for a few other edge cases - `Number.isFinite()` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite).
- Since `textField.text` should return string, it is safer to check if the property is truthy. This will also catch `null` and `undefined` values. `"0"` is truthy in JS.
Problem:

Avoid infinity values in the numeric widget if there is no default value

---

src/core/attributeformmodel.cpp
src/core/attributeformmodel.h
src/core/attributeformmodelbase.h
src/qml/FeatureListForm.qml

Fixes #2406 
1) create a feature with dependent fields. Make sure the newly created feature hides some of the fields.
2) open the newly created feature feature form.
3) the hidden fields are visible.
The problem was that `AttributeFormModelBase::applyFeatureModel` was not called once the form is opened.
Probably "the best solution" would be to use the `FeatureListModelSelection::focusedItemChanged()` event to call `AttributeFormModelBase::applyFeatureModel`. However, this would make more spaghetti, than explicitly calling the method.

Make sure the field visibility is enforced when opening the form of the feature created just before

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java
platform/android/src/ch/opengis/qfield/QFieldUtils.java
src/qml/qgismobileapp.qml

This builds on top of #2397 . It adds a mechanism to treat a .zip file as an archived project when the presence of a QGIS project file is detected. When that's the case, QField will decompress the project into the Imported protects directory.

Handle importing of zipped projects

---

src/core/scalebarmeasurement.cpp
src/qml/FeatureListForm.qml

- if the scaledDistance.value is nan, better show "Unknown" than "nan km"
- if the scaledDistance.value is 0 (submeter values), better show all the decimals
- fix a warning on startup
Fix #2408 #1046

Use QGIS native pretty scale calculation for projected CRS

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java

Guard QField from crashing when handling an intent with missing mime type

---

src/qml/QFieldCloudPopup.qml

ATM, if a user is going into the cloud log in panel through the cloud project panel after hitting a network error, he/she/they will see this:
Not a great look, leads to confusion as to whether there's an error even though the person successfully logged in.
This PR fixes that by hiding the project sync/push error widget when the log in panel is open.

Fix confusing error widget when going into cloud log in panel

---

platform/android/res/menu/project_item_menu.xml
platform/android/res/values/strings.xml
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java

Title says it all; when users navigate to the import datasets folder, a new "remove dataset" action is added in the item popup menu.

Remove QField imported datasets feature

---

platform/android/res/menu/project_folder_menu.xml
platform/android/res/values/strings.xml
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
platform/android/src/ch/opengis/qfield/QFieldUtils.java

Alright, this is truly the last piece of the restricted storage implementation puzzle. 
When in the root directory of imported projects, a new menu item appears to allow for users to remove imported project folders.

Remove project folder within QField imported projects feature

---

platform/android/res/xml/file_paths.xml

Fixes an IllegalArgumentException failure, spotted on sentry.

Fix project activity crash when trying to use the 'send to' action with sample projects' datasets

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
platform/android/src/ch/opengis/qfield/QFieldUtils.java

PR fixes a crash when opening datasets and archived project from a signal messenger conversation.

Tweak inputStreamToFile implementation to guard from signal messenger crasher

---

platform/android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
platform/android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java

Guard from crashing when extras are missing from the {camera,gallery} activity

---

src/core/recentprojectlistmodel.cpp

For people upgrading QField from a pre-November 2021 Google-imposed reduced storage access, users could see recent projects from storage locations that they do not have access to anymore. This PR hides those projects / datasets from the recent projects model to avoid people staring at a blank canvas.
@m-kuhn , as discussed.

Only add recent projects that are readable to the model

---

platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java

I'm not able to replicate the crash itself but sentry's stacktrace is useful enough to know we benefit from adding this safeguard.

Fix project activity crash seen on sentry

---

.github/workflows/android.yml
.github/workflows/desktop.yml
.github/workflows/ios.yml
.github/workflows/sync-translations.yml
.github/workflows/translations.yml

This is a proposal PR
This aims to synchronize the complete translations into our sources.
It does synchronization once a day.
Advantages:
- Translated builds without transifex tokens (locals, other ci)
- Seeing translations as part of the code
- Reduced build time
- Reduced build failure risk triggered by unavailable external services
- Safety copy and historization of translations
Disadvantages:
- Duplicated information
- Release branches do not get translation updates
- Latest translation might be a couple of hours old at build time

Auto sync translations

---

platform/android/res/xml/file_paths.xml

Fixes a crash seen on sentry when someone tries to use the "send to..." action in the project/dataset picker activity on external storage direct access (i.e. android < 11)

Fix the 'send to...' action in the project activity for non-app locations

---

vcpkg/overlay/qgis/auxiliary.patch
vcpkg/overlay/qgis/portfile.cmake

This is an attempt to prevent the following crasher seen on sentry:
The crash is most likely linked to this issue (https://github.com/opengisch/QField/issues/2483).
It's not addressing the spatialite/proj issue this stacktrace hints at, but at least it delays such a crash until someone tries to open an actual spatialite connection. 
(This is a temporary patch of https://github.com/qgis/QGIS/pull/47431)

Patch QgsAuxiliaryStorage to avoid needless spatialite connection

---

images/images.qrc
images/themes/qfield/nodpi/ic_compass_direction.svg
images/themes/qfield/nodpi/ic_gps_direction.svg
images/themes/qfield/nodpi/ic_movement_direction.svg
src/qml/LocationMarker.qml
src/qml/qgismobileapp.qml

This PR implements a proper magnetometer-based on-canvas compass in QField. The feature requires devices to have a magnetometer sensor hardware (PSA: when you buy a mobile device, make sure you check if that hardware is present or not, many entry level devices leave that piece of hardware out to lower production cost).
The sensor is only turned on whenever the positioning is active to insure we're not draining battery needlessly.
The visual compass looks like this:
(Temporarily include #2539 until that is merged)

Implement magnetometer-based on-canvas compass

---

src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/qml/qgismobileapp.qml

Two actions were added to the map canvas menu and location menu:
- copy [pressed map canvas] coordinates to clipboard
- copy current location to clipboard
Obligatory screenshots:
@suricactus , that one's for you :wink: good idea.

Add useful copy {coordinates,current location} to clipboard menu actions

---

src/core/screendimmer.cpp

Tested QField using bluetooth mouse and keyboard revealed this shortcoming.

Avoid dimming when moving mouse / pen around the screen

---

src/core/qfieldcloudconnection.cpp
src/core/qfieldcloudconnection.h
src/core/qfieldcloudprojectsmodel.h

Initially developed for particular use, but I found it would be much easier and nicer to solve the issue on the cloud. However, this code can help in the future to improve error handling on QField side, so I am commiting it anyway.

Add cloud error class that wraps the error response within an object

---

src/core/platforms/platformutilities.cpp

Fix missing vertical grids when located in the QField app data directory

---

src/core/platforms/platformutilities.cpp

[Backport release-2_0] Fix missing vertical grids when located in the QField app data directory

---

images/images.qrc
images/themes/qfield/nodpi/ic_place_white_24dp.svg
src/qml/BookmarkRenderer.qml

Beyond looking better (i.e. a white dot instead of a hole on the top part of the marker), a bunch of advantages here:
- we can perfectly match looks of border width with other marker overlays (all using QML items)
- far less complex code (the color overlay filter is gone in favor of good old color fill property)
Here's how it looks standing next to other overlay markers:
In 2.1, I'm planning to add a "add bookmark" feature, where users can specify the bookmark marker color among other things.

Improve bookmark marker by using a Shape item instead of an SVG

---

src/qml/CalendarPanel.qml
src/qml/editorwidgets/DateTime.qml
src/qml/imports/Theme/QfToolButton.qml

As mentioned during the implementation of temporal support for QField, this follow up PR deduplicates code by having the datetime editor widget rely on the calendar panel item.
In addition, I've implemented a press and hold behavior for the increase/decrease year/month buttons in the calendar panel so values continuously increase/decrease while holding those:
https://user-images.githubusercontent.com/1728657/158005686-cfb74135-3eb1-4b5f-ba53-dfb619ef8bf3.mp4

Calendar panel follow ups

---

src/core/bookmarkmodel.cpp
src/core/bookmarkmodel.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/qml/BookmarkHighlight.qml
src/qml/BookmarkProperties.qml
src/qml/BookmarkRenderer.qml
src/qml/imports/Theme/Theme.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

This PR completes the implementation of bookmarks support in QField by allowing users to add and edit bookmarks.
Adding bookmarks can be in two different ways:
1/ long pressing on the map canvas to add a bookmark at the pressed location
2/ long pressing on the location/GPS button (bottom right of the screen) to add a bookmark from the current location
In addition, bookmark details can be edited by long pressing on a bookmark marker. Currently users can edit the bookmark name or remove the bookmark.
Screencast of bookmark addition / editing:
https://user-images.githubusercontent.com/1728657/158046114-2e8d5a66-6cb3-4c97-afdc-0a4b6cbf822d.mp4
Edit: one important fix in there is the de-duplication of the system bookmark manager. Somehow I had missed the one attached to QgsApplication until …

Allow users to add and edit bookmarks

---

src/qml/editorwidgets/relationeditors/relation_editor.qml

Fix #2343 
@jpdupuy here is an example of the two relation editors in the advanced editor widget, one with and one without the configuration set.

Support "show delete child button" configuration for relations

---

src/core/qgismobileapp.cpp

Since we cannot connect the Androids "Documents" path anymore, I think a good way to go is to write directly into the project's folder. This is the proposed folder in QGIS as well and I think it's clear for the user to find it again. Since it's opening right after writing, the user is free to put it somewhere else.
@nirvn Can you please check if it is really that simple as I thought :-)

Print pdfs to the project folder

---

src/qml/qgismobileapp.qml

Title says it all. Regression occurred way back in 1.6, in this commit (https://github.com/opengisch/QField/commit/ee78e9b780f3740ffad6908cd68f39e9158bd7a9).
@signedav , I assume that line change back then was accidental?

Fix longstanding regression whereas length/area information is missing when digitizing features

---

src/qml/CalendarPanel.qml

The two improvements included here:
- the "hit" area for selecting the date has grown as it was rather small (more specifically, not tall enough), making it hard to use with fingers.
- the calendar now highlights "today" by underlining the day number that matches the current date.
- double clicking on a day will select the date.
This improves the attribute form, as well as temporal filter since all is shared now :partying_face:

Calendar panel usuability improvements

---

src/qml/qgismobileapp.qml

PR fixes this navigation button issue:

Fix navigation button not snapping to the right edge of the screen

---

.docker/android_dev/Dockerfile
.github/workflows/android.yml
cmake/Platform.cmake
platform/android/CPackAndroidDeployQt.cmake.in
scripts/build-vcpkg.sh

This PR fixes self-built vcpkg-based APKs using the android_dev docker's ./scripts/build.sh method.

Fix/unlock self-built APKs using android_dev docker

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java
platform/android/src/ch/opengis/qfield/QFieldUtils.java

Fixes this sentry item:
```
[RuntimeException android.app.ActivityThread in performLaunchActivity](https://sentry.io/organizations/opengisch/issues/3117434221/?project=6119013&query=is%3Aunresolved&sort=freq&statsPeriod=14d)
Unable to start activity ComponentInfo{ch.opengis.qfield_dev/ch.opengis.qfield_dev.QFieldActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(java.lang.String)' on a null object reference
```

Fix java crasher seen on sentry

---

src/core/qgismobileapp.cpp
src/core/qgssggeometry.cpp
src/core/qgssggeometry.h
src/qml/FeatureListSelectionHighlight.qml
src/qml/GeometryRenderer.qml
src/qml/NavigationHighlight.qml

This makes our QSGeometry-based items look _a lot_ smoother. 
Before:
PR:
Take a close look at the edges of long segments, gone are non antialiased lines.

Enable antialiasing by default on QML scenes

---

src/qml/editorwidgets/Range.qml

This PR aims at improving (and possibly fixing) #2584.
Long story short is that if a user clicks at the very edge of the +/- button in the feature form's number edit widget, the release/canceled signal gets lost when the feature form moves to a different tab.
I have fixed this so that the increase/decrease value timer only starts on a pressandhold signal, which should reduce accidental loss of control.

Make number edit widget's spin buttons less prone to go wild

---

src/qml/editorwidgets/Range.qml

[Backport release-2_0] Make number edit widget's spin buttons less prone to go wild

---

src/qml/RelationCombobox.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/ValueRelation.qml

Our value relation editor widget had *two* feature list model running for each attribute (one for single-selection and one for multi-selection), ouch! This meant that for every editor refresh (say due to filter, current form feature change, etc.), we we triggering the dataset/provider twice.
Among other things, it lead to this obscure bug (https://github.com/opengisch/QField/issues/2594) which this PR fixes.
Safer QField, less CPU, less bandwidth.
I've also taken the time to dissect a infinite value loop detected by QML, that's never good.

Do not double-compile value relation feature lists

---

src/qml/LocationMarker.qml
src/qml/qgismobileapp.qml

The documentation is really unclear here, but as far as my understanding goes as of March 23, 2022, the NMEA direction data we get from an external GNSS device is a compass value. 
This PR insures that we treat the value as such.

When connected to an external GNSS device, disable compass for now

---

src/qml/LocatorItem.qml
src/qml/LocatorSettings.qml
src/qml/qgismobileapp.qml

If people want to quickly access the main menu, they don't need to go through opening the dashboard and clicking on the gear icon, they can now hold press the top-left dashboard button:
The idea behind this (beyond a speedy shortcut) is that the more long press actions we have, the higher the chance people try and discover those across the app (e.g. location button, navigation button, etc.)

Add a couple of long press action for map buttons (main and search)

---

src/qml/QFieldCloudLogin.qml
src/qml/imports/Theme/QfTextField.qml

What this PR is trying to fix is a bug in Qt/QML that ends up with users unable to trigger the opening of their virtual keyboard on Android when focusing on a text input.
One reliable way to reproduce the issue: remove QField from your android device, re-install it, click on open QFieldCloud project, see how when you click on the user or password text input, the keyboard never shows up.
Bonus because we use QfEditInput, we get _for free_ a show password in the QFieldCloud login panel:
@suricactus , that should make you happy ;)

Try to fix virtual keyboard sometimes not popping up when focusing on text input

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/core/qgsquick/qgsquickmapcanvasmap.h

Without this, layers that signals repaint requests a lot (e.g., animation markers in upcoming 3.26 but _also_ layers set to auto refresh every X secs) would freeze map canvas.

[qgsquick] Properly handle deferred layer repaint requests

---

src/qml/editorwidgets/Range.qml

Avoid throwing harmless but disturbing warning messages when typing into range editor widget

---

src/qml/About.qml
src/qml/WelcomeScreen.qml
src/qml/imports/Theme/QfButton.qml
src/qml/qgismobileapp.qml

@m-kuhn , here's how it looks now:
I've taken the liberty to change the "we've asked already" settings key so users are re-asked with this much clearer UI.

Further improve the metrics popup, re-asks to get a clear(er) answer

---

src/core/platforms/android/androidplatformutilities.cpp
src/qml/SystemLoader.qml

By current stats, the 6th most reported crash on sentry has to do with the feedback context passed onto the system loader scene. I vote to remove that crash prone code in favor of an indefinite loader bar instead.
The crash isn't that bad since just re-launching QField works, but it does happen immediately after installing QField, which isn't a great look.

Remove crash prone feedback connection in the system loader scene

---

src/qml/editorwidgets/Range.qml

[Backport release-2_0] Avoid throwing harmless but disturbing warning messages when typing into range editor widget

---

platform/android/src/ch/opengis/qfield/QFieldUtils.java

Fixes this sentry issue: https://sentry.io/organizations/opengisch/issues/3155005227/?project=6119013&query=is%3Aunresolved

Avoid crashing when parsing a DownloadsProvider URI with a non-numerical ID

---

platform/android/res/menu/project_folder_menu.xml
platform/android/res/menu/project_item_menu.xml
platform/android/res/values/strings.xml
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
platform/android/src/ch/opengis/qfield/QFieldProjectListAdapter.java
platform/android/src/ch/opengis/qfield/QFieldUtils.java

This PR implements two ways to export project folder content out of QField's app files directory:
**'Send Compressed Folder to...'**
When selected, QField compresses the content of the select folder (as well as its sub folders) into a ZIP archive, and then asks the user through which app on his/her device the compressed project folder should be send through. The implementation allows for sending a root project folder (in the QField's imported projects directory), as well as being able to send selective folders _within_ that root project folder. This means that for e.g., users could decide to compress and send only a /data sub-folder, or a /dcim sub folder.
**'Export to Folder...'**
When selected, QField will ask users to pick a folder (using the Android system's folder picker activity) …

Implement send compressed folder and export project folder [to folder] functionality

---

platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java

This PR adds a back button in the open local project/dataset activity's navigation bar:
That harmonizes this piece of Java UI with other QML counterparts.

Add a up/back button in the open local project/dataset activity navigation bar

---

src/core/appinterface.cpp
src/core/appinterface.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/qml/editorwidgets/ExternalResource.qml

This PR adds the necessary bits on the QField side of things to implement a maximum picture width/height restriction to images/photos from the camera (native or Qt) and gallery. 
Note to self/others: we should eventually add Q_INVOKABLE functions to the QgsProject class in QGIS to avoid the iface.readProject{Num,Double}Entry() bridges in here. But that's for the future.

Allow for pictures taken (through camera or gallery) to be restricted to a maximum width/height

---

src/core/rubberband.cpp
src/core/rubberband.h
src/core/sgrubberband.cpp
src/core/sgrubberband.h
src/qml/qgismobileapp.qml

Until now, we were not taking into account the device pixel ratio when rendering the rubber band's QSGGeometry. This meant that lines would look fine on some screens (i.e. a developer's desktop screen) but would look quite small on devices with high density screens.
A similar fix was applied to the line polygon geometry objects a short while back.
This fixes #2362.

Insure that our rubber bands take device pixel ratio into account to harmonize rendering on all screen densities

---

platform/android/AndroidManifest.xml.in
platform/android/build.gradle.in
platform/android/res/values/colors.xml
platform/android/res/values/strings.xml
platform/android/res/values/styles.xml
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java

This PR introduces a one-time pop up dialog when users first launch the project/dataset picker activity to provide them with a one-click access to storage handling documentation:
Hopefully this will help guide QField 1.x users migrating into the new Google-imposed storage paradigm. It also serves as a good intro to newcomers too.

Storage help

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/core/qgsquick/qgsquickmapcanvasmap.h

... leading to added feature going missing on canvas until the user pans/zooms around.
This only affects master.

[qgsquick] Fix map canvas regression with non-deferred layer repaint request

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java
platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
platform/android/src/ch/opengis/qfield/QFieldUtils.java

TIL: some ZIP programs don't include directory items, only the files (attached to which they prepend folder names to the file name string).
So for e.g., some ZIP programs do:
- my_dir/
- my_dir/my_file.txt
While other ZIP programs would only do:
- my_dir/my_file.txt
This PR insures QField behaves on both types.

Fix QField unable to import project from a number of ZIP files, rename functions

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java
src/core/platforms/android/androidplatformutilities.cpp
src/core/utils/fileutils.cpp
src/core/utils/fileutils.h

Big, bad bug ATM: when installing _or upgrading_ QField on Android, the subsequent first launch "breaks" the virtual keyboard. Simple steps to witness the issue:
- Uninstall QField
- Re-install QField
- Launch QField, click on the "QFieldCloud projects" button
- Tap on the username text field
- **Notice the virtual keyboard _fails to show up_ :fearful: **
- Go back to the welcome screen
- Click on the simple bees farming demo
- Click on the map search bar
- **Notice the virtual keyboard _fails to show up_ :fearful: **
It only happens once. And the only thing that happens once when installing or upgrading is the asset copying process, which creates a pair of QApplication + QQmlApplicationEngine to provide some feedback, then quit() the app, followed by the creation of another …

Fix virtual keyboard not opening when first launching QField on Android platform

---

src/qml/QFieldCloudPopup.qml

Improved text as suggested by @BoswachterMarc in #2469 .
|----------|--------|
|  ![image](https://user-images.githubusercontent.com/2820439/157409820-97f9999e-6dad-4b3f-9077-0d4e6e2de62c.png) | ![image](https://user-images.githubusercontent.com/2820439/157409657-560a941e-ac0c-4d9b-a1a4-a8aea7454aab.png) |

Improve help text by replacing "local cloud layers" with "local layers"

---

src/core/qgismobileapp.cpp
src/qml/About.qml
src/qml/QFieldCloudLogin.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldSettings.qml

Doing this allows us to skip CSS style declarations in a bunch of placement, but more importantly, it gets rid of the 1990s default blue hyperlink color for our changelogs panel. Long story short there is that QML Text formatted using MarkdownText hard-code style hyperlinks using the app's palette. 
My teeth won't grind every time I see an hyperlink in our release notes, woupidou.

Set a nice QField-green default app-wide hyperlink color

---

src/core/qgismobileapp.cpp

The previous code was bad in two ways:
1/ it'd set the PGSYSCONFDIR to <system root>/QField/ even if a .pg_service.conf was not present
2/ it prioritized the less secure <system root>/QField/ location
This change is required to help crafting a proper documentation on this feature. In the documentation, we should only refer to <system root>/Android/data/ch.opengis.qfield/files/QField as the proper/safer location to store the .pg_service.conf.
We still need to keep the old location as a mean to insure compatibility with preexisting users on Android <= 9.

Improve .pg_service.conf logic, prioritize the more secure location

---

src/qml/Changelog.qml

This fixes https://github.com/opengisch/QField/issues/2818 -- 
Long story short, we were waiting for a successful network fetching of the changelog to update the appVersion setting, which meant that if a device isn't meant to or is unable to connect to a network, the changelog overlay would pop up on every single launch.
I think we're better to play conservative here and only try to show the content once per app version update.

Always show the changelog once per version update

---

src/qml/qgismobileapp.qml

Because knowing which CRS the coordinates are in is crucial.
E.g., copying a map canvas point to clipboard now stores: `X 537944.86, Y 1368649.16 (EPSG:3148 Indian 1960 / UTM zone 48N)`.

Append CRS informatio when copying map canvas point/position  location to the clipboard

---

src/qml/QFieldSettings.qml
src/qml/RelationCombobox.qml
src/qml/Tracking.qml
src/qml/VariableEditor.qml
src/qml/editorwidgets/CheckBox.qml
src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/Range.qml
src/qml/editorwidgets/TextEdit.qml
src/qml/editorwidgets/UuidGenerator.qml
src/qml/editorwidgets/ValueMap.qml
src/qml/imports/Theme/QfTextField.qml
src/qml/imports/Theme/Theme.qml

This PR fixes the visual inconsistency spotted in this screenshot:
I took the opportunity to move those colors to our Theme object.

User proper accentLightColor for the image frame

---

src/core/locator/featureslocatorfilter.cpp
src/core/locator/featureslocatorfilter.h
src/qml/LocatorItem.qml

Because we don't need to confuse users with an irrelevant action, let's hide the set feature as destination action in the search bar's features locator:

The features locator should not show "set feature as navigation destinaiton" action for geometryless layers

---

src/core/locator/featureslocatorfilter.cpp
src/core/locator/featureslocatorfilter.h
src/qml/LocatorItem.qml

[Backport release-2_1] The features locator should not show "set feature as navigation destinaiton" action for geometryless layers

---

cmake/Package.cmake

Fix packaging error
```
Running CPACK. Please wait...
CMake Warning (dev) at C:/builddir/BundleConfig.cmake:25 (set):
Syntax error in cmake code at
C:/builddir/BundleConfig.cmake:25
when parsing string
usr\bin
Invalid escape sequence \b
```

Double escape backslash

---

platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java

Tiny tweaks/improvements:
- The 'additional files directory' now always sits below the main QField directory
- An SD card image is now used to better communicate with the users were the files reside
Screenshot:

Slightly improve handling of removal (sd card) storage in the project dataset picker

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/qgismobileapp.cpp
src/core/qgsquick/qgsquickcoordinatetransformer.cpp
src/qml/About.qml

This PR reworks the way we handle the QField data dir (within which users can set fonts, basemap/localized path datasets, etc.) so we take into account _all_ available external files directory to catch secondary /Android/data/ch.opengis.qfield/files living in external SD card.
See https://github.com/opengisch/QField/discussions/2878 for more background.
@Crapaud04 , please give these APKs a try.

Handle _all_ external dirs as potential QField data dirs

---

src/core/bookmarkmodel.cpp
src/core/bookmarkmodel.h
src/qml/BookmarkProperties.qml
src/qml/imports/Theme/Theme.qml

This PR applies a couple of tweaks to bookmarks handling to make them even more useful (based on field use):
- Get rid of the "update bookmark details" button in favor of saving as edits are done, much smoother experience
- Make the color buttons slightly bigger to increase tap area
- Use a red color for the remove bookmark icon
In addition, a "copy bookmark details" button has been added, which copies a string into the clipboard that looks like:
```
near pp, anomaly
X 490289.77, Y 1283316.02 (EPSG:3148 Indian 1960 / UTM zone 48N)
```
This insures that spatial details of bookmarks can be retrieved and shared more easily.

Allow copying bookmark details to clipboard, plus usuability improvements

---

src/app/main.cpp

This PR fixes a pretty serious issue on Android (and iOS):
- on Android, we were setting the QGIS user profile directory to match that of QGIS' data resources (i.e. what is supposed to be a read-only directory that provides templates). It did work in part because qgis.db was in that directory to begin with, _however_ it meant that at every QField update, we'd _overwrite_ the user qgis.db with the template one. Practically speaking, this meant that every time someone updates QField, he/she would lose _all saved bookmarks_ :fearful: 
- On iOS, we were setting the QGIS user profile to the same problematic location, on top of which it was a read-only directory, meaning bookmarks wouldn't even save across sessions.
This is one of these "how was it ever working to begin with" moments :wink:

Do *not* use qgis data directory as profile directory

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/qml/LayerTreeItemProperties.qml

Also add a little padding so the whole layer is visible. As requested in #2739 .
Also removed `LayerTreeItemProperties.isSpatialLayer` (qml) - it is better suited to be as Cpp model attribute
https://user-images.githubusercontent.com/2820439/168296652-52d182d6-5e6b-4159-bb8f-426101e15ced.mp4
A project based on advanced bee for testing:
[qf_2739_zoom_to_layer.zip](https://github.com/opengisch/QField/files/8688318/qf_2739_zoom_to_layer.zip)

Add zoom to group in the legend properties

---

src/qml/LocatorItem.qml

[Backport release-2_1] When triggering a search result action (i.e. right-end buttons), close the search result

---

src/core/CMakeLists.txt
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/android/androidprojectsource.cpp
src/core/platforms/android/androidprojectsource.h
src/core/platforms/ios/iosplatformutilities.h
src/core/platforms/ios/iosplatformutilities.mm
src/core/platforms/ios/iosprojectsource.h
src/core/platforms/ios/iosprojectsource.mm
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/projectsource.cpp
src/core/projectsource.h
src/qml/qgismobileapp.qml

this allows to import project from a local folder (copies directory to writable location + opens first project in this folder)
further improvements (choose the project + retrieve already imported folders/projects) will follow later

import local folder on iOS

---

src/core/platforms/ios/iosplatformutilities.h
src/core/platforms/ios/iosplatformutilities.mm

Tried QFieldCloud on QField iOS earlier today. One fundamental flaw: I couldn't get to download a 80mb project because the screen kept auto-locking (followed by outstanding network requests shutting down).
Let's just do what we do with QField, which is disable auto lock.

Don't auto lock please

---

scripts/ci/generate-version-details.sh

Small follow up to the PR I (accidentally) merged an hour ago to invert QField Dev package naming.
Issue raised through failed automated deployment of QField Dev on the play store.

Fix QField Dev package naming

---

src/core/localfilesmodel.cpp
src/core/utils/fileutils.cpp
src/core/utils/fileutils.h
src/core/utils/qfieldcloudutils.cpp
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/qgismobileapp.qml

Commits' description self explanatory :)
Showing the cloud project name instead of the folder name (i.e. the cloud project UUID) is a nice improvement:
File size information added to dataset items:

Local data picker follow ups

---

src/core/featuremodel.cpp
src/core/utils/geometryutils.cpp
src/qml/qgismobileapp.qml

This PR harmonizes the way we format coordinates in our coordinate cursor overlay vs. the positioning information panel.
Fixed:
(A commit in there fix compilation of QField against upcoming QGIS 3.26 too)

Harmonize position

---

src/core/distancearea.cpp
src/core/distancearea.h
src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h
src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/qml/MeasuringTool.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

Doing some field monitoring and need to quickly send screen grabs of QField representing line measurements. QField until now treats all measurements as filled. This makes for less than ideal screen grabs (confusing for viewers, etc.)
This PR fixes that by treating measurement geometry as a line until the user overs the current coordinate onto the first digitized coordinate. Hovering temporarily transform the geometry to an area, while clicking on add vertex while hovering over the first vertex transform the geometry to an area until the feature is cleared.
Screencast:
https://user-images.githubusercontent.com/1728657/170182115-c54fa882-b428-402f-a66f-4d4eaa57831c.mp4
I've also improved the digitizing text overlay by hiding Segment: XXXX when the segment length is 0.00000 :)

Measuring tool improvements

---

resources/sample_projects/advanced_bee_farming.qgs
resources/sample_projects/live_qfield_users_survey.qgs
resources/sample_projects/simple_bee_farming.qgs
scripts/cppcheck.sh
src/core/CMakeLists.txt
src/core/locator/gotolocatorfilter.cpp
src/core/qgismobileapp.cpp
src/core/utils/coordinatereferencesystemutils.cpp
src/core/utils/coordinatereferencesystemutils.h
src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/core/utils/snappingutils.h
src/core/utils/stringutils.cpp
src/core/utils/stringutils.h
src/qml/About.qml
src/qml/BookmarkProperties.qml
src/qml/BookmarkRenderer.qml
src/qml/CoordinateLocator.qml
src/qml/LayerTreeItemProperties.qml
src/qml/NavigationHighlight.qml
src/qml/NavigationInformationView.qml
src/qml/NavigationRenderer.qml
src/qml/PositionInformationView.qml
src/qml/QFieldSettings.qml
src/qml/qgismobileapp.qml

_(This PR temporarily includes commits from #2942)_
This PR enhances QField so its respects projects' coordinate display unit (i.e. map unit vs geopgraphic). The displayed coordinates that will respect the flags are: the positioning information panel, the navigation information panel, the copy coordinates to clipboard actions, and the coordinate text overlay.
Case in point: sample projects' CRS shipped in QField is pseudo mercator (so the XYZ tiles can project neatly on the map canvas). Until now, it meant QField would display coordinates in what is for many users an obscure pair of pseudo mercator X,Y.
This is QField's simple bee project, displaying coordinates in pseudo mercator:
Now, this is the same simple bee project with QField respecting the project's coordinate display unit type: …

QField should respect projects' coordinate display unit type

---

src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/ValueRelation.qml

This PR fixes https://github.com/opengisch/QField/issues/2954 and https://github.com/opengisch/QField/issues/2865.
The problem had to do with us setting the allowMulti property _after_ the attributeValue property was set, which meant that the model would always parse the original attributeValue as _single value_. The world would subsequently collide, leaving users in tears.
Thanks goes to @bsaglio2001 who filed a detailed issue with a test project.

Fix value relation editor widget's allow multi(ple selection) mode

---

cmake/VcpkgToolchain.cmake
vcpkg/overlay/qgis/vcpkg-cmake-wrapper.cmake

It only works in very defined scenarios and otherwise wastes time for local builds

Disable NuGet caching by default

---

platform/android/AndroidManifest.xml.in
platform/android/res/values/strings.xml
platform/android/res/values/styles.xml
platform/android/src/ch/opengis/qfield/QFieldActivity.java

This PR does a couple of nice things to our android dialogs (emitted from the main QtActivity)
- instead of using a layout straight from the 90s, it uses a slightly more modern design
- instead of using an old Android default blue color, it uses our QField green :heart_eyes: 
- progress bar dialogs' spinner is now using our QField green too (instead of light gray)
Before (left) vs. PR (right):

Android {alert,progress} dialog improvements

---

src/app/main.cpp
src/core/qgismobileapp.cpp

Setting the default surface when initializing the QtQmlApplicationEngine appears to be too late in the process, Qt tells us the following:
> Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
I've moved it into main.cpp, and the warning is gone.
@mbernasocchi , although I couldn't reproduce your weird "canon" glitch, I think this could be a cause.

Fix what appears to be a serious warning from Qt

---

src/core/qgismobileapp.cpp
src/core/utils/layerutils.cpp
src/core/utils/layerutils.h

This PR makes use of a new feature in QGIS 3.26 to allow for users' base map projects to dictate the symbols and labeling styles of features when opening individual datasets.
E.g., this is my base map project's default styles settings:
This translates into this beautiful rendering when opening individual (in this case point) dataset in QField:

Respect a base map project's default styles (if any) when opening individual datasets

---

images/qtquickcontrols2.conf

This avoid tiny font size in QML Dialog items (as well as combobox's default styling, etc.)
Makes us look better :)

Harmonize default font size across all QML items

---

src/qml/qgismobileapp.qml

We had two connection { itarget: iface; function onLoadProjectEnded() { ... } }, which isn't great :) this PR fixes that, and insures that both the welcome screen _as well as_ the local data picker is closed when we start loading a project. 
PR aimed at fixing a situation whereas if someone opens the local data picker, switch to a different app and open a given project via file association, the local data picker wouldn't go away.

Regroup onLoadProjectEnded under one function, insure local data picker is closed when loading a project

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/core/projectinfo.cpp
src/core/qgismobileapp.cpp
src/core/qgsquick/qgsquickmapsettings.cpp
src/core/qgsquick/qgsquickmapsettings.h

This PR improves our handling of individual datasets containing temporal fields. When opening datasets, QField now checks for the presence of a {date,datetime} field. If such a field is present, QField will automatically setup temporal properties, allow for users to then filter those datasets using QField's temporal UI.
This means that people can now consume e.g. GPX files, and be able to narrow down the drawing of track points to a specific date and time:

When opening individual datasets with a {date,datetime} field, setup temporal properties

---

src/qml/qgismobileapp.qml

This PR fixes the following situation whereas on narrow screen heights buttons overlap each other:
In this scenario, IMHO it's better to just remove the zoom in and out button instead of having worlds collide :)

Avoid zoom in/out button overlapping bottom-right buttons on narrow screen heights

---

src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

Follow up to https://github.com/opengisch/QField/commit/b38bf0aafdf6192359658374c883d78a1909bf7f which caused a regression whereas configuration-less relation editor widget (i.e., auto generated form) would have the add child feature button gone missing.
This fixes #2999 .
@suricactus , tweaked your logic a bit to fix the regression, all good?

Relation editor's add button gone missing regression fix

---

src/core/locator/featureslocatorfilter.cpp
src/core/navigation.cpp
src/core/navigation.h
src/qml/NavigationInformationView.qml
src/qml/imports/Theme/QfToolButton.qml
src/qml/qgismobileapp.qml

This PR implements a navigation to feature vertices functionality within QField. First, a small screencast:
When setting a navigation destination using a feature, a new purple feature bar title appears as part of the navigation information panel. For single points, a destination name is displayed (matching a given vector layer's display name field / expression).
For multipoint or {multi,single}{line,polygon}, new navigation buttons are located at the left and right of the destination name. Those buttons allow users to cycle through vertices of the feature picked as navigation destination. Tap and holding onto these buttons will cycle through vertices (comes in handy when you have a feature with a large vertex count).

Navigation to feature vertices

---

src/qml/FeatureListForm.qml

After much testing, I found out that 100% of the time, when using the feature form's set feature as destination menu action, you really want to jump onto the map canvas after that (especially now that we have feature vertex navigation). Let's improve UX and auto close the feature form.

Improve navigation UX by auto-closing the feature form when using the set feature as destination action

---

src/core/positioning/abstractgnssreceiver.h
src/core/positioning/bluetoothreceiver.cpp
src/core/positioning/internalgnssreceiver.cpp
src/core/positioning/positioning.cpp
src/core/positioning/positioning.h
src/core/qgismobileapp.cpp
src/qml/LocationMarker.qml
src/qml/PositionInformationView.qml
src/qml/QFieldSettings.qml
src/qml/qgismobileapp.qml

This PR fixes a couple of bluetooth GNSS device issues following the revamp of our positioning framework. Nothing major, but good to have been able to test a GNSS device that supports NMEA through bluetooth prior to 2.2.

Fix handling of bluetooth gnss receiver's socket state following revamp of positioning

---

src/core/positioning/internalgnssreceiver.cpp
src/core/positioning/internalgnssreceiver.h

Moving our positioning code to C++ made it super easy to add satellite-related information to our handling of _internal_ GNSS positioning.

QField :heart: satellites

---

src/core/featuremodel.cpp

Spotted on sentry, not 2.2.0 specific, has been there forever.

Avoid crashing by checking whether there's a geometry to constGet

---

src/app/main.cpp

Since `missing proj.db` is a message I have seen all to often, I'd prefer to have this printed on app start for easier debugging
This will also look for proj relative to the app binary on macos/linux

Print proj location on app startup

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp

Helps with animation as the QML spinner element isn't needlessly showing and hiding.

[qgsquick] Fix silent refresh not sticking until the end of a refresh cycle

---

src/app/main.cpp

@m-kuhn , a quick fix to follow up on your fantastic vcpkg work of the last few weeks. When doing home builds on my linux machine, the custom PROJ_LIB and GDAL_DATA paths are messing things up (as it should, since I'm not building with vcpkg).
The commit insures that those custom paths are only added when RELATIVE_PREFIX_PATH is set (which in turns is set when building WITH_VCPKG).
I'm also not force pushing the custom proj path into the console if it's empty, makes for a cleaner console when developing which increases the chances of catching regressions causing console outputs :)

Do not add custom gdal and proj data paths when building against system libraries, bad stuff happens

---

.github/workflows/android.yml

Advantages: less spam
Disatvantages: no notification on new builds for testing

Use sticky comment for android builds

---

src/core/navigation.cpp
src/core/navigation.h

@m-kuhn , a subset of https://github.com/opengisch/QField/pull/3092 -- I've tested locally and it works (I think the error was the source string not liking ":..." instead of "qrc:...").
@lucienicolier , can you test this one out?

Use QSoundEffect instead of QSound for the proximity alarm

---

CMakeLists.txt
cmake/FindQGIS.cmake
cmake/Package.cmake
src/app/CMakeLists.txt
src/core/CMakeLists.txt
src/qml/CMakeLists.txt
test/CMakeLists.txt

Adds  a new `BUILD_WITH_QT6` option which defaults to `OFF`

CMake changes for Qt6

---

src/core/vertexmodel.cpp
src/core/vertexmodel.h
test/test_vertexmodel.cpp

This PR fixes #3128 -- while QGIS should improve its handling of nan values, QField should _not_ break geometries to begin with :)

Fix serious brokenness with vertex editor mishandling ZM geometries

---

src/core/multifeaturelistmodelbase.cpp

Consider checked features with same vector layer and feature ID to avoid out of sync feature details between selected and all feature lists.
Fixes #3127.

Harden the selected feature check in the multi feature list model

---

src/core/printlayoutlistmodel.cpp

Fixes the following bug reported on sentry: https://sentry.io/organizations/opengisch/issues/3015822389/?project=6119013&query=is%3Aunresolved+release%3A%22ch.opengis.qfield%402.2.1+-+Coordinated+Capybara%2B2020199%2A%22&sort=freq&statsPeriod=7d

Fix an out-of-bound crash when trying to get a layout name

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java

Reported on sentry: https://sentry.io/organizations/opengisch/issues/3428431498/?project=6119013&query=is%3Aunresolved+release%3A%22ch.opengis.qfield%402.2.1+-+Coordinated+Capybara%2B2020199%2A%22&sort=freq&statsPeriod=7d
There's more to this than merely fixing the crash (i.e., we need to figure out a way on handling devices like Xiaomi who don't implement all of Android API promises). But for now I think no crash > crash :wink:

Don't crash on Android when no ACTION_OPEN_DOCUMENT_TREE activity is available

---

src/core/printlayoutlistmodel.cpp

[Backport release-2_2] Fix an out-of-bound crash when trying to get a layout name

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java

[Backport release-2_2] Don't crash on Android when no ACTION_OPEN_DOCUMENT_TREE activity is available

---

src/core/attributeformmodelbase.cpp

4th most reported crash on sentry these past 7 days.

Fix crash when attribute form model tries to update a field index out of bound

---

src/core/attributeformmodelbase.cpp

[Backport release-2_2] Fix crash when attribute form model tries to update a field index out of bound

---

src/core/layertreemodel.cpp

This PR fixes QField's ignorance of map layers' private flag. 
(TIL: QGIS has private layers; @elpaso , belated thanks for this :))

Insure that private layers are not added to the legend (fixes #3154)

---

images/images.qrc
images/themes/qfield/nodpi/ic_copy_black_24dp.svg
images/themes/qfield/nodpi/ic_paste_black_24dp.svg
src/qml/BarcodeReader.qml
src/qml/EmbeddedFeatureForm.qml
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/RelationCombobox.qml
src/qml/editorwidgets/EditorWidgetBase.qml
src/qml/editorwidgets/TextEdit.qml
src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml
src/qml/qgismobileapp.qml

This PR integrates QField's brand new code reader functionality with the feature form's text edit widget. 
The fill value with decoded code action resides in a brand new menu attached to the text edit widget when editing is turned on:
_Notice the 3-dot icon button at the right end of the Beekeeper attribute_
When clicking on the 3-dot icon button, a menu appears with three possible actions, including 'Scan Code':
Selecting the action will open QField's code reader and begin scanning for {QR,bar}codes to decode:
Users then click on the (:heavy_check_mark:) OK button to fill the attribute with the decoded value:
:magic_wand: 
This new 3-dot menu was implemented in such a way that allows for other editor widgets to implement their own specific menu actions, as well as allowing for the …

QR (et cie) code reader <-> feature form's text edit widget integration 

---

src/qml/qgismobileapp.qml

```
qrc:/qml/qgismobileapp.qml:1455: TypeError: Property 'resetAttributes' of object FeatureForm_QMLTYPE_165_QML_285(0xb4000071eb31bd40) is not a function
{
file: qrc:/qml/qgismobileapp.qml, 
line: 1455
}
```

Fix resetting attributes on creation issue

---

platform/android/build.gradle.in
platform/android/src/ch/opengis/qfield/QFieldActivity.java
src/core/CMakeLists.txt
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/qml/DashBoard.qml
src/qml/EmbeddedFeatureForm.qml
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/NavigationBar.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/PageHeader.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/QFieldSettings.qml
src/qml/WelcomeScreen.qml
src/qml/qgismobileapp.qml

This PR upgrades QField Android to allow for elements to be drawn under the top status bar. Here's how it looks:
Beyond making QField behave like modern Android apps, it expands the canvas extent by quite a few pixels which is always welcome :)
Note: the implementation is futureproof and allows for scene left,right,bottom margins even though ATM we don't need to rely on that.

Let's get QField to draw outside of the box

---

cmake/FindQca.cmake

On opensuse Qca header are installed under `/usr/include/qt5/Qca-qt5/QtCrypto`

Find Qca on openSUSE

---

src/core/qgismobileapp.cpp
src/qml/BluetoothDeviceChooser.qml

We were forcing a qml-module-qbluetooth dependency merely to get an enum, let's avoid that. Kills an issue on Qt6.

Remove needless QtBluetooth QML dependency which is gone in Qt6

---

src/app/main.cpp
src/core/qgismobileapp.cpp
src/qml/BookmarkRenderer.qml
src/qml/CMakeLists.txt
src/qml/LocationMarker.qml
src/qml/NavigationRenderer.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/imports/Theme/+Qt5/QfDropShadow.qml
src/qml/imports/Theme/+Qt5/QfOpacityMask.qml
src/qml/imports/Theme/+Qt6/QfDropShadow.qml
src/qml/imports/Theme/+Qt6/QfOpacityMask.qml
src/qml/imports/Theme/QfToolButton.qml
src/qml/imports/Theme/qmldir
src/qml/qgismobileapp.qml
src/qml/qmlqt5.qrc
src/qml/qmlqt6.qrc
test/test_qml_editorwidgets.cpp

Playing a nice little trick so we can maintain support for both Qt5 and Qt6 when it comes to graphical effects.
_(This trick also means we can maintain both a Qt5 barcode reader and a Qt6 bardcode reader and not lock QField into an overly-early Qt6-only stage for our src/ tree)_

Support graphicaleffects for both Qt5 and Qt6

---

src/qml/QFieldCloudPopup.qml

The PR fixes a blank avatar where our beloved Nyuki shows in the (fixed) screenshot below:
I pushed the same fix for the cloud projects list panel but forgot to apply it to the project synch panel.

Fix missing Nyuki avatar when user avatar image is invalid, part 2

---

src/core/attributeformmodelbase.cpp

E.g.
- https://sentry.io/organizations/opengisch/issues/3339596703/?project=6119013
- https://sentry.io/organizations/opengisch/issues/3525218534/?project=6119013

Avoid double std::unique_ptr::reset, long shot to fix sentry-reported crash

---

src/core/featuremodel.cpp
src/core/featuremodel.h
src/core/layertreemodel.cpp
src/core/positioning/internalgnssreceiver.cpp
src/core/rubberband.cpp
src/core/rubberband.h
src/core/tracker.cpp
src/qml/LayerTreeItemProperties.qml
src/qml/Tracking.qml

This PR unlocks position tracking for point layers (implements https://github.com/opengisch/QField/issues/1921).
Contrary to line of polygon layers, tracking against a point layer will create one feature per triggered tracking record. This allows for all @position_* variables exposed here (https://qfield.org/docs/prepare/gnss.html) to be used in attributes' default value expression.
When starting tracking on a point layer, a feature form will pop up. Attribute values entered that _do not_ have a default value expression (or provider-side default value like FIDs) will be remembered across the created features. This means that for e.g., an attribute could be used to identify a user name creating a given point track, and that attribute value will be remembered during the tracking session. …

Allow position tracking on point layers

---

src/qml/LayerTreeItemProperties.qml
src/qml/Legend.qml
src/qml/imports/Theme/QfButton.qml

With the recent addition of the show label checkbox, the layer opacity, and the show visible features list, the layer properties popup has reached a state of overcrowdedness :)
This PR proposes some modest improvements:
The changes include:
- Moving the rarely-used 'reload data' to sit at the top-right of the popup as a label-less reload icon tool button
- Removing the expend legend items checkbox (which was cutting through styling-related items) and moving the functionality to a double-tap on legend item action (feels a lot more natural and de-crowds the popup)
- Putting the show >>visible<< features list action into a new dropdown menu attached to the show feature list button
I feel pretty good about all of these changes, and it's nice to have a new dropdown menu functionality coded …

Layer properties popup reorganizing

---

src/core/identifytool.cpp

QField's identify tool was not respecting vector layer's active state of renderer rules/categories, leading to "invisible" features being identified while tapping on the map canvas. 
~~This fixes an issue that was filed a while back but can't relocate it on github :fearful:~~
Fixes #3182.

Fix hidden {rule,category,graduation} symbols still identified on the map

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/core/multifeaturelistmodel.cpp
src/core/multifeaturelistmodel.h
src/qml/LayerTreeItemProperties.qml

This PR makes the show (visible/all) features list actions found in the layer properties popup that much more useful by respecting the sub-layer legend symbol item's filter expression.
For e.g., say you have a vector layer with a categorized renderer that has three categories (status=GOOD, status=UNSURE, status=BAD), you can trigger a features list that will filter features by the long-pressed category in the legend tree.  It is :magic_wand: 
E.g.:
https://user-images.githubusercontent.com/1728657/187057176-81b6a1c2-5516-4abd-8b57-334aca16f867.mp4
Thanks to @nyalldawson for the inspiration through his QGIS feature selection implementation.
(Fixes #2272)

When triggering show (visible/all) features list, respect selected sub-layer symbol filter

---

src/qml/LayerTreeItemProperties.qml

We can rely on the model logic here (https://github.com/opengisch/QField/blob/master/src/core/layertreemodel.cpp#L850) which sets the opacity to -1 for non spatial layer items (i.e. group items, legend items, geometryless table) to show/hide the opacity slider. We avoid create a parallel set of conditions.

Fix opacity slider shown in instances where we can't adjust opacity

---

src/core/layertreemodel.cpp
src/core/projectinfo.cpp
src/core/projectinfo.h
src/core/qgismobileapp.cpp
src/qml/LayerTreeItemProperties.qml
src/qml/Legend.qml

This PR implements functionality to save and restore customized a given project map layer styling across QField sessions. At this moment, it will properly save/restore layer opacity, label visibility, as well as individual layer's visibility (i.e. [x] show on map) state.
Note: The implementation covers both project and individual dataset contexts when it comes to opacity, label visibility, however the individual layer's [x] show on map are not remember when opening individual datasets.
Here's a video showcasing the enhancement:
https://user-images.githubusercontent.com/1728657/186128295-7d4886c5-d119-4b2c-ad62-9556d4dc85a6.mp4
You can see various styling attributes (layer opacity, layer visibility, and label visibility) are all remembered _across_ a given project sessions.

Remember map layer styling (opacity, labels visibility) across QField sessions

---

src/core/appinterface.cpp
src/core/appinterface.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h
src/core/screendimmer.cpp
src/core/screendimmer.h
src/qml/QFieldSettings.qml
src/qml/imports/Theme/QfSlider.qml
src/qml/imports/Theme/qmldir
src/qml/qgismobileapp.qml
src/qml/qml.qrc

Some people, including me, find the default timeout inconvinient. Therefore, let the users decide how long that should be.
A future improvement can be https://github.com/opengisch/QField/issues/3264 .
For now... Fairy, let us see if it works as expected.

Configure the timeout to dim screen, rather than simple disabling it

---

src/core/rubberband.cpp
src/qml/qgismobileapp.qml

I was looking into https://github.com/opengisch/QField/issues/3266 and I got a really bad crash here:
I also think topological editing should be visible for point layers, so we can disable and enable it.
I still believe the buttons on the bottom right behave in a weird way, continue investigating.

Fix crash when entering geometry editing mode of a point and show topo edit on point editing

---

src/core/distancearea.cpp
src/core/distancearea.h
src/core/qgismobileapp.cpp
src/qml/qgismobileapp.qml

QField's measuring tool now respects these project settings:
We also now have sensible defaults (i.e. meters for distance and square meters for area)
@mbernasocchi , here we are :)

Measuring tool should respect the project's distance and area units type

---

.github/workflows/ios.yml

As per Qt's QBluetoothSocket documentation (https://doc.qt.io/qt-5/qbluetoothsocket.html):
> On iOS, this class cannot be used because the platform does not expose an API which may permit access to QBluetoothSocket related features.

Disable bluetooth support on iOS, that's simply not supported by Qt

---

doc/dev.md
src/core/deltafilewrapper.cpp
test/CMakeLists.txt
test/test_deltafilewrapper.cpp

When a field is nullable and it's value is changed to zero or other way
around, QField deltafilewrapper check the difference using a simple
`QVariant(1) == QVariant(2)`. However, there are special cases such as
`QVariant(0) == QVariant( QJsonValue::Null )` that return TRUE, even
though one of the values has undefined NULL value.
This fix checks explicitly about such cases and fixes the issue.
Also added appropriate test case.

Fix delta generation on NULL and 0

---

src/core/qfieldcloudprojectsmodel.cpp

Prevent situations like this:
While I can choose whether I use the default `Qt::DisplayRole` for sorting, or create a new role and use `QSortFilterProxyModel::setRole` for that, I preferred the latter as it gives a nice default display name everywhere.

Prevent random sorting of the cloud projects

---

src/core/layertreemodel.cpp

As reported here: https://github.com/opengisch/QField/issues/3279
In some cases the layer is so badly broken, thah it returns a `nullptr` when casted. In that case, we didn't check for nullptr and got a bad crash. All is fixed now.

Fix crash when the layer is invalid

---

cmake/qgis-cmake-wrapper.cmake
src/app/CMakeLists.txt
src/app/main.cpp
vcpkg/overlay/qca/portfile.cmake

This PR fixes the authentication manager on Android, which had regressed since our move to a vcpkg static build setup.

Handle static link to QCA ossl plugin on static builds

---

src/qml/DashBoard.qml

This PR fixes a glitch on iOS with dashboard top buttons wrongly placed / overlapping legend:

Fix dashboard buttons glitch on iOS

---

platform/ios/Info.plist.in
src/core/platforms/ios/iosplatformutilities.h
src/core/platforms/ios/iosplatformutilities.mm
src/qml/WelcomeScreen.qml

This PR unlocks local files (datasets and full project) support on iOS:
Files can be copied into the QField's Documents storage via the iPhone's Files app or via iTunes on a desktop (mac, windows, linux):

Implement basic iOS local files / project support

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/qml/QFieldCloudScreen.qml

While this is not the nicest solution, it is good enough until `QFieldCloudProjectsModel` looks as it looks now.
In a good day the API will support pagination and it would not be that painfully slow.

Fetch public projects with a separate request

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java
src/core/platforms/android/androidplatformutilities.cpp

Two fixes in there:
1/ only try to get the display cutout when minimum version requirement is met (ANDROID >= 9)
2/ while the inter tubes are vague, I think the status_bar_height dimensions need to be fetched within the onCreate function of our activity
I've also added a fail-safe whereas a default margin will be served if everything else doesn't.

Fix status bar margin on a number of devices

---

.docker/android_dev/Dockerfile
.github/workflows/android.yml
cmake/qgis-cmake-wrapper.cmake
vcpkg/overlay/json-c/pkgconfig.patch
vcpkg/overlay/json-c/portfile.cmake
vcpkg/overlay/json-c/vcpkg.json
vcpkg/triplets/arm-android.cmake
vcpkg/triplets/arm64-android.cmake

Gives me crash-free local APKs again, and ~~hopefully~~ the unwind flags will work on armv7.
Edit: @marioba confirmed the APKs here are crash-free again.

Go back to 22 to be crash free

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/core/qgsquick/qgsquickmapcanvasmap.h

A bit of cleanup while I was upstreaming temporal functionality (https://github.com/qgis/QGIS/pull/50312).

Reduce diff between upstream QGIS and QField's qgsquickmapcanvasmap.{cpp,h}

---

src/app/main.cpp

Follow up to https://github.com/opengisch/QField/commit/9300e0f474216512530f3e7edfb33b0f11103202 , which while fixing an important regression on relative paths broke home builds against system-installed QGIS.
Hope it's the last time we tweak this part of the code for the foreseeable future :)

Do not set package data path on non-relative prefix path setup

---

src/qml/Changelog.qml

Title says it all, spotted during the auto deployment of 2.3.5.

Harmonize margins of changelog popup, which also avoids overlap with the status bar area

---

test/qfield_testbase.h

A bunch of tests are failing, but at least they compile (inc. spix)

Remove QTEST_ADD_GPU_BLACKLIST_SUPPORT[_DEFS] so tests can compile under Qt6

---

src/qml/Changelog.qml

[Backport release-2_3] Harmonize margins of changelog popup, which also avoids overlap with the status bar area

---

test/CMakeLists.txt
test/spix/smoke_test.py
test/test_attributeformmodel.cpp
test/test_deltafilewrapper.cpp
test/test_digitizinglogger.cpp
test/test_layerobserver.cpp
test/test_orderedrelationmodel.cpp
test/test_referencingfeaturelistmodel.cpp

This PR harmonizes C++ test names (CamelCase, without a "Test" prefix). While doing so, I realized two tests hadn't been ported to catch 2 and were simply not being run anymore. They have been revived.
I've also disabled spix test on Qt6 builds has images there as saved with an alpha band (whereas Qt5 doesn't), which leads to screenshot comparison failures. To revisit later (we'd probably want to submit a patch to spix so it behaves the same on Qt5 and Qt6)

Test names harmony and revivals

---

src/qml/editorwidgets/TextEdit.qml

PR fixes this ugly situation:
_Look at the input_label / output_label overlap with values_

Avoid text overlap artifacts when non multiline attribute has \n characters

---

src/qml/editorwidgets/TextEdit.qml

[Backport release-2_3] Avoid text overlap artifacts when non multiline attribute has \n characters

---

src/core/tracker.cpp

This fixes number one crasher reported by sentry over the last 14 days.

Tracker should not access its rubber band model when null

---

src/core/tracker.cpp

[Backport release-2_3] Tracker should not access its rubber band model when null

---

src/core/platforms/android/androidplatformutilities.cpp
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h

This PR improves handling of print atlases when printed through the main menu button, i.e.:
Prior to this PR, the behavior would be random. If no feature atlas had been printed yet, it would be handled as a non-atlas layout and show broken atlas references, e.g.:
With the PR, QField now respect the atlas context. It can come in handy with filter expressions whereas a user could print all features created within the last 24 hours, etc.
This UX shortcoming was discovered while improving the bee sample project.

Allow for atlases to be printed from the main menu, respect pre-existing filtering

---

src/qml/editorwidgets/EditorWidgetBase.qml

This PR fixes #3415 and #3282, whereas the text edit widget menu (copy, paste, scan QR code) would be stacked _below_ a feature form panel.

Insure that the text edit widget's menu always appears on top of feature forms

---

src/qml/QFieldCloudLogin.qml

This most likely fixes the issue reported here (https://github.com/opengisch/QField/issues/3417).

Suggest no predictive text for the QFieldCloud login password field

---

src/qml/QFieldCloudLogin.qml

[Backport release-2_3] Suggest no predictive text for the QFieldCloud login password field

---

src/qml/editorwidgets/EditorWidgetBase.qml

[Backport release-2_3] Insure that the text edit widget's menu always appears on top of feature forms

---

src/qml/qgismobileapp.qml

PR fixes the following surprise during our release yesterday:

Auto-dismiss changelog popup when project is loading (aka fix failing spix test on release page)

---

src/core/positioning/abstractgnssreceiver.h
src/core/positioning/bluetoothreceiver.cpp
src/core/positioning/bluetoothreceiver.h
src/core/positioning/positioning.cpp
src/qml/BluetoothDeviceChooser.qml
src/qml/qgismobileapp.qml

When the bluetooth device chooser combobox's Component.onCompleted is triggered, positioningSettings.positioningDevice isn't yet set to the actual value, resulting in the wrong combobox index being selected. The fix is to rely on the 'raw' settings object at that early stage.
Issue didn't impact positioning functionality per say (i.e. the bluetooth device is still picked), but does result in confusing UI/UX. 
@mbernasocchi , we had spotted this issue together while testing GNSS devices on the last hackfest day.

Insure that the bluetooth combobox has the right item selected

---

platform/android/AndroidManifest.xml.in

This PR removes file association with .shp files (only file association via file browser, you can still open these in QField's local datasets screen). The rational is that a .shp will _always_ have sidecar, and therefore can never work as a standalone file being opened via file association.

Remove shapefile file association, it'll _always_ require full storage access due to sidecar files

---

platform/android/AndroidManifest.xml.in

[Backport release-2_4] Remove shapefile file association, it'll _always_ require full storage access due to sidecar files

---

.gitmodules
CMakeLists.txt

Ported from https://github.com/opengisch/QField/pull/3432
One less submodule, android openssl will only be pulled in for android builds.

Use FetchContent for android openssl

---

src/core/locator/featureslocatorfilter.cpp

@mbernasocchi , good catch, this has been - unknowingly to all of us - plaguing QField for well, forever. :)
I suspect this fixes issue #3351.

Fix search bar's go to point feature partially broken when layer CRS != project CRS

---

src/core/positioning/bluetoothreceiver.cpp
src/core/positioning/bluetoothreceiver.h
src/core/positioning/positioning.cpp
src/core/positioning/positioning.h
src/qml/qgismobileapp.qml

While testing external GNSS devices during the October hackfest, I noticed our elevation wasn't matching what was reported by the device manifacturers' own apps. Turns out our ellipsoidal elevation setting wasn't being respected anymore (a regression from the rework of the positioning framework).
This PR fixes that.

Fix regression with exernal GNSS receiver not respecting the ellisoidal elevation setting

---

src/core/distancearea.cpp
src/core/distancearea.h
src/qml/qgismobileapp.qml

This PR adds an azimuth detail to the information overlay when using the measuring tool (or while digitizing when the "show digitizing information" toggle is turned on).
In action:
https://user-images.githubusercontent.com/1728657/197734785-9605c550-13ce-49d7-aa20-9a4f238fc412.mp4
_Funded by [Groupements Forestiers Québec](https://groupementsforestiers.quebec/)_

Add azimuth details to measuring tool (and digitizing when set to show details)

---

src/core/featuremodel.cpp
src/core/featuremodel.h
test/CMakeLists.txt
test/test_featuremodel.cpp

This PR addresses issues with regards to default values relying on  positioning (or QFieldCloud) variables set to be applied on feature update. Until now, QField deferred the updating of such default value to QGIS code. The latter however does not have access to the full set of expression context QField injects (positioning, QFieldCloud user / email information, etc.).
We now take care of updating default values, resulting it access to the full set of variables QField exposes. The modification fixes #3380 and fixes #3485. 
A new test has been added to insure this functionality will work from now on until the end of times :wink: .
_Funded by [Egis](https://www.egis-group.com/)_

Do not rely on QGIS to set default values on update, it lacks QField-specific scopes

---

src/core/featuremodel.cpp
src/core/featuremodel.h
test/CMakeLists.txt
test/test_featuremodel.cpp

[Backport release-2_4] Do not rely on QGIS to set default values on update, it lacks QField-specific scopes

---

images/images.qrc
images/themes/qfield/nodpi/ic_elevation_green_24dp.svg
images/themes/qfield/nodpi/ic_elevation_white_24dp.svg
src/core/CMakeLists.txt
src/core/qgismobileapp.cpp
src/core/qgsquick/qgsquickelevationprofilecanvas.cpp
src/core/qgsquick/qgsquickelevationprofilecanvas.h
src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/qml/ElevationProfile.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc
vcpkg/overlay/qgis-qt6/mesh.patch
vcpkg/overlay/qgis-qt6/portfile.cmake
vcpkg/overlay/qgis/mesh.patch
vcpkg/overlay/qgis/portfile.cmake

This PR adds basic elevation profiling functionality to QField's measurement tool (a screencast of the UI/UX in action is available here: https://twitter.com/QFieldForQGIS/status/1584441812592119808).
Once this foundation is laid, a bunch of interesting features could be added. To name a few:
- tap on profile canvas to identify features
- tap along elevation profile to highlight location along the profiling curve on the map canvas
- overlay device/external GNSS location on the elevation profile
- draw elevation profile of a layer feature's line geometry from the feature form menu action
- etc.

Brand new elevatin profile support for QField's measurement tool

---

src/core/attributeformmodelbase.cpp

It does make sense to do "live" update of default values when the [ ] apply default value on update checkbox isn't on for new features that haven't been created (i.e. saved) yet while editing the feature form post digitizing.
This fixes #3509 and in doing so harmonizes QField's behavior with that of QGIS.

Update default values when editing a new feature to match QGIS behavior

---

src/qml/editorwidgets/relationeditors/relation_editor.qml

This PR is the QField-side implementation of new functionality to allow users to customize the maximum number of items shown in the relation editor widget. For e.g., this is set to a maximum of 7:
The configuration happens on the QGIS side of things through qfieldsync. A new table widget can be found in a vector layer properties dialog's QField section:
This allows for different relationships to have individual max. visible items count (which is quite nice when preparing complex feature forms).
_Funded by [Ministère des Forêts, de la Faune et des Parcs du Québec](https://mffp.gouv.qc.ca)._

Implement functionality to determine maximum number of items shown in the relation editor widget

---

src/qml/FeatureListForm.qml
src/qml/NavigationBar.qml

This PR fixes #3517 , making fullscreen toggling of feature form via dragging of navigation bar bulletproof. I've also added the possibility to toggle fullscreen by dragging left/right when the feature form is displayed on the right side of the screen (i.e. tablet in landscape mode).
(It's a pretty important fix to maximize benefits of the new feature form's multi-column capability)

Fix fullscreen toggle when dragging feature form title, allow for horizontal directions

---

src/core/qgismobileapp.cpp

Most PDFs are handled by default by gdal as having a DPI of 96 even when the real value is much higher. Since we've added gdal driver options support in QGIS' gdal provider a few versions ago, we can go ahead and hardcode a DPI value of 300. This will insure nice high-res GeoPDFs will render beautifully. If a PDF has a DPI of 96, it changes absolutely nothing.
A GeoPDF without this fix:
Exact same GeoPDF with this fix in:

Hardcode a DPI value of 300 for PDFs as most PDFs fail to register thr proper resolution

---

src/core/localfilesmodel.cpp

@3nids , small improvement to show root directories using "/storage/emulated/0" instead of "0" in the all access APKs.

Improve root directory labels in the local data file picker

---

src/core/qgismobileapp.cpp

@m-kuhn , it's not fixing the iOS crasher, but it's remove a few lines of code to maintain.

Remove proj code in favor of QgsProjUtils function

---

src/qml/editorwidgets/Range.qml

This fixes https://github.com/opengisch/QField/issues/3446 -- long story short, I had first implemented the range editor widget's increase / decrease button such that when it was trying to add/remove from a null value, it'd use the editor configuration's minimum / maximum value.
That behavior ultimately turns out not to be so great in most scenarios (esp. when QGIS by default will set min/max values to the theoretical minimum and maximum value for an int. 
Instead, when pressing those buttons and the current value is null, it'll set the value to 0.

Avoid using range's min/max when increasing/decreasing from null value

---

src/qml/editorwidgets/CheckBox.qml

Up to now, QField's checkbox editor widget would look exactly then same when displaying a NULL value vs. a FALSE value. That's not great, looked especially odd when a non null constraint was on and QField would display "value can't be not null, current value: false" :)
This is how the widget looks now when the value being edited is NULL:

Implement NULL state for checkbox editor widget

---

src/core/attributeformmodel.h
src/core/attributeformmodelbase.cpp
src/core/attributeformmodelbase.h
src/core/submodel.cpp
src/qml/FeatureForm.qml

This PR implements columns support in QField's feature forms. Here's how it looks:
As QField is dedicated to be your friendly neighborhood, the implementation takes into account the available horizontal space; if the device offers a screen width that's too narrow, columns will display as it used to be until now. If space is available, the multi column support will kick in:
https://user-images.githubusercontent.com/1728657/198229949-07818cf6-5ebb-4097-8446-067ab1a07487.mp4
I've done a fair amount of testing as this changes a crucial part of QField. Two fundamental changes here:
- departing from a two level list (i.e. tabs + flattened attributes) into a full on tree
- switching from a ListView item to a Flow + Delegate pair of items
Kudos to QML for being awesome :)
Pro tip: the functional …

Add columns support to the feature form

---

src/core/attributeformmodelbase.cpp
src/core/submodel.cpp
src/core/submodel.h
src/qml/FeatureForm.qml

PR involves adding an enabled/disabled state to our SubModel class, and insure that we never end up handling root tabs as group containers when QField unloads itself (and somehow the feature form model ends up in a state where tabs become items of the form, which is bad).
Did quite a few of tests today in preparation to QField 2.5, that's the only regression from the work done last week I spotted :partying_face: 
Edit: root cause of the issue found (fixed in the 3rd commit). The other changes are good changes in any case.

Fix freeze when quitting QField while the bees demo feature form is open

---

src/core/platforms/android/androidplatformutilities.h
src/core/platforms/ios/iosplatformutilities.h
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/qgismobileapp.cpp
src/qml/imports/Theme/Theme.qml

This implements a solution for #3289, whereas QField now sizes its fonts based on the default system font size (on windows, linux, and macos).

Respect system font size on windows, linux, and macos

---

src/app/main.cpp
src/core/qgismobileapp.cpp

@m-kuhn , as discussed. Even if it doesn't miraculously help iOS, I think the change is desired. It's nice to only call the proj_context_set_search_paths _once_.

Only call proj_context_set_search_paths once, see if it helps iOS

---

.github/workflows/ios.yml

according to https://json.schemastore.org/github-workflow.json macOS should be macos

fix runs-on warning

---

src/core/qgismobileapp.cpp
src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/qml/NavigationInformationView.qml
src/qml/PositioningInformationView.qml
src/qml/qgismobileapp.qml

Without this, QField won't respect coordinate display settings when opening a project saved under QGIS >= 3.28. 
Long story short, before QGIS 3.28, the handling of coordinate display CRS was a mess, and it's now powerful. :)

Update project coordinate display CRS to rely on QGIS 3.28 niceties

---

src/qml/WelcomeScreen.qml

This was irritating me: on most smartphones in portrait mode, we'd end up with a needless scroll bar on the welcome screen. Turns out the recent project list view's height property was wrong. This PR fixes that.

Fix height of welcome screen's recent projects list to avoid needless scrollbar

---

src/core/qgismobileapp.cpp
src/core/utils/layerutils.cpp
src/core/utils/layerutils.h

This PR unlocks elevation profiling on _all projects_ by default by automatically setting up an online elevation layer for projects having a 'flat' terrain (i.e., no DEM / mesh setup).
This means that users can do elevation profiling with preexisting projects without a need to change anything, or against individual datasets being opened in QField. 
Bringing elevation profiling to the masses! :)
To work properly, it requires the following QGIS fixes (https://github.com/qgis/QGIS/pull/50795 and https://github.com/qgis/QGIS/pull/50778), which will be taken care of in a different PR.

When loading a project that has a flat terrain, auto setup an online elevation layer

---

src/qml/FeatureForm.qml
src/qml/RelationCombobox.qml
src/qml/editorwidgets/ExternalResource.qml
src/qml/editorwidgets/Range.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/TextEdit.qml

Now that we deal with feature form groups as containers, we can come up with a better visual representation of  a given group's background color. This is especially important when we groups with more than one column.
This PR has colored groups look like this:
For comparison's sake, here's how it used to look like:
---
PSA: this background color is customizable in QGIS:
In this PR, we take that color and tweak its alpha value to offer a nicer blend effect with QField's feature form.

Improve QField's use of feature form group color

---

src/core/attributeformmodelbase.h
src/core/featurelistmodel.cpp
src/core/featurelistmodel.h
src/core/featuremodel.cpp
src/core/featuremodel.h
src/core/geometry.cpp
src/core/geometry.h
src/core/layerresolver.cpp
src/core/layerresolver.h
src/core/multifeaturelistmodel.cpp
src/core/multifeaturelistmodel.h
src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h
src/core/tracker.h

Reliable way to crash QField:
1. Load the waste waters sample project
2. In the legend, select the point layer
3. Open the home screen
4. Select waste waters in the recent projects
5. *boom*
The crash happens here:
Cause: when selecting the point layer, QField builds the layer's feature form, which includes relation values widgets. When we re-load the waste waters (step 4), we end up clearing the current project, which means removing all layers. At which point, the feature form's relation values have raw vector layer pointers to removed/deleted project vector layers. Then worlds collide.
We can protect ourselves by using QPointer instead of raw pointers. I've took the liberty to upgrade a few raw pointers in addition to the one that fixes the crash described above.

Protect from random crashes when unloading a project

---

.github/workflows/android.yml

[Backport release-2_5] Do not upload "all-access" to playstore

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp

Backport #3596
_Sentry: https://sentry.io/organizations/opengisch/issues/3726630215/?project=6119013&referrer=release-issue-stream_

[Backport release-2_5] Fix crash when activating measuring tool in a number of projects

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp

Alright, we'll have enough crash fixes for a 2.5.1
_Sentry: https://sentry.io/organizations/opengisch/issues/3715900875/?project=6119013&referrer=release-issue-stream_

Fix crash when adding features on a vector layer that had been drawn onto an elevation profile

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp

[Backport release-2_5] Fix crash when adding features on a vector layer that had been drawn onto an elevation profile

---

src/core/attributeformmodelbase.cpp

Without this fix, the 2nd tab here (main cover/node) wouldn't show a constraint error badge:

The attribute form model isn't a 2-level situation anymore, adjust root-tab constraint data

---

src/core/submodel.cpp
src/core/submodel.h

We don't need to connect to model signals when a submodel enabled property is set to false, let's just not connect (that'll save us a few CPU cycles, and will likely prevent unforeseen situations)

Avoid connecting to model signals when submodel is disabled

---

src/core/attributeformmodelbase.cpp

[Backport release-2_5] The attribute form model isn't a 2-level situation anymore, adjust root-tab constraint data
