opengisch/QField

.github/workflows/ios.yml
src/core/qgismobileapp.cpp

If this works, IMHO it'd be good to push a QField 2.4.5 version on iOS to fix the crasher (reported here https://github.com/opengisch/QField/issues/3545)
The downside is that it'll disable vertical grid shift on iOS until we have a proper fix. IMHO, a "price" worth paying.

Temporary fix to avoid a dead QField on iOS

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp
src/core/qgsquick/qgsquickelevationprofilecanvas.h
src/qml/ElevationProfile.qml

Useful when dealing with remote elevation sources:
https://user-images.githubusercontent.com/1728657/199455201-904003b9-4c3c-43f3-aa06-004db13dd1f3.mp4

Add a busy indicator when elevation profile canvas is rendering

---

src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/editorwidgets/Range.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

Fix range editor widget' inc./dec. buttons reacting to feature form scrolling

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Get rid of the last CI_PACKAGE_FILE_BASENAME references in our workflows

---

.github/workflows/android.yml

[Backport release-2_5] Fix if condition in android workflow

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp

This PR fixes https://github.com/opengisch/QField/issues/3595 .

Fix crash when activating measuring tool in a number of projects

---

src/core/attributeformmodelbase.cpp
src/core/submodel.cpp
src/core/submodel.h
src/qml/FeatureForm.qml

15% deployment on the play store is revealing :)

Submodel and feature form fix

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp

Gives us sharper labels and grid on high dpi screens.

Taking into account dpi and device pixel ratio when drawing plots

---

src/core/attributeformmodelbase.cpp
src/core/submodel.cpp
src/core/submodel.h
src/qml/FeatureForm.qml

[Backport release-2_5] Submodel and feature form fix

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp

[Backport release-2_5] Taking into account dpi and device pixel ratio when drawing plots

---

src/qml/QFieldCloudLogin.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml

Avoid running the QFieldCloud login shader effect when not visible

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

Fix outsized feature form field heights

---

src/qml/QFieldCloudLogin.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml

[Backport release-2_5] Avoid running the QFieldCloud login shader effect when not visible

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

[Backport release-2_5] Fix outsized feature form field heights

---

src/qml/BrowserPanel.qml
src/qml/QFieldCloudLogin.qml
src/qml/qgismobileapp.qml

QFieldCloud account registration in in-app browser

---

src/core/submodel.cpp
src/core/submodel.h

[Backport release-2_5] Avoid connecting to model signals when submodel is disabled

---

src/qml/BrowserPanel.qml
src/qml/QFieldCloudLogin.qml
src/qml/qgismobileapp.qml

[Backport release-2_5] QFieldCloud account registration in in-app browser

---

src/qml/editorwidgets/TextEdit.qml

This PR fixes https://github.com/opengisch/QField/issues/3643 -- the things you can fix while riding in a car ;)

Fix multiline-enabled text editor widget

---

src/qml/editorwidgets/TextEdit.qml

[Backport release-2_5] Fix multiline-enabled text editor widget

---

src/qml/FeatureForm.qml

[Backport release-2_5] Fix QML container not loading regression

---

src/core/attributeformmodelbase.cpp

Fix constraints not ignored within hidden containers

---

src/core/featuremodel.cpp
src/core/featuremodel.h

@marioba , this fixes the problem you had reported to you which we discussed yesterday.

Avoid feature model's double setFeature() calls when creating a new feature

---

src/core/platforms/platformutilities.cpp
src/qml/qgismobileapp.qml

Fix iOS bottom UI elements overlap with system bar

---

src/qml/imports/Theme/QfTextField.qml

Fix password text field height clipped

---

src/qml/editorwidgets/CheckBox.qml

Discovered while debugging another issue.

Fix regression with the checkbox editor widget whereas clicking outside of the switch wouldn't change value

---

src/core/attributeformmodelbase.cpp

[Backport release-2_5] Fix constraints not ignored within hidden containers

---

src/core/platforms/platformutilities.cpp
src/qml/qgismobileapp.qml

[Backport release-2_5] Fix iOS bottom UI elements overlap with system bar

---

src/qml/imports/Theme/QfTextField.qml

[Backport release-2_5] Fix password text field height clipped

---

src/qml/FeatureForm.qml

[Backport release-2_5] Fix freeze (on slower device it can be 1-2sec) regression when clicking on layer tree items

---

src/qml/FeatureForm.qml

Keep the feature form model alive when hiding form to digitize child geometry

---

src/core/rubberband.cpp
src/core/vertexmodel.cpp
src/qml/geometry_editors/VertexEditorToolbar.qml
src/qml/qgismobileapp.qml

Geometry editor rubberband fix

---

src/core/rubberband.cpp
src/core/vertexmodel.cpp
src/qml/geometry_editors/VertexEditorToolbar.qml
src/qml/qgismobileapp.qml

[Backport release-2_5] Geometry editor rubberband fix

---

src/core/qgismobileapp.cpp

Cleaner code, less maintenance on our end, de-duplication of CRS and extent handling. Win, win, win.
It also makes it a lot easier in the future to add support for layer types other than vector and raster (e.g. mesh, point cloud, etc.)

Remove home-made sublayer handling in favor of QgsProviderRegistry's querySublayers

---

css/qfield.css
index.html

@mbernasocchi , as discussed, this is the BOSA award we settled on (i.e. one badge floating above the carousel).

Add BOSA award

---

platform/android/build.gradle.in

Security and bug fixes according to their respective release notes.

Update a couple of android gradle dependencies

---

platform/ios/Info.plist.in

[Backport release-2_5] Add missing ios description

---

src/qml/NavigationBar.qml
src/qml/qgismobileapp.qml

Avoid using printing to PDF on iOS

---

privacy_policy.html

- Add 3rd party sentry privacy policy link
- Fix first paragraph missing the company name leading to a broken, incomplete sentence.

Privacy policy update

---

src/core/qgismobileapp.cpp
src/core/qgismobileapp.h

@m-kuhn , the QField side of things :)

Remove itinerary code

---

src/core/rubberbandmodel.cpp

@m-kuhn , this PR fixes #3714.

Insure that created {point,line,polygon} geometries respect their layer's Z/M dimensions

---

src/qml/PositioningInformationView.qml

Inconsistencies (including usage of '-' instead of N/A as well as 'nan') spotted in @mbernasocchi 's videos.

Make sure all NaN values in the positioning information panel are using qsTr()

---

src/core/projectinfo.cpp
src/core/qgismobileapp.cpp

Some changes in #includes on QGIS dev (to become 3.30) necessitate some include additions on our side.

Fix building against QGIS dev

---

src/core/positioning/nmeagnssreceiver.cpp
src/core/positioning/nmeagnssreceiver.h
vcpkg/overlay/qgis-qt6/nmea.patch
vcpkg/overlay/qgis-qt6/portfile.cmake
vcpkg/overlay/qgis/nmea.patch
vcpkg/overlay/qgis/portfile.cmake

@m-kuhn , as discussed yesterday.

Re-add grouping of NMEA sentences, based on time

---

src/core/locator/gotolocatorfilter.cpp

Fixes https://github.com/opengisch/QField/issues/3782

Support for geo: prefix

---

src/qml/LocationMarker.qml
src/qml/imports/Theme/+Qt6/QfDropShadow.qml

[Backport release-2_6] Fix location marker glitch

---

src/qml/TcpDeviceChooser.qml
src/qml/UdpDeviceChooser.qml

Localhost does not seem to work on android.

use 127.0.0.1 instead of localhost in udp

---

src/qml/TcpDeviceChooser.qml
src/qml/UdpDeviceChooser.qml

Backport #3801
**Authored by:** @mbernasocchi

[Backport release-2_6] use 127.0.0.1 instead of localhost in udp

---

src/core/positioning/bluetoothreceiver.cpp
src/core/positioning/bluetoothreceiver.h
src/core/positioning/tcpreceiver.cpp
src/core/positioning/udpreceiver.cpp

Spotted while developing the serial port receiver.

Positioning cleanup: remove unused #include and fix typo

---

src/core/positioning/bluetoothreceiver.cpp
src/core/positioning/bluetoothreceiver.h
src/core/positioning/tcpreceiver.cpp
src/core/positioning/udpreceiver.cpp

[Backport release-2_6] Positioning cleanup: remove unused #include and fix typo

---

.github/workflows/ios.yml
.qt6/vcpkg.json
CMakeLists.txt
images/images.qrc
images/themes/qfield/nodpi/ic_serial_port_receiver_black_24dp.svg
src/app/CMakeLists.txt
src/core/CMakeLists.txt
src/core/positioning/abstractgnssreceiver.h
src/core/positioning/positioning.cpp
src/core/positioning/positioningdevicemodel.cpp
src/core/positioning/positioningdevicemodel.h
src/core/positioning/serialportmodel.cpp
src/core/positioning/serialportmodel.h
src/core/positioning/serialportreceiver.cpp
src/core/positioning/serialportreceiver.h
src/core/qgismobileapp.cpp
src/qml/PositioningDeviceSettings.qml
src/qml/QFieldSettings.qml
src/qml/SerialPortDeviceChooser.qml
src/qml/qml.qrc
vcpkg.json

Did someone say Bluetooth support for QField Windows through virtual serial port would be cool? Yep :)
More details on how that's done: https://junipersys.com/support/article/14876

Add a new positioning serial port receiver

---

.github/workflows/ios.yml
.qt6/vcpkg.json
CMakeLists.txt
images/images.qrc
images/themes/qfield/nodpi/ic_serial_port_receiver_black_24dp.svg
src/app/CMakeLists.txt
src/core/CMakeLists.txt
src/core/positioning/abstractgnssreceiver.h
src/core/positioning/positioning.cpp
src/core/positioning/positioningdevicemodel.cpp
src/core/positioning/positioningdevicemodel.h
src/core/positioning/serialportmodel.cpp
src/core/positioning/serialportmodel.h
src/core/positioning/serialportreceiver.cpp
src/core/positioning/serialportreceiver.h
src/core/qgismobileapp.cpp
src/qml/PositioningDeviceSettings.qml
src/qml/QFieldSettings.qml
src/qml/SerialPortDeviceChooser.qml
src/qml/qml.qrc
vcpkg.json

[Backport release-2_6] Add a new positioning serial port receiver

---

src/qml/PositioningDeviceSettings.qml

[Backport release-2_6] Fix positioning device types list on Android

---

CMakeLists.txt
cmake/VcpkgToolchain.cmake

Minimal fix to windows build workflow,  until work is done to rebase against latest vcpkg.

Fix windows builds

---

CMakeLists.txt
cmake/VcpkgToolchain.cmake

[Backport release-2_6] Fix windows builds

---

images/icons/qfieldcloud_background.svg
src/qml/QFieldCloudLogin.qml

Attaching a source string to a ShaderEffect fragmentShader property is gone in Qt 6.4

---

src/core/positioning/positioning.cpp
src/core/positioning/positioning.h

This fixes ellipsoidal height setting ignored on serial ports

Fix serial port not parented to positioning object

---

src/core/positioning/positioning.cpp
src/core/positioning/positioning.h

[Backport release-2_6] Fix serial port not parented to positioning object

---

src/qml/editorwidgets/ExternalResource.qml

Quick UI follow up on the fresh audio of audio playback. Instead of using the gallery button to pick audio, use the file button. It's purely a visual change, but IMHO important as the audio picker isn't using the gallery.

Use the file picker button for selectin pre-existing audio clips

---

get_latest/index.html

Title says it all, we know have a working dmg installer to link to.

Add macos to get latest web shortcut

---

src/qml/LayerLoginDialog.qml

[Backport release-2_6] Add appropriate input method flags to the layer login popup's user and password fields

---

src/qml/editorwidgets/DateTime.qml

This fixes https://github.com/opengisch/QField/issues/3892

Fix focus issue when closing date/time panel

---

src/qml/editorwidgets/DateTime.qml

[Backport release-2_6] Fix focus issue when closing date/time panel

---

.github/workflows/code_layout.yml

See https://github.com/opengisch/QField/actions/runs/4232664525 for example of failure.

Ubuntu 18.04 image has been retired, causing failures

---

src/qml/Legend.qml

@m-kuhn , as (brilliantly) suggested.

Implement right-click action on legend items

---

src/qml/Legend.qml

[Backport release-2_6] Implement right-click action on legend items

---

.tx/config

Updated resource identifiers in tx config

---

src/core/qgsquick/qgsquickcoordinatetransformer.cpp

[Backport release-2_6] Try fixing vertical grid paths containing space(s)

---

.github/workflows/sync-translations.yml
.github/workflows/translations.yml
scripts/ci/pull_translations.sh

Removing unnecessary flags from tx pull

---

src/qml/editorwidgets/ExternalResource.qml

Because while it's nice to preview videos within the feature form itself, there's nothing that beats fullscreen video playback :)

Allow opening of video attachment in external editor, restore empty image icon

---

platform/ios/Info.plist.in
src/core/audiorecorder.cpp
src/core/platforms/ios/iosresourcesource.mm
src/qml/QFieldAudioRecorder.qml
src/sentry/sentry_cocoa.mm

Invaluable info coming from sentry, and from our favorite unnamed iOS tester :wink:

iOS microphone and video fixes

---

CMakeLists.txt
src/core/CMakeLists.txt
src/core/appinterface.cpp
src/core/appinterface.h
src/core/platforms/platformutilities.cpp
src/core/utils/ziputils.cpp
src/core/utils/ziputils.h
src/qml/BusyOverlay.qml
src/qml/Changelog.qml
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

[Backport release-2_7] Import from URL action 

---

src/qml/QFieldLocalDataPickerScreen.qml

[Backport release-2_7] Fix missing font declaration for import ULR dialog leading to tiny buttons

---

src/core/platforms/ios/iosplatformutilities.h
src/core/platforms/ios/iosplatformutilities.mm

Shot in the dark (no punt intended).

Implement system dark theme detection on iOS

---

src/core/platforms/ios/iosplatformutilities.h
src/core/platforms/ios/iosplatformutilities.mm

[Backport release-2_7] Implement system dark theme detection on iOS

---

src/core/rubberbandmodel.cpp

[Backport release-2_7] Revert "Absence of data is not 0, use NaN"

---

src/qml/MapCanvas.qml

Related: https://github.com/opengisch/QField/discussions/4040

Give the rotation threshold a higher value

---

src/qml/MapCanvas.qml

[Backport release-2_7] Give the rotation threshold a higher value

---

src/qml/qgismobileapp.qml

If that's the only regression map canvas rotation has led to, I'll be as happy as a  fish in water :wink:

Account for canvas rotation when moving features (fix #4038)

---

src/qml/qgismobileapp.qml

[Backport release-2_7] Account for canvas rotation when moving features (fix #4038)

---

src/core/CMakeLists.txt
src/core/qgismobileapp.cpp
src/core/utils/relationutils.cpp
src/core/utils/relationutils.h
src/qml/editorwidgets/RelationReference.qml

[Backport release-2_7] Fallback when relation id is not set

---

i18n/qfield_ar.ts
i18n/qfield_bg.ts
i18n/qfield_bs.ts
i18n/qfield_cs.ts
i18n/qfield_de.ts
i18n/qfield_en.ts
i18n/qfield_es.ts
i18n/qfield_fi.ts
i18n/qfield_fr.ts
i18n/qfield_gl.ts
i18n/qfield_hr.ts
i18n/qfield_hu.ts
i18n/qfield_id.ts
i18n/qfield_it.ts
i18n/qfield_ja.ts
i18n/qfield_ka.ts
i18n/qfield_ko.ts
i18n/qfield_nl.ts
i18n/qfield_pl.ts
i18n/qfield_pt.ts
i18n/qfield_pt_BR.ts
i18n/qfield_ro.ts
i18n/qfield_ru.ts
i18n/qfield_sl.ts
i18n/qfield_uk.ts
i18n/qfield_zh.ts

Manual `./scripts/ci/pull_translations.sh` run so 2.7.2 can reflect up-to-date translation efforts by the community.

Manual translation pull for 2.7.2

---

vcpkg/overlay/qgis/portfile.cmake
vcpkg/overlay/qgis/sharedmem_ios.patch

[Backport release-2_7] Disable shared mem on iOS

---

src/core/deltafilewrapper.cpp
src/core/layerobserver.cpp
src/core/layerobserver.h

Seems QField sometimes does not know what is the source layer primary key OR source layer id in the deltas, so let's help QField share what is wrong.

Added more detailed logs what is going on when creating deltas

---

src/core/deltafilewrapper.cpp
src/core/layerobserver.cpp
src/core/layerobserver.h

[Backport release-2_7] Added more detailed logs what is going on when creating deltas

---

src/qml/PositioningDeviceSettings.qml
src/qml/QFieldSettings.qml

Fix combobox item icon not following dark theme setting

---

src/core/positioning/bluetoothdevicemodel.cpp
src/core/positioning/bluetoothreceiver.cpp
src/core/positioning/bluetoothreceiver.h

[Backport release-2_7] Greatly imrove bluetooth connection

---

test/nmea_server/nmeaserver.py

Script updated so the TCP server doesn't die after a client terminates the connection; makes it a lot easier to test things out without having to restart the server all, the, time.
Also moved things around a bit on the UDP server side to harmonize code part across TCP and UDP.

Improvements to the nmeaserver.py script

---

src/core/sensorlistmodel.cpp

Fix crash on QField exit

---

src/qml/RelationCombobox.qml

[Backport release-2_7] Fix relation combobox add button's icon dark theme color

---

src/qml/editorwidgets/DateTime.qml
src/qml/editorwidgets/ExternalResource.qml

Extracting what's good out of https://github.com/opengisch/QField/pull/4123
The DateTime editor widget change is less scary than it looks, it's mostly indentation reformatting.

A few micro optimization for the feature form

---

src/qml/editorwidgets/ValueRelation.qml

Fix multi-select value relation editor widget with dark theme

---

src/qml/FeatureForm.qml

Fix header bar title overflowing into form when adding features

---

src/qml/qgismobileapp.qml

[Backport release-2_7] Fix follow orientation math to avoid a refresh on every minor compass value change

---

src/qml/FeatureForm.qml

[Backport release-2_7] Fix header bar title overflowing into form when adding features

---

src/qml/editorwidgets/ValueRelation.qml

[Backport release-2_7] Fix multi-select value relation editor widget with dark theme

---

src/qml/LocationMarker.qml

That bugged me for way too long.

Fix location movement marker not centered when rotated

---

src/qml/LocationMarker.qml

[Backport release-2_7] Fix location movement marker not centered when rotated

---

src/core/attributeformmodelbase.cpp
src/core/featuremodel.cpp
src/core/featuremodel.h

Well, I'm shocked this wasn't causing more issue reports so far.

Insure that the attribute form has all the context needed to generate default values

---

CMakeLists.txt

What are the chances this will work on first try?

Up vcpkg (gdal 3.6.3, sqlite 3.40.1, proj 9.2, etc.)

---

src/core/attributeformmodelbase.cpp
src/core/featuremodel.cpp
src/core/featuremodel.h

[Backport release-2_7] Insure that the attribute form has all the context needed to generate default values

---

src/qml/FeatureForm.qml

This is not as much an optimization as moving some CPU cost around.

Feature form optimization

---

src/qml/FeatureForm.qml

[Backport release-2_7] Feature form optimization

---

src/core/layertreemodel.cpp
src/core/sensorlistmodel.cpp
src/core/sensorlistmodel.h
src/core/tracker.cpp
src/qml/LayerTreeItemProperties.qml

Fixes some really odd behavior when tracking against point layers.

A few tracker-related fixes and optimization

---

src/core/layertreemodel.cpp
src/qml/LayerTreeItemProperties.qml

Cherry-picked relevant 2.7 commits from #4158 .

[backport release-2_7] Layer tree fixes

---

src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h

[Backport release-2_7] Fix rubber band model wrongly added M dimension when we want Z

---

src/core/qgismobileapp.cpp
src/core/recentprojectlistmodel.cpp

Fixes https://github.com/opengisch/QField/issues/4174

Avoid re-adding the sample projects to recent projects all the time

---

src/core/snappingresult.cpp
src/core/snappingresult.h

Ref: https://opengisch.sentry.io/issues/4091272718/?project=6119013&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=2

Store snapped vector layer as a QPointer<QgsVectorLayer>

---

src/qml/qgismobileapp.qml

@m-kuhn , as discussed with Nathan.

Do not assume that the map canvas fills the whole screen when handling follow location maths

---

src/qml/qgismobileapp.qml

[Backport release-2_7] Do not assume that the map canvas fills the whole screen when handling follow location maths

---

src/core/layerobserver.cpp

Possible fix to https://github.com/opengisch/QField/issues/4195

Remove offending qInfo()

---

src/qml/QFieldLocalDataPickerScreen.qml

When re-opening the import URL dialog, clear previous URL

---

src/qml/DigitizingToolbar.qml

**The problem**
When someone clicks on the digitizing toolbar's "accept" green (check) button, a vertex is added prior to finalizing the geometry. That happens to make for a better UX as it saves time avoiding the need to click on add vertex (plus) button followed by an immediate  click on the accept button upon digitizing the last vertex.
That accept button has currently no notion of averaged positioning requirement, and ATM adds a vertex no matter what. This is a problem for surveyors who have activated minimum avg. positioning count requirement.
**The possible solutions**
a/ we add a level of complexity to the code and have the accept button also trigger an avg. positioning vertex capture; it becomes complex as you need to handle long-press, press and release with auto terminate …

Insure a non-averaged position vertex is added when accepting geometry upon hitting the accept/confirm button

---

src/core/expressionevaluator.cpp
src/qml/editorwidgets/ExternalResource.qml

[Backport release-2_7] Add a fallback to old photo_naming key when fetching attachment file path expression

---

src/qml/About.qml
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/MessageLog.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/QFieldCloudScreen.qml
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/QFieldSettings.qml
src/qml/WelcomeScreen.qml
src/qml/qgismobileapp.qml

Manual backport of scene bottom margin improvements (i.e. avoid overlap with iOS navigation bar)

[Backport release-2_7] Bottom margin improvements

---

src/qml/QFieldLocalDataPickerScreen.qml

[Backport release-2_7] When re-opening the import URL dialog, clear previous URL

---

src/core/layerobserver.cpp

[Backport release-2_7] Remove offending qInfo()

---

src/core/qgismobileapp.cpp

[Backport release-2_7] Handle detection of mixed geometry sublayers in KML/geojson/etc.

---

src/qml/DigitizingToolbar.qml

[Backport release-2_7] Insure a non-averaged position vertex is added when accepting geometry upon hitting the accept/confirm button

---

src/core/positioning/bluetoothdevicemodel.cpp
src/core/positioning/bluetoothdevicemodel.h

Delay creation of the bluetooth discovery agent until we need it

---

src/core/positioning/bluetoothdevicemodel.cpp
src/core/positioning/bluetoothdevicemodel.h

[Backport release-2_7] Delay creation of the bluetooth discovery agent until we need it

---

src/core/CMakeLists.txt
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/android/androidprojectsource.cpp
src/core/platforms/android/androidprojectsource.h
src/core/platforms/android/androidresourcesource.cpp
src/core/platforms/android/androidresourcesource.h
src/core/platforms/android/androidviewstatus.cpp
src/core/platforms/android/androidviewstatus.h
src/service/CMakeLists.txt
src/service/qfieldservice.cpp
src/service/qfieldservice.h

Extracting what I can from https://github.com/opengisch/QField/pull/4229 as we go along.

QField Android Qt6 support in src/core and src/service

---

src/core/utils/relationutils.cpp

Fixes https://opengisch.sentry.io/issues/4040693241/?project=6119013&query=is%3Aunresolved&referrer=issue-stream&stream_index=3

Add a check for a valid layer

---

src/core/utils/relationutils.cpp

[Backport release-2_7] Add a check for a valid layer

---

scripts/build.sh

One more bit taken out of https://github.com/opengisch/QField/pull/4229.

Make docker building cancelable

---

src/core/featuremodel.cpp

This PR fixes an important UX in our handling of newly created features. 
Until now, when users were digitizing a new feature, we would end up resetting attributes (inc. calculating default values) *twice*:
- Once (FeatureForm::resetAttributes) when clicking on the "OK" button in the digitizing toolbar as we are showing feature form; and
- Once more (QgsVectorLayerUtils::createFeature in FeatureForm::create) when actually saving the feature when clicking on the "OK" button in the feature form header bar.
This was bad for a few reasons:
- Any value change made by users for an attribute that had a default value (not set to update on feature change) would be silently overwritten.;
- The second feature reset was missing a bunch of important expression contexts (positioning, QFieldCloud, etc.) …

Only reset attributes once in feature model when creating a new feature

---

platform/linux/AppRun
platform/linux/CPackLinuxDeployQt.cmake.in
platform/linux/qfield.desktop

Fixes https://github.com/opengisch/QField/pull/4225

Specify reasonable default fonts path

---

src/qml/editorwidgets/CheckBox.qml

[Backport release-2_8] Fix checkbox editor widget losing binding to value (fixes #4287)

---

.github/workflows/android.yml
platform/android/build.gradle.in
platform/android/gradle/wrapper/gradle-wrapper.properties
src/qml/MapCanvas.qml
src/qml/qgismobileapp.qml

Free ourselves from the insanity-inducing taphandler to handle main taps/clicks

---

images/images.qrc
images/themes/qfield/nodpi/ic_add_black_24dp.svg
images/themes/qfield/nodpi/ic_remove_black_24dp.svg
src/qml/FeatureForm.qml
src/qml/editorwidgets/Range.qml

(Ref.: https://www.google.com/url?sa=j&url=https%3A%2F%2Fopengisch.sentry.io%2Fissues%2F4196539185%2F%3Fproject%3D6119013%26query%3D%26referrer%3Dissue-stream%26statsPeriod%3D1h%26stream_index%3D0&uct=1645670830&usg=RB41fW9e_pNkNvuGC-JywKX_vng.&source=chat)

Fix Qt6 crash when toggling feature form container visibility

---

src/core/utils/snappingutils.cpp
src/core/utils/snappingutils.h
src/qml/CoordinateLocator.qml
src/qml/editorwidgets/TextEdit.qml

[Backport master] Avoid at times tremendous cost of snapping when cursor is not visible

---

src/core/CMakeLists.txt
src/core/qgismobileapp.cpp
src/qml/qgismobileapp.qml

Title says it all :partying_face:

Print to PDF on iOS now that we can!

---

src/core/utils/relationutils.cpp

Attempt at fixing https://github.com/opengisch/QField/issues/4278

Fix crash when QField exits with an open feature form containing relationships

---

src/qml/BadLayerItem.qml
src/qml/QFieldSettings.qml

[Backport release-2_8] More bottom margins improvements

---

platform/android/AndroidManifest.xml.in
src/core/qgismobileapp.h

No actual work needed to unlock this, merely adding the extension into our lists of supported datasets.

Add mbtiles in the list of supported individual datasets

---

platform/android/AndroidManifest.xml.in
src/core/qgismobileapp.h

[Backport release-2_8] Add mbtiles in the list of supported individual datasets

---

src/core/bookmarkmodel.cpp
src/core/bookmarkmodel.h
src/qml/QFieldLocalDataPickerScreen.qml

[Backport release-2_8] Fix copying bookmark details into clipboard

---

src/core/utils/positioningutils.cpp
src/core/utils/positioningutils.h
src/qml/PositioningPreciseView.qml
src/qml/qgismobileapp.qml

Because up is not always north:
https://github.com/opengisch/QField/assets/1728657/3d0aa350-ba16-4024-812e-c0da7c87366d

Insure that our compass points to true north, not the grid north

---

.github/workflows/android.yml

@m-kuhn , I had fixed commit comments, not PR comments. Oups.

Fix auto-generated pull request comment's arm-neon APK links

---

src/core/utils/positioningutils.cpp
src/core/utils/positioningutils.h
src/qml/PositioningPreciseView.qml
src/qml/qgismobileapp.qml

Manual backport of https://github.com/opengisch/QField/pull/4377

[backport release-2_8] Insure that our compass points to true north, not the grid north

---

src/core/attributeformmodelbase.cpp
src/core/attributeformmodelbase.h

@lindacamathias , et voila. It should be _muuuch_ faster!

Attribute form optimization, handling of  field present in multiple tabs

---

src/qml/editorwidgets/CheckBox.qml

[Backport release-2_8] Fix checkbox editor widget value comparison

---

CMakeLists.txt
src/app/main.cpp

[Backport release-2_8] Package CAs for curl

---

src/qml/FeatureListForm.qml
src/qml/Legend.qml
src/qml/NavigationBar.qml

Fixes https://github.com/opengisch/QField/issues/4421

Allow stealing from mousearea to fix regression

---

src/core/multifeaturelistmodel.cpp

[Backport release-2_8] Fix the show visible feature(s) action with reprojected layers

---

doc/dev.md

Add a few extra Ubuntu dependencies and improve pastability of a command

---

src/core/projectinfo.cpp
src/core/projectinfo.h
src/qml/Legend.qml
src/qml/qgismobileapp.qml

Some cleanups in preparation for snapping work coming in the very near future.

ProjectInfo class cleanup and optimization

---

src/qml/LayerTreeItemProperties.qml
src/qml/Legend.qml
src/qml/imports/Theme/Theme.qml

This PR refactors the legend to allows for its badges to respond to taps. More preparatory work for snapping improvements.
(it temporarily includes https://github.com/opengisch/QField/pull/4471)

Legend badge actions + dark theme support

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp

Significant leak plugged, brought to you by a joint @m-kuhn @nirvn session.

Plug those map canvas leaks

---

.github/workflows/ios.yml
.github/workflows/macos.yml

[Backport release-2_8] Upgrade import-codesign-certs to v2

---

src/qml/qgismobileapp.qml

This PR addresses the last known Qt6 regression (did I just use that same formula a week ago? :wink:) whereas the hoverhandler for the stylus and mouse is wrongly triggered by taps on the screen.
What was happening here is that the Qt5 hack to use a Timer would not work anymore and as soon as the 750ms timer would set the isBeingTouched property to false, the stylus hoverhandler would activate.
The new implementation here is a lot more robust, and doesn't go through a shaky Timer.

Implement a more robust hover skipping when tapping the screen 

---

.docker/android_dev/Dockerfile

Forgot to update this when upgrading our various builds to 6.5.2.

Fix local docker android builds

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp

[Backport release-2_8] Plug those map canvas leaks

---

src/core/qgssggeometry.cpp
src/core/sgrubberband.cpp

[Backport release-2_8] Buffer polygons prior to passing them to QgsTessellator to fix crashes

---

src/qml/QFieldSettings.qml

try to make clear that antenna height setting is pole + phase centre.

better antenna height text

---

i18n/qfield_ar.ts
i18n/qfield_bg.ts
i18n/qfield_bs.ts
i18n/qfield_cs.ts
i18n/qfield_de.ts
i18n/qfield_en.ts
i18n/qfield_es.ts
i18n/qfield_fi.ts
i18n/qfield_fr.ts
i18n/qfield_gl.ts
i18n/qfield_hr.ts
i18n/qfield_hu.ts
i18n/qfield_id.ts
i18n/qfield_it.ts
i18n/qfield_ja.ts
i18n/qfield_ka.ts
i18n/qfield_ko.ts
i18n/qfield_nl.ts
i18n/qfield_pl.ts
i18n/qfield_pt.ts
i18n/qfield_pt_BR.ts
i18n/qfield_ro.ts
i18n/qfield_ru.ts
i18n/qfield_sl.ts
i18n/qfield_tr.ts
i18n/qfield_uk.ts
i18n/qfield_zh.ts

That'll resurrect a fair amount of strings on top of what we're looking for.

Vanished, come back to life

---

src/qml/WelcomeScreen.qml

|-|-|
| ![Peek 2023-08-20 13-29](https://github.com/opengisch/QField/assets/2820439/fbb1e542-350f-4990-a7e4-c63142a353d4) | ![Peek 2023-08-20 13-27](https://github.com/opengisch/QField/assets/2820439/382b8da3-3e98-48ee-a42e-e88df61d2089) |

Fix back button on welcome screen when no project is opened

---

platform/android/res/values/strings.xml
platform/android/src/ch/opengis/qfield/QFieldActivity.java

[Backport release-2_8] Catch missing android activity and inform users instead of crashing

---

src/core/qgssggeometry.cpp
src/core/sgrubberband.cpp

Fixes https://opengisch.sentry.io/issues/4355284062/?project=6119013&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

Fix crash when preparing/buffering a polygon fails prior to tessellation

---

src/core/qgssggeometry.cpp
src/core/sgrubberband.cpp

[Backport release-2_8] Fix crash when preparing/buffering a polygon fails prior to tessellation

---

src/qml/editorwidgets/TextEdit.qml

Fixes https://github.com/opengisch/QField/issues/4510 .

Fix bad padding for multiline text edit widget on Qt6

---

src/qml/LocatorItem.qml

Stumbled on this while doing screenshots for the QR code scanner documentation.

Fix clipped icons for the locator item actions

---

src/qml/editorwidgets/+Qt6/ExternalResource.qml

Two reasons why we want to do this:
a/ prevent Video[Output] crashers on @lindacamathias 's Samsung S10 device 
b/ speed up loading of feature form by deferring cost of Video[Output] initialization
@m-kuhn , as discussed, this is the last blocker for a 3.0. With that in, sample bees will not crash.

Defer loading of external resource editor widget Video item until we actually need it

---

src/core/attributeformmodelbase.cpp

@lindacamathias , orange badge resurrected.

Fix soft constraint check typo

---

scripts/build-for-linux.sh

- Install to user
- Run from user
- Fail on error

Improve build for linux script

---

src/qml/LocationMarker.qml

Tiny tweaks to make things look better.

Improve location marker color handling following rework of compass indicator

---

src/qml/editorwidgets/Range.qml

@mbernasocchi , @itsakifa , ping.

Better default slider position for null values in the range slider editor widget

---

.docker/android_dev/Dockerfile
.github/workflows/android.yml
.github/workflows/ios.yml
.github/workflows/linux.yml
scripts/build-for-linux.sh
scripts/build-vcpkg.sh
src/core/qgismobileapp.cpp
src/qml/About.qml

Bye bye camera crash on Android.

Update Qt to 6.5.3

---

src/core/locator/activelayerfeatureslocatorfilter.cpp
src/qml/DashBoard.qml

Because digitizing is precious.

Avoid accidentally losing a feature being digitized hitting the browse/digitize toggle

---

src/core/qgssggeometry.cpp

This PR fixes missing inner ring outlines when highlighting polygons.
With this PR, you can see the inner ring of the highlighted polygon properly gets a bright yellow outline:
I've taken the time to de-duplicate the code between multipart and singlepart polygon handling.

Fix missing inner ring outlines when highlighting polygons

---

src/qml/qgismobileapp.qml

Some more field testing of 3.0; turns out the stylus improvements (working around poor Qt handling) went a bit too far when it comes to blocking stylus map canvas action when the feature form is opened.
Long story short, we ended up blocking all stylus (and by default mouse :scream:) map canvas actions when we should only block those overlapping the feature form itself. Without this PR, we can't identify features when the feature form is opened for e.g., which is bad! :)

Do not block all stylus-driven map canvas click when feature form is visible, only block those falling under the feature form

---

src/core/linepolygonhighlight.cpp
src/core/linepolygonhighlight.h
src/core/rubberband.cpp
src/core/rubberband.h

[Backport release-3_0] Significant optimization in handling of rubber band and line/polygon items

---

src/qml/qgismobileapp.qml

[Backport release-3_0] Do not block all stylus-driven map canvas click when feature form is visible, only block those falling under the feature form

---

src/core/qgssggeometry.cpp

[Backport release-3_0] Fix missing inner ring outlines when highlighting polygons

---

src/core/utils/stringutils.cpp
src/core/utils/stringutils.h
src/qml/editorwidgets/TextEdit.qml

[Backport release-3_0] Fix handling of non-HTML text values having had links inserted (fixes #4615)

---

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp
src/core/qgsquick/qgsquickmapcanvasmap.cpp

[Backport release-3_0] Use screen's physical DPI value again, android regression fixed in Qt 6.5.3

---

src/qml/BrowserPanel.qml
src/qml/qgismobileapp.qml

[Backport release-3_0] Clear WebView's cache on Android to avoid interference with authentication methods

---

.github/workflows/ios.yml

[Backport release-3_0] Fix iOS release

---

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

[Backport release-3_0] Fix setting an int property to a string value breaks children deletion

---

src/qml/FeatureForm.qml

[Backport release-3_0] Re-add background rectangle to deal with (now rare but still present) Qt flow glitches

---

src/qml/imports/QFieldControls/+Qt6/CalendarPanel.qml

Fixes https://github.com/opengisch/QField/issues/4650 .

Fix calendar popup's {previous,next} {month,year} buttons on Qt6

---

src/qml/imports/QFieldControls/+Qt6/CalendarPanel.qml

[Backport release-3_0] Fix calendar popup's {previous,next} {month,year} buttons on Qt6

---

src/core/identifytool.cpp
src/qml/qgismobileapp.qml

[Backport release-3_0] Revert increased identify search radius now that Qt6 DPI issue is resolved

---

resources/sample_projects/live_qfield_users_survey.qgs
src/core/qgismobileapp.cpp

Fixes https://github.com/opengisch/QField/issues/4656

Use the preferred openstreetmap URL to improve performance and caching

---

resources/sample_projects/live_qfield_users_survey.qgs
src/core/qgismobileapp.cpp

[Backport release-3_0] Use the preferred openstreetmap URL to improve performance and caching

---

src/core/qfieldcloudconnection.cpp

@mbernasocchi , @suricactus , as discussed.

Fix wrong user/password state misrepresented as expired session

---

src/core/qfieldcloudconnection.cpp

[Backport release-3_0] Fix wrong user/password state misrepresented as expired session

---

src/qml/geometryeditors/FillRing.qml

Fixes https://github.com/opengisch/QField/issues/4663 -- Qt6 isn't tolerant of stupid mistakes, nice! :)

Fix initiation of fill ring geometry editor, Qt6 isn't tolerant

---

.github/workflows/android.yml

[Backport release-3_0] Fix missing debug symbols on sentry

---

src/core/layertreemapcanvasbridge.cpp
src/core/rubberbandmodel.cpp
src/qml/LayerTreeItemProperties.qml

One crasher (:fearful:) and one vertex data loss (:fearful:) fixed (:partying_face:).

Tracker fixes

---

src/core/layertreemapcanvasbridge.cpp
src/core/rubberbandmodel.cpp
src/qml/LayerTreeItemProperties.qml

[Backport release-3_0] Tracker fixes

---

src/core/linepolygonhighlight.cpp
src/core/rubberband.cpp

[Backport release-3_0] Fix rubber band display 'glitchy' following optimization

---

src/core/qgssggeometry.cpp
src/core/sgrubberband.cpp

[Backport release-3_0] Fix rubber band polygon highlight going missing due to coordinate distance fail

---

src/core/qgismobileapp.cpp
vcpkg/overlay/qgis-qt6/portfile.cmake
vcpkg/overlay/qgis-qt6/project_load.patch

Fixes https://github.com/opengisch/QField/issues/4669 
@m-kuhn , as discussed throughout the day :)

Project load fix undet Qt6 builds

---

CMakeLists.txt

[Backport release-3_0] Update app icon

---

src/core/qgismobileapp.cpp
vcpkg/overlay/qgis-qt6/portfile.cmake
vcpkg/overlay/qgis-qt6/project_load.patch

[Backport release-3_0] Project load fix undet Qt6 builds

---

src/core/distancearea.cpp
src/core/locator/activelayerfeatureslocatorfilter.cpp
src/core/locator/bookmarklocatorfilter.cpp
src/core/locator/expressioncalculatorlocatorfilter.cpp
src/core/locator/featureslocatorfilter.cpp
src/core/locator/gotolocatorfilter.cpp
src/core/qfieldcloudprojectsmodel.cpp
vcpkg/overlay/qgis-qt6/exif_orientation_fix.patch
vcpkg/overlay/qgis-qt6/portfile.cmake

[Backport release-3_0] Fix problematic image orientation when maximum image size is enabled

---

src/qml/FeatureForm.qml

Fix HTML widget not loading anymore

---

src/qml/FeatureForm.qml

[Backport release-3_0] Fix HTML widget not loading anymore

---

src/core/linepolygonhighlight.cpp
src/core/qgismobileapp.cpp

[Backport release-3_0] Be nice, don't touch customized flat terrain provider, users wanted it that way

---

.github/workflows/android.yml
.github/workflows/ios.yml
.github/workflows/linux.yml

[Backport release-3_0] Add qimageformats plugin to allow for tiff WMS layers

---

src/qml/imports/QFieldControls/+Qt6/CalendarPanel.qml

Fixes https://github.com/opengisch/QField/issues/4720 as well as dark theme compatibility.

Fix calendar panel not dark theme friendly and won't open to set date

---

src/qml/QFieldLocalDataPickerScreen.qml
src/qml/imports/QFieldControls/+Qt6/CodeReader.qml
src/qml/qgismobileapp.qml

Takes care of a few warnings on launch, spotted while looking at Sentry.

Fix a bunch of QML warnings

---

src/core/qgssggeometry.cpp
src/core/sgrubberband.cpp

[Backport release-3_0] Revert geometry/rubberband item's buffer parameter change

---

platform/linux/qfield.metainfo.xml

See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html\#tag-id-generic

Fix AppStream ID

---

src/core/utils/featureutils.cpp

Note to self: do not do testing with cheap non-high dpi smartphones.

Fix view parent/children feature panning/zooming on high dpi screens

---

src/qml/DashBoard.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/QFieldLocalDataPickerScreen.qml

Well, it would not be me if I don't fix a few warnings :)

Silent material warnings

---

src/qml/FeatureForm.qml

Fixes https://github.com/opengisch/QField/issues/4366

[Backport release-3_0] One more swing at fixing the HTML editor widget

---

src/core/utils/featureutils.cpp

[Backport release-3_0] Fix view parent/children feature panning/zooming on high dpi screens

---

.github/workflows/macos.yml
scripts/ci/env_gh.sh

Forward port of release fixes from release-3_0 branch

Release fixes

---

src/qml/FeatureListForm.qml
src/qml/qgismobileapp.qml

ApplicationWindow.overlay ain't a thing anymore on Qt6

---

src/qml/RelationCombobox.qml

@lindacamathias , this should make your client happy :wink:

Additional fix to insure the value relation autocompleter resets when return key triggered match fails

---

src/qml/qgismobileapp.qml

Glad we haven't shipped 3.1 with that.

Fix rendering of rotated digitizing rubberband (anchors == death)

---

CMakeLists.txt
cmake/qgis-cmake-wrapper.cmake

Catching up to this point: https://github.com/microsoft/vcpkg/commit/18368dba5b9cab3e4cf7643f2a640058bb450bed

Update vcpkg revision to catch 6.6.1 on windows, macos

---

src/qml/FeatureListForm.qml
src/qml/OverlayFeatureFormDrawer.qml

[Backport release-3_1] Harmonize and increase width of feature addition/view form

---

.docker/android_dev/Dockerfile
.github/workflows/android.yml
cmake/Platform.cmake
scripts/build-vcpkg.sh

[Backport release-3_1] Update Android NDK (r25) to match what is used in pre-built Qt libraries

---

.github/workflows/macos.yml

[Backport release-3_1] Switch ci to macos-12

---

.github/workflows/android.yml
platform/android/build.gradle.in

[Backport release-3_1] Sentry update

---

src/core/positioning/bluetoothdevicemodel.cpp
src/core/positioning/bluetoothreceiver.cpp
src/core/positioning/internalgnssreceiver.cpp

[Backport release-3_1] Guard against null object when checking permissions

---

src/qml/qgismobileapp.qml

[Backport release-3_1] Fix confusing 'snap to 45 degree' toast when opening QField

---

src/core/barcodedecoder.cpp

[Backport release-3_1] Add an additional safeguard when the barcode decoder attempts to process a video frame

---

src/core/projectinfo.cpp
src/core/projectinfo.h
src/qml/Legend.qml
src/qml/qgismobileapp.qml

[Backport release-3_1] Fix significant issues with saving/restoring customized project settings

---

src/core/qgismobileapp.cpp
src/core/qgismobileapp.h

[Backport release-3_1] Play it safe, use a QPointer to the map canvas item to reduce risks of crash

---

src/qml/MapCanvas.qml
src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml
src/qml/qgismobileapp.qml

[Backport release-3_1] Further strenghten finger hovering protection

---

src/qml/LinePolygon.qml

Why do we love making screencasts? Bugs are found!

Fix lingering artifact when clearing navigation destination

---

src/qml/LinePolygon.qml

[Backport release-3_1] Fix lingering artifact when clearing navigation destination

---

src/qml/CoordinateLocator.qml

[Backport release-3_1] Fix coordinate cursor locked to position not sticking to position

---

src/qml/DigitizingToolbar.qml
src/qml/geometryeditors/VertexEditor.qml
src/qml/qgismobileapp.qml

@lindacamathias , that should do it.

Fix toggling of geometry editor type using the stylus

---

src/qml/DigitizingToolbar.qml
src/qml/geometryeditors/VertexEditor.qml
src/qml/qgismobileapp.qml

[Backport release-3_1] Fix toggling of geometry editor type using the stylus

---

.github/workflows/android.yml

Small follow up to https://github.com/opengisch/QField/pull/4898

Re-add x86 APK in comment, fix deployment to google play store

---

scripts/build-for-linux.sh

Deferring linux workflow for now

Switch local linux build script to building Qt

---

src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h
src/core/rubberbandshape.cpp

The removed method might raise questions, feel free to revert if I misunderstood it's usage and purpose.

Add docs to all public methods and properties of `RubberbandModel`

---

src/core/changelogcontents.cpp

[Backport release-3_1] Implement a mean to filter out platform-specific parts of release changelogs

---

.github/workflows/macos.yml

Should fix https://github.com/opengisch/QField/issues/4932

Fix macos release asset upload

---

.github/workflows/macos.yml

[Backport release-3_1] Fix macos release asset upload

---

.github/workflows/windows.yml

[Backport release-3_1] Disable ccache for windows

---

src/qml/imports/Theme/QfToolButton.qml

[Backport release-3_1] Fix handling of ripple effect on tool buttons in dark mode

---

.docker/android_dev/Dockerfile
platform/android/res/values/strings.xml
platform/android/src/ch/opengis/qfield/QFieldActivity.java
src/core/appinterface.cpp
src/core/platforms/android/androidplatformutilities.cpp
src/core/platforms/android/androidplatformutilities.h
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/qgismobileapp.cpp

Trying to get us below the acceptable ANR rate on play store. Bonus: people will see a progress bar instead of a frozen app :wink:
Tested, we can nice indeterminate progress bar when importing 50mb geotiffs instead of a frozen app.

Android freeze fix

---

src/core/attributeformmodelbase.cpp

This PR fixes https://github.com/opengisch/QField/issues/4855

Fix typo in field expression-based constraint update logic

---

src/core/attributeformmodelbase.cpp

[Backport release-3_1] Fix typo in field expression-based constraint update logic

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java

@m-kuhn , thanks for spotting this one.

Fix crash when sending dataset which include sidecar files

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java

[Backport release-3_1] Fix crash when sending dataset which include sidecar files

---

src/core/layertreemodel.cpp
src/core/layertreemodel.h
src/core/qgismobileapp.cpp
src/qml/qgismobileapp.qml

[Backport release-3_1] When opening or reloading a project, clear the previous one to empty the layer tree

---

.github/workflows/sync-translations.yml
.github/workflows/translations.yml

Fixes https://github.com/opengisch/QField/issues/4953

We're missing translation, update workflows to ubuntu to 22.04 to catch Qt 5.15 tools

---

src/core/qgismobileapp.cpp

[Backport release-3_1] Clear project in readProjectFile to avoid threading issues

---

src/core/qfieldcloudprojectsmodel.cpp

Together with https://github.com/opengisch/qfieldcloud/pull/854 will make the localized datasets experience finally fully integrated.

If a layer is detected as localized by QFC, do not show QFC error panel

---

src/core/qgismobileapp.cpp

[Backport release-3_1] Clear project on exit instead of only removing all layers

---

src/qml/LayerTreeItemProperties.qml

[Backport release-3_1] Be cool, just activate positioning instead of hiding the tracker button

---

src/qml/editorwidgets/CheckBox.qml

@lucienicolier , fixes checkbox issue raised by IG group.

Fix custom checked/unchecked state values matching for checkbox editor widget

---

src/qml/editorwidgets/CheckBox.qml

[Backport release-3_1] Fix custom checked/unchecked state values matching for checkbox editor widget

---

src/app/main.cpp
src/core/featurelistmodel.cpp
src/core/fieldexpressionvaluesgatherer.h

[Backport release-3_1] Initiate expression context when gathering feature lists

---

src/core/positioning/tcpreceiver.cpp

Fixes https://github.com/opengisch/QField/issues/4981

Let's unlock gpsd support in our TCP receiver in 3 lines

---

src/core/navigation.cpp
src/core/navigationmodel.cpp
src/core/qgismobileapp.cpp
src/qml/WelcomeScreen.qml
src/qml/qgismobileapp.qml

[Backport release-3_1] Write settings to permanent storage when OS or user force kills app

---

src/core/locator/activelayerfeatureslocatorfilter.cpp
src/core/locator/bookmarklocatorfilter.cpp
src/core/locator/expressioncalculatorlocatorfilter.cpp
src/core/locator/featureslocatorfilter.cpp
src/core/locator/gotolocatorfilter.cpp

Fix compilation against upcoming QGIS 3.36.1

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
scripts/vcpkg-format.py
vcpkg.json
vcpkg/ports/qca/vcpkg.json
vcpkg/ports/qgis/vcpkg.json
vcpkg/ports/sentry-cocoa/vcpkg.json

Format vcpkg manifest files

---

doc/dev.md

Incorporates updates from https://github.com/opengisch/QField/pull/5016 and other targets

Update development documentation

---

src/core/peliasgeocoder.cpp

[Backport release-3_2] Fix build against QGIS master

---

src/qml/Changelog.qml
src/qml/FeatureForm.qml
src/qml/QFieldCloudLogin.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldSettings.qml
src/qml/editorwidgets/TextEdit.qml

Make all `onLinkActivated` proper functions with parameters

---

src/core/utils/fileutils.cpp

PR fixes https://github.com/opengisch/QField/issues/5093 .

Fix type leading to erroneous geotagging (fixes #5093)

---

src/core/utils/fileutils.cpp

[Backport release-3_2] Fix type leading to erroneous geotagging (fixes #5093)

---

src/core/qfieldcloudprojectsmodel.cpp
src/qml/QFieldCloudPopup.qml

[Backport release-3_2] Fix autopush timer interval value

---

.github/workflows/windows.yml

Has Qt6 improved the situation there?

Try enabling Bluetooth on Windows

---

.github/workflows/windows.yml

[Backport release-3_2] Try enabling Bluetooth on Windows

---

src/core/featurechecklistmodel.cpp

Fixes https://github.com/opengisch/QField/issues/5110

Fix handling of empty string in the value relation editor widget

---

src/core/featurechecklistmodel.cpp

[Backport release-3_2] Fix handling of empty string in the value relation editor widget

---

src/qml/qgismobileapp.qml

[Backport release-3_2] Do not disable stylus hovering when mouse acts as touchscreen

---

src/core/deltalistmodel.cpp
src/core/deltalistmodel.h
src/qml/QFieldCloudDeltaHistory.qml

[Backport release-3_2] Fix changes list popup looking broken when empty

---

src/core/qfieldcloudconnection.cpp

[Backport release-3_2] Strip HTML when receiving HTML server errors in cloud API

---

src/qml/DashBoard.qml
src/qml/QFieldCloudPopup.qml

before:
[Screencast from 2024-03-22 05-07-43.webm](https://github.com/opengisch/QField/assets/2820439/f5138825-ce06-4ace-a365-5cb73e77954a) 
after:
[Screencast from 2024-03-22 05-03-24.webm](https://github.com/opengisch/QField/assets/2820439/3e199bf5-3baf-4264-b955-899fafba391a)

When a project is open and user logouts, they can no longer login

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/utils/fileutils.h
test/test_deltafilewrapper.cpp

[Backport release-3_2] Performance boost when downloading packages

---

src/qml/BusyOverlay.qml

[Backport release-3_2] Add a shield/background to the busy indicator message to increase readability

---

src/qml/PositioningInformationView.qml

[Backport release-3_2] Insure that the positioning information panel respects project distance unit type for altitude and accuracy

---

src/core/deltafilewrapper.cpp

[Backport release-3_2] Prevent deltas having empty strings as WKT geometry

---

.github/workflows/android.yml

10 sec instead of 2 minutes over here is *lovely*.

Speed up downoad of APKs by a lot (thanks @m-kuhn!)

---

test/spix/smoke_test.py

Unfortunately, it's only working around the mystery, but I can't figure it out ATM :/

Fix linux CI red state

---

.github/workflows/android.yml
.github/workflows/ios.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
test/spix/smoke_test.py

[Backport release-3_2] Pin cmake version to 3.29.0

---

vcpkg/ports/liblzma/add_support_ios.patch
vcpkg/ports/liblzma/build-tools.patch
vcpkg/ports/liblzma/fix_config_include.patch
vcpkg/ports/liblzma/portfile.cmake
vcpkg/ports/liblzma/usage
vcpkg/ports/liblzma/vcpkg-cmake-wrapper.cmake
vcpkg/ports/liblzma/vcpkg.json
vcpkg/ports/liblzma/win_output_name.patch

[Backport release-3_2] [liblzma] Switch to active repo, uncompromised version

---

src/core/drawingcanvas.cpp
src/qml/DashBoard.qml
src/qml/MapCanvas.qml
src/qml/QFieldSketcher.qml
src/qml/qgismobileapp.qml

@domi4484 , aimed at fixing what you spotted.

Refinements to improved map canvas handlers

---

src/qml/NavigationInformationView.qml
src/qml/PositioningPreciseView.qml
src/qml/qgismobileapp.qml

[Backport release-3_2] Insure that the navigation information and position precise view panels respect the project's distance unit

---

src/qml/BadLayerItem.qml
src/qml/CodeReader.qml
src/qml/PositioningSettings.qml
src/qml/QFieldCamera.qml
src/qml/QFieldCloudDeltaHistory.qml
src/qml/QFieldSettings.qml
src/qml/QFieldSketcher.qml
src/qml/WelcomeScreen.qml
src/qml/qgismobileapp.qml

Console is now QML warning-free. They were all harmless, but they were lowering impact of new warning being introduced by new code, some of which might actually be harmful in the future.
It also makes sentry logs cleaner. Win-win.

Takes care of all remaining harmless warnings

---

src/qml/FeatureForm.qml

@domi4484 , as spotted by your keen eyes ;)

Fix right margin of the feature form

---

src/qml/PluginManagerSettings.qml

Add warning about the self-identified nature of authorship

---

platform/android/src/ch/opengis/qfield/QFieldActivity.java

@itsakifa , this will do the trick :)

Insure a plugins directory is created in Android's data directory

---

src/qml/WelcomeScreen.qml
vcpkg.json

Quality of life fix for windows and linux users.

Fix mouse wheel scrolling not working on recent projects area

---

src/qml/TrackerSettings.qml

PR fixes https://github.com/opengisch/QField/issues/5253 (master only)

Fix project tracker regression (fixes #228)

---

src/qml/InformationDrawer.qml
src/qml/NavigatingDrawer.qml
src/qml/NavigationInformationView.qml
src/qml/PositioningInformationView.qml
src/qml/PositioningPreciseView.qml
src/qml/SensorInformationView.qml
src/qml/imports/Theme/Theme.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

This PR aims at improving both the style as well as the UX of the way we display positioning/navigation/sensor information on top of the main canvas. 
@mohsenD98 , I've given you write access to QField's main repository, I'd recommend you update you branch to use this.

Information drawer functionality

---

src/qml/ElevationProfile.qml
src/qml/InformationDrawer.qml
src/qml/qgismobileapp.qml

How it looks:
https://github.com/opengisch/QField/assets/1728657/5c2117a3-3086-4bf6-b053-66df4de4d7f2

Information drawer follow up polishing / cleanup

---

src/qml/RelationCombobox.qml
src/qml/editorwidgets/ValueMap.qml

@domi4484 , fixes the regression we discussed on clickup.

Fix looks of value map and value relation combo boxes

---

README.md

Resolves [Issue #5265](https://github.com/opengisch/QField/issues/5265)

Updated README.md to include SHA-256 Hash of Signing Certificate

---

src/core/utils/projectutils.cpp
src/core/utils/projectutils.h
src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

@3nids , this will fix your client's issue.

When a given project transaction mode isn't disabled, parent features must be saved prior to adding children

---

.github/workflows/translations.yml

See https://github.com/opengisch/QField/actions/runs/9354685337/job/25750886771

Fix push translations workflow

---

.github/workflows/linux.yml

See https://github.com/opengisch/QField/actions/runs/9354685331/job/25748082888

Only run clang tidy on prs

---

platform/macos/CPackMacDeployQt.cmake.in

Macos 13, this one is for you ...

Retry create dmg on failure

---

src/qml/qgismobileapp.qml

@lindacamathias , @ZsanettMed , the follow up to finger tap-on-canvas digitizing mode you were all waiting for :wink:

Finger tap-on-canvas digitizing should move cursor but still let user confirm via vertex addition button

---

src/qml/qgismobileapp.qml

[Backport release-3_3] Finger tap-on-canvas digitizing should move cursor but still let user confirm via vertex addition button

---

.github/workflows/android.yml
.github/workflows/ios.yml
CMakeLists.txt

Do not set QT_HOST_PATH

---

src/core/pluginmanager.cpp

Zipped plugins filename suffix handling improvements

---

src/core/pluginmanager.cpp

[Backport release-3_3] Zipped plugins filename suffix handling improvements

---

src/app/CMakeLists.txt

this seems to be a left over from https://github.com/opengisch/QField/commit/23fe72d213c3199a1b9c0b6abca21140b1793b2c

remove unused var

---

src/core/pluginmanager.cpp
src/qml/PluginManagerSettings.qml
src/qml/qgismobileapp.qml

[Backport release-3_3] Plugins permission UI/UX improvements

---

.github/workflows/linux.yml
.github/workflows/windows.yml
src/core/featuremodel.cpp
src/core/featuremodel.h
src/core/positioning/gnsspositioninformation.h
src/core/positioning/internalgnssreceiver.cpp
src/core/utils/expressioncontextutils.cpp

[Backport release-3_3] Avoid flagging internal positioning device as invalid caused by access error, cleanup positioning includes

---

src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/qml/OverlayFeatureFormDrawer.qml
src/qml/qgismobileapp.qml

[Backport release-3_3] Exposing more to plugins

---

src/core/vertexmodel.cpp

Fixes https://github.com/opengisch/QField/issues/5345

Only add Z and M point values passed onto the model when the geometry type requires it

---

doc/dev.md

See https://github.com/opengisch/QField/discussions/5353?converting=1#discussioncomment-9813463

Fix windows build instructions

---

src/qml/qgismobileapp.qml

Fix stylus regression when editing a feature containing long combobox dropdown lists

---

src/qml/SensorInformationView.qml

without this, sensors data is gone missing :scream:

Fix sensors information panel's height issue leading to missing numbers

---

src/core/utils/qfieldcloudutils.h

[Backport release-3_3] Fix cloud user information @variables gone missing

---

src/qml/qgismobileapp.qml

[Backport release-3_3] Fix stylus regression when editing a feature containing long combobox dropdown lists

---

src/qml/editorwidgets/ValueMap.qml

[Backport release-3_3] Make value map value filtering case insensitive

---

src/qml/SensorInformationView.qml

[Backport release-3_3] Fix sensors information panel's height issue leading to missing numbers

---

src/qml/FeatureListForm.qml
src/qml/NavigationInformationView.qml
src/qml/PositioningInformationView.qml
src/qml/SensorInformationView.qml

[Backport release-3_3] Information panel text elide + feature form editing data loss fixes

---

src/qml/QFieldCloudPopup.qml

Fix https://github.com/opengisch/QField/issues/5371

Fix typo: synchornization to synchronization

---

src/qml/NavigationInformationView.qml

[Backport release-3_3] Fix color of text and button elements in the navigation to geometry bar [on light theme]

---

src/qml/RelationCombobox.qml
src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

[Backport release-3_3] Provider users with visual feedback when initiating a child addition process

---

test/test_qml.cpp

@mohsenD98 , part of the answer you are looking for :)

Initiate QGIS as part of QML tests

---

src/qml/QFieldCloudPopup.qml
src/qml/imports/Theme/QfCollapsibleMessage.qml

Fix hard to read cloud server error reporting's details text

---

src/qml/QFieldCloudPopup.qml
src/qml/imports/Theme/QfCollapsibleMessage.qml

[Backport release-3_3] Fix hard to read cloud server error reporting's details text

---

src/core/featurechecklistmodel.cpp
src/core/featurechecklistmodel.h
src/qml/editorwidgets/ValueRelation.qml

Fix value relation editor widget serious warnings

---

src/core/parametizedimage.cpp

@mbernasocchi , as discussed on chat.

Fix handling of pixel ratio for raster image decorator

---

src/core/parametizedimage.cpp

[Backport release-3_3] Fix handling of pixel ratio for raster image decorator

---

CMakeLists.txt

[Backport release-3_3] Install cacert.pem

---

.pre-commit-config.yaml
src/qml/editorwidgets/ValueMap.qml

@ZsanettMed , fixes the issues reported by the client.

Stabilize value map filtering

---

src/core/qgismobileapp.cpp
src/core/utils/expressioncontextutils.cpp
src/core/utils/expressioncontextutils.h

Implement invokable functions for plugins to handle global/project/layer variables

---

src/core/processing/processingalgorithm.cpp
src/core/processing/processingalgorithmparametersmodel.cpp
src/core/processing/processingalgorithmparametersmodel.h
src/core/processing/processingalgorithmsmodel.cpp
src/qml/FeatureListForm.qml
src/qml/LayerLoginDialog.qml
src/qml/ProcessingAlgorithmForm.qml
src/qml/QFieldCloudLogin.qml
src/qml/editorwidgets/ValueMap.qml
src/qml/imports/Theme/QfComboBox.qml
src/qml/imports/Theme/QfTextField.qml
src/qml/imports/Theme/qmldir
src/qml/processingparameterwidgets/distance.qml
src/qml/processingparameterwidgets/enum.qml
src/qml/processingparameterwidgets/number.qml
src/qml/qml.qrc

These parameters gives us these additional in-place algorithms:
- Affine transform
- Array of offset (parallel) lines
- Array of translated features
- Densify by interval
- Extend lines
- Fix geometries
- Offset lines
- Multi-ring buffer (constant distance)
- Segmentize by maximum distance
- Simplify
- Snap points to grid
- Split lines by maximum length
- Tapered buffers
- Translate
The array of translated features algorithms are quite useful, and makes the processing preview really shine :) 
Array of translated features:
https://github.com/opengisch/QField/assets/1728657/f3cd0583-8465-402f-805f-11b9d5633654
Array of offset (parallel) lines:
https://github.com/opengisch/QField/assets/1728657/b1914664-efa3-48dc-a1ed-5614acb15c85

Add support for distance and enum parameters in processing algorithms

---

src/qml/FeatureForm.qml

Fix this warning: 
```
qrc:/qml/FeatureForm.qml:766:11: QML ToolBar: Possible anchor loop detected on vertical anchor.
qrc:/qml/FeatureForm.qml:766:11: QML ToolBar: Possible anchor loop detected on vertical anchor.
qrc:/qml/FeatureForm.qml:766:11: QML ToolBar: Possible anchor loop detected on vertical anchor.
```

Fix vertical anchors loop warning.

---

src/qml/EmbeddedFeatureForm.qml
src/qml/FeatureForm.qml

This Pr Aims to resolve [**#4512**](https://github.com/opengisch/QField/issues/4512)
Also we fixed opacity issue of save button.

Reset child feature form tab.

---

src/qml/ElevationProfile.qml

Fix missing elevation profile chart labels

---

src/qml/ElevationProfile.qml

[Backport release-3_3] Fix missing elevation profile chart labels

---

images/images.qrc
images/themes/qfield/nodpi/ic_arrow_drop_down_48dp.svg
images/themes/qfield/nodpi/ic_arrow_drop_up_48dp.svg
src/qml/QFieldGuide.qml
src/qml/qgismobileapp.qml
src/qml/qml.qrc

[Screencast from 2024-07-16 18-08-02.webm](https://github.com/user-attachments/assets/51185768-96c9-4120-ae0d-1620765dac11)
_this feature will be added later._

Add QFieldGuide component.

---

src/core/drawingcanvas.cpp
src/core/drawingcanvas.h
src/core/utils/fileutils.cpp

Fixes https://github.com/opengisch/QField/issues/5446

Insure that exif tags from photo being sketched are transferred onto the saved drawing

---

platform/android/src/ch/opengis/qfield/QFieldUtils.java
src/core/appinterface.cpp

Ignore content of .qfieldsync folder when seeking project file

---

src/qml/editorwidgets/TextEdit.qml

Fix https://github.com/opengisch/QField/issues/5450

Fix handling of textt-as-number for numeric text edit widget

---

src/core/drawingcanvas.cpp
src/core/drawingcanvas.h
src/core/utils/fileutils.cpp

[Backport release-3_3] Insure that exif tags from photo being sketched are transferred onto the saved drawing

---

src/qml/QFieldGuide.qml
test/qml/Utils.js
test/qml/tst_qFieldGuide.qml

Add a simple test and refactor.

Refactor QFieldGuide component and add a test.

---

src/qml/Legend.qml
src/qml/editorwidgets/TextEdit.qml
src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

Manually backporting https://github.com/opengisch/QField/pull/5452 and https://github.com/opengisch/QField/pull/5455

Manual backport of a couple of fixes to release-3_3 branch

---

src/qml/QFieldSettings.qml

Fixes https://github.com/opengisch/QField/issues/5468

Fix settings' panel tabs not translatable

---

src/qml/QFieldSettings.qml

[Backport release-3_3] Fix settings' panel tabs not translatable

---

src/app/main.cpp
src/qml/qgismobileapp.qml

Fixes https://github.com/opengisch/QField/issues/5474

Fix untranslatable map canvas menu item and install/upgrade message

---

src/qml/RelationCombobox.qml

Backport Fix RelationCombobox not autocompleting on second feature

---

src/app/main.cpp
src/qml/qgismobileapp.qml

[Backport release-3_3] Fix untranslatable map canvas menu item and install/upgrade message

---

src/qml/editorwidgets/ValueRelation.qml

Fixes https://github.com/opengisch/QField/discussions/5480  -- proof of life:

Fix value relation handling of group name display when multi-selection is enabled

---

src/qml/editorwidgets/ValueRelation.qml

Manual backport of https://github.com/opengisch/QField/pull/5482

[backport release-3_3] Fix value relation handling of group name display when multi-selection is enabled

---

Gemfile.lock

Keeping ourselves green is a never ending task.

Fix broken iOS and macos CI actions

---

Gemfile.lock

[Backport release-3_3] Fix broken iOS and macos CI actions

---

src/qml/About.qml

On Desktop platforms, make the data directory location a clickable hyperlink

---

src/qml/About.qml

[backport release-3_3] On Desktop platforms, make the data directory location a clickable hyperlink

---

.github/workflows/android.yml
src/qml/editorwidgets/TextEdit.qml

Manual backport of https://github.com/opengisch/QField/pull/5506

 [backport release-3_3] Fix handling of autogenerated fid in feature form, adjust default NDK following github Ubuntu 22.04 image update #5510 

---

src/core/attributeformmodelbase.cpp
src/core/featuremodel.cpp

Fixes https://github.com/opengisch/QField/issues/5513

Fix current_parent_* for (embedded) feature model

---

src/core/attributeformmodelbase.cpp
src/core/featuremodel.cpp

[Backport release-3_3] Fix current_parent_* for (embedded) feature model

---

src/qml/About.qml
src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/LayerLoginDialog.qml
src/qml/LayerTreeItemProperties.qml
src/qml/LocatorItem.qml
src/qml/MessageLog.qml
src/qml/ProcessingAlgorithmForm.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml
src/qml/QFieldSettings.qml
src/qml/RelationCombobox.qml
src/qml/TrackerSettings.qml
src/qml/WelcomeScreen.qml
src/qml/editorwidgets/ValueMap.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml
src/qml/imports/Theme/QfScrollBar.qml
src/qml/imports/Theme/Theme.qml
src/qml/imports/Theme/qmldir
src/qml/qml.qrc

In this PR, we are introducing our customized QfScrollBar, which features a consistent styling across all scrollbars. By implementing this component, we aim to unify the appearance of scrollbars throughout the application, reduce code duplication, and enhance ease of use.
How to Use:
- For a vertical scrollbar, simply use:
`
ScrollBar.vertical: QfScrollBar {}
`
- For a horizontal scrollbar, you can implement:
`
ScrollBar.horizontal: QfScrollBar {}
`    
There's no need to specify policy indicators or any other configurations, as this component is designed to handle all of that automatically.
**Previous:**
[old-scrollBars.webm](https://github.com/user-attachments/assets/e5a393c5-7ec9-490a-a56d-3a383862c425)
**QfScrollBar-Demo:**   
[Screencast from 2024-08-05 …

QFieldCloud projects (et cie) scroll bar harmonization/improvement

---

src/qml/QFieldCloudScreen.qml

In this PR we solve a tiny problem of Indeterminate.
**Previous:**
[Screencast from 2024-08-09 15-22-09.webm](https://github.com/user-attachments/assets/37915763-a9cc-4d6c-99b8-8755bab553c1)
**Now:**
[Screencast from 2024-08-09 15-12-35.webm](https://github.com/user-attachments/assets/ccd5101a-996e-4cba-9649-75d30c0b6cda)

Indeterminate while connecting.

---

src/core/deltafilewrapper.cpp
src/core/deltafilewrapper.h
test/test_deltafilewrapper.cpp

[Backport release-3_3] Fix loss of images when merging patches against pre-existing create/patch deltas

---

.github/workflows/linux.yml
platform/android/AndroidManifest.xml.in
src/core/qfieldcloudconnection.cpp
src/core/qfieldcloudconnection.h
src/core/utils/qfieldcloudutils.cpp
src/core/utils/qfieldcloudutils.h
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/qgismobileapp.qml

Manual backport of the following PRs:
- https://github.com/opengisch/QField/pull/5531
- https://github.com/opengisch/QField/pull/5542

[backport release-3_3] Attachment uploads fixes

---

src/core/utils/stringutils.cpp
src/core/utils/stringutils.h
src/qml/RelationCombobox.qml
src/qml/editorwidgets/ValueMap.qml
test/test_stringutils.cpp

Fixes https://github.com/opengisch/QField/issues/5489

Value {map, relation} editor widget: fix representation problem with < character

---

src/core/utils/stringutils.cpp
src/core/utils/stringutils.h
src/qml/RelationCombobox.qml
src/qml/editorwidgets/ValueMap.qml
test/test_stringutils.cpp

[backport release-3_3] Value {map, relation} editor widget: fix representation problem with < character

---

.docker/android_dev/Dockerfile
.github/workflows/android.yml
cmake/Platform.cmake

[Backport release-3_3] Bump android version to 34

---

src/core/featurechecklistmodel.cpp
src/qml/editorwidgets/ValueRelation.qml

[backport release-3_3] Harmonize handling of QField's (multi)value relation editor widget with that of QGIS

---

src/core/positioning/positioning.cpp

[Backport release-3_3] Insure that the orientation value is between 0 and 360 (instead of ~-90 to 270)

---

src/qml/WelcomeScreen.qml
src/qml/imports/Theme/QfScrollBar.qml

**New look:**    
[Screencast from 2024-08-16 12-13-47.webm](https://github.com/user-attachments/assets/2136a89a-2647-4dfe-ad40-4582794538b3)

Better looking scrollBar in welcome screen.

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/qml/QFieldCloudScreen.qml
src/qml/SearchBar.qml
src/qml/imports/Theme/QfSearchBar.qml
src/qml/imports/Theme/qmldir
src/qml/qml.qrc

This PR aims to enhance the user experience by adding a search bar to the project section. The search bar allows users to quickly find specific projects by searching for keywords in the `owner name`, `project name`, or `project description`. now users can now quickly find specific projects without having to manually scroll through the list of projects. Also this might increase user engagement and satisfaction.
Overall, this PR aims to improve the overall user experience by providing an effective way to find projects.
**Demo:**  
[Screencast from 2024-08-17 18-05-24.webm](https://github.com/user-attachments/assets/3c1750df-1af0-4d8f-9ffc-9b67a03e8dbd)

Search cloud projects list functionality

---

src/qml/QFieldCloudScreen.qml

@mohsenD98 , this fixes a regression from the cloud project search PR whereas cloud projects can't be downloaded/opened anymore.

Fix cloud projects list clicks/touches

---

.github/workflows/ios.yml
src/core/utils/fileutils.cpp
src/qml/QFieldCamera.qml

Localized text stamps, should have been in the initial PR.

Localize text stamps, tweak font/buffer size of text stamps a bit

---

src/qml/WelcomeScreen.qml

Refer Android/iOS/Windows users to their respective stores

---

src/qml/WelcomeScreen.qml

[Backport release-3_4] Refer Android/iOS/Windows users to their respective stores

---

cmake/NSIS.template.in
cmake/Package.cmake

[Backport release-3_4] Add file association for .qgs/.qgz on Windows

---

.github/workflows/ios.yml
.github/workflows/macos.yml
platform/macos/CPackMacDeployQt.cmake.in

Could we get to green macos on forked repo?

---

src/qml/QFieldCamera.qml

We ain't tamping, we're stamping! :wink:

Fix typo in stamping toaster notification

---

src/qml/QFieldCamera.qml

[Backport release-3_4] Fix typo in stamping toaster notification

---

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

Fix variable scoping error with relation editor widgets

---

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

[Backport release-3_4] Fix variable scoping error with relation editor widgets

---

.github/workflows/macos.yml
CMakeLists.txt
src/core/CMakeLists.txt
src/qml/qgismobileapp.qml
vcpkg.json

Giving some more love to plugin developers.

Enable websockets support in QField

---

src/core/featuremodel.cpp

[Backport release-3_4] Fix multi-editing can lead to crash

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

[Backport release-3_4] Some (micro) optimizations of feature form

---

platform/android/AndroidManifest.xml.in
src/qml/Toast.qml

[Backport release-3_4] Insure that QField toasts appear above the virtual keyboard

---

src/core/positioning/nmeagnssreceiver.cpp

Regression raised by our friends at FeelGood GeoSolutions.

Fix missing + IMU in the quality description

---

src/core/positioning/nmeagnssreceiver.cpp

[Backport release-3_4] Fix missing + IMU in the quality description

---

.clang-format
src/core/localfilesmodel.cpp
src/core/localfilesmodel.h
src/qml/QFieldLocalDataPickerScreen.qml

[Backport release-3_4] Allow for users to see and send NMEA logs

---

src/app/main.cpp

[Backport release-3_4] Insure that the defautl text format font matches what we're passing through env. variables

---

src/core/attributeformmodelbase.cpp

Fixes https://github.com/opengisch/QField/issues/5688

Fix multiline handling of expressions within QML / HTML editor widgets

---

src/core/processing/processingalgorithmparametersmodel.cpp
src/core/processing/processingalgorithmsmodel.cpp
src/qml/processingparameterwidgets/source.qml
src/qml/qml.qrc

This PR was originally authored by @qsavoye here: https://github.com/opengisch/QField/pull/5678 -- big thanks! It's merely cleanup of tiny fixes here and there revision. Unfortunately I squashed all into one commit.
The change unlocks the following algorithms:
- difference
- clip
- split with lines

Add processing's feature source parameter support

---

src/core/attributeformmodelbase.cpp
src/qml/editorwidgets/Binary.qml
src/qml/qml.qrc

[Backport release-3_4] Prevent crashes when opening a feature form containing a blob attribute

---

src/qml/qgismobileapp.qml

[Backport release-3_4] What's new for new users is not a great experience

---

src/qml/RelationCombobox.qml
src/qml/imports/Theme/QfSearchBar.qml

[Backport release-3_4] Insure that search bar reacts to partial text entered by all virtual keyboards

---

src/qml/QFieldGuide.qml

Somehow (!) pointer to item of QFieldGuide is out of sync!
this commit fixes that with more enhanced logic!

Fix QFieldGuide component: adjust pointerToItem.

---

src/qml/QFieldGuide.qml

[Backport release-3_4] Fix QFieldGuide component: adjust pointerToItem.

---

src/core/qfieldcloudprojectsmodel.cpp

[Backport release-3_4] Fix LocalModification flag not properly restored when opening a cloud project prior successfully logging into the server

---

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

[Backport release-3_4] Avoid needless save when adding a child to a parent that is already part of its dataset

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/utils/fileutils.cpp
src/core/utils/fileutils.h

[Backport release-3_4] Avoid constantly re-downloading same large files from the cloud by fixing checksum

---

src/app/main.cpp

Fixes https://github.com/opengisch/QField/issues/5744

Fix UI not following system language when available

---

src/app/main.cpp

[Backport release-3_4] Fix UI not following system language when available

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/qml/qgismobileapp.qml

[Backport release-3_4] Fix attachments not uploaded immediately when hitting the synchronize button

---

src/core/qfieldappauthrequesthandler.cpp
src/qml/qgismobileapp.qml

[Backport release-3_4] Fix layer login popup getting into the top / bottom system OS margins

---

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

[Backport release-3_4] When setting up our tracking feature, we avoid saving at all times, make relations accept that reality

---

src/qml/RelationCombobox.qml
src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml

[Backport release-3_4] Fix geometry digitizing step missing when adding a relationship parent via the relation combobox

---

.github/workflows/apple_certs.yml
fastlane/Fastfile

Avoid troubles 12 months from now

Nuke apple certs each month

---

src/qml/PluginManagerSettings.qml
src/qml/QFieldCloudScreen.qml

Because a clean console is a clear console...

Fix all remaining onLinkActivated warnings

---

src/core/platforms/ios/iosresourcesource.mm

Fixes https://github.com/opengisch/QField/issues/5785

Fix iOS image and video filename from gallery

---

src/core/locator/locatormodelsuperbridge.cpp
src/qml/LocatorItem.qml
src/qml/qgismobileapp.qml

Restructuring work setting the way for plugin to talk to the locator bridge.

Relocate the locator model super bridge object outside of the search bar

---

src/core/locator/featureslocatorfilter.cpp
src/qml/LocatorItem.qml

Fixing what's been spotted in the wild :)

A couple of search bar locator fixes

---

src/qml/qgismobileapp.qml

Fix typo in translation string

---

src/qml/qgismobileapp.qml

Thanks to the 24 days before Christmas for having "caught" this one.

Insure grid decoration overlay respects projects' X/Y interval and offset values

---

src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/qml/editorwidgets/ExternalResource.qml

[Backport release-3_4] Fix sketching over image attachments sometimes not working

---

platform/android/src/ch/opengis/qfield/QFieldUtils.java

As seen on sentry https://opengisch.sentry.io/issues/4955278131/?project=6119013&query=is%3Aunresolved%20device%3A%22Redmi%20Note%20%2A%22&referrer=issue-stream&statsPeriod=7d&stream_index=9

Fix crash on a few Android devices

---

platform/android/src/ch/opengis/qfield/QFieldUtils.java

[Backport release-3_4] Fix crash on a few Android devices

---

src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/core/qgsquick/qgsquickmapsettings.cpp
src/qml/imports/Theme/QfTextField.qml

This fixes an irritating white line that can often appear on the right edge of the map canvas, e.g. this:
I can't count the nb of times this has hit my eyes and felt irritated about it. Good riddance.

Finally fix that white line on the edge of the map canvas!

---

src/qml/imports/Theme/QfTextField.qml

Not sure if this ever worked :)

Fix the text field's show/hide password button gone missing

---

src/qml/MapCanvas.qml

When using mouse, the map rotation calculation is improved

Improve map rotation by mouse event

---

CMakeLists.txt
src/core/CMakeLists.txt
vcpkg.json

Checking that all platforms are a-OK.

Add dependency to Qt remote objects

---

src/core/CMakeLists.txt
src/core/positioning/abstractgnssreceiver.h
src/core/positioning/egenioussreceiver.cpp
src/core/positioning/egenioussreceiver.h
src/core/positioning/gnsspositioninformation.cpp
src/core/positioning/gnsspositioninformation.h
src/core/positioning/internalgnssreceiver.cpp
src/core/positioning/internalgnssreceiver.h
src/core/positioning/nmeagnssreceiver.cpp
src/core/positioning/nmeagnssreceiver.h
src/core/positioning/positioning.cpp
src/core/positioning/positioning.h
src/core/positioning/positioningdevicemodel.cpp
src/core/positioning/positioninginformationmodel.cpp
src/core/positioning/positioningsource.cpp
src/core/positioning/positioningsource.h
src/core/positioning/serialportreceiver.cpp
src/core/positioning/serialportreceiver.h
src/core/positioning/tcpreceiver.cpp
src/core/positioning/tcpreceiver.h
src/core/positioning/udpreceiver.cpp
src/core/positioning/udpreceiver.h
src/core/qgismobileapp.cpp
src/qml/QFieldSettings.qml
src/qml/qgismobileapp.qml

First positioning framework restructuring to rely on Qt remote objects, which ultimately will lead us to background positioning.  The PR aims at feature parity between our old way and this new approach. 
@m-kuhn , @suricactus , I would _love_ your review here since we're dealing with a significant part of QField. Some would say the most important part :wink: 
~~(PR includes https://github.com/opengisch/QField/pull/5903 , I'll rebase once that is merged)~~

Implement Processing <-> ProcessingSource dynamics

---

platform/android/AndroidManifest.xml.in
platform/android/src/ch/opengis/qfield/QFieldCloudService.java
src/app/main.cpp
src/core/platforms/android/androidplatformutilities.cpp
src/service/CMakeLists.txt
src/service/qfieldcloudservice.cpp
src/service/qfieldcloudservice.h

Let's make some syntax room for more services :)

Rename QFieldService to QFieldCloudService

---

src/core/platforms/android/androidplatformutilities.cpp
src/qml/NavigationBar.qml

Fix compilation following merging of the background positioning PR

---

index.html

Fixes https://github.com/opengisch/QField/issues/5921

Link to privacy policy

---

src/core/focusstack.cpp
src/core/focusstack.h
src/qml/About.qml
src/qml/BookmarkProperties.qml
src/qml/BrowserPanel.qml
src/qml/Changelog.qml
src/qml/DashBoard.qml
src/qml/EmbeddedFeatureForm.qml
src/qml/LayerTreeItemProperties.qml
src/qml/Legend.qml
src/qml/LocatorItem.qml
src/qml/LocatorSettings.qml
src/qml/MessageLog.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/PluginManagerSettings.qml
src/qml/PositioningDeviceSettings.qml
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/QFieldSettings.qml
src/qml/RelationCombobox.qml
src/qml/WelcomeScreen.qml
src/qml/editorwidgets/ValueMap.qml
src/qml/qgismobileapp.qml

OK, so we can't get rid of focus stack, but hopefully we can improve it a bit.

Generalize the focus stack to also handle popups

---

.github/workflows/ios.yml
.github/workflows/macos.yml
platform/macos/create_dmg.sh

- Merge the x64 and arm64 mac packages into a single universal package.
- Sign and notarize the dmg for releases

Create universal mac package

---

vcpkg.json

Enables:
ZSTD	
WEBP	
LERC	
LERC_DEFLATE	
LERC_ZSTD

Enable more tiff encodings

---

platform/android/build.gradle.in
platform/android/gradle/wrapper/gradle-wrapper.properties

Better aligns with upcoming Qt 6.8.2

Update gradle dependencies

---

src/qml/MessageLog.qml

Fix parenting of message log's manual sentry submission dialog

---

src/qml/DashBoard.qml

One tiny visual fix, and one really irritating bug whereas digitizing wouldn't be remembered after two sessions.

More dashboard fixes following UI/UX revamp

---

src/qml/CoordinateLocator.qml

Alright, seems February 2, 2025, was the day I got enlightened about this long-standing issue! :wink: 
@mohsenD98 , thanks for giving this a try nevertheless!

Fix long-standing binding loop error when snapping to angle enabled

---

src/qml/NavigationBar.qml
src/qml/QFieldCloudScreen.qml
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/qgismobileapp.qml

Fixes this unwanted gap between the edge of the list and the section header:

Fix weeks-old visual glitch with the cloud projects list

---

CMakeLists.txt
src/core/webdavconnection.cpp
src/qml/BookmarkProperties.qml
src/qml/DashBoard.qml
src/qml/LocatorSettings.qml
src/qml/PluginManagerSettings.qml
src/qml/QFieldAudioRecorder.qml
src/qml/QFieldCamera.qml
src/qml/QFieldLocalDataPickerScreen.qml
src/qml/TemporalProperties.qml
vcpkg/ports/qgis/vcpkg.json
vcpkg/ports/qtmultimedia/fix_avfoundation_target.patch
vcpkg/ports/qtmultimedia/vcpkg.json
vcpkg/ports/qtpositioning/vcpkg.json
vcpkg/ports/qtquick3d/vcpkg.json

On top of Qt 6.8.2, we get:
- gdal 3.10.1
- sqlite 3.49.0
- openjpeg 2.5.3

Update vcpkg revision to catch Qt 6.8.2 et al

---

src/app/main.cpp
src/core/platforms/platformutilities.cpp
src/core/platforms/platformutilities.h
src/core/qgismobileapp.cpp

[Backport release-3_5] Rework pg_service.conf handling to support SSL keys authentication

---

vcpkg.json
vcpkg/ports/qgis/vcpkg.json

[Backport release-3_5] What is causing our AppImage to die?

---

src/qml/qgismobileapp.qml

[Backport release-3_5] Restore Stylus Binding to CoordinateLocator

---

src/qml/CoordinateLocator.qml

[Backport release-3_5] Center Map on Vertex Addition When Position Locked & Off-Screen

---

src/core/drawingcanvas.cpp

[Backport release-3_5] Fix image attachments rotation issues after drawing on them

---

.github/ISSUE_TEMPLATE/10_bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

Re-order wording of issue action titles to put verb first

---

src/qml/qgismobileapp.qml

Cleaner consoles make for happier developers.

Silence another (harmless) warning on QField launch/exit

---

src/qml/qgismobileapp.qml

[Backport release-3_5] Silence another (harmless) warning on QField launch/exit

---

src/core/distancearea.cpp
src/core/navigation.cpp
src/core/scalebarmeasurement.cpp
src/core/tracker.cpp

Another crasher revealed by the Play Store but impacts us across all platform.

Fix crash with scalebar measurement when points can't be transformed

---

.github/workflows/linux.yml
.github/workflows/windows.yml

[Backport release-3_5] Disable sentry on system where it's inactive

---

src/core/locator/gotolocatorfilter.cpp

port of https://github.com/qgis/QGIS/pull/60739

fix goto locator to support leading NESW

---

src/core/webdavconnection.cpp

We did have the action enabled for files, but the code was not adapted for it. This PR fixes that.
@mohsenD98 , that should help you.

Allow for individual files to be uploaded to a WebDAV remote server

---

src/core/locator/gotolocatorfilter.cpp

Backport #6041
**Authored by:** @3nids

[Backport release-3_5] fix goto locator to support leading NESW

---

src/qml/DashBoard.qml

[Backport release-3_5] Remove text label from the show project folder button in the dashboard

---

src/core/webdavconnection.cpp

[Backport release-3_5] Allow for individual files to be uploaded to a WebDAV remote server

---

.github/workflows/ios.yml

[Backport release-3_5] Trying to upgrade to Xcode 16 to build against iOS SDK 18

---

src/core/webdavconnection.h

Add missing [header] documentation to the WebdavConnection class

---

src/core/rubberbandmodel.cpp

[Backport release-3_5] Do not hard-wipe the last rubberband coordinate when resetting

---

src/service/qfieldpositioningservice.cpp
src/service/qfieldpositioningservice.h

[Backport release-3_5] When the user de-activate positioning within a session, let the positioning service notification reflect that

---

src/qml/FeatureListForm.qml
src/qml/QFieldSketcher.qml
src/qml/qgismobileapp.qml

[Backport release-3_5] Fix esc/back key not closing the QFieldCloud push/synchronize popup

---

vcpkg/ports/qtbase/android_cursor_location.patch
vcpkg/ports/qtbase/bluetooth_mouse_fix.patch
vcpkg/ports/qtbase/portfile.cmake
vcpkg/ports/qtmultimedia/portfile.cmake
vcpkg/ports/qtmultimedia/video_recording_fix.patch

[Backport release-3_5] Backport crucial Qt 6.8.3 fixes to our overlay Qt ports

---

src/qml/BusyOverlay.qml

[Backport release-3_5] Overlay to Block UI Interaction During Busy State.

---

src/qml/QFieldLocalDataPickerScreen.qml

Fix some weird right-end padding/margin issue, provides a bit of margin to the dialog on narrow screens, makes it clearer forgetting the user name also forgets the password, etc.

A bit more polishing for the import WebDAV dialog

---

src/core/pluginmanager.cpp
src/qml/PluginManagerSettings.qml

[Backport release-3_5] A bit of plugins polishing

---

src/qml/QFieldLocalDataPickerScreen.qml

[Backport release-3_5] A bit more polishing for the import WebDAV dialog

---

.github/workflows/ios.yml
.github/workflows/macos.yml
test/spix/smoke_test.py

[Backport release-3_5] Upgrade to macos 15 runners

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h

Fixes
- https://opengisch.sentry.io/issues/6238436440/?project=6119013&query=is%3Aunresolved%20stack.function%3AQFieldCloudProjectsModel%3A%3AprojectDownloadFinished&referrer=issue-stream&stream_index=9
- https://opengisch.sentry.io/issues/6263037827/?project=6119013&query=is%3Aunresolved%20stack.function%3AQFieldCloudProjectsModel%3A%3AprojectDownloadFinished&referrer=issue-stream&stream_index=1
- etc.

Fix accessing deleted network reply pointer

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h

[Backport release-3_5] Fix accessing deleted network reply pointer

---

src/core/qfieldcloudprojectsmodel.cpp

Attempt at fixing https://github.com/opengisch/QField/issues/6112

Fix windows errors removing temporary files when downloading a cloud project

---

src/app/main.cpp

[Backport release-3_5] Debugging Android graphic glitches

---

resources/templates/oauth2_verification_finished.html

@lukasgraf , as spotted on your screencast video.

Make the OAuth2 html template mobile friendly

---

.github/workflows/macos.yml
src/core/utils/layerutils.h

[Backport release-3_5] Add a mechanism to explicitly close a feature iterator

---

platform/android/AndroidManifest.xml.in
platform/android/src/ch/opengis/qfield/QFieldActivity.java

[Backport release-3_5] Fix reliability of file association on Android

---

.github/workflows/android.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
src/core/qfieldcloudconnection.cpp

@lukasgraf , @faebebin , as discussed / reported :)

Clear cookies when logging out of QFC

---

.github/workflows/ios.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
Gemfile.lock

Pretty much every single one of our CIs started failing overnight due to cmake 4.0 upgrade.

Extra CI fixes with regards to cmake 4

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

Fixes https://github.com/opengisch/QField/issues/6166

Fix feature form's show label setting not respected

---

src/qml/QFieldCloudLogin.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml

QFieldCloud login UI tweaks

---

src/qml/QFieldLocalDataPickerScreen.qml

[Backport release-3_5] Disable the OK button ok the Import WebDAV folder dialog until a folder has been selected

---

src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h
src/core/utils/qfieldcloudutils.h
src/qml/QFieldCloudScreen.qml
src/qml/qgismobileapp.qml

This PR adds logic to support downloading of localized datasets from a special localized datasets project hosted on QFieldCloud.

Cloud project's localized datasets support

---

src/core/qfieldcloudproject.cpp
src/core/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloudprojectsmodel.h

Made to work with tweaks applied to the QFieldCloud localized datasets branch.
I much, much prefer this way.

Update QFieldCloud's localized datasets to latest server handling

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

Respect QML/Text/HTML widget's show label property

---

src/qml/FeatureForm.qml

Add some bottom and right margin to the feature form's text widget

---

src/qml/FeatureForm.qml

[Backport release-3_5] Add some bottom and right margin to the feature form's text widget

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

[Backport release-3_5] Respect QML/Text/HTML widget's show label property

---

src/qml/FeatureForm.qml
src/qml/editorwidgets/Range.qml
test/qml/tst_editorwidgets.qml

Fixes https://github.com/opengisch/QField/issues/6201 and https://github.com/opengisch/QField/issues/4222

Fix range float step increase/decrease leading to decimal issues

---

src/qml/FeatureForm.qml
src/qml/editorwidgets/Range.qml
test/qml/tst_editorwidgets.qml

[Backport release-3_5] Fix range float step increase/decrease leading to decimal issues

---

platform/ios/Info.plist.in
src/core/CMakeLists.txt
src/core/qfieldurlhandler.cpp
src/core/qfieldurlhandler.h
src/core/qgismobileapp.cpp
src/core/qgismobileapp.h

:cherries:  on top of the sundae.

Implement qfield scheme on iOS

---

src/qml/qgismobileapp.qml

Fix geometry editor's eraser tool when using freehand mode

---

assistance.html
certified-hardware.html
css/qfield.css
index.html
partner.html
sdgs.html
support.html
works-with-hardware.html

@anjakyra , as discussed yesterday, the PR fixes the collapsed menu's support us right margin:
I've also fixed the bottom's about section contour background size so it covers all of the area on narrow screens.

Refresh website tiny tweaks

---

src/core/qgismobileapp.cpp
src/core/trackingmodel.cpp
src/core/trackingmodel.h
src/qml/TrackerSettings.qml
src/qml/TrackingSession.qml

Master-only regression fix plus general tracker improvements.
Fixes https://github.com/opengisch/QField/issues/6119

Fix tracking position information property error

---

src/qml/qgismobileapp.qml

[Backport release-3_5] Fix geometry editor's eraser tool when using freehand mode

---

src/qml/QFieldCloudPopup.qml

@mohsenD98 , as revealed by your screenshot.

Fix longstanding error with the reset current cloud project action

---

src/core/attributeformmodelbase.cpp
src/qml/FeatureForm.qml

Fix hidden editor widget showing as text edit

---

src/core/utils/stringutils.cpp
src/core/utils/stringutils.h
src/qml/QFieldAudioRecorder.qml

Attempt at addressing https://github.com/opengisch/QField/issues/6203

Let's try to create more wildly used m4a audio extension

---

src/core/locator/activelayerfeatureslocatorfilter.cpp
src/core/locator/featureslocatorfilter.cpp
src/qml/editorwidgets/RelationEditorBase.qml
src/qml/editorwidgets/RelationReference.qml
src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
src/qml/editorwidgets/relationeditors/relation_editor.qml
src/qml/qgismobileapp.qml

Small papercut fixes, mostly around relations-related UI and search bar.

A variety of paper cut fixes to make QField as smooth as it can be

---

src/core/pluginmanager.cpp
src/core/pluginmanager.h
src/core/qgismobileapp.cpp
src/core/utils/projectutils.cpp
src/core/utils/projectutils.h
src/qml/FeatureForm.qml
src/qml/OverlayFeatureFormDrawer.qml
src/qml/qgismobileapp.qml

Never make the feature addition drawer interactive, too hard to scroll

---

src/qml/OverlayFeatureFormDrawer.qml

Little polishing, last commit prior to 3.6!

Add animation behavior to feature addition form's fullscreen toggling

---

src/qml/Legend.qml

[Backport release-3_6] Fix badge alignment of geometryless layers

---

src/qml/Toast.qml
src/qml/qgismobileapp.qml

Better image decorator placement on short heights & fix toast logics

---

src/qml/Toast.qml
src/qml/qgismobileapp.qml

[Backport release-3_6] Better image decorator placement on short heights & fix toast logics

---

src/core/qgsquick/qgsquickmapsettings.cpp
src/qml/geometryeditors/VertexEditor.qml

[Backport release-3_6] Fix map center positioning with rotation and information drawer

---

src/core/qfieldcloud/qfieldcloudproject.cpp
src/core/qfieldcloud/qfieldcloudproject.h
src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp

Pretty much the title, check the individual commit messages.

feat(localized): adapt to the latest changes in the server API and support vector files as shared datasets

---

src/core/qfieldcloud/qfieldcloudproject.cpp
src/core/qfieldcloud/qfieldcloudproject.h
src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp

[Backport release-3_6] feat(localized): adapt to the latest changes in the server API and support vector files as shared datasets

---

src/core/appinterface.cpp
src/core/utils/fileutils.cpp
src/core/utils/fileutils.h

[Backport release-3_6] Fix unzip trying to write directories

---

images/images.qrc
images/themes/qfield/nodpi/ic_star_filled_white_24dp.svg
platform/android/src/ch/opengis/qfield/QFieldActivity.java
src/core/identifytool.cpp
src/core/qfieldcloud/qfieldcloudproject.cpp
src/core/qfieldcloud/qfieldcloudproject.h
src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloud/qfieldcloudprojectsmodel.h
src/qml/QFieldCloudScreen.qml

[Backport release-3_6] Implement dynamic sorting of QFieldCloud projects list

---

src/core/attributeformmodelbase.cpp
src/core/pluginmanager.cpp
src/core/utils/featureutils.cpp

Thanks sentry, thanks play store.

Fix two additional 3.6 crashers

---

src/core/attributeformmodelbase.cpp
src/core/pluginmanager.cpp
src/core/utils/featureutils.cpp

[Backport release-3_6] Fix two additional 3.6 crashers

---

src/core/trackingmodel.h

[Backport release-3_6] Fix tipo leading to tracker settings panel always skipped

---

src/qml/qgismobileapp.qml

There's plenty to do with that and plugins.

Provide an object name for the coordinate locator item

---

src/qml/FeatureListForm.qml
src/qml/NavigationBar.qml
src/qml/qgismobileapp.qml

[Backport release-3_6] Add feature processing capability to individual features.

---

src/core/featuremodel.cpp
src/core/vertexmodel.cpp
src/core/vertexmodel.h

[Backport release-3_6] Handle topological addition of vertices across layers when using the vertex editor tool

---

src/core/featuremodel.cpp

[Backport release-3_6] Improve handling of topological editing with feature additions, add geometry lock logic

---

src/core/locator/gotolocatorfilter.cpp

Fixes https://github.com/opengisch/QField/issues/6337

Bring back to life the goto locator's navigation action

---

src/qml/TrackerSettings.qml

Fixes https://github.com/opengisch/QField/issues/6346

Keep track of cancelled tracking sessions

---

src/qml/QFieldLocalDataPickerScreen.qml

[Backport release-3_6] Improve wrapping of local data view's filenames

---

src/qml/TrackerSettings.qml

[Backport release-3_6] Keep track of cancelled tracking sessions

---

src/qml/qgismobileapp.qml

Fixes https://github.com/opengisch/QField/issues/6357 
@boardend , this should do it, glad you stumbled on this one.

When turning positioning off, canvas lock should also be turned off

---

src/core/qfieldcloud/qfieldcloudproject.cpp

Because it can well happen that a cloud user has no access to the shared dataset special project but _does_ have access to the project itself. 
Reported by Groupement Forestier Quebec.

Fix cloud projects not downloading when shared datasets special project access is denied

---

src/core/qfieldcloud/qfieldcloudproject.cpp

[Backport release-3_6] Fix cloud projects not downloading when shared datasets special project access is denied

---

src/qml/MapCanvas.qml

[Backport release-3_6] Stop rendering when freezing canvas for anything but follow events

---

platform/android/res/xml/network_security_config.xml

Attempt at fixing https://github.com/opengisch/QField/issues/6376

Re-allow non-https connections through webview items

---

platform/android/res/xml/network_security_config.xml

[Backport release-3_6] Re-allow non-https connections through webview items

---

src/core/multifeaturelistmodelbase.cpp
src/core/multifeaturelistmodelbase.h

Fix identification of multiple features against an online raster layer

---

src/qml/qgismobileapp.qml

[Backport release-3_6] Allow multiple undo/redo operations without requiring drawer to close

---

src/qml/qgismobileapp.qml

Refining the canvas locked to position revamp.

Insure that zooming and and out will redraw canvas when needed while locked to position

---

src/core/featuremodel.cpp

Avoid creating an editing session by skipping any layer that will not be topologically impacted by feature editing / addition.

Optimize topological editing handling

---

src/qml/qgismobileapp.qml

[Backport release-3_6] Insure that zooming and and out will redraw canvas when needed while locked to position

---

src/core/featuremodel.cpp

[Backport release-3_6] Optimize topological editing handling

---

src/core/qgismobileapp.cpp
src/core/qgsquick/qgsquickmapcanvasmap.cpp
src/qml/qgismobileapp.qml

[Backport release-3_6] Further behavior and UX polishing to the new canvas locked to position mode

---

src/qml/qgismobileapp.qml

[Backport release-3_6] Fix stylus/pen regression when clicing on the accept tool button

---

src/qml/qgismobileapp.qml

[Backport release-3_6] Take map canvas orientation into consideration for the the preview quadrants selection strategy

---

src/qml/DashBoard.qml

@suricactus , as discussed in our nice afternoon brainstorming session.

Don't make people confused by disappearing UI, inform them

---

src/core/qfieldcloud/qfieldcloudproject.cpp

Ouf, glad I caught this one, would have been a nightmare to dissect on sentry

Fix crash when downloading cloud projects

---

src/core/locator/activelayerfeatureslocatorfilter.cpp
src/core/locator/featureslocatorfilter.cpp
src/qml/FeatureListForm.qml

[Backport release-3_6] A couple of feature form fixes

---

src/qml/DashBoard.qml
src/qml/NavigationBar.qml
src/qml/QFieldGuide.qml
src/qml/qgismobileapp.qml

Manual backports to release-3.6

[Backport release-3_6] Singlepart point feature rotation + dashboard guide 

---

.docker/android_dev/Dockerfile
.github/workflows/android.yml
cmake/Platform.cmake
platform/android/build.gradle.in

We're a few weeks away from needing to target android 35.

Android updates

---

vcpkg/ports/qtpositioning/androidaltitude.patch
vcpkg/ports/qtpositioning/portfile.cmake

This PR fixes https://github.com/opengisch/QField/issues/6460 , for some background read the relevant Qt bug here https://bugreports.qt.io/browse/QTBUG-106049
Time to celebrate vcpkg again.

Fix altitude reporting on Android >= 15

---

src/core/featuremodel.cpp
src/core/featuremodel.h
src/qml/geometryeditors/VertexEditor.qml

[Backport release-3_6] Fix vertex editor not respecting project overlap/intersection settings

---

src/core/drawingcanvas.cpp
src/core/platforms/platformutilities.cpp
src/core/utils/urlutils.cpp
src/core/utils/urlutils.h
src/qml/QFieldAudioRecorder.qml
src/qml/QFieldCamera.qml
src/qml/QFieldSketcher.qml
src/qml/editorwidgets/ExternalResource.qml

@SeqLaz , should be available for you to test in ~40 minutes.

Fix image sketching and audio recording on Windows

---

src/core/drawingcanvas.cpp
src/core/platforms/platformutilities.cpp
src/core/utils/urlutils.cpp
src/core/utils/urlutils.h
src/qml/QFieldAudioRecorder.qml
src/qml/QFieldCamera.qml
src/qml/QFieldSketcher.qml
src/qml/editorwidgets/ExternalResource.qml

[Backport release-3_6] Fix image sketching and audio recording on Windows

---

src/core/geometry.cpp
src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h
src/core/tracker.cpp
src/core/tracker.h

A couple of optimizations which should make the tracker session a tiny bit faster to process individual incoming positions.

Tracker session optimizations

---

src/qml/FeatureForm.qml
src/qml/FeatureListForm.qml
src/qml/OverlayFeatureFormDrawer.qml

Tiny follow up to make things look even nicer!

Follow up left/right margin: fix feature form header margins

---

src/qml/qgismobileapp.qml

@SeqLaz . @suricactus , as raised in clickup.

Fix type leading to auto push interval configuration not taken into account

---

src/core/positioning/abstractgnssreceiver.h
src/core/positioning/nmeagnssreceiver.cpp
src/core/positioning/nmeagnssreceiver.h
src/core/positioning/positioning.cpp
src/core/positioning/positioning.h
src/core/positioning/positioningsource.cpp
src/core/positioning/positioningsource.h
src/qml/qgismobileapp.qml

@SeqLaz , @suricactus , as raised on clickup.

Fix NMEA connection logging on Android

---

src/qml/qgismobileapp.qml

[Backport release-3_7] Fix type leading to auto push interval configuration not taken into account

---

src/qml/FeatureListForm.qml
src/qml/qgismobileapp.qml

Possibly fixes https://github.com/opengisch/QField/issues/6513

Skip feature form-driven map canvas margins when moving/rotating features

---

src/core/positioning/abstractgnssreceiver.h
src/core/positioning/nmeagnssreceiver.cpp
src/core/positioning/nmeagnssreceiver.h
src/core/positioning/positioning.cpp
src/core/positioning/positioning.h
src/core/positioning/positioningsource.cpp
src/core/positioning/positioningsource.h
src/qml/qgismobileapp.qml

[Backport release-3_7] Fix NMEA connection logging on Android

---

src/qml/FeatureListForm.qml
src/qml/qgismobileapp.qml

[Backport release-3_7] Skip feature form-driven map canvas margins when moving/rotating features

---

src/core/utils/geometryutils.cpp
src/core/utils/geometryutils.h
src/core/utils/layerutils.cpp
src/core/utils/layerutils.h
src/qml/qgismobileapp.qml

[Backport release-3_7] Expose map canvas point handler item to plugins

---

src/core/featurelistextentcontroller.cpp
test/spix/smoke_test.py

[Backport release-3_7] Fix feature list extent controller's lack of layer<->project CRS awareness

---

src/core/deltafilewrapper.cpp
src/core/deltafilewrapper.h
src/qml/QFieldCloudPopup.qml
src/qml/qgismobileapp.qml
test/test_deltafilewrapper.cpp

Hopefully it'll help us better understand what's happening for users facing these errors.
The PR also exposes a couple of properties as Q_PROPERTY instead of Q_INVOKABLE, a bit more QMLesque :)

Provide users (and us) more details when delta file wrapper is in error state

---

src/core/clipboardmanager.cpp

@mohsenD98 , stumbled on this while testing your PR.

Fix clipboard holds feature property not emitting signal when going from true to false

---

src/core/qfieldcloud/qfieldcloudproject.cpp

Avoid caching issues with QFieldCloud by avoiding caching altogether 

---

src/core/qfieldcloud/qfieldcloudproject.cpp

[Backport release-3_7] Avoid caching issues with QFieldCloud by avoiding caching altogether 

---

src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h

[Backport release-3_7] Fix tracking not creating tracks after first track stopped

---

CMakeLists.txt
src/core/CMakeLists.txt
src/core/featuremodel.cpp
src/core/featuremodel.h
src/core/positioning/filereceiver.cpp
src/core/positioning/filereceiver.h
src/core/positioning/positioningdevicemodel.cpp
src/core/positioning/positioningdevicemodel.h
src/core/positioning/positioningsource.cpp
src/core/rubberbandmodel.cpp
src/core/rubberbandmodel.h
src/qml/FileDeviceChooser.qml
src/qml/PositioningDeviceSettings.qml
src/qml/QFieldSettings.qml
src/qml/qml.qrc
test/CMakeLists.txt
test/test_tracking.cpp

[Backport release-3_7] Postioning's logs file receiver to replay NMEA logs and tracking test cases

---

src/core/featurechecklistmodel.cpp

Fixes https://github.com/opengisch/QField/issues/6549

Let value relation handle searches the way it did until recently

---

src/core/pluginmanager.cpp
src/core/pluginmanager.h
src/core/pluginmodel.cpp
src/core/pluginmodel.h

[Backport release-3_7] Properly restore user-activated plugin on relaunch

---

src/core/featurechecklistmodel.cpp
src/core/featurelistmodel.cpp
src/qml/RelationCombobox.qml

This PR fixes https://github.com/opengisch/QField/issues/6556 -- we were lucky it ever worked prior to 3.7 to begin with. Test case coming up tomorrow.

Fix presence of null value in multi-selection value relation

---

src/qml/RelationCombobox.qml

[Backport release-3_7] Fix value relation combobox index when setting item from a filtered search popup list

---

.github/workflows/ios.yml

See https://github.com/actions/runner-images/issues/12758

Try to heal iOS builds

---

src/core/featurechecklistmodel.cpp
src/qml/RelationCombobox.qml

Fixes value relation regression reported @ https://github.com/opengisch/QField/issues/6584 , as well as insuring that the list is always sorted.

Fix one additional value relation regression

---

src/core/featurechecklistmodel.cpp
src/qml/RelationCombobox.qml

[Backport release-3_7] Fix one additional value relation regression

---

src/qml/editorwidgets/RelationEditorBase.qml

Fixes https://github.com/opengisch/QField/issues/6599 , a regression that slipped into QField 3.7.0.

Re-allow the addition of children when constraints of parent feature are not yet met

---

src/core/positioning/bluetoothdevicemodel.cpp
src/qml/BluetoothDeviceChooser.qml

Discovered while trying to debug https://github.com/opengisch/QField/issues/6598

Fix discovered Bluetooth device missing its address in the model

---

src/core/pluginmanager.cpp

Fixes https://github.com/opengisch/QField/issues/6613

Insure that repository-installed plugins can be disabled across sessions

---

src/core/positioning/bluetoothdevicemodel.cpp
src/qml/BluetoothDeviceChooser.qml

[Backport release-3_7] Fix discovered Bluetooth device missing its address in the model

---

src/qml/editorwidgets/DateTime.qml

[Backport release-3_7] Be slightly more resiliant to weird expression-driven values with our datetime editor widget

---

src/qml/RelationCombobox.qml

[Backport release-3_7] Fix value relation crash when searching for values and returning no matches

---

src/qml/QFieldSettings.qml

[Backport release-3_7] Fix visiblity of the orthometric vertical adjustment combobox item visibility

---

src/qml/imports/Theme/QfToolButton.qml

Follow up to the de-greening PR.

Fix counter badge border color

---

src/core/qfieldcloud/deltafilewrapper.cpp
src/core/qfieldcloud/deltafilewrapper.h
src/core/qfieldcloud/layerobserver.cpp
src/core/qfieldcloud/layerobserver.h
src/core/qfieldcloud/qfieldcloudproject.cpp
src/core/qfieldcloud/qfieldcloudproject.h
src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp
src/qml/DashBoard.qml
src/qml/LocatorSettings.qml
src/qml/QFieldCloudPopup.qml
src/qml/QFieldCloudScreen.qml
src/qml/qgismobileapp.qml
test/test_deltafilewrapper.cpp
test/test_digitizinglogger.cpp
test/test_layerobserver.cpp

First step to allow for each QFieldCloudProject to have a delta file wrapper member and unlock push changes / synchronization of cloud projects _other than_ the one currently opened.

Gut project *out* of the delta file wrapper code to allow for some good stuff to come

---

src/core/deltafilewrapper.cpp
src/core/deltafilewrapper.h

Manual backport of good delta fixes for QField 3.7.8

Delta fixes for undo/redo delta id scrambling 

---

src/core/qfieldcloud/qfieldcloudproject.cpp
src/core/qfieldcloud/qfieldcloudproject.h
src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp
src/core/qfieldcloud/qfieldcloudprojectsmodel.h

Some more cloud model <-> cloud project sanity.
@mohsenD98 , this will help you in your work.

Fix QFieldCloud projects model's deltas count data not refreshing

---

src/qml/DashBoard.qml
src/qml/ProjectCreationScreen.qml
src/qml/QFieldCloudScreen.qml
src/qml/imports/Theme/QfProjectThumbnail.qml

This PR applies minor UI polishing to improve consistency and readability
- Aligns the welcome page project name style with the project creation basemap names  
(removes green color and underline).  
- Slightly increases the badge size for text counters to make them more readable.

Enhances UI elements for improved readability
