opengisch/QField

src/core/attributeformmodelbase.cpp
=> [Backport release-2_5] Avoid double attribute form model reset (revert needless change)

src/core/qgismobileapp.cpp
This PR fixes an issue with single-point datasets (or multiple points _at same location_ datasets) whereas in those scenarios, _no default extent was set_, leading to unexpected results (such as carrying on the extent of the previous project, which can cause chaos and can end up with a frozen canvas).
As a nice bonus, the code is taken from QGIS' QgsMapSettings::fullExtent() (https://github.com/qgis/QGIS/blob/master/src/core/qgsmapsettings.cpp#L719) which means QField's opening of datasets will now result in the same default extent as you would get on QGIS.
=> Better initial extent when opening individual datasets with single-point (or multiple points at same location) datasets

src/core/qgismobileapp.cpp
=> [Backport release-2_5] Better initial extent when opening individual datasets with single-point (or multiple points at same location) datasets

src/qml/FeatureForm.qml
This PR fixes a regression introduced in 2.5 whereas neither QML nor HTML containers end up loading their content. 
Proof of resurrection:
Fixes #3661
Fixes #3659.
=> Fix QML container not loading regression

src/core/featuremodel.cpp, src/core/featuremodel.h
=> [Backport release-2_5] Avoid feature model's double setFeature() calls when creating a new feature

src/core/platforms/ios/iospicturesource.mm
This PR insures that the destination path (defined in qfieldsync via expression) of a photo taken by the camera or gallery exists on iOS. Fixes https://github.com/opengisch/QField/issues/3602 (pretty crucial).
=> When using the camera or gallery on iOS to fetch a photo, insure destination path is created

src/qml/FeatureForm.qml
So, TIL moment: a ListView QML item will not create model delegate items until the ListView item is visible, whereas Flow QML items will create model delegate items all the time.
In QField 2.5, this resulted in the add feature overlay drawer's feature form to populate the Flow item when the form itself was invisible, which in turn meant that selecting layers in the layer tree would lead to noticeable UI freeze on older devices. This PR fixes that by deferring the creation of the feature form items when the feature form itself is visible. This brings us back to 2.4 speeds.
=> Fix freeze (on slower device it can be 1-2sec) regression when clicking on layer tree items

src/core/platforms/ios/iospicturesource.mm
=> [Backport release-2_5] When using the camera or gallery on iOS to fetch a photo, insure destination path is created

src/qml/editorwidgets/CheckBox.qml
=> [Backport release-2_5] Fix regression with the checkbox editor widget whereas clicking outside of the switch wouldn't change value

src/core/attributeformmodelbase.cpp
This PR fixes an issue that's been lingering in our code for a long time whereas feature form tabs with expression-based visibility are not attaching their expression strings to children containers, leading to invisible container items still reporting failing constraints even though those should be ignored.
=> Insure that child containers of a tab with an expession-based visibility carry on the parent expression

src/qml/FeatureForm.qml
=> [Backport release-2_5] Keep the feature form model alive when hiding form to digitize child geometry

CMakeLists.txt, platform/android/AndroidManifest.xml.in, platform/android/res/values/strings.xml, platform/android/src/ch/opengis/qfield/QFieldService.java, src/app/CMakeLists.txt, src/app/main.cpp, src/core/platforms/android/androidplatformutilities.cpp, src/core/platforms/android/androidplatformutilities.h, src/core/platforms/platformutilities.cpp, src/core/platforms/platformutilities.h, src/core/qfieldcloudconnection.cpp, src/core/qfieldcloudconnection.h, src/core/qfieldcloudprojectsmodel.cpp, src/qml/qgismobileapp.qml, src/service/CMakeLists.txt, src/service/qfieldservice.cpp, src/service/qfieldservice.h
This PR implements a basic background service through which attachments are uploaded to the cloud. This means that even if people's devices are locked or QField is not in the foreground, the upload will continue.
=> Migrate QFieldCloud attachment upload to a background service

src/core/featuremodel.cpp, src/core/qgismobileapp.cpp, src/core/tracker.cpp, src/core/tracker.h, src/core/trackingmodel.cpp, src/core/trackingmodel.h, src/core/utils/layerutils.cpp, src/core/utils/layerutils.h, src/qml/PositioningSettings.qml, src/qml/QFieldSettings.qml, src/qml/Tracking.qml, src/qml/qgismobileapp.qml
This PR extents QField's tracking measure value support by adding new measure types and exposing the capability in the tracking UI:
When a layer's geometry used to track position has an M value, the UI will display a combobox allowing for users to specify which measure value to attach to vertices. The measure type are:
- seconds since the start of the tracking session (pre-existing)
- speed
- bearing / direction
- horizontal accuracy
- vertical accuracy
- PDOP
- HDOP
- VDOP
| Screenshot 1 | Screenshot 2 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1728657/206883523-9c2dd989-e2d7-4604-82d3-8b27f587b217.png) | ![image](https://user-images.githubusercontent.com/1728657/206883515-52ba758a-4f9d-49c5-8663-9d60c8eb2bce.png) |
Alright, because this thing is actually quite …
=> Add a bunch of measure types attached to vertices M value when tracking as well as digitizing and locked to position

src/app/main.cpp
This PR fixes #3309 (and likely other obscure bugs on older devices).
=> Revert app-wide antialiasing on QML surfaces on Android

src/app/main.cpp
Backport to 2.5 branch. IMHO would be worth releasing a final 2.5 with this fix included.
=> Revert customized default format sampling on Android

src/core/CMakeLists.txt, src/core/positioning/bluetoothdevicemodel.cpp, src/core/positioning/bluetoothdevicemodel.h, src/core/positioning/positioningdevicemodel.cpp, src/core/positioning/positioningdevicemodel.h, src/core/qgismobileapp.cpp, src/qml/BluetoothDeviceChooser.qml, src/qml/PositioningDeviceSettings.qml, src/qml/QFieldSettings.qml, src/qml/imports/Theme/QfTextField.qml, src/qml/qml.qrc
This PR is the first step towards moving away from a Bluetooth-centric positioning device settings UI into an emancipated world where TCP/UDP/Bluetooth/etc. devices are handled.
Settings now looks like this:
The add / edit / remove buttons are all implemented, which means Bluetooth devices can be added and the UI tested. That looks like this:
A big positive of this revamped approach is that someone will be able to setup multiple devices and will simply require to switch item in the combobox to hop from one to the other instead of going through a round of setup. This is beneficial even for Bluetooth devices, e.g. instead of having to do re-scans every time a user wants to switch from one Bluetooth device to the other, he/she/they will rely on saved device details. *Much faster*.
=> Add positioning device model, implement combobox UI

src/qml/TcpDeviceChooser.qml, src/qml/UdpDeviceChooser.qml
That way, we get a nice virtual digits-only keyboard for ports and no auto uppercasing mess for host address.
=> Add useful text field hints to TCP/UDP device configuration widgets

src/qml/LocationMarker.qml, src/qml/PositioningPreciseView.qml, src/qml/qgismobileapp.qml
This PR cleans up the location marker by removing the "compass" magnetometer away from the marker into the main qgismobileapp file. The relocation makes sense since it's used not only by the location marker but also the precise "stakeout" view.
The goal here is to eventually allow for the location marker to be used as part of a model of locations, where the location marker could be used to display live location from various sources. To that end, a color property was added to the location marker to add markers with custom colors.
=> Location marker cleanup and compass relocation

src/qml/PositioningDeviceSettings.qml
Weird, Android (contrary to other platforms) doesn't seem to apply the inserts within one function, leading to chaos.
TIL: the only way to fix the glitches on Android platform is to bind the model to the listview _after_ adding/removing items.
=> Fix positioning device types list on Android

src/core/appinterface.cpp
This PR fixes #3704 , whereas captured photos were not properly rotated when applying a project's maximum image size (when set through qfieldsync).
=> When restricting image size, respect rotation metadata (fixes #3704)

src/core/appinterface.cpp
=> [Backport release-2_6] When restricting image size, respect rotation metadata (fixes #3704)

platform/android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java, platform/android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java, src/core/platforms/android/androidplatformutilities.cpp
This PR fixes #3736 and #3799 , whereas photos captured in QField Android with an expression that would create a folder not present during the initial project import would fail to copy via USB cable.
=> Fix USB copying photos captured by QField Android in a project subfolder created during capture

platform/android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java, platform/android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java, src/core/platforms/android/androidplatformutilities.cpp
=> [Backport release-2_6] Fix USB copying photos captured by QField Android in a project subfolder created during capture

src/core/platforms/platformutilities.cpp
=> [Backport release-2_6] As we do with Android and iOS, create QField's app data directory's subfolders

src/core/qfieldcloudconnection.cpp
@mbernasocchi , this is an answer to what you pointed out yesterday. QField didn't handle the 'maintenance' redirect scenario triggered by the outage, ending up in an infinite logging screen that never resolved to a success or failure.
=> Handling login error caused by redirect

src/core/attributeformmodelbase.cpp
Fix https://github.com/opengisch/QField/issues/3857 and harmonize handling of child feature's attribute linked to a parent feature in feature form. 
Until now, we were hiding a child feature's attribute linked to a parent feature from the feature form. This can create confusion (see issue above), and doesn't match QGIS' behavior. This PR goes for _disabling_ editing on the attribute instead of completely hiding it. IMHO, this is a better option and deliver a better representative of underlying data and relations.
=> Avoid hidding attribute linked to parent feature in relation, just disable

src/qml/FeatureForm.qml, src/qml/editorwidgets/UuidGenerator.qml
In QGIS, the UUID edit widget will create a unique UUID whether it's [x] editable or not, let's do the same, otherwise ppl are left with broken UUID widgets.
Seen while dissecting https://github.com/opengisch/QField/issues/3857.
=> Fix UUID edit widget not creating UUIDs when in read-only mode

src/core/layertreemodel.cpp
=> Fix layer tree node extent breaks map canvas for 1-point vector layers

.github/workflows/code_layout.yml
=> [Backport release-2_6] Ubuntu 18.04 image has been retired, causing failures

src/qml/imports/Theme/QfToolButton.qml
Many advantages, but the two biggest ones are:
- possibility to style the button color which will come in handy for non-default QField themes, as well as reducing need to maintain multiple versions of an icon merely to have different color state (also allows for nice animated transitions across colors)
- Bye bye blurry icons
=> Instead of a custom implementation, use QML Button's icon implementation

src/qml/MapCanvas.qml, src/qml/qgismobileapp.qml
With this PR, clicking twice on the bottom-right positioning button will have QField's map canvas follow _both_ the location as well as compass orientation.
=> Implement a follow compass orientation mode

src/core/attributeformmodel.h, src/core/attributeformmodelbase.cpp, src/qml/FeatureForm.qml
This PR implements feature form's attribute label font and color override:
=> Respect feature form's attribute label font and color override

.github/workflows/sync-translations.yml, scripts/ci/pull_translations.sh
As usual will fail due to forks not authorized to used secrets.
=> Fixing translation sync: first stab

images/images.qrc, images/themes/qfield/nodpi/ic_flash_auto_black_24dp.svg, images/themes/qfield/nodpi/ic_flash_off_black_24dp.svg, images/themes/qfield/nodpi/ic_flash_on_black_24dp.svg, src/core/appinterface.cpp, src/core/platforms/android/androidplatformutilities.cpp, src/core/platforms/android/androidresourcesource.cpp, src/qml/Changelog.qml, src/qml/QFieldCamera.qml, src/qml/QFieldSettings.qml, src/qml/imports/Theme/QfToolButton.qml
Enhancements include:
- significant UI/UX improvements
- zoom controls (pinch and mouse wheel, with button to reset to 1.0x zoom)
- flash controls
- GPS metadata
- video recording duration label
Still image capture:
Video capture:
The PR also fixes a longstanding issue whereas resizing photos to match the qfieldsync maximum image size setting would result in loss of metadata.
=> Non-native QML camera enhancements

CMakeLists.txt, src/core/CMakeLists.txt, src/core/appinterface.cpp, src/core/appinterface.h, src/core/platforms/platformutilities.cpp, src/core/utils/ziputils.cpp, src/core/utils/ziputils.h, src/qml/BusyOverlay.qml, src/qml/Changelog.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/qgismobileapp.qml, src/qml/qml.qrc
*A picture*
*An explanation*
This PR add a new 'import URL' action in the local data picker screen, which allows for users to paste a URL (say a dropbox link) and have QField automatically download and import the dataset or zipped project.
This is useful across Android and iOS, but comes in especially handy for iOS as it has currently no other mean to import datasets and projects nor file association. Without this, users have to do a fair amount of acrobatics when trying to import within the phone directly.
*Why ZipUtils?*
It's there until the ZipUtils::files() and the new parameter in ZipUtils::unzip() is upstreamed.
=> Import from URL action 

src/qml/QFieldLocalDataPickerScreen.qml
When writing documentation shows you that font declaration you'd missed...
=> Fix missing font declaration for import ULR dialog leading to tiny buttons

src/core/rubberbandmodel.cpp
This reverts commit adfdc1475eb87c46d357cf6c67f570983b438d92 , which turned out to break digitizing on (at least) shapefile layers with Z or ZM dimension geometries.
Fixes https://github.com/opengisch/qfieldsync/issues/504
Fixes #4035
=> Revert "Absence of data is not 0, use NaN"

src/core/CMakeLists.txt, src/core/qgismobileapp.cpp, src/core/utils/relationutils.cpp, src/core/utils/relationutils.h, src/qml/editorwidgets/RelationReference.qml
When the relation reference widget does not have a relation id set, in QField it will show "invalid relation". On QGIS it will fallback to any relation available for this field.
If no configuration is ever done on the attribute form (and only the relation is added in QGIS project properties) this situation occurs.
Fixes https://github.com/opengisch/QField/issues/4049
=> Fallback when relation id is not set

src/qml/RelationCombobox.qml
This fixes the black + button on dark theme:
=> Fix relation combobox add button's icon dark theme color

src/qml/QFieldCloudPackageLayersFeedback.qml
Fix black text on dark background seen here:
=> Fix QFieldCloud layer packaging feedback dialog text color with dark theme

src/qml/qgismobileapp.qml
This PR fixes the follow compass orientation threshold math to avoid a rotation for every tiny angle change.
Should fix https://github.com/opengisch/QField/issues/4127
=> Fix follow orientation math to avoid a refresh on every minor compass value change

src/qml/QFieldCloudPackageLayersFeedback.qml
=> [Backport release-2_7] Fix QFieldCloud layer packaging feedback dialog text color with dark theme

src/core/CMakeLists.txt, src/core/locator/expressioncalculatorlocatorfilter.cpp, src/core/locator/expressioncalculatorlocatorfilter.h, src/core/locator/locatormodelsuperbridge.cpp
In May, 2017, @nyalldawson , had a great locator filter idea in the form of an expression calculator. I've been using this every other week in QGIS, and it's time QField equips itself with the same nifty tool :)
In action, a simple math expression:
=> Add a nifty expression calculator in the search bar

src/core/featuremodel.cpp
This fixes value relations editor widget against array/list fields. Interesting corner scenario, glad I stumbled on this.
=> Objects and arrays are passed from QML to C++ as QJSValue objects, convert

images/icons/qfield_logo_beta.svg, images/icons/qfield_logo_pr.svg
The logos were using a dark shade of blue which didn't look great against dark gray backgrounds (such as our dark theme).
=> Dark theme friendly PR / nightly QField logos

src/core/featurelistmodel.cpp, src/qml/RelationCombobox.qml
This PR improves the value relation editor widget's search popup by placing matching features that *begins with* the searched term at the top of the list. In addition, the list will highlight in underscore the matching part.
In action:
A bunch of cleanups and optimization (e.g. avoiding double scrollview situation) also made their way into the widget.
Finally, the widget now behaves like QGIS when a preexisting attribute value is not found in the list. Instead of showing a blank, it now shows the value within brackets:
=> Value relation editor widget search improvements & cleanups

src/core/appinterface.cpp, src/core/appinterface.h, src/core/platforms/platformutilities.cpp, src/core/qgismobileapp.cpp, src/core/qgismobileapp.h, src/core/qgsquick/qgsquickmapcanvasmap.cpp, src/qml/QFieldSettings.qml, src/qml/VisibilityFadingRow.qml, src/qml/WelcomeScreen.qml, src/qml/qgismobileapp.qml
This PR implements a reload last opened project on launch functionality, which can be toggled on/off from within the welcome screen:
In addition to reloading the last opened project, QField allows for users to set a given project as the "default project"; if a default project exists, the reload project on launch function turns onto a "reload default project on launch", which can come in handy if users do not want file association launch of QField to overwrite the default project normally loaded. The option to toggle a given project as default project is found within the recent project actions menu:
The PR also cleans up a bunch of visual glitches when QField loads a project on launch (i.e. either via file association or this new functionality).
=> Reload last opened / default project on launch functionality

platform/android/src/ch/opengis/qfield/QFieldActivity.java, src/core/platforms/ios/iosplatformutilities.mm, src/core/platforms/platformutilities.cpp, src/core/positioning/abstractgnssreceiver.h, src/core/positioning/nmeagnssreceiver.cpp, src/core/positioning/nmeagnssreceiver.h, src/core/positioning/positioning.cpp, src/core/positioning/positioning.h, src/qml/PositioningSettings.qml, src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
This PR implements a new NMEA setence logging [to file] functionality. It can be activated when a bluetooth/tcp/udp postioning receiver is selected:
One file per session is created, with the following filename template (nmea-year-month-dayThours:minutes:secondes):
As per usual, I did a bit of cleanup here and there, and added a capabilities flag to our positioning receivers (future-proofing us some more).
=> NMEA sentence logging functionality

src/core/attributeformmodelbase.cpp
Ref: https://opengisch.sentry.io/issues/3728760751/?project=6119013&query=is%3Aunresolved+lastSeen%3A-20h&referrer=issue-stream&statsPeriod=14d&stream_index=7
=> Safeguard from crashing when an attribute form setData refers to out-of-model index

src/core/snappingresult.cpp, src/core/snappingresult.h
=> [Backport release-2_7] Store snapped vector layer as a QPointer<QgsVectorLayer>

src/core/attributeformmodelbase.cpp
=> [Backport release-2_7] Safeguard from crashing when an attribute form setData refers to out-of-model index

src/core/attributeformmodelbase.cpp
=> [Backport release-2_7] Revert "Update default values when editing a new feature to match QGIS behavior"

src/qml/About.qml, src/qml/FeatureForm.qml, src/qml/FeatureListForm.qml, src/qml/MessageLog.qml, src/qml/OverlayFeatureFormDrawer.qml, src/qml/QFieldCloudScreen.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/QFieldSettings.qml, src/qml/WelcomeScreen.qml, src/qml/qgismobileapp.qml
Had the opportunity to test QField's latest enhancements on an iOS device yesterday and saw a bunch of UI shortcoming with regards to handling of scene's bottom margin (i.e. the iOS navigation bar). This PR fixes all issues I've spotted yesterday.
The biggest one being the iOS bar overlapping the positioning information panel at the bottom of the main screen, preventing users from reading numbers there :scream:
=> Scene bottom margin improvements (i.e. avoid overlap with iOS navigation bar)

platform/android/src/ch/opengis/qfield/QFieldActivity.java, src/core/platforms/android/androidplatformutilities.cpp
Look at all that extra map canvas visibility:
Equally importantly, I came to realize we need this to insure the UI is sound on iOS (which is less frequently tested by main devs.). Case in point: https://github.com/opengisch/QField/pull/4199
=> Allow QField to draw under Android's bottom navigation bar

src/core/identifytool.cpp, src/core/multifeaturelistmodelbase.cpp
This PR improves feature list sorting by respecting the sorting expression defined in a given vector layer's attribute table configuration. If the sorting expression is empty, QField will fallback to sorting features by display expression. This enhancement results in a much friendlier display of features when identifying through map canvas taps or by through the show feature list button in the layer properties popup.
For documentation purposes, the way to configure an attribute table sorting is by:
a/ in table view, clicking on a column header (easy enough)
b/ also in table view, right clicking on any part of the column header and selecting the 'Sort...' menu item, giving users the possibility to enter complex expressions to sort features.
c/ in form view, clicking on the expression …
=> Feature list sorting capability 

src/qml/LocatorSettings.qml
"Trigger without its prefix" tends to be quite obscure to casual users.
I couldn't test (cannot build currently).
=> Simplify the wording for locator search

src/qml/qgismobileapp.qml
0.5s feels too sluggish, and we can _easily_ afford 0.25s.
=> Locking compass update rate to 0.5sec was maybe a too extreme, change to 0.2sec

src/qml/imports/Theme/QfTextField.qml, src/qml/qgismobileapp.qml
@suricactus , have you ever gone "CHRIST!" trying to hit that show password button? I've just gone through that pain one time too many.
The other commit is a cherry to avoid breakage on Qt6 builds (I didn't want to open two separate PRs).
=> Let's make sure the show password button has a sane finger hit area

src/qml/BluetoothDeviceChooser.qml, src/qml/DashBoard.qml, src/qml/NavigationBar.qml, src/qml/PositioningDeviceSettings.qml, src/qml/QFieldCloudScreen.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/QFieldSettings.qml, src/qml/RelationCombobox.qml, src/qml/SerialPortDeviceChooser.qml, src/qml/Tracking.qml, src/qml/WelcomeScreen.qml, src/qml/editorwidgets/EditorWidgetBase.qml, src/qml/editorwidgets/ValueMap.qml, src/qml/qgismobileapp.qml
Without this fix, combobox (and some non-combobox) popup menus can overlap the top and bottom margins, making it impossible for users to select the item(s) falling within those regions.
Fixes stuff like this:
=> Insure that all QField popup menus don't overlap with scene margins

src/qml/SensorInformationView.qml, src/qml/qgismobileapp.qml
Once again the creation of documentation led to the discovery of a glitch :)
PSA: the visible property shouldn't be use to drive a parent visibility state as the visibility state of children is *always* false when the parent is hidden. I keep forgetting this lesson.
=> Fix visibility toggling of sensors information panel

cmake/Platform.cmake, platform/android/build.gradle.in, platform/android/gradle.properties
More mergeable findings from https://github.com/opengisch/QField/pull/4229 .
=> Gradle-related fixes to avoid running out of memory and variable colision when building against Qt6

src/core/layertreemodel.cpp
Prevent multiple layers to appear selected in mutually exclusive groups.
=> Add `FlatLayerTreeModel::Visible` to be refreshed in QML on data change

src/core/layertreemodel.cpp
=> [Backport release-2_8] Add `FlatLayerTreeModel::Visible` to be refreshed in QML on data change

src/core/featuremodel.cpp
=> [Backport master] Attribute values need to be reset to have their default value calculated by QGIS

src/core/attributeformmodelbase.cpp, src/qml/FeatureForm.qml, src/qml/FeatureListForm.qml, src/qml/qgismobileapp.qml
The objective was to get rid of a glitch on Qt6 whereas the content of all tabs in a multitab feature form is shown overlapping one another. To do so, I needed to simplify the layout logic. There was a lot of unneeded layers / items which complicated the reading of the QML which is now gone (let's consider this a microoptimization too :) )
While I have not been completely successful (yet), this PR is worth merging; it does fix the feature form when first shown, so that's a nice win.
=> Modernize FeatureForm and FeatureListForm code a bit 

src/core/utils/snappingutils.cpp, src/core/utils/snappingutils.h, src/qml/CoordinateLocator.qml, src/qml/editorwidgets/TextEdit.qml
@mbernasocchi , you sir stumbled on a pretty nasty situation, this PR so fix it.
Long story short, until this PR, when loading a project, QField would *always* try to snap the coordinate cursor once, even when we are non in digitizing or measurement mode. This meant that as soon as a project had snapping turned out, we'd run a snap whether we need it or not.
Now, a snap can cost virtually nothing, or it can be hugely costly. In your case Marco, the project was set to snap on all layers, with two layers being two big WFS layers. This resulted in QField doing a background fetch of all feature for both layers during project load. :scream: 
This PR improves the situation by insure that we will only snap when the coordinate cursor is on. At the very least that'll get people to see their …
=> Avoid at times tremendous cost of snapping when cursor is not visible

src/app/main.cpp
Well, Qt 6.5.1 brought this real bad crash on app launch (works *once* then always crashes). Something to do with qml caching. We can disable for now until Qt fixes this regression...
=> Fix systematic crash of QField on launch

src/app/main.cpp, src/qml/DashBoard.qml, src/qml/LocatorItem.qml, src/qml/MapCanvas.qml, src/qml/OverlayFeatureFormDrawer.qml, src/qml/PositioningDeviceSettings.qml, src/qml/QFieldSettings.qml, src/qml/RelationCombobox.qml, src/qml/VariableEditor.qml, src/qml/editorwidgets/DateTime.qml, src/qml/editorwidgets/Range.qml, src/qml/editorwidgets/TextEdit.qml, src/qml/imports/Theme/QfTextField.qml
Polishing QField under Qt6, fixing our use of QML properties under Material 3 (i.e. Qt >= 6.5).
=> Qt6 QML polishing

src/core/utils/relationutils.cpp
=> [Backport master] Fix crash when QField exits with an open feature form containing relationships

CMakeLists.txt
(See https://github.com/microsoft/vcpkg/pull/29067)
=> Update vcpkg to fix 404 links on windows builds

src/qml/BadLayerItem.qml, src/qml/QFieldSettings.qml
Hopefully that covers all remaining scenarios we needed to account for the scene's bottom margin (i.e. nav bar overlay)
=> More bottom margins improvements

vcpkg/overlay/gdal/cmake-project-include.cmake, vcpkg/overlay/gdal/find-link-libraries.patch, vcpkg/overlay/gdal/fix-gdal-target-interfaces.patch, vcpkg/overlay/gdal/libkml.patch, vcpkg/overlay/gdal/portfile.cmake, vcpkg/overlay/gdal/usage, vcpkg/overlay/gdal/vcpkg-cmake-wrapper.cmake, vcpkg/overlay/gdal/vcpkg.json
This PR fixes https://github.com/opengisch/QField/issues/3611
=> Fix broken gdal JPEG driver on iOS by relying on internal lib

.github/workflows/android.yml, .github/workflows/code_layout.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml
Trying to avoid having half a dozen "build" checks, which makes it hard to figure out which is which:
The change also helps add critical contexts to the action page. See how easy it is to identify this action page as a linux build now that we have a proper label (instead of generic "build"):
=> Better github checks naming

src/core/qgismobileapp.cpp
This change relies on QGIS' optimal insertion method when opening individual datasets and insert the layers within a base map project.
For e.g, say your base map project layer tree looks like this:
- audio notes (point layer)
- satellite image (XYZ tile layer)
Until now, if you open a geotiff against that basemap project, it'd be added _at the very top_ of the layer tree, hiding the audio notes point layer. With this change, the geotiff would be inserted below all vector layers and above XYZ {raster,vector} layers. This is a much friendlier behavior that expands the uses for base map projects
=> Insert individual dataset layer(s) optimally within base map projects

src/core/bookmarkmodel.cpp, src/core/bookmarkmodel.h, src/qml/QFieldLocalDataPickerScreen.qml
Here's our 2.8.3 justification :) the copy bookmark details [text into clipboard] function broke in 2.7 or 2.6, this fixes the situation.
A tiny UI polishing commit also included to avoid triggering two PRs x 2 (master and backport).
=> Fix copying bookmark details into clipboard

src/qml/editorwidgets/+Qt5/ExternalResource.qml, src/qml/editorwidgets/+Qt6/ExternalResource.qml
This is an issue only present on the dev branch.
=> Properly reset the attachment editor widget to avoid previous image showing

src/qml/editorwidgets/ExternalResource.qml
Manual backport of https://github.com/opengisch/QField/pull/4373 , turns out it is also a problem on 2.8.2.
@suricactus , same commit you reviewed yesterday.
=> Manual backport of f3619c9

src/qml/editorwidgets/CheckBox.qml
Fixes https://github.com/opengisch/QField/issues/4380 .
Long story short, 1 is not equal to '1' :)
=> Fix checkbox editor widget value comparison

src/core/layertreemodel.cpp, src/core/layertreemodel.h, src/qml/LayerTreeItemProperties.qml
This PR adds a credits label in the layer properties popup. In action:
This can be quite useful when packaging projects to be released to the public and are under legal obligation or providing attribution (or you know, just because you're good person :wink:).
=> Add attribution/credits details in the layer properties popup

src/core/qgismobileapp.cpp
And with this 3-line change, we do much, much better with vector tile fonts out of the box:
=> Enable automatic fetching of missing fonts through QGIS' font manager

src/core/utils/geometryutils.h, src/qml/qgismobileapp.qml
This fixes https://github.com/opengisch/QField/issues/4414
TIL: in Qt5 QML, assigned an object property to a variant property would copy the value; in Qt6, it binds the variant to the object property. That's a pretty significant change.
E.g.:
property variant startPoint: undefined
startPoint = mapSettings.extent.center
In Qt5, startPoint would have a copied QgsPoint. In Qt6, it binds the value to mapSettings.extent.center and updates. Ouf.
=> Fix move feature(s) action

src/core/qgismobileapp.cpp
This PR makes QField a tiny bit more intelligent in the way it handled non single file export of atlas. If we're exporting a single atlas feature, QField will now open the resulting singular pdf.
=> Open exported atlas PDF in non-single file mode when only one feature is being escorted

src/qml/FeatureListForm.qml
Fascinating. This was _always_ broken, since day one. But, Qt5 QML was much more tolerant (read: way too tolerant) and would just allow for a list object to be passed as an int value. Good grief.
Fixes https://github.com/opengisch/QField/issues/4430
=> Fix the delete selected feature(s) action

src/qml/FeatureForm.qml, src/qml/RelationCombobox.qml
The big UX improvement is the addition of a visual feedback that tells the user that an entered auto-complete value is *not* within the value relation list:
[Screencast from 2023-06-25 16-57-20.webm](https://github.com/opengisch/QField/assets/1728657/16fac1ce-4619-464d-8239-69a565a55850)
The handling of the Enter/Return action has also been fixed to avoid a reset to NULL value when the user tries to submit an auto-completion via that key press.
=> Value relation editor widget autocomplete fixes and improvements

src/qml/FeatureForm.qml, src/qml/Legend.qml, src/qml/QFieldCloudScreen.qml, src/qml/WelcomeScreen.qml, src/qml/qgismobileapp.qml
Looks much, much better and feels integrated with other lists.
=> Harmonize pressed state legend items by using a ripple element

src/core/multifeaturelistmodel.cpp
This PR fixes https://github.com/opengisch/QField/issues/4404 and the title is self-explanatory.
=> Fix the show visible feature(s) action with reprojected layers

src/core/projectinfo.cpp, src/core/projectinfo.h, src/qml/DashBoard.qml, src/qml/Legend.qml, src/qml/qgismobileapp.qml
This PR improves the handling of QField's browse vs. digitize mode UX by remembering the mode _as well as the active layer_ across sessions _per project_. Gone are the days when users needed to open the dashboard and toggle digitize on for projects that are mainly used to... digitize :wink:
=> Remember project state mode (browse or digitize) and active layer across sessions

src/app/main.cpp, src/core/projectinfo.cpp, src/qml/OverlayFeatureFormDrawer.qml
TIL: aliasing an alias isn't something Qt6 likes (and really, isn't something we should do anyways).
=> Fix Qt >= 6.5.1 crasher, re-enable disk cache

src/qml/QFieldSettings.qml, src/qml/Tracking.qml, src/qml/editorwidgets/CheckBox.qml, src/qml/editorwidgets/Range.qml, src/qml/editorwidgets/TextEdit.qml, src/qml/editorwidgets/ValueMap.qml, src/qml/imports/Theme/QfTextField.qml
Qt 6.5.2 doesn't like a 1-pixel Rectangle TextEdit background item.
=> Fix QfTextField regression in Qt 6.5.2 and use the widget in more places

src/core/layertreemodel.cpp, src/core/layertreemodel.h, src/core/qgismobileapp.cpp, src/qml/Legend.qml, src/qml/imports/Theme/QfToolButton.qml, src/qml/qgismobileapp.qml
This PR implements a functionality to toggle individual vector layer's snapping enabled state for projects' snapping configuration mode set to advanced. A quick showcase first:
[Screencast from 2023-07-26 16-43-19.webm](https://github.com/opengisch/QField/assets/1728657/fe3064b1-2bdc-455b-80e3-fc3fd1cee943)
As with everything else we do in QField, the implementation tries to avoid adding UI elements until it is relevant and useful. As such, the snapping badges are only visible when QField is set to digitizing mode. When in browse mode, the badges disappear.
Alongside the previous PR that added a global snapping on/off switch, this gives us really nice snapping flexibility straight within QField.
=> Advanced snapping configuration toggling capability

src/core/positioning/nmeagnssreceiver.cpp
IMU altitude is always ellipsoidical, substract elevation_diff if orhometric altitude from device is selected
=> Fix IMU altitude computation

src/core/qgssggeometry.cpp, src/core/sgrubberband.cpp
The tiny buffering operation works wonders in taking care of overlapping vertices, and in doing so fix QgsTessellator crashes when creating a polygon highlight/rubberband.
=> Buffer polygons prior to passing them to QgsTessellator to fix crashes

src/core/qgsquick/qgsquickmapcanvasmap.cpp, src/core/qgsquick/qgsquickmapcanvasmap.h, src/qml/MapCanvas.qml, src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
This PR implements a map canvas quality property which allows users to trade rendering sharpness in favor of lower memory usage and rendering time. The UI is found in the settings panel below the language combobox:
Three quality settings are available: Best quality (current rendering), lower quality, and lowest quality.
Behind the scene, what we are doing is lowering the rendered output size to create smaller images resulting in smaller memory footprint (very useful for devices with low RAM) and less CPU cycles spent rendering (i.e., lowering battery drain).
Fixes #1447
=> Add a rendering quality property to the map canvas

src/qml/qgismobileapp.qml
The hoverHandler.hovered property does not reflect the actual hovered state of the map canvas, use the proper object property.
=> Use the proper hovered property that reflects skipped hovering

src/qml/NavigationBar.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/qgismobileapp.qml
Good lesson learned here: when a Text item's textFormat is set to anything but Text.PlainText, it'll enable a hover state (for hyperlinks) which interferes with HoverHandler items.
=> Avoid coordinate cursor label stealing hovering state, fix map canvas menu height

src/qml/qgismobileapp.qml
When we migrated to Qt6, we had to change our map canvas DPI from physical to logical DPI here (https://github.com/opengisch/QField/blob/master/src/core/qgsquick/qgsquickmapcanvasmap.cpp#L283). It resulted in a smaller search area on Android, which makes it quite hard to hit points.
The PR adjusts the value to be friendlier on highdpi screens using Qt6.
=> Tweak search radius value to take into account Qt6's change from physical to logical DPI

src/core/positioning/internalgnssreceiver.cpp, src/core/positioning/nmeagnssreceiver.cpp, src/core/positioning/positioning.cpp, src/core/positioning/positioning.h, src/qml/qgismobileapp.qml
When IMU is active, the GNSS device provides the position at the end of the pole.
The antenna height must not be subtracted again from the Z value.
=> Skip antenna height correction when IMU is active

src/core/qgsquick/qgsquickmapcanvasmap.cpp, src/core/qgsquick/qgsquickmapcanvasmap.h, src/core/tracker.cpp, src/qml/MapCanvas.qml, src/qml/qgismobileapp.qml
This PR implements a mean to force deferred repaints for all layer repaint requests _when one or more tracking sessions are ongoing_ to avoid a "frozen" map canvas state when tracked feature addition/change's repaint trigger interval is smaller than the time it takes to draw the canvas.
=> Force deferred repaint for all layer requests when tracking is on

platform/android/res/values/strings.xml, platform/android/src/ch/opengis/qfield/QFieldActivity.java
@m-kuhn , @ZsanettMed , fixes a crash reported on sentry-db-fwd (https://opengisch.sentry.io/issues/4041139270/?project=4504830515085312&query=is%3Aunresolved&referrer=issue-stream&stream_index=3)
=> Catch missing android activity and inform users instead of crashing

src/core/attributeformmodelbase.cpp, src/core/attributeformmodelbase.h, src/qml/FeatureForm.qml
This PR implements support for the {attribute,feature} form's text widget. The implementation takes a slightly different path from that of the QML and HTML container and apply the new path to the latter two; I'm hoping will result in faster feature form loading as it kills a few unnecessary QML item creations.
The PR also makes the text editor widget (as well as its QML and HTML siblings) dynamic and responsive to feature attribute value change as the feature is being edited.
Simple example: notice how the text editor's "parent feature details" text value changes as I'm picking a different parent feature in a parent<->child relationship:
[Screencast from 2023-08-23 18-22-42.webm](https://github.com/opengisch/QField/assets/1728657/5326beac-3aa3-4491-bcbe-73db155cdf7d)
=> Feature form's text widget implementation

src/qml/imports/QFieldControls/+Qt5/QFieldAudioRecorder.qml, src/qml/imports/QFieldControls/+Qt6/QFieldAudioRecorder.qml
A UI/UX shortcoming identified when working on the code reader. Equivalent commit for the code reader UI here (https://github.com/opengisch/QField/pull/4539/commits/49502b5574f7ec05d4951dc232fd20a54b79fc81)
=> Make the accept audio recording button valid state much more visible

src/core/CMakeLists.txt, src/core/locator/activelayerfeatureslocatorfilter.cpp, src/core/locator/activelayerfeatureslocatorfilter.h, src/core/locator/locatormodelsuperbridge.cpp, src/core/locator/locatormodelsuperbridge.h, src/qml/LocatorItem.qml, src/qml/LocatorSettings.qml, src/qml/qgismobileapp.qml
This PR adds a new functionality to the search bar: an active layer feature matching. To begin with, here's a screencast showcasing the UI/UX:
[Screencast from 2023-09-01 11-07-04.webm](https://github.com/opengisch/QField/assets/1728657/71fd9a70-7e97-4691-96ac-03dc190a0754)
Few notes:
- The search functionality _must be activated via its *f* prefix_ as the search can be quite costly;
- Contrary to the all features (within all layers) search, this search functionality allows for single character searches (thanks to it being prefixed), and will not only try to match against a feature's display name but also _all text and numerical fields_;
- When an attribute match occurs, the attribute value and attribute name are highlighted, while the feature display name is appended as a second text row …
=> Brand new search bar active layer feature matching functionality + UI/UX improvements

src/qml/Legend.qml, src/qml/LocationMarker.qml
Alright, this turned out to be quite an instructive investigation.
Animated QML items are great looking, but turns out they end up *flooding* the main app event queue, which in turn has some significant consequence when trying to invoke methods on the main app thread (e.g. rendering maps with data-defined expression that require a main thread method invocation).
The biggest issue here turned out to be the legend. _Even if_ an animated item is not visible, the animation does run and does trigger a lot of event. In our case, we had an animated tracker badge _for each legend item_ triggering events, which meant that a large project would create loads and loads of events.
Solution: if an animation isn't providing that much more visual feedback, kill it. If it's important or can be confined, …
=> Event queue optimizations

src/core/appinterface.cpp, src/core/appinterface.h, src/qml/MessageLog.qml, src/qml/qgismobileapp.qml, vcpkg/overlay/qgis-qt6/portfile.cmake, vcpkg/overlay/qgis-qt6/profiler.patch, vcpkg/overlay/qgis/portfile.cmake, vcpkg/overlay/qgis/profiler.patch
We've got the runtime profiler to thanks for the massive optimization found here (https://github.com/opengisch/QField/pull/4571), we might as well expose it :wink: 
It'll help advanced users getting a clear sense of rendering and project load bottlenecks.
Photo time:
Outputting the data through the message log also means users can send that over sentry, which I'm sure will come in handy.
Note: it requires upcoming 3.34 to work, so APKs won't show anything for now.
=> Runtime profiler logging capability

src/qml/FeatureForm.qml, src/qml/MapCanvas.qml, src/qml/qgismobileapp.qml
This fixes:
- deleting a parent feature being added following the addition of a child is not working
- stylus usage while adding a child geometry
- parent feature form being added not re-appearing after cancelling a child addition
In addition, some changes were committed to improve the stylus experience by attempting to work around Qt limitation / poor handling of the stylus. Massive UX improvement there.
=> Fix a couple of children geometry addition issues

src/core/tracker.cpp, src/core/tracker.h, src/core/trackingmodel.cpp, src/core/trackingmodel.h, src/qml/PositioningSettings.qml, src/qml/Tracking.qml, src/qml/TrackingSession.qml, src/qml/qgismobileapp.qml, src/qml/qml.qrc
This PR implements a new functionality to QField's tracker, allowing users to set a maximum distance tolerance in-between tracked points/vertices beyond which a received position will be flagged as erroneous.
UI-wise, it looks like this:
I've taken the opportunity to clean up the documentation a bit, as well as renaming a source file and some variables to (hopefully) increase readability of code.
=> Brand new tracker functionality: maximum distance tolerance

src/core/positioning/nmeagnssreceiver.cpp, src/core/positioning/positioning.cpp, src/core/positioning/positioning.h, src/core/qgismobileapp.cpp, src/qml/PositioningInformationView.qml, src/qml/PositioningSettings.qml, src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml, test/qml/tst_positioning.qml
This also avoid the possibility to make a double geoid correction (from device + from file)
- Orthometric is visible only for devices supporting it
- Geoid files are visibles only if available
=> Move Orthometric from device settings into Vertical grid shift correction combobox

src/core/attributeformmodelbase.cpp
Well, unsure why I went for the hyper convoluted way before now, but this code is much, _much_ cleaner.
Hoping this will fix some crash reported on sentry, e.g.:
https://opengisch.sentry.io/issues/4307906818/?project=6119013&query=is%3Aunresolved+child&referrer=issue-stream&statsPeriod=14d&stream_index=1
https://opengisch.sentry.io/issues/4483277442/?project=6119013&query=is%3Aunresolved+child&referrer=issue-stream&statsPeriod=14d&stream_index=3
https://opengisch.sentry.io/issues/4341391515/?project=6119013&query=is%3Aunresolved+child&referrer=issue-stream&statsPeriod=14d&stream_index=4
I can't reproduce myself but I'm hoping the simplified code will fix things.
=> Simplify logic of checking for failing hard/soft constraints in tabs/containers

platform/android/src/ch/opengis/qfield/QFieldActivity.java, src/core/appinterface.h, src/core/platforms/android/androidplatformutilities.cpp, src/core/platforms/android/androidplatformutilities.h, src/core/platforms/platformutilities.h, src/qml/DigitizingToolbar.qml, src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
This PR implements a mechanism through which volume keys on Android devices can be used to add or remove vertices while in digitizing mode. A new toggle in the Settings panel allows for users to disable the behavior.
This can be useful for people who walk around with the coordinate cursor locked to the current GNSS position and want to add vertices without the need to precisely hit the add vertex button on the screen.
=> Implement digitizing throuhg volume keys on Android devices

src/qml/editorwidgets/CheckBox.qml
Fix for a regression seen running against QGIS master.
=> Fix checkbox editor widget against datasets delivering boolean fields as strings

platform/android/AndroidManifest.xml.in, platform/android/src/ch/opengis/qfield/QFieldActivity.java
Starting with Android 13, a new pair of permissions is required to access to photos/images stored in the device's gallery. Without it, we hit a security error wall. 
This restores photo editing under these devices for the foreseeable future.
=> Add new image and video media reading permission on Android >= 13 (API >= 33)

src/qml/EmbeddedFeatureForm.qml, src/qml/LayerTreeItemProperties.qml, src/qml/TrackerSettings.qml
TIL: interestingly, Qt 6.5.3 doesn't like closing popup via deactivating a parent Loader item.  If the popup isn't closed when the Loaded is deactivated, the popup disappears but the shading overlay stays.
=> Tiny fixes/tweaks as we are marching towards release

src/core/linepolygonhighlight.cpp, src/core/linepolygonhighlight.h, src/core/rubberband.cpp, src/core/rubberband.h
Until now, we have been wasting quite a lot of CPU cycles re-building the OpenGL nodes of rubber band and line/polygon quick items every time the map extent changed. 
For simple panning operations, there are _no reason whatsoever_ we'd want to re-build the nodes, a simple setX() setY() transform will do.
When we zoom in or out, we eventually want to rebuild to make sure we're super accurate when zooming into _centimeter_ accuracy. 
This PR achieves that by triggering a rebuild when the map unit per point changes significantly/enough to justify the cost. 
On complex geometries, this makes panning around _blazingly fast_ when it used to be real sluggish until now.
=> Significant optimization in handling of rubber band and line/polygon items

src/core/utils/stringutils.cpp, src/core/utils/stringutils.h, src/qml/editorwidgets/TextEdit.qml
QField now handles insertion of hyperlinks in non-HTML text edit widget the same way QGIS does, which in turn fixes automatically inserted links (e.g. https://github.com/opengisch/QField/issues/4615)
=> Fix handling of non-HTML text values having had links inserted (fixes #4615)

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp, src/core/qgsquick/qgsquickmapcanvasmap.cpp
Fixes a 3.0 visual regression reported here (https://github.com/opengisch/QField/issues/4625). We're lucky, Qt 6.5.0 through to 6.5.2 had a regression which was fixed in 6.5.3, woupidou. 
Thanks to the user for reminding me to test this again.
=> Use screen's physical DPI value again, android regression fixed in Qt 6.5.3

src/core/attributeformmodelbase.cpp
Fixes the following sentry-reported crashers:
The issue reported here (https://github.com/opengisch/QField/issues/4636) will also be fixed by this. The virtual field was a red herring.
=> When resetting the attribute form model, clear the containers QMap to avoid crashers

src/core/attributeformmodelbase.cpp
=> [Backport release-3_0] When resetting the attribute form model, clear the containers QMap to avoid crashers

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
This fixes https://github.com/opengisch/QField/issues/4631
Qt6 doesn't allow a property int to be set to a string. Why Qt5 was allowing this to begin with is a mystery :)
=> Fix setting an int property to a string value breaks children deletion

src/core/referencingfeaturelistmodel.cpp
Our referencing feature list model was needlessly triggering (possibly costly) features fetches when the  referencing feature property was set with the exact same feature (which does happen when QML builds our feature form item). This offers yet another nice optimization for our feature form.
This PR also fixes https://github.com/opengisch/QField/issues/3031 . It doesn't fix the root cause of it (it freezes in the OGR connection pool, stuck in a loop evaluating expressions et al), but by axing the number of feature fetches by half, the connection pool never gets saturated.
=> Safeguard from triggering needless feature gathering when referincing feature list model gets passed the same feature

src/core/referencingfeaturelistmodel.cpp
=> [Backport release-3_0] Safeguard from triggering needless feature gathering when referincing feature list model gets passed the same feature

src/core/identifytool.cpp, src/qml/qgismobileapp.qml
Early in the post-Qt6 migration era, we had to increase the identify search radius as the DPI wasn't reflecting screen pixel density. It's been fixed now (thanks to Qt 6.5.3), we can go back to a slightly smaller search radius.
One reason why that's important is that we cap our feature request to 200 (it was 100 for years until today), but that doesn't yet filter out the features that are *not* rendered (due to out-of-scale or out-of-rule situations). If the search radius is too high, we end up with an oddly small number of features shown as identified, which could have felt like a regression on QField 3.
=> Revert increased identify search radius now that Qt6 DPI issue is resolved

src/qml/geometryeditors/FillRing.qml
=> [Backport release-3_0] Fix initiation of fill ring geometry editor, Qt6 isn't tolerant

src/core/rubberbandmodel.cpp
While the old logic worked fine *displaying* the rubber band, the logic prevented us from resuming the digitizing of a polygon through the resulting model as it was skipping the first vertex.
This fixes resuming of tracking against a polygon layer.
=> Use a better logic when building a rubber band model from a polygon geometry

src/core/qgssggeometry.cpp, src/core/sgrubberband.cpp
The rubber band uses scene coordinates, and when buffering it often creates vertices that are closer than what the QGIS tesselator likes, this PR fixes that (which means we don't suffer from highlights going missing when digitizing)
I've also taken the time to change the buffer style to reduce the number of additional vertices, we don't need round microscopic buffers :)
=> Fix rubber band polygon highlight going missing due to coordinate distance fail

src/core/linepolygonhighlight.cpp, src/core/rubberband.cpp
Title says it all.  We need to reset X,Y, and scale values when dirtying the rubber band (or line geometry) item to avoid glitches. Without this fix, moving around while digitizing features has the rubber band doing micro jumps.
=> Fix rubber band display 'glitchy' following optimization

src/core/rubberbandmodel.cpp
=> [Backport release-3_0] Use a better logic when building a rubber band model from a polygon geometry

scripts/build-for-linux.sh
@m-kuhn , I rebooted my home machine over the weekend and it took me longer than I care to admit to realize curl was needed when building with vcpkg. Let's make sure nobody else will scratch their head wondering why the boostrapping of vcpkg fails :)
=> Update build-for-linux.sh with additional requirement

src/core/appinterface.cpp, src/core/appinterface.h, src/core/positioning/gnsspositioninformation.cpp, src/core/positioning/gnsspositioninformation.h, src/core/positioning/positioning.cpp, src/core/positioning/positioning.h, src/core/qgismobileapp.cpp, src/core/utils/expressioncontextutils.cpp, src/core/utils/fileutils.cpp, src/core/utils/fileutils.h, src/qml/PositioningPreciseView.qml, src/qml/editorwidgets/+Qt5/ExternalResource.qml, src/qml/editorwidgets/+Qt6/ExternalResource.qml, src/qml/imports/QFieldControls/+Qt5/QFieldCamera.qml, src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml, src/qml/qgismobileapp.qml
This is some restructuring to prepare for interesting functionality. 
To begin with, this permits us to easily add a @{position,gnss}_orientation variable, which gives users the possibility of capturing in a feature attribute the orientation of the device during a point being captured.
This will also allow us (in a different PR) to write the orientation into an image file via exif tag writing.
=> Move the magnetometer reading into the c++ positioning class, add @{position,gnss}_orientation variable

src/qml/imports/QFieldControls/+Qt5/QFieldCamera.qml, src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml
This PR adds a UI  to the QField camera to toggle geotagging:
When enabled, the following tags are added:
- latitude, longitude, and altitude (provided they are valid values)
- ground speed
- compass orientation
=> Add QField camera UI to toggle geotagging

src/core/distancearea.cpp, src/core/locator/activelayerfeatureslocatorfilter.cpp, src/core/locator/bookmarklocatorfilter.cpp, src/core/locator/expressioncalculatorlocatorfilter.cpp, src/core/locator/featureslocatorfilter.cpp, src/core/locator/gotolocatorfilter.cpp, src/core/qfieldcloudprojectsmodel.cpp, vcpkg/overlay/qgis-qt6/exif_orientation_fix.patch, vcpkg/overlay/qgis-qt6/portfile.cmake
This PR fixes a bug causing the Exif.Image.Orientation value to be (re)written in a problematic way when maximum image size is enabled.
=> Fix problematic image orientation when maximum image size is enabled

src/core/linepolygonhighlight.cpp, src/core/rubberband.cpp
Hopefully this is the last regression we'll have to fix following the significant optimization of rubber band and geometry highlight items.
Fixes #4700.
I'd say this warrants a new release ASAP.
=> Fix display of rubber band and geometry highlight on rotated canvas

src/qml/imports/QFieldControls/+Qt5/QFieldCamera.qml, src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml
This is actually quite important as someone might turn (or even walk) away from their position/orientation at the time they snapped the photo prior to accepting the snapped photo.
=> Add GPS metadata to image reflecting the time the photo was snapped

src/core/linepolygonhighlight.cpp, src/core/rubberband.cpp
=> [Backport release-3_0] Fix display of rubber band and geometry highlight on rotated canvas

vcpkg/overlay/qgis-qt6/layout_fix.patch, vcpkg/overlay/qgis-qt6/portfile.cmake
Patching QGIS to include two layout fixes that plug a project load regression on QField introduced in 3.32. The two commits are:
- https://github.com/qgis/QGIS/commit/a0cdf36e0fc10b04afaaa4d270d4c90836236629
- https://github.com/qgis/QGIS/commit/87907a812f4901e7c028741a04e8aeb1ef290187
=> Fix significant project load regressions when multiple layout legends are present

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml
Without the extra module, Qt fails to load tiffs, which is required for the WMS provider to behave.
It also unlocks image/webp WMS layers.
=> Add qimageformats plugin to allow for tiff WMS layers

vcpkg/overlay/qgis-qt6/layout_fix.patch, vcpkg/overlay/qgis-qt6/portfile.cmake
=> [Backport release-3_0] Fix significant project load regressions when multiple layout legends are present

src/core/qgssggeometry.cpp, src/core/sgrubberband.cpp
This PR aims at fixing a crasher that emerged in QField 3.0.3:
Stacktrace:
Looking at the list of commits (https://github.com/opengisch/QField/compare/v3.0.2...v3.0.3) I can only see one culprit: the buffer parameter change here (https://github.com/opengisch/QField/commit/869c1977182b25ef989c27bd3dfbcc7a7a7e7e55#diff-6ec0f90b884446f8c30d9dd753160c7e100e8929ae79edd44679d1df523bee57R167)
The logic behind that change was to reduce the number of vertices produced by the buffering operation as a tiny optimization. That appears to have had negative consequences. Let's revert.
(Note that the other change, the removeDuplicateNodes call in the rubber band, is important and not tied to the crash, hence keeping it in.
=> Revert geometry/rubberband item's buffer parameter change

src/core/layertreemodel.cpp, src/core/layertreemodel.h
Trying to fix this (https://opengisch.sentry.io/issues/4569883968/?project=6119013&query=is%3Aunresolved&referrer=issue-stream&sort=user&statsPeriod=7d&stream_index=10) which has been a longstanding crasher, but appears to be more frequent in Qt6.
The stacktrace is really unhelpful, but it does tell us that FlatLayerTreeModelBase::data's check for a valid source model QModelIndex doesn't appear to be enough.
I think moving from a `QList<QModelIndex>` to a `QList<QPersistentModelIndex>` could improve things here.
=> Move from QModelIndex to QPersistentModelIndex in the layer tree proxy model class

src/qml/imports/QFieldControls/+Qt6/CalendarPanel.qml
=> [Backport release-3_0] Fix calendar panel not dark theme friendly and won't open to set date

src/qml/QFieldLocalDataPickerScreen.qml, src/qml/imports/QFieldControls/+Qt6/CodeReader.qml, src/qml/qgismobileapp.qml
=> [Backport release-3_0] Fix a bunch of QML warnings

src/core/appinterface.cpp, src/core/appinterface.h, src/core/layerobserver.cpp, src/qml/MessageLog.qml, src/sentry/sentry_classic.cpp, src/sentry/sentry_cocoa.mm, src/sentry/sentry_wrapper.h
=> [Backport release-3_0] Refine manual log submission

src/core/layertreemodel.cpp, src/core/layertreemodel.h
=> [Backport release-3_0] Move from QModelIndex to QPersistentModelIndex in the layer tree proxy model class

.docker/android_dev/Dockerfile, cmake/Package.cmake, scripts/build-vcpkg.sh, scripts/build.sh
Improvements:
- Fix building for arch other than arm64 (!)
- Use a single variable to drive Qt version number
- Avoid using "qfield" as app name so development doesn't come at the cost of removing the official QField installed through the play store :)
=> Improve android docker build process

src/qml/qgismobileapp.qml
After some more debugging, turns out adding a second finger onto the screen retriggers the whole hovering chain of event, however depending on how fast the second finger is added, the ordering is inconsistent. 
The solution here is to (re-)introduce a timer that gives us a threshold to have events go in any order Qt sees fit.
=> Re-introduce a timer to avoid finger hover / stylus interference

images/images.qrc, images/themes/qfield/nodpi/ic_3x3_grid_white_24dp.svg, src/qml/imports/QFieldControls/+Qt5/QFieldCamera.qml, src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml
This PR implements a grid overlay to QField's QML {still,video} camera. I've always found such a functionality super useful when trying to take technical photos. The overlay can be turned on/off via an overlay button located at the top left corner of the screen.
Screenshot time:
With that in, as well as the recent geotagging functionality, I'm wondering whether we should switch the default camera _back_ to the QML camera. People have reported the memory saturation crash gone when using the QML camera. Food for thoughts.
(Edit: forgot to mention the commit also fixes an issue with the capture/record button overlapping the system's bottom margin within which we shouldn't have anything interactive)
=> Add a grid pattern overlay feature to QField's QML camera

src/core/locator/activelayerfeatureslocatorfilter.cpp, src/core/locator/featureslocatorfilter.cpp, src/core/projectinfo.cpp, src/qml/LocatorItem.qml
This PR improves the handling of the search bar's filters list (i.e. when no search term is entered) by _disabling_ the active layer search item when no vector layer is active/selected in the dashboard's legend. The user will also be thrown a toast message if they click on the filter informing them of what is required to use the filter.
@mbernasocchi , as requested.
=> Search bar's filters list improvement

src/core/locator/activelayerfeatureslocatorfilter.cpp, src/core/locator/featureslocatorfilter.cpp, src/core/projectinfo.cpp, src/qml/LocatorItem.qml
=> [Backport release-3_0] Search bar's filters list improvement

src/qml/qgismobileapp.qml
=> [Backport release-3_0] Re-introduce a timer to avoid finger hover / stylus interference

src/qml/qgismobileapp.qml
This PR fixes the bug aspect of what was raised here (https://github.com/opengisch/QField/issues/4770). The screen lock mode definitively needs to prevent back button action. That was an implementation gap.
=> Fix screen lock not blocking back button presses

src/core/vertexmodel.h
The recent vertex editor addition exposed an issue with the registration VertexModel metatype interfering with Qgis enums.
In turn, that causes the smoke test to die (app launch doesn't like the Qt errors thrown). Luckily, the offending Q_PROPERTY in VertexModel isn't used so we can remove it.
I had seen this issue before, but the errors were triggered only when activating the vertex model (vs. now on app launch). We have other classes that have a Qgis::GeometryType Q_PROPERTY (e.g. rubberband), it's a mystery to me why VertexModel clashes here. I suspect it has to do with the Q_DECLARE_METATYPE( VertexModel::Vertex ); at the end of the header file as it is not present in other classes with the same property.
=> Remove unused property that creates tons of Qt warnings, which in turn breaks the smoke/spix test

src/qml/MapCanvas.qml
The muscle memory expecting panning when middle-click dragging on the canvas is really high, and ATM QField rotates when doing that. 
To harmonize with QGIS while still allowing for rotation, let's use shift+middle-click to rotate, and pan when no modifier is present. It also aligns with what GIMP does.
@suricactus , as discussed.
=> Add a shift modifier to rotate via hold middle-click, and go back to pan with no modifier

src/core/localfilesmodel.cpp
Before (left) vs PR (right):
Makes for a much cleaner view.
=> Hide project file's preview images from the local file picker/project folder

src/core/layertreemodel.cpp, src/core/layertreemodel.h
This reverts commit c37cef76d09b8c85874e4dbf330733416ee5e62e -- turned out to create a separate set of issues, including corruption of legend icons. Darn.
=> Revert "Move from QModelIndex to QPersistentModelIndex in the layer tree proxy model class

src/qml/CoordinateLocator.qml, src/qml/qgismobileapp.qml
This is a sister PR to https://github.com/opengisch/QField/pull/4789 -- now that we moved our rubber band rendering to rely on Shape, we benefit from revamping the coordinate locator to also rely on shape so we can aim at rendering the exact same visual buffer outlines.
I've taken the opportunity to clean up the item a bit and make it more QML-esque by relying for a property to style the snapped state.
But above all, the usage of a shape item gives us a lot more flexibility in the way we style the cursor, which allowed me to refine or cursor.
Video first:
[Screencast from 2023-11-21 20-15-18.webm](https://github.com/opengisch/QField/assets/1728657/3d94ffbd-a31c-4ad9-a11d-dbc81afa1de9)
Notice that when the cursor isn't snapped to a feature geometry, it now has an "open" look, whereas the …
=> Improve the looks and  behavior of the coordinate locator item

src/qml/ScaleBar.qml
Let's put an end of rectangle abuse and move to proper shape-based rendering.
One of the things it fixes is a small visual imperfection our scale bar had for as long as I can remember:
The inconsistent top of the tick's outline width is gone:
=> Improve scalebar rendering by moving to shapes

src/core/qfieldcloudprojectsmodel.cpp, src/core/qgismobileapp.cpp
@suricactus , a few notes on this:
- calling mProject->setFileName(QString()) does *not* clear the project, it merely changes the project file path string, which is used for e.g. in expressions when calling @project_folder. I've changed this to mProject->clear().
- I've removed the old way we were reloading the project when a synchronization (i.e. setting a signal connection in qgismobileapp.cpp via finding a child of the QML scene), it felt a bit shaky. Instead, we reload the project via appinterface which feels more straightforward. It took me way too long to find out where the connection was to begin with :)
- The PR also fixes an issue whereas downloading a cloud project would _always_ set the current project file name to '', which if you had a different project opened meant that …
=> Fix cloud project synchronization on Windows

src/core/featuremodel.cpp, src/core/featuremodel.h, src/core/layertreemodel.cpp, src/core/multifeaturelistmodelbase.cpp, src/qml/NavigationBar.qml, src/qml/qgismobileapp.qml
This PR implements a new expression driven locked geometry state for individual features within vector layers. This allows for a same layer to hold both features that have their geometry locked while others can still be edited. 
The code also covers moving of a group of selected features. If the group of selected features contains one or more locked features, it will not be possible to move the group. However, if all features are defined by the expression as not locked, group move will be allowed.
It's a really nice addition, makes it possible for administrators of project to define within a single layer features deemed as having a finalized geometry state vs. not.
Within a QFieldCloud environment, it gets even sweeter as cloud variables can drive locked state.
_(Requires this QFieldSync …
=> Implement expressed driven feature-level locked geometry

src/qml/CoordinateLocator.qml, src/qml/VisibilityFadingRow.qml, src/qml/qgismobileapp.qml
PR merely avoids having a column that shares both horizontal and vertical elements to insure the column size only covers buttons, not a large rectangle with a dead area.
=> Fix bottom-right stylus dead zone

.docker/android_dev/Dockerfile, .github/workflows/android.yml, cmake/Platform.cmake, scripts/build-vcpkg.sh
Hoping this can resolve an obscure armv7-only crash that appeared when we updated to Qt 6.6 (e.g. https://opengisch.sentry.io/issues/4561431917/?project=6119013&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=5)
=> Update Android NDK (r25) to match what is used in pre-built Qt libraries

.github/workflows/android.yml, platform/android/build.gradle.in
Seen references of sentry SDK 0.6.X fixing some crashes on Android r25b (what we use now).
Objective: the QField 3.1.1 release has been 20% deployed (earlier today) and I've spotted an immediate spike in sentry-related crashes. Doing some research on sentry SDK github's page indicates that our old sentry android version shipped with an SDK (0.5.4) that was prone to crashing.
I've asked @lindacamathias to test QField 3.1.1 on her old device, it crashes.
She then tried this PR, it doesn't crash anymore.
=> Sentry update

src/core/positioning/bluetoothdevicemodel.cpp, src/core/positioning/bluetoothreceiver.cpp, src/core/positioning/internalgnssreceiver.cpp
This fixes a crash on QField 3.1 whereas setting the GNSS receiver to an external device would crash.
The reason behind this crash is caused by the following chain of events:
1/ QField launches and activates positioning (per last session's setting);
2/ At this stage, the positioning is activating the internal gnss receiver, which calls handleConnect and request permission;
3/ After the permission is requested, but _before_ its signal is responded to, we restore the external positioning (per saved positioning ID), which means we kill the internal gnss receiver object
4/ the permission request triggers the signal, we answer to it, and we end up calling a function to a deleted object
To guard from this, this PR does two things:
1/ use the QCoreApplication::checkPermission function, avoiding …
=> Guard against null object when checking permissions

src/qml/qgismobileapp.qml
By triggering the toast on a onCheckedChanged signal, we end up pushing a toast message every time QField is launched. Reason why we didn't spot this earlier is because when the welcome screen is visible, toast messages aren't shown. But for users that launch QField through file association or having re-open last project toggled on, this message is super confusing for users.
=> Fix confusing 'snap to 45 degree' toast when opening QField

src/core/barcodedecoder.cpp
From google play store: 
```
#00  pc 0x00000000005274d8  /data/app/~~NvLQJeNXuJ1MIvzR2SZqNA==/ch.opengis.qfield-OYiB52lJAdLR_0PRU7Huow==/lib/arm64/libQt6Gui_arm64-v8a.so (BuildId: 0dec58bd9c200cd94edc46d18eee12fee52ae8dc)
#01  pc 0x00000000005280b0  /data/app/~~NvLQJeNXuJ1MIvzR2SZqNA==/ch.opengis.qfield-OYiB52lJAdLR_0PRU7Huow==/lib/arm64/libQt6Gui_arm64-v8a.so (BuildId: 0dec58bd9c200cd94edc46d18eee12fee52ae8dc)
#02  pc 0x000000000044d134  /data/app/~~NvLQJeNXuJ1MIvzR2SZqNA==/ch.opengis.qfield-OYiB52lJAdLR_0PRU7Huow==/lib/arm64/libQt6Gui_arm64-v8a.so (QRhi::endOffscreenFrame(QFlags<QRhi::EndFrameFlag>)+64) (BuildId: 0dec58bd9c200cd94edc46d18eee12fee52ae8dc)
#03  pc 0x00000000000c7978  /data/app/~~NvLQJeNXuJ1MIvzR2SZqNA==/ch.opengis.qfield-OYiB52lJAdLR_0PRU7Huow==/lib/arm64/libQt6Multimedia_ …
```
=> Add an additional safeguard when the barcode decoder attempts to process a video frame

src/core/qgismobileapp.cpp, src/core/qgismobileapp.h
Crash seen on google play store's crash reporting (which is becoming quite good):
```
backtrace:
#00  pc 0x0000000001eb0264  /data/app/~~AidkTkmVejfLrdD_MYFiCA==/ch.opengis.qfield-thT7LfUTg_MgkCMOzMjSww==/lib/arm64/libqfield_arm64-v8a.so (QgsQuickMapCanvasMap::isRendering() const) (BuildId: a75578015316ac7d9753d901e88698581a3e774f)
#01  pc 0x0000000001f8979c  /data/app/~~AidkTkmVejfLrdD_MYFiCA==/ch.opengis.qfield-thT7LfUTg_MgkCMOzMjSww==/lib/arm64/libqfield_arm64-v8a.so (QgisMobileapp::saveProjectPreviewImage()+52) (BuildId: a75578015316ac7d9753d901e88698581a3e774f)
#02  pc 0x0000000001f89430  /data/app/~~AidkTkmVejfLrdD_MYFiCA==/ch.opengis.qfield-thT7LfUTg_MgkCMOzMjSww==/lib/arm64/libqfield_arm64-v8a.so (QgisMobileapp::loadProjectFile(QString const&, QString const&)+2420) (BuildId: …
```
=> Play it safe, use a QPointer to the map canvas item to reduce risks of crash

src/core/projectinfo.cpp, src/core/projectinfo.h, src/qml/Legend.qml, src/qml/qgismobileapp.qml
This PR reworks the way we save and restore user-customized layer styling (label visibility and layer opacity) as well as layer/project snapping enabled state. The previous way was saving and restoring whole layer XML style and snapping configuration, which resulted in subsequent changes to project configuration not respected by QField.
This meant that until now, symbology / labeling changes to a given layer or tweaking to advanced snapping configuration (e.g. snapping to vertex + segment instead of vertex alone) would not be loaded properly.
I'm shocked it took us so long to realize this was an issue, esp. considering it "freezes" symbologies. 
Fixes https://github.com/opengisch/QField/issues/4866.
=> Fix significant issues with saving/restoring customized project settings

vcpkg/overlay/qgis-qt6/portfile.cmake, vcpkg/overlay/qgis-qt6/wrongattributeerrormessage.patch
Because this is really uncomfortable to decipher and debug
=> Improve error message on value not compatible with attribute type

src/qml/MapCanvas.qml, src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml, src/qml/qgismobileapp.qml
The PR fixes one corner scenario identified whereas the timer resetting the skipHover boolean could happen at the same time as a second tap on the screen, resulting in the stylus hover being wrongly triggered as skipHover was then set to false.
Other code changes are made to strengthen the handling of the dummy hover.
With these changes in, things appear to be in good shape.
----
----
After more debugging, another crucial finding: once the PinchArea is active, the dummy hover handler that is safeguarding taps from being registered as stylus is not working because the PinchArea prevents the latter from stealing focus. 
We must therefore also keep track of the pinch state. One more corner scenario fixed.
----
Also turns out that an hoverhandler on Android won't "de-hover" when using edge …
=> Further strenghten finger hovering protection

src/qml/editorwidgets/DateTime.qml
I am not sure why was that `label.text` was not updating when `main.value` was updated, but this seems to solve the issue. Also note that in my understanding the `main.currentValue` was no longer used in the code, so I took use of it.
Finally, I also changed the `if` on line 45, so when the value is set to `null` it does not become automatically 1970-01-01 .
Steps to reproduce (before this patch is applied): 1) Open a feature form with date field
2) Click on set to now button
3) Delete the contents
4) Click on set to now button
5) Nothing happens
Inspured by #4803 report.
=> Date field does not update value when modified in QField

src/qml/geometryeditors/FillRing.qml, src/qml/geometryeditors/SplitFeature.qml
=> Properly cancel geometry editor's fill ring and split feature tools

src/qml/qgismobileapp.qml
To avoid the following:
https://github.com/opengisch/QField/assets/1728657/4b294bab-e283-430f-9e31-304dbdd0fe9c
=> Disable map canvas interaction when the QFieldCloud projects panel and the local data picker panel are visible too

src/qml/CoordinateLocator.qml
@suricactus , the removed `!!mapSettings.visibleExtent` check in the displayCoordinate property was actually important, without it, the coordinate isn't refreshed when panning/zooming around, which results in the cursor not sticking to position.
=> Fix coordinate cursor locked to position not sticking to position

src/qml/qgismobileapp.qml
=> [Backport release-3_1] Disable map canvas interaction when the QFieldCloud projects panel and the local data picker panel are visible too

src/qml/geometryeditors/FillRing.qml, src/qml/geometryeditors/SplitFeature.qml
=> [Backport release-3_1] Properly cancel geometry editor's fill ring and split feature tools

src/qml/QFieldCloudPopup.qml
Fixes this:
It's a master-only regression, no need for backport.
=> Fix wrong color of undo icon in the cloud popup panel

src/core/attributeformmodel.cpp, src/core/attributeformmodel.h, src/core/attributeformmodelbase.cpp, src/core/attributeformmodelbase.h, src/core/featuremodel.cpp, src/core/referencingfeaturelistmodel.cpp, src/core/referencingfeaturelistmodel.h, src/qml/editorwidgets/RelationReference.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
This PR unlocks addition of children features to a parent feature that is being added _but not yet created_ . There is logic in there to recognize attribute values that are provided by the data provider upon feature creation (e.g. "fid") and propagate that to children features to guarantee the parent<->children relationship is maintained.
In addition, the PR adds a currently missing parent form scope (i.e. @current_parent_{value,feature,geometry}). This allows for default value expressions to capture the parent feature's values without the need to rely on the get_feature(). The latter wouldn't work when adding a new feature which hasn't been committed yet.
I.e., getting a parent feature's attribute would be `attribute(@current_parent_feature,'my_attribute_name')` instead of …
=> Allow for children to be added to a parent feature being added but not yet created

CMakeLists.txt, src/core/CMakeLists.txt, src/core/barcodevideofilter.cpp, src/core/qfieldcloudconnection.cpp
Since we're not glued to Qt 5.14 anymore, we can make the Qt minimum version 5.15, and in doing so we get rid of the need to link against OpenGL for barcode decoding.
=> QField needs OpenGL linking no more

src/core/changelogcontents.cpp
This PR gives us the possibility to filter out chunks of our release changelogs based on the platform QField is being executed from. The functionality relies on markdown  to mark boundaries of platform-specific blocks. It also has the benefit of showing *everything* when viewing the release changelogs on a browser.
E.g., this would tell our changelog code that the block is Android-specific, which we would only show for QField instances run on Android:
```
- Camera won't crash anymore!
```
The logic also allows for multiple platforms, e.g. this would be shown on all desktop platforms:
```
- Fullscreen mode implemented, just hit f11!
```
=> Implement a mean to filter out platform-specific parts of release changelogs

src/qml/About.qml, src/qml/LayerTreeItemProperties.qml, src/qml/NavigationBar.qml, src/qml/QFieldCloudScreen.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/WelcomeScreen.qml, src/qml/editorwidgets/TextEdit.qml, src/qml/imports/Theme/Theme.qml, src/qml/qgismobileapp.qml
This results in a much nicer main menu button (following our re-work of it to include a top row of icons). It also slightly increases the hit area, which feels better.
Before (left) vs. PR (right):
=> Improve and harmonize menu item's left padding throughout QField

src/qml/imports/Theme/QfToolButton.qml
Just noticed that the QML camera's "capture" button is missing a ripple effect, making it hard to figure out whether an action was taken. Cause was a bad logic for ripple effect's color pick on dark theme.
=> Fix handling of ripple effect on tool buttons in dark mode

.github/workflows/android.yml, .github/workflows/ios.yml, scripts/ci/upload_artifacts.sh
Currently apks are named like `qfield-v3.1.7-arm64-android.apk`, whereas other platforms do `qfield-v3.1.7-windows-x64.exe`
This changes the scheme and it's now `qfield-v3.1.7-android-arm64.apk` which also makes the android artifacts appear next to each other on the release page
=> Align apk naming

src/core/layertreemodel.cpp, src/core/layertreemodel.h, src/core/qgismobileapp.cpp, src/qml/qgismobileapp.qml
When opening or reloading a project, clear the previous one to empty the layer tree, which should avoid pointer to removed source layer tree items. 
Furthermore, we're doing a better handling of project clearing by removing the source mapping _at the beginning_ of the clearing.
=> When opening or reloading a project, clear the previous one to empty the layer tree

i18n/qfield_ar.ts, i18n/qfield_bg.ts, i18n/qfield_bs.ts, i18n/qfield_cs.ts, i18n/qfield_de.ts, i18n/qfield_en.ts, i18n/qfield_es.ts, i18n/qfield_fi.ts, i18n/qfield_fr.ts, i18n/qfield_gl.ts, i18n/qfield_hr.ts, i18n/qfield_hu.ts, i18n/qfield_id.ts, i18n/qfield_it.ts, i18n/qfield_ja.ts, i18n/qfield_ka.ts, i18n/qfield_ko.ts, i18n/qfield_nl.ts, i18n/qfield_pl.ts, i18n/qfield_pt.ts, i18n/qfield_pt_BR.ts, i18n/qfield_ro.ts, i18n/qfield_ru.ts, i18n/qfield_sk.ts, i18n/qfield_sl.ts, i18n/qfield_uk.ts, i18n/qfield_zh.ts
Thanks to @zhuwq75 for alerting us to the fact that our translation synchronization was broken. 
The lupdate version we were using in the relevant workflows until now was 5.12 (ubuntu 20.04). After updating the workflow to ubuntu 22.04 to get lupdate version 5.15, over a hundred crucial strings that had disappeared are now back. 
This is a backport fix, master has been fixed by the updated workflows already.
=> Fix translation files after updating to lupdate 5.15

src/core/qgismobileapp.cpp
See https://opengisch.sentry.io/issues/4868150364/events/5b17c754818442d7865406c574cdca77/?project=6119013&query=is%3Aunresolved&referrer=next-event&statsPeriod=14d&stream_index=8
To reproduce the crash on Android with QField 3.1.8, follow these steps:
- Open QField, load a project (sample bees)
- Put QField in the background, and through file association (say a messenger app with a geopackage), open a dataset or zipped project
- QField is brought back to the front, and *boom*
That's because we were clearing the project in QgisMobileapp::loadProjectFile when called by AppInterface::instance()->loadFile _from the java the activity thread_. Solution is to clear the project somewhere else when that is triggered by the QML scene, which is on the same thread as the QgsProject member.
=> Clear project in readProjectFile to avoid threading issues

src/qml/BadLayerItem.qml
|-|-|
| ![image](https://github.com/opengisch/QField/assets/2820439/715080dc-c3e5-47a7-9705-a699353c379e) | ![image](https://github.com/opengisch/QField/assets/2820439/51c7be24-1a21-434b-8b9c-348781c89cd7) |
=> Add a link to "Portable project" docs instead of reference only

src/core/appinterface.cpp, src/core/appinterface.h, src/core/qgismobileapp.cpp, src/core/qgismobileapp.h, src/qml/QFieldCloudScreen.qml
1) download cloud project
2) open it
3) go back to qfc projects screen
4) delete it
5) go to main screen
6) clicking top-right back to current project shows some non-sense
=> Do not allow to return to current project if it is a deleted cloud project

src/core/featuremodel.cpp, src/core/layertreemodel.cpp, src/core/qgsquick/qgsquickelevationprofilecanvas.cpp, src/core/utils/geometryutils.cpp
We can't get rid of Qt deprecated warnings, but we sure can deal with the QGIS ones :)
=> Remove a couple of QGIS deprecated function warnings

vcpkg/overlay/jasper/check-for-atomics-support.patch, vcpkg/overlay/jasper/fix-library-name.patch, vcpkg/overlay/jasper/no_stdc_check.patch, vcpkg/overlay/jasper/portfile.cmake, vcpkg/overlay/jasper/vcpkg.json
@m-kuhn , here we go, backport-only
=> [backport release-3_1] Temporarily add jasper overlay to fix windows build

src/core/qgismobileapp.cpp
At the very least, that will trigger an aboutToBeCleared signal which will freeze the layer tree from responding to layer removal signals, which should speed exit time.
Also hoping it'll address this: https://opengisch.sentry.io/issues/4832201805/?project=6119013&query=is%3Aunresolved+release%3A%22ch.opengis.qfield%403.1.9%2A%22&referrer=issue-stream&sort=user&statsPeriod=24h&stream_index=2
=> Clear project on exit instead of only removing all layers

src/qml/LayerTreeItemProperties.qml
@mbernasocchi , :gift: sledge's learned lesson: don't make it so hard to find QField's tracking functionality :wink:
=> Be cool, just activate positioning instead of hiding the tracker button

src/core/navigation.cpp, src/core/navigationmodel.cpp, src/core/qgismobileapp.cpp, src/qml/WelcomeScreen.qml, src/qml/qgismobileapp.qml
I was testing https://github.com/opengisch/QField/pull/4988 on iOS yesterday when I realized modified settings were for the most part never saved. That's because on iOS, there's no double back button quitting per say, only force quitting by swiping the app up.
This commit remedies to that situation. It also benefits Android when people force kill app. Simple step to reproduce issue:
- Open QField
- Load bees project
- Add a navigation destination (long press on canvas -> set as destination)
- Suspend QField, then force kill it by showing running apps and swipping QField up into nonexistence)
- Re-open QField, destination gone.
=> Write settings to permanent storage when OS or user force kills app

src/core/layerobserver.cpp
In theory it is possible to have a layer becoming from invalid to valid, even though not directly observed. IMO having the signal handlers will not hurt even if the layer remains invalid.
=> Add layer observer signal handlers even if the layer is invalid

src/qml/PositioningPreciseView.qml
This PR fixes https://github.com/opengisch/QField/issues/5021 whereas QField precise view was broken on compass-less devices.
=> Fix precise view on compass-less devices

.github/workflows/ios.yml, .github/workflows/macos.yml, vcpkg/triplets/arm64-osx.cmake, vcpkg/triplets/x64-osx.cmake
So far we have build dependencies and application for different versions of x64-osx. This is now fixed to 10.15 (should hopefully be old enough to keep some hardware working).
Also introduces cancellation of parallel jobs on the same PR.
And uses a newer macos version (13) to build for mac
=> Fix deployment target for x64-osx

src/qml/Toast.qml
This PR kills a bunch of frustrating scenarios with the toaster message by:
- insuring that the hit area to close the message on top matches the size of the toast message;
- leaving a gap on the right and left edge so people can still interact with map canvas edge tool buttons;
- closing the toaster message on pressed rather than clicked event.
=> Toaster quality of life improvements

src/core/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloudprojectsmodel.h
This fixes situations where projects made public are not appearing in the "My Projects" tab even though they should when the user role origin is *not* 'public' (i.e. owner, collaborator, team_member).
This made it virtually impossible to find your own collaborating projects as soon as they were made public as on QField it'd mean opening the community tab, which triggers a loooong projects fetch.
=> Cloud projects where a given user role isn't originating from 'public' should be in My Projects tab

src/core/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloudprojectsmodel.h, src/qml/QFieldCloudPopup.qml, src/qml/QFieldCloudScreen.qml
This PR improves the cloud project download/synchronization UX  by providing better feedback to users, including:
- Having a functional progress bar reflecting download % in the cloud projects list (until now, it was always indefinite)
- Adding a progress bar in the cloud project popup when hitting synchronize
- Making a better job at differentiating packaging job waiting vs. initial communication to server vs. download (on the projects list, due to a broken logic, it could be stuck never reaching the download % feedback)
- Adding total download size detail (e.g., Downloading, fetched %10 of 200MB).
In action:
[Screencast from 2024-02-23 16-24-11.webm](https://github.com/opengisch/QField/assets/1728657/45ee1fd9-7dea-4b9c-be27-8893c86a8134)
[Screencast from 2024-02-23 …
=> Improve cloud project download/synchronization feedback

.github/workflows/windows.yml, cmake/qgis-cmake-wrapper.cmake, vcpkg/ports/qgis-qt6/portfile.cmake, vcpkg/ports/qgis-qt6/sts.patch
Windows builds are broken with the following error:
```
FAILED: output/bin/qfield_spix.exe 
C:\Windows\system32\cmd.exe /C "cd . && D:\a\_temp\390076282\cmake-3.28.3-windows-x86_64\bin\cmake.exe -E vs_link_exe --intdir=src\app\CMakeFiles\qfield_spix.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\Llvm\x64\bin\lld-link.exe /nologo @CMakeFiles\qfield_spix.rsp  /out:output\bin\qfield_spix.exe /implib:src\app\qfield_spix.lib /pdb:output\bin\qfield_spix.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console  /DEBUG /OPT:REF /OPT:ICF  && C:\Windows\system32\cmd.exe /C "cd /D C:\builddir\src\app && "C:\Program Files\PowerShell\7\pwsh.exe" -noprofile …
```
=> Update QGIS to 3.36.0 final (+fix windows build following runner image update)

src/core/deltafilewrapper.cpp, src/core/deltafilewrapper.h, src/core/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloudprojectsmodel.h, src/qml/QFieldCloudPopup.qml, src/qml/qgismobileapp.qml
First, a glorious image:
Now the description :wink: 
This PR improves the delta file wrapper (keeping track of changes done by users) by adding an awareness of a "pushing" state. When in that state, the delta file wrapper will continue collecting changes, but will keep them pending until we either:
- successfully pushed the previous deltas, upon which the deltas collected during the "pushing" state are added to a new deltas "ID"; or
- fail at pushing the previous deltas, upon which the deltas collected during the "pushing" state are added *on top* of the previous deltas.
This means that we have a fully functional QField _while pushing_, insuring that no data addition/editing/deletion is loss while communicating to the cloud server. 
At this stage, this already fixes a known data loss …
=> Enable background pushing of changes to the cloud as well as automated auto-push

src/core/projectinfo.cpp, src/core/projectinfo.h, src/qml/qgismobileapp.qml
Quiet weekend means a surprise enhancement :wink:
This PR implements basic support for tile and copyright decoration handling (provided those have been enabled in the QGIS project file).
In action:
[Screencast from 2024-02-20 10-15-12.webm](https://github.com/opengisch/QField/assets/1728657/5d9444c0-23ef-4419-af28-29a27c01b131)
=> Implement basic support for title and copyright decoration

src/core/appinterface.cpp, src/core/appinterface.h, src/core/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloudprojectsmodel.h, src/core/qgismobileapp.cpp, src/core/qgismobileapp.h, src/qml/QFieldCloudPopup.qml, src/qml/qgismobileapp.qml
This PR ties in with the following qfieldsync improvement: https://github.com/opengisch/qfieldsync/pull/566
QField will now read and respect the auto-push settings defined in a project file, insuring that people managing a 'fleet' of QField users can easily deploy auto push to their users and insure it's turned on.
=> Enforce auto-push settings coming from the project file

src/core/locator/locatormodelsuperbridge.cpp
Let's disable it for QField 3.2 release. There's no point in shipping a broken locator, it just leads to confusing UI. We can re-enable once the API access situation is resolved.
=> Disable Finnish address search locator until API access can be restored

.github/workflows/android.yml
We live in a world with limited resources
=> Enable concurrency groups on android workflows

test/spix/smoke_test.py
Thanks to our postgis instance's recent lack of stability, I've noticed the test covering postgis SSL connection is wrongly named.
=> Rename test function name (old copy/paste typo)

src/qml/editorwidgets/+Qt5/ExternalResource.qml, src/qml/editorwidgets/+Qt6/ExternalResource.qml
Fixes issue reported here: https://github.com/opengisch/QField/issues/5057
Edit: it's halfway in-between bug fix and new functionality as loading of http(s) images was never officially supported :)
=> Allow for http(s) images and videos to display in attachment widgets

src/core/qfieldcloudprojectsmodel.cpp
The expected workflow is to either "push" or "sync" changes to QFC. If one is just pushing, then it is weird to "sync", because one should have clicked "sync" in the first place.
Anyway, my assumptions were wrong and people were reporting a non-existent bug. Therefore I suggest we reduce the cache just 1s, so at least we don't bombard the QFC API with multiple requests per second.
=> Cache for 1s instead of 5s because of impatient users reportining bugs

images/images.qrc, images/themes/qfield/nodpi/ic_pin_black_24dp.svg, src/core/featuremodel.cpp, src/core/projectinfo.cpp, src/core/projectinfo.h, src/qml/FeatureForm.qml
QGIS has a nice attribute form field configuration that defines whether entered attribute values while digitizing a new feature should be remembered when adding subsequent feature(s):
QField has had that option for a long time, in fact longer than when this was introduced, which explains why when the configuration was added upstream, we skipped that beat. This PR embraces the QGIS setting.
This decomplexify data entry for field users as it removes the need to click on that 'remember' checkbox at least once per session, and can help project managers in not having to teach users how to activate this as they can configure it on behalf of users in the project file itself.
The PR also tries to improve the QField UI around this functionality by moving away from a label-less checkbox towards a …
=> Embrace QGIS' reuse last entered value setting

src/core/deltalistmodel.cpp, src/core/deltalistmodel.h, src/qml/QFieldCloudDeltaHistory.qml
At least show some indication that no changes have been pushed yet.
|-|-|
| ![image](https://github.com/opengisch/QField/assets/2820439/044c9c04-0f1b-4386-b3b9-6d4a766bb4d9) | ![image](https://github.com/opengisch/QField/assets/2820439/af280764-b1b8-4c0f-9d1b-7796f5ad457c) |
Here how it looks in the white theme:
=> Fix changes list popup looking broken when empty

src/core/projectinfo.cpp, src/core/projectinfo.h, src/core/qfieldcloudconnection.h, src/core/utils/qfieldcloudutils.cpp, src/core/utils/qfieldcloudutils.h, src/qml/DigitizingToolbar.qml, src/qml/EmbeddedFeatureForm.qml, src/qml/FeatureListForm.qml, src/qml/OverlayFeatureFormDrawer.qml, src/qml/TrackerSettings.qml, src/qml/TrackingSession.qml, src/qml/geometryeditors/VertexEditor.qml, src/qml/qgismobileapp.qml
So far the `cloud_username` and `cloud_email` variables were only available if the user successfully logs in. This PR stores the project's cloud username and email as project info that can be retrieved even when offline.
Tested when the username changes or very slow login, the QGIS expression variable value updates as soon as the cloud response is received.
Fixes #5116 and https://github.com/opengisch/QField/discussions/5088
=> Add the ability to use `cloud_username` and `cloud_email` in offline

src/core/qfieldcloudconnection.cpp
It breaks the QField message log, as it supports HTML.
| before | after | 
|-|-|
| ![image](https://github.com/opengisch/QField/assets/2820439/74b467fb-78df-4cd8-853b-e7abcdd7be2a) | ![image](https://github.com/opengisch/QField/assets/2820439/d00504a4-ffa4-47d1-bb53-0e312dd57778) |
=> Strip HTML when receiving HTML server errors in cloud API

src/core/qfieldcloudprojectsmodel.cpp, src/core/utils/fileutils.h, test/test_deltafilewrapper.cpp
Use `md5` checksum instead of `sha256` checksum to gain extra performance
when downloading packaged files in QField. The `sha256` causes N+1 requests
to the S3 storage, therefore makes the QFieldCloud response on the 
`packages/<projec-id>/latest` endpoint super slow.
This change will cause an extra initial download of the project file for
all users when they sync, since we renamed `lastProjectFileSha256` to
`lastProjectFileMd5`. IMO it is acceptable, otherwise we have to handle
extra code that I would prefer not to maintain.
See https://github.com/opengisch/qfieldcloud/pull/885
=> Performance boost when downloading packages

src/core/positioning/positioning.cpp
If we emit the averagedPositionCountChanged() signal before positionInformationChanged(), we end up with QML code handling the averaged position information from the previous averaging. Moving the signal at the very end insures that the right averaged location & information is used when adding vertices.
=> Avoid last averaged position not taken into account when adding vertex

src/qml/PositioningInformationView.qml
Fixes the bug raised within the enhancement request here (https://github.com/opengisch/QField/issues/4899) whereas the positioning information panel didn't respect the project distance unit type. Now, when people set distance to feet, they'll see altitude and accuracy numbers in feet:
=> Insure that the positioning information panel respects project distance unit type for altitude and accuracy

src/core/positioning/positioning.cpp
=> [Backport release-3_2] Avoid last averaged position not taken into account when adding vertex

src/qml/BusyOverlay.qml
Fixes https://github.com/opengisch/QField/issues/5039
Looks like this:
=> Add a shield/background to the busy indicator message to increase readability

src/qml/MapCanvas.qml, src/qml/qgismobileapp.qml
Some more preparation for finger tapping to vertex at finger position. We need to insure we never mix up stylus and finger.
=> Since stylus leaving proximity of screen doesn't change the hovered state, we have to take that into account

src/core/deltafilewrapper.cpp
For some reason a geometryless layer would produce WKTs that are empty strings. Did not manage to reproduce locally, but this later fails in posgres, as `ST_GeomFromText( '' )` raises.
Related PR: https://github.com/opengisch/qfieldcloud/pull/917
Fix: https://github.com/opengisch/QField/issues/4796
=> Prevent deltas having empty strings as WKT geometry

src/core/featuremodel.cpp
This is a follow up fix to the work done revamping relationship handling for features being created.
=> Now that we allow children creation prior to parent creation, we need to update default values to take possible children into consideration

src/core/utils/fileutils.cpp, src/core/utils/fileutils.h, src/qml/editorwidgets/+Qt5/ExternalResource.qml, src/qml/editorwidgets/+Qt6/ExternalResource.qml
This insures unsupported formats such as dxf are treated as files.
=> Only show the attachment widget's image frame for supported types by Qt

src/core/utils/fileutils.cpp, src/core/utils/fileutils.h, src/qml/editorwidgets/+Qt5/ExternalResource.qml, src/qml/editorwidgets/+Qt6/ExternalResource.qml
=> [Backport release-3_2] Only show the attachment widget's image frame for supported types by Qt

src/core/featurelistmodel.cpp, src/core/featurelistmodel.h, src/qml/RelationCombobox.qml, src/qml/editorwidgets/ValueRelation.qml
This PR implements grouping functionality to the value relation editor widget (the QGIS counterpart having been implemented here: https://github.com/qgis/QGIS/pull/56655). 
Here's how the UI looks when both a group field has been picked, as well as the [x] display group name checkbox has been toggled on.
First, the relation combobox dropdown list:
Then, the relation combobox's search popup list:
_Note that you will need a QGIS development build to configure the value relation in your QGIS project until QGIS 3.38._
=> Grouping functionality for the value relation editor widget

src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
This PR implements a new finger tap digitizing mode whereas users can tap anywhere on the canvas to add vertices. It resembles stylus/mouse digitizing, except it's with the finger. For those willing to sacrifice accuracy for speed, this is a great mode.
The mode can be enabled in the settings panel. To avoid a sense of chaos/overcrowding in the settings' general tab, I have added section (much like we did for tracker settings):
A bunch of pointer/finger interaction code has been cleaned up too to try and make it slightly more readable, with a couple of fixes in (inc. a crucial one for mouse digitizing).
=> Implement a finger tap digitizing mode

src/core/featurehistory.cpp
Fix typo reported by a member of our ever expanding community of translators. Thanks @michausm.
=> Fix typo in the feature history class

src/core/featurehistory.cpp
=> [Backport release-3_2] Fix typo in the feature history class

vcpkg/ports/liblzma/add_support_ios.patch, vcpkg/ports/liblzma/build-tools.patch, vcpkg/ports/liblzma/fix_config_include.patch, vcpkg/ports/liblzma/portfile.cmake, vcpkg/ports/liblzma/usage, vcpkg/ports/liblzma/vcpkg-cmake-wrapper.cmake, vcpkg/ports/liblzma/vcpkg.json, vcpkg/ports/liblzma/win_output_name.patch
The original upstream repo is disabled. The bminor fork is active. Version 5.4.4 is not currently known to be compromised by the xz vulnerability.
=> [liblzma] Switch to active repo, uncompromised version

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml
Intermittent problems with 3.29.1 https://github.com/microsoft/vcpkg/issues/37968#issuecomment-2037815125
=> Pin cmake version to 3.29.0

src/qml/NavigationInformationView.qml, src/qml/PositioningPreciseView.qml, src/qml/qgismobileapp.qml
I think that's the last bit of our UI that wasn't respecting the project distance unit :partying_face: 
Proof of life:
@ConJaySten , this fixes the issue you raised here (https://github.com/opengisch/QField/pull/5127#issuecomment-2028673711).
=> Insure that the navigation information and position precise view panels respect the project's distance unit

src/core/CMakeLists.txt, src/core/appinterface.cpp, src/core/appinterface.h, src/core/pluginmanager.cpp, src/core/pluginmanager.h, src/core/qgismobileapp.cpp, src/core/qgismobileapp.h, src/qml/DashBoard.qml, src/qml/Legend.qml, src/qml/QFieldSketcher.qml, src/qml/TrackerSettings.qml, src/qml/imports/QFieldControls/CodeReader.qml, src/qml/qgismobileapp.qml
Before I go further, I'd like to get this reviewed and merged so the very foundation here is approved by more than me ;-P
=> Basic plugins framework

src/core/qgismobileapp.cpp, src/core/utils/featureutils.cpp, src/core/utils/featureutils.h, src/core/utils/layerutils.cpp, src/core/utils/layerutils.h, src/qml/geometryeditors/FillRing.qml, src/qml/imports/Theme/Theme.qml, src/qml/qgismobileapp.qml, test/test_featureutils.cpp, vcpkg/ports/qgis/invoke.patch, vcpkg/ports/qgis/portfile.cmake
This PR enables plugins to do the following:
- retrieve map layers by name from a QgsProject instance
- iterate through features from a vector layer
- change a feature attribute value through the vector layer's changeAttributeValue(s) functions
- retrieve field information (such as attribute index from a given field name)
The invoke.patch changes are being upstreamed, but since we're on 3.36 for now, we can enjoy vcpkg's patching powers :muscle: 
Upstream PRs:
- https://github.com/qgis/QGIS/pull/57161
- https://github.com/qgis/QGIS/pull/57166
Iterating through features is done like this:
```
let layers = qgisProject.mapLayersByName('Apiary')      
let layer = layers[0]      
let it = LayerUtils.createFeatureIteratorFromExpression(layer, "fid IN (47,48,49)")
while (it.hasNext())
{
let …
```
=> Empower plugins with more functionalities

src/core/CMakeLists.txt, src/core/platforms/platformutilities.cpp, src/core/pluginmanager.cpp, src/core/pluginmanager.h, src/core/qgismobileapp.cpp, src/core/utils/featureutils.cpp, src/core/utils/featureutils.h, src/core/utils/projectutils.cpp, src/core/utils/projectutils.h, src/qml/BadLayerItem.qml, src/qml/BookmarkProperties.qml, src/qml/BrowserPanel.qml, src/qml/Changelog.qml, src/qml/LayerLoginDialog.qml, src/qml/LocatorSettings.qml, src/qml/MessageLog.qml, src/qml/PageHeader.qml, src/qml/PluginManagerSettings.qml, src/qml/PositioningDeviceSettings.qml, src/qml/QFieldCloudPopup.qml, src/qml/QFieldCloudScreen.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/QFieldSettings.qml, src/qml/RelationCombobox.qml, src/qml/TrackerSettings.qml, src/qml/geometryeditors/FillRing.qml, src/qml/imports/Theme/QfPageHeader.qml, src/qml/imports/Theme/qmldir, src/qml/qgismobileapp.qml, src/qml/qml.qrc
~~(This PR temporarily includes https://github.com/opengisch/QField/pull/5189 , that should be reviewed and merged first)~~
This PR is the last foundational stone to the plugin framework. It implements a basic plugins popup where users can clear their remembered project plugin permissions, as well as install (from a URL) and activate/deactivate app plugins. 
Here's an exciting screencast:
https://github.com/opengisch/QField/assets/1728657/f187657b-d5f3-4092-a184-6dad5755a679
Plugins pop up when no plugin is present:
=> Plugins management UI implementation

src/core/pluginmanager.cpp, src/core/pluginmanager.h, src/qml/PluginManagerSettings.qml
Last bits, I consider the framework done after this.
An uninstall mechanism is now in place for app plugins so people can easily uninstall plugins (instead of knowing where they need to go in their device's storage). In addition, a version metadata detail has been added so authors and users can better debug issues. An homepage metadata detail was also added.
Screenshot:
=> Implement plugin uninstall mechanism + adding a pair of metadata details

src/core/CMakeLists.txt, src/core/parametizedimage.cpp, src/core/parametizedimage.h, src/core/projectinfo.cpp, src/core/projectinfo.h, src/core/qgismobileapp.cpp, src/qml/qgismobileapp.qml
This PR implements support for projects' image decoration (joining the title and copyright decorations implement in QField 3.2).
To support fill and outline settings, a new ParametizedImage item was added, which relies on SVG and image cache to configure the fill and stroke color of the image. It will probably come in handy in other scenarios too.
As per the two other decorations we have, QField will enforce an harmonious position for the decoration.
In action:
The decoration gives users a simple way to further "brand" their projects.
Relevant QGIS documentation: https://docs.qgis.org/3.34/en/docs/user_manual/map_views/map_view.html#image-decoration
_Sponsored by Deutsches Archäologisches Institut (DAI)_
=> Project image decoration support

src/qml/RelationCombobox.qml, src/qml/editorwidgets/RelationReference.qml, src/qml/editorwidgets/ValueMap.qml, src/qml/editorwidgets/ValueRelation.qml
Search button is visible only for more than 6 items
And fix a bunch of qml warnings
=> Make value map searchable only if it contains more than 6 items

src/core/rubberbandmodel.cpp, src/qml/TrackerSettings.qml
PR fixes https://github.com/opengisch/QField/issues/5234 and https://github.com/opengisch/QField/issues/5235.
=> A couple of tracker fixes 

.github/workflows/windows.yml, vcpkg/triplets/x64-windows-static.cmake
Proof of life
https://github.com/opengisch/QField/actions/runs/9086145917/artifacts/1502820554
=> Sign windows installer

src/core/bookmarkmodel.cpp, src/core/featurelistextentcontroller.cpp, src/core/featurelistextentcontroller.h, src/core/locator/activelayerfeatureslocatorfilter.cpp, src/core/locator/featureslocatorfilter.cpp, src/core/locator/finlandlocatorfilter.cpp, src/core/locator/gotolocatorfilter.cpp, src/core/qgsquick/qgsquickmapcanvasmap.cpp, src/core/qgsquick/qgsquickmapcanvasmap.h, src/core/qgsquick/qgsquickmapsettings.cpp, src/core/qgsquick/qgsquickmapsettings.h, src/core/utils/featureutils.cpp, src/core/utils/featureutils.h, src/qml/DigitizingToolbar.qml, src/qml/ElevationProfile.qml, src/qml/FeatureListForm.qml, src/qml/InformationDrawer.qml, src/qml/MapCanvas.qml, src/qml/NavigationInformationView.qml, src/qml/PositioningInformationView.qml, src/qml/PositioningPreciseView.qml, src/qml/SensorInformationView.qml, src/qml/geometryeditors/VertexEditor.qml, src/qml/imports/Theme/QfOverlayContainer.qml, src/qml/imports/Theme/Theme.qml, src/qml/imports/Theme/qmldir, src/qml/qgismobileapp.qml, src/qml/qml.qrc
This PR implements the concept of margins (bottom and right for now) to the map canvas. Those margins allow for us to overlay elements on top of the map canvas and take those margins into account when setting the map extent / center. 
Practically speaking, this allows for zooming to feature / point to recenter around the portion of the map that's not covered by overlaid elements.
Needed for the ongoing revamp of information panel -> drawer (see https://github.com/opengisch/QField/pull/5251)
Here's a screencast of what it does:
https://github.com/opengisch/QField/assets/1728657/e49496db-af2d-4c59-8691-9a7293ec7518
Note how the auto re-centering to positioning and destination is contained within the part of the map canvas that's not partially hidden by the information drawer. Big win! This …
=> Implement margins concept for map canvas

.github/workflows/linux.yml, src/core/qgsquick/qgsquickelevationprofilecanvas.cpp, src/core/qgsquick/qgsquickelevationprofilecanvas.h, src/qml/ElevationProfile.qml, src/qml/NavigationInformationView.qml, src/qml/PositioningInformationView.qml, src/qml/SensorInformationView.qml
This allows us to have an harmonized looks with other information overlays. Proof of life:
The PR also further tweaks the positioning/navigation/sensors panel to have the values stand out more against their labels. In action:
@m-kuhn , I think that's what you were requesting right? Looking good :)
=> Add a couple of properties to the elevation profile canvas to style axis labels + information cells tweaking

src/core/qgsquick/qgsquickelevationprofilecanvas.cpp, src/core/qgsquick/qgsquickelevationprofilecanvas.h, src/qml/ElevationProfile.qml
=> Add remaining properties needed to unlock beautiful dark theme support to the elevation profile canvas

.github/workflows/linux.yml
The exclude parameter covers files, not check names. I've tried to come up with a narrower set of checks to insure we actually look at what's being told to us vs. ignoring :)
=> Fix wrong usage of 'exclude' for the clang-tidy CI check

src/qml/MapCanvas.qml, src/qml/QFieldSettings.qml, src/qml/imports/Theme/Theme.qml, src/qml/qgismobileapp.qml
So in this PR i am going to add an option that enables or disables the mapRotation, so if user don't wants rotation it wont rotate accidentally.   
**In first step** I merged 3 rows in `canvasMenu`. previously there was 3 row showing X, Y, Copy coordinates. Now we show all the info in one row.    
**In second step** I also added this option in Settings page.
=> Lock map rotation

src/qml/editorwidgets/ValueMap.qml
@mohsenD98 , while testing feature attribute transfer functionality, I stumbled on an issue with the value map toggle buttons whereas once you manually click on a button, changes coming from the model are ignored. That's fixed.
I've tweaked the looks / spacing / colors a bit too to harmonize it with other pre-existing editor widgets.
=> Value map toggle buttons functionality follow ups

src/core/qgismobileapp.cpp, vcpkg/ports/qgis/fontsdownload.patch, vcpkg/ports/qgis/portfile.cmake
@itsakifa , as discussed, this should help your client a lot. For one, they can create a "fonts" subfolder to their project folder (i.e. without a dot) to add project fonts on windows/macos. I've also cleaned up the app-wide font loading code, maybe it'll help on that front. Finally, the fix on QGIS master to re-enable auto-download of fonts has been added (thanks vcpkg), so in theory the client won't need to add much by QField 3.3 :)
=> App-wide/project fonts fixes

src/qml/LayerLoginDialog.qml
=> Fix login popup styling in dark theme

src/qml/editorwidgets/ValueMap.qml
Alright, this is the last bit needed to ship the nice new value map editor widget's toggle buttons UX:
While I was hoping we could have a reasonable threshold to hard-code the switch between combo box and toggle buttons, I just tested a couple of projects, and the change is too disruptive to now make it an opt-in. 
In the future, I wouldn't be surprised to see QGIS implement the UX here, but for now let's rely on our beloved qfieldsync plugin.
=> Adjust value map editor widget to be responsive to new qfieldsync configuration

src/qml/FeatureForm.qml, src/qml/QFieldCloudScreen.qml, src/qml/QFieldSettings.qml, src/qml/editorwidgets/ValueMap.qml, src/qml/imports/Theme/QfTabBar.qml, src/qml/imports/Theme/qmldir, src/qml/qml.qrc
In this PR, we address two minor issues:
1- Fix #5242: The issue where tabs are not following the selected container has been resolved.
2- Additionally, we've fixed the elide problem in MapValue.
These changes aim to improve the overall user experience and stability of application.
**Resolved video:**   
[Screencast from 2024-05-31 07-34-16.webm](https://github.com/opengisch/QField/assets/36326627/dbb7bc20-ef10-4561-acd8-d54109207912)
=> Sync tabs with swipe view in FeatureForm.

src/core/qgismobileapp.cpp
=> Add iOS support for dropping a pg_service.conf into QField's app data folder

src/core/attributeformmodelbase.cpp
Without this fix, cardinal relation IDs go blank, and QField shows the link/join instead of the actual content of the child layer.
@3nids , another fix for your client.
=> Fix relation editor's cardinal relation ID value passing

src/qml/PluginManagerSettings.qml
=> Direct users to the actual plugins documentation page now that it's up

src/qml/qgismobileapp.qml
Follow up to our great information overlay revamp: this fixes the coordinate cursor going _under_ the elevation profile panel or the positioning + navigation panels.
=> Insure that the coordinate cursor center around non-obstructed area of the canvas

src/qml/qgismobileapp.qml
This PR Resolves an issue where the `snappingToAngle` functionality was not working while Geometry editor mode was enabled. The issue was caused by a incorrect setting of the `rubberbandModel` for the `CoordinateLocator`. This commit corrects the setting, ensuring that `snappingToAngle` functionality works as expected in GeometryEditor mode.
**What was the problem?**
`rubberbandModel` in `CoordinateLocator` was `digitizingToolbar.rubberbandModel` but we know when we enable `geometryEditors` there is `geometryEditorsToolbar.editorRubberbandModel` that handles vertexes.  
```QML
CoordinateLocator {
...
rubberbandModel: digitizingToolbar.rubberbandModel
...
}
```
**Fix:**  
```QML
rubberbandModel: geometryEditorsToolbar.stateVisible ? geometryEditorsToolbar.editorRubberbandModel : …
```
=> Fix snappingToAngle while editing geometry (reshape).

src/qml/editorwidgets/ValueMap.qml
This PR tries to resolve this (https://github.com/opengisch/QField/issues/2193#issuecomment-2166436054).
**Issue:** Button interface widget must be bind with `ComboBox` all the time to ensure its functionality, but in some cases we had assignment on `toggleButtons.selectedIndex`. this assignment breaks the binding so we need to remove the assignment.
**Fix** instead of assignment on `toggleButtons.selectedIndex` we can assign to `comboBox.currentIndex` and binding will do the rest.
=> Fix Button interface: highlight issue when default is selected.

src/qml/editorwidgets/ValueMap.qml
=> [Backport release-3_3] Fix Button interface: highlight issue when default is selected.

.github/workflows/linux.yml, .github/workflows/windows.yml, src/core/featuremodel.cpp, src/core/featuremodel.h, src/core/positioning/gnsspositioninformation.h, src/core/positioning/internalgnssreceiver.cpp, src/core/utils/expressioncontextutils.cpp
The macos spix tests already revealed something interesting: on that platform, when creating the internal positioning device, we get an AccessError (as permission has not yet been asked to the user). However in our code, we invalidate the device upon creation when any error is detected. This PR addresses that by allowing for the device to be created, allowing for users to ask for permission afterwards when turning the positioning on.
I've also taken the opportunity to cleanup obsolete includes.
=> Avoid flagging internal positioning device as invalid caused by access error, cleanup positioning includes

src/core/pluginmanager.cpp, src/qml/PluginManagerSettings.qml, src/qml/qgismobileapp.qml
Fixing a couple of issues identified while preparing the plugins blog post:
- It's way too easy to hit the clear permissions button, I've moved it into a dropdown menu attached to the install plugins button. Bonus: makes the UI look a lot better on screen with narrow height (e.g. a phone in landscape orientation).
- The permission clearing logic was broken for app-wide plugins, fixed that.
How it looks now:
Dropdown menu:
=> Plugins permission UI/UX improvements

src/qml/QFieldCloudLogin.qml
This is a better experience, offers users the possibility to bookmark app.qfield.cloud in their browsers, and above all, ATM, webviews are broken on linux and possibly windows :)
=> On desktop OSes (linux, windows, macos), register QFieldCloud accounts in the OS browser

src/qml/QFieldCloudLogin.qml
=> [Backport release-3_3] On desktop OSes (linux, windows, macos), register QFieldCloud accounts in the OS browser

src/core/utils/geometryutils.cpp, src/core/utils/geometryutils.h, src/qml/OverlayFeatureFormDrawer.qml, src/qml/qgismobileapp.qml
Additional tweaks as part of plugin framework blog post.
=> Exposing more to plugins

src/core/vertexmodel.cpp
=> [Backport release-3_3] Only add Z and M point values passed onto the model when the geometry type requires it

src/qml/DigitizingToolbar.qml, src/qml/qgismobileapp.qml
This PR addresses issue #2252, resolving a bug in the current project workflow. 
**Issue:** When a user is in `digitizing` mode and attempts to exit the current project, they are not properly confirmed to discard their digitizing work. This PR ensures that the user is prompted to confirm discarding their digitizing work before exiting the project.
With this fix, users can now confidently switch between projects without worrying about unintended data persisting.
**Demo** 
[**Demo of functionality**](https://github.com/opengisch/QField/assets/36326627/e2e531ec-531a-444d-866e-2fcf72992fcd)
**About Code Review**  
reason for this line in `DigitizingToolbar.qml`  
```QML
homeButton.waitingForDigitizingFinish = false
```
Imagine this process: click on homeButton, dont discard, discard from …
=> Close current project while digitizing

src/core/valuemapmodelbase.cpp, src/qml/Legend.qml, src/qml/editorwidgets/ValueMap.qml
@SeqLaz , this takes care of the two issues you reported in clickup.
@3nids , this also takes care of the issue your client reported which you mentioned in Google Chat.
=> Legend badge visual glitche + a pair of value map issues addressed

src/core/attributeformmodelbase.cpp
Fixes issue raised here: https://github.com/opengisch/QField/discussions/5327
=> Fix @current_parent_* default value not saved on child creation

src/core/utils/qfieldcloudutils.h
Follow up to https://github.com/opengisch/QField/commit/89d4ca2a8126ebb22fc3903110d9b55560e4bb8b , fix @cloud_{username,email} gone blank.
@suricactus , all good? Sorry I didn't catch this when reviewing your PR back then.
=> Fix cloud user information @variables gone missing

src/qml/editorwidgets/ValueMap.qml
@domi4484 , a quick follow up on the nice feature you developed.
=> Make value map value filtering case insensitive

src/core/valuemapmodelbase.cpp, src/qml/Legend.qml, src/qml/editorwidgets/ValueMap.qml
=> [Backport release-3_3] Legend badge visual glitche + a pair of value map issues addressed

src/core/attributeformmodelbase.cpp
=> [Backport release-3_3] Fix @current_parent_* default value not saved on child creation

src/qml/FeatureListForm.qml, src/qml/NavigationInformationView.qml, src/qml/PositioningInformationView.qml, src/qml/SensorInformationView.qml
_(I pity the CI stress we're causing this last 24 hours, making one PR for two issues :wink:)_
This PR fixes two issues. One has to do with information panels strings not being clipped to their parent  cell, e.g. this:
We're now properly clipping and adding elides when needed. Ridiculous proof-of-fix:
The second fix is more significant and has to do with avoiding potential data loss while editing a feature and accidentally causing the feature form to close when swiping its navigation bar down. Fixes https://github.com/opengisch/QField/issues/5084.
=> Information panel text elide + feature form editing data loss fixes

src/qml/VariableEditor.qml, src/qml/imports/Theme/QfSwipeAnimator.qml, src/qml/imports/Theme/qmldir, src/qml/qml.qrc
This is the initial step in the redesign of the VariableEditor component. In this iteration, we have taken the first step towards the makeover by removing the background color from rows. Additionally, we have addressed indentation issues and applied some cosmetic improvements to the QML code.
**New look:**
=> Variable Editor: First step of redesign

src/qml/NavigationInformationView.qml
When we upgraded our information panels, we tweaked the look of the navigation to geometry bar from an opaque purple to a lighter semi opaque background color, leading to white-on-light-white situation using QField's light theme.
This PR fixes that. Proof of life:
Fixes issue raised in https://github.com/opengisch/QField/discussions/5370
=> Fix color of text and button elements in the navigation to geometry bar [on light theme]

src/qml/Legend.qml
Fix https://github.com/opengisch/QField/issues/5372
=> Don't show the snapping badge for geometryless vector layers

src/qml/Legend.qml
=> [Backport release-3_3] Don't show the snapping badge for geometryless vector layers

src/qml/editorwidgets/ValueMap.qml
=> [Backport release-3_3] Fix accidental mixup between value<->key<->description in the value map editor widget

src/qml/RelationCombobox.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
When adding a child via the feature form against remote layers (e.g. WFS layers), the UI can sit waiting for a long time. It's not ideal at all. This PR adds a busy indicator to let the user know that their click/tap has been registered and is being processed.
@3nids , I believe this will address your client's issue.
=> Provider users with visual feedback when initiating a child addition process

src/core/qgismobileapp.cpp, src/core/utils/expressioncontextutils.cpp, src/core/utils/expressioncontextutils.h
Based on a good plugin framework suggestion raised here (https://github.com/opengisch/qfield-template-plugin/issues/1), this PR implements a mechanism through which global/project/layer expression variables can be added/edited/removed via javascript.
This allows for plugin authors to develop interesting UI/UX to define these variables alongside default expressions attached to layers.
=> Implement invokable functions for plugins to handle global/project/layer variables

platform/android/src/ch/opengis/qfield/QFieldActivity.java
This PR fixes https://github.com/opengisch/QField/issues/5383 -- we were essentially taking up a lot of storage on Android saving images in _two_ locations.
=> Avoid double-storing photos taken by QField when using the native camera

platform/android/src/ch/opengis/qfield/QFieldActivity.java, src/core/CMakeLists.txt, src/core/featureexpressionvaluesgatherer.h, src/core/featurelistmodel.h, src/core/orderedrelationmodel.cpp, src/core/platforms/android/androidplatformutilities.cpp, src/core/platforms/android/androidplatformutilities.h, src/core/platforms/platformutilities.h, src/core/positioning/geofencer.cpp, src/core/positioning/geofencer.h, src/core/projectinfo.h, src/core/qgismobileapp.cpp, src/qml/PositioningSettings.qml, src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
This PR adds geofencing capabilities to QField configured via qfieldsync. The geofencing functionality features three behavior that can:
- alert users when within areas (default behavior)
- alert users when outside all areas
- inform users when entering and leaving an area
The configuration in qfieldsync is done so through the project properties dialog's qfieldsync panel:
On the QField side, opening a project will automatically adopt the geofencing settings. The picked polygon layer's display name setting will be used as area name.
UX when geofencing is set to alert users when entering geofenced areas:
https://github.com/opengisch/QField/assets/1728657/fcb169d2-5442-414c-a8e0-a5a4060b8e64
UX when geofencing is set to alert users when outside all geofenced areas: …
=> Implementation of geofencing functionality

src/core/featurechecklistmodel.cpp, src/core/featurechecklistmodel.h, src/qml/editorwidgets/ValueRelation.qml
Spotted while fixing https://github.com/opengisch/QField/pull/5397
Less warnings == better world. In this case, I think the warnings were indicating a possible scenario in which we get our model wires crossed. 
Possibly fixing https://github.com/opengisch/QField/issues/5374
=> Fix value relation editor widget serious warnings

src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
@mbernasocchi , as discussed. The setting is now project-level, and can be enabled/disabled in qfieldsync.
Much better.
=> Make geofencing digitizing prohibition a project-level setting via qfieldsync

src/qml/FeatureForm.qml, src/qml/OverlayFeatureFormDrawer.qml
This PR tries to resolve this issue: 
**Steps to remake issue:**
- Select the apiary layer in the legend, then insure that editing is ON
- Add an apiary point onto the map (fill in the required info), and make sure you click on the OK check mark button when - you are in the 2nd or 3rd tab.
- Then when the form is gone, add another apiary point.
- You'll see the feature form opens at the tab you last  had focused.
- What we should do here is that when we create a new feature, it should reset to the 1st tab.
**Fix:**
we add a reset tab function in `FeatureForm.qml` and after `confirm` or `cancel` we call that.  
Closes #5417
=> Rest feature form tabs on confirmed or cancelled.

src/qml/Legend.qml
Valid issue raised by the Groupement Forestiers Quebec via email.
ATM, with the improved legend allowing for collapsing/expanding and toggling visibility within the legend itself, it has become really hard to understand the relationship between layers and symbol children:
This is what it looked like before:
This PR addresses this by insuring we're never collapsing the horizontal space occupied by the collapse/expand button.
=> Do not collapse width of the expand/collapse button when layer has no children to help visual glance at legend

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
This PR fixes https://github.com/opengisch/QField/issues/5445 -- long story short here: a while back, we allowed for addition of children while a parent had yet to be saved due to unmet constraints. This can be useful for some workflows, but it turns out to break a couple of scenarios, including the one reported here where geopackage have foreign key constraints.
To be safe, let's always try to save().
=> Always (try to) save parent features prior to adding children

src/qml/Legend.qml
=> [Backport release-3_3] Do not collapse width of the expand/collapse button when layer has no children to help visual glance at legend

platform/android/src/ch/opengis/qfield/QFieldUtils.java, src/core/appinterface.cpp
=> [Backport release-3_3] Ignore content of .qfieldsync folder when seeking project file

src/qml/RelationCombobox.qml
Reset of the flag `isLastKeyPressedReturn` was missing.
This issue is happening only when using the enter button of the virtual keyboard
=> Fix RelationCombobox not autocompleting on secon feature

scripts/build-for-linux.sh, src/qml/QFieldGuide.qml, src/qml/WelcomeScreen.qml, src/qml/imports/Theme/QfProgrerssRing.qml, src/qml/imports/Theme/qmldir, src/qml/qgismobileapp.qml, src/qml/qml.qrc, test/spix/smoke_test.py
This pull request introduces a guided tutorial for new users when they launch the application for the first time. The goal is to provide an intuitive onboarding experience, setting the stage for a successful and enjoyable usage of Qfield.
**Demonstration**:
To illustrate the new feature, please watch the demo:    
**Dark**   
[Screencast from 2024-07-25 11-46-19.webm](https://github.com/user-attachments/assets/8cdac7fc-cd04-4ac4-9aa6-dfbbb8217322)    
**Light**
[Screencast from 2024-07-25 11-46-52.webm](https://github.com/user-attachments/assets/e4adf855-a469-4b73-bc14-c1af627f6605)
As shown in the demo, we have implemented a tutorial panel that introduces key features step-by-step. The guide is designed to gradually introduce users to the application's functionality.
In this initial …
=> Start with a Guided Tour.

src/core/layertreemodel.cpp, src/core/layertreemodel.h, src/core/projectinfo.cpp, src/core/projectinfo.h, src/qml/Legend.qml, src/qml/qgismobileapp.qml
Alongside a development build of qfieldsync (see https://github.com/opengisch/qfieldsync/pull/601) which will be released when we launch QField 3.4, this PR implements support for map theme's default active layer.
When a given project defines a default active layer for a given map theme, QField will now automatically activate that layer in the legend, enabling faster digitizing and easier UX for users.
In action:
https://github.com/user-attachments/assets/2422fbc0-87b7-4e4d-9a2d-37433ee5ca62
=> Implement support for map theme default active layer

src/qml/QFieldGuide.qml
A bit of guides polishing, including:
- Fix next button color on dark theme (i.e., white text on main green color is barely readable)
- Fix oversized close button, and tweak its margins to sit better alongside other items
- Add font sizes for all text elements, make the title strong font (i.e. default font size + bold) and the description tip font
- Harmonize bottom margin
After the tweaks, we look like this:
=> Polish guides looks, font sizes, and colors

test/qml/tst_positioning.qml
Using `nmea`, we need to verify that the `positionInformation` in `featureModel` is assigned with values and is **not** `null`.
=> Add positioning test for featureModel.

src/core/locator/helplocatorfilter.cpp
These aren't super relevant to QField users, and create undesired noise.
=> Exclude success stories and technical reference sections from the documentation / help locator

.github/workflows/android.yml, src/qml/editorwidgets/TextEdit.qml
This PR fixes https://github.com/opengisch/QField/issues/5502 , a regression which slipped in 3.3.7. It's a bad one, I think we should push 3.3.9 ASAP.
To that end, this PR fixes Android CI following an Ubuntu 22.04 image update which changed the default Android NDK to r27 (see https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240730.2).
=> Fix handling of autogenerated fid in feature form, adjust default NDK following github Ubuntu 22.04 image update

src/core/utils/qfieldcloudutils.cpp, src/core/utils/qfieldcloudutils.h, src/qml/QFieldCloudPopup.qml, src/qml/imports/Theme/QfCollapsibleMessage.qml
This pull request introduces a new function, which takes a server-side error message and returns a user-friendly version. The function simplifies and clarifies complex error messages, making it easier for users to understand what went wrong and how to fix it.
**Key Features:**
- Translates technical error messages into user-friendly messages
- Provides clear and concise explanations of complex errors
**Benefits:**
- Increased customer satisfaction by providing clear explanations of what went wrong
- Reduced support requests by making it easier for users to troubleshoot issues on their own
**Related:**
https://github.com/opengisch/QField/discussions/5493
**New Look:**
=> translate server side error messages.

src/core/deltafilewrapper.cpp, src/core/deltafilewrapper.h, test/test_deltafilewrapper.cpp
The mysterious image loss issue has been resolved! 
Long story short, if a photo was changed/added in a follow up edit after a feature was added or already edited once _prior to pushing_, the photos would go missing as the logic to merge new patches into pre-existing create and patch deltas were not adding the necessary file checksums.
The PR fixes that. Woupidou.
=> Fix loss of images when merging patches against pre-existing create/patch deltas

src/qml/QFieldCamera.qml
This PR streamlines the UX of activating QField camera geotagging by avoiding a "dead" tool button when positioning is not active. 
The new behavior allows for toggling of geotagging irrespective of the positioning active state. When taking a photo, a warning message will teach users about the need for an active positioning state. This new UX is simpler, and more informative.
Based on feedback provided by @cemno here: https://github.com/opengisch/QField/issues/5532
=> Improve QField image geotagging UX

src/core/utils/qfieldcloudutils.h, src/qml/QFieldLocalDataPickerScreen.qml
This PR adds a mechanism - through the project folder panel - which allows users to push images and PDFs contained within a cloud project folder (or one of its subfolders) to the QFieldCloud server. 
The action is available through a raster image's 3-dot menu within the project folder panel:
It is enabled _only for raster files_ to prevent the world from colliding if we were to push back geopackages to the cloud, messing up with delta handling et al.
Practically speaking, this allows: a/ users to recover images that never made it into the server automatically (it shouldn't happen, but as Jurassic Park told us, life finds a way), and b/ users to send back printed layouts and atlases back onto the server.
=> Allow for users to manually push images/PDF files to the cloud from the project folder panel

.github/workflows/linux.yml, platform/android/AndroidManifest.xml.in, src/core/qfieldcloudconnection.cpp, src/core/qfieldcloudconnection.h, src/core/utils/qfieldcloudutils.cpp, src/core/utils/qfieldcloudutils.h, src/qml/qgismobileapp.qml
Prior to this PR, if you had 20 attachments added prior to pushing changes, QField would try to upload those 20 attachments _simultaneously_ in parallel. On slow internet connections, this would lead to _really slow_ simultaneous transfers. In turn, it could well have resulted in QField never able to successfully upload most of its queue prior to the app being shutdown or put in background on platforms but Android. The PR improves things there by having the files uploaded sequentially one by one.
Furthermore, a failed attachment upload caused by a momentary server/network error was never retried _on the spot_,. It was merely left in the queue to try again the next time users would push changes. While this wasn't causing data loss, I think we still should retry a failed upload a few times …
=> Improve logic and handling of of attachments upload to QFieldCloud

src/core/utils/snappingutils.cpp
Fixes issue raised in this discussion (https://github.com/opengisch/QField/discussions/5546). 
@DrawQuick , in 15 minutes or so you will find test APKs in this pull request to test that the disappearing coordinate cursor disappearing issue has been fixed. Thanks for the report.
=> Fix snapping result point reprojection when current layer has a Z/M dimension

src/core/utils/snappingutils.cpp
=> [Backport release-3_3] Fix snapping result point reprojection when current layer has a Z/M dimension

src/core/featurechecklistmodel.cpp, src/qml/editorwidgets/ValueRelation.qml
PR fixes https://github.com/opengisch/QField/issues/5539 , and aligns QField's behavior with that of QGIS by returning null when no value is checked .
=> Harmonize handling of QField's (multi)value relation editor widget with that of QGIS

src/core/expressionvariablemodel.cpp, src/core/expressionvariablemodel.h, src/qml/QFieldSettings.qml, src/qml/VariableEditor.qml, src/qml/qgismobileapp.qml
This PR enhances the existing settings page by introducing project variables to the list of displayed variables. This feature allows users to conveniently view all relevant project-specific variables.   
**`wastewater management` sample project:**
=> Project variables

src/core/projectinfo.cpp, src/core/projectinfo.h, src/qml/qgismobileapp.qml
This PR fixes missing cloud user details context for expressions when loading a new cloud project.
Long story short here, when we load a new cloud project, the cloud user information having not been saved before is simply not written, and therefore the cloud user information changed signal returns empty values.
=> Fix cloud user information context when loading a new cloud project

.github/workflows/linux.yml, src/core/expressionvariablemodel.cpp, src/core/expressionvariablemodel.h, src/qml/VariableEditor.qml
This PR represents the second step in revamping the variables page within the settings. As you know in [**This PR**](https://github.com/opengisch/QField/pull/5577), we introduced project variables to the existing list, which previously only displayed application-wide (global) variables.
In this step, we've made it possible to edit project variables (_but unremovable_). The changes will remain effective throughout the session, but once the project is closed and reopened, the values will revert to their original settings.
**Stay tuned:** 
for step three, where we will focus on enhancing the visual design! :)
**Demo:**    
You can see editable but unremovable project variables here:
=> Editable project variables.

src/qml/QFieldSettings.qml
Fixes https://github.com/opengisch/QField/issues/5591
IIRC "below bad" has been mentioned as an unsuitable wording before.
If _bad_ is set to 3m, we want values _above_ (like 5m) to be treated as bad, not values _below_.
=> Improve wording for position accuracy

.docker/android_dev/Dockerfile
Thanks to @qsavoye for finding out why our builds were weighting hundreds of mbs. Beyond the smaller APK size, it also allows us to use the NDK versioning number as the Android workflow (instead of r26d vs 26.3.11579264), which makes updating even simpler.
=> Improve size of docker self-built APKs

src/core/expressionevaluator.cpp, src/core/expressionevaluator.h, src/qml/editorwidgets/ExternalResource.qml, src/qml/qgismobileapp.qml, test/CMakeLists.txt, test/test_expressionevaluator.cpp
The PR improves our expression evaluator class through the following changes:
- avoid a QgsProject::instance() use in favor of a property
- add a map settings property to unlock map canvas scoping
- allow for expressions to run without the presence of a layer or feature 
- add an expression template mode (i.e. resolving a 'my field value is [% "MY_FIELD" %]')
This aimed at fixing QField not handling expression templates in title and copyright decorators. Without further due, here are expression template within decorations:
https://github.com/user-attachments/assets/7e06a791-0dca-4ad8-b218-e5ec840ded02
The title decoration relies on a @project_title variable:
```
[%@project_title%]
```
The copyright decoration here relies both on the map canvas context (showing the map scale) as well as …
=> Expression template support for title and copyright decorations

README.md
We also long ago removed the 'beta' label to linux and macos in QField's documentation, we should reflect that here.
=> Update README.md to point to Microsoft Store for Windows

cmake/NSIS.template.in, cmake/Package.cmake
Taken from https://cmake.org/cmake/help/book/mastering-cmake/chapter/Packaging%20With%20CPack.html?highlight=zip#setting-file-extension-associations-with-nsis 
Testing [a link](ms-windows-store://pdp/?productid=XP99H3BCX4BW7F).
=> Add file association for .qgs/.qgz on Windows

.github/workflows/android.yml, .github/workflows/apple_certs.yml, .github/workflows/s3clean.yml, .github/workflows/sync-translations.yml
=> Skip comment when CI not running from opengisch repository

src/qml/QFieldCamera.qml
Tiny long hanging fruit coming from our ideas platform: https://ideas.qfield.org/app-feature-requests/p/directional-watermark-on-pictures
=> Add orientation (aka compass direction) detail when watermarking/stamping photos

src/qml/QFieldCamera.qml
=> [Backport release-3_4] Add orientation (aka compass direction) detail when watermarking/stamping photos

src/core/attributeformmodelbase.cpp, src/qml/FeatureForm.qml
Shaving off 100-200ms on large-ish feature form configurations.
@3nids , this follows the discussion we had on google chat yesterday.
=> Some (micro) optimizations of feature form

src/core/featuremodel.cpp
Stumbled on this crash (regression due to a change in the way we handle multi-selection lists in 3.4) while investigating https://github.com/opengisch/QField/discussions/5651
=> Fix multi-editing can lead to crash

src/core/positioning/internalgnssreceiver.cpp
Corner scenario, but still important to fix on 3.4
=> Fix crash occuring when the internal receiver is request permission while immediately replaced with external receiver on launch

platform/android/AndroidManifest.xml.in, src/qml/Toast.qml
Very important fix considering we now have geofencing alerts, which would display _below_ the virtual keyboard prior to this PR.
Edit: PR also add missing vibration permission into the Android manifest (commit missed the original geofencing PR!).
=> Insure that QField toasts appear above the virtual keyboard

.clang-format, src/core/localfilesmodel.cpp, src/core/localfilesmodel.h, src/qml/QFieldLocalDataPickerScreen.qml
Unlocks easier sharing of NMEA logs:
=> Allow for users to see and send NMEA logs

src/app/main.cpp
This avoid QField needlessly trying to fetch an Open Sans font on app launch (which in turn makes our testing CI more resilient to sporadic font download failures).
=> Insure that the defautl text format font matches what we're passing through env. variables

src/core/attributeformmodelbase.cpp, src/qml/editorwidgets/Binary.qml, src/qml/qml.qrc
Fixes the crash raised in https://github.com/opengisch/QField/issues/5668 . That will leave us with one day implementing blob support if it gets funded.
=> Prevent crashes when opening a feature form containing a blob attribute

src/qml/qgismobileapp.qml
For new users, every single thing is new :)
Removing the changelog will leave space for some first-use introduction UI if we want to in the future.
=> What's new for new users is not a great experience

src/core/attributeformmodelbase.cpp
=> [Backport release-3_4] Fix multiline handling of expressions within QML / HTML editor widgets

src/qml/RelationCombobox.qml, src/qml/imports/Theme/QfSearchBar.qml
On some virtual keyboards, a textfield's text property isn't update when typing a word (with e.g. auto completion on). The fix is to use displayText.
Fixes https://github.com/opengisch/QField/issues/5682 .
=> Insure that search bar reacts to partial text entered by all virtual keyboards

src/core/qfieldcloudprojectsmodel.cpp
When we moved projects list fetching to paged requests, the modelReset signal isn't happening at the right time anymore. Adjust.
Fixes https://github.com/opengisch/QField/issues/5708
=> Fix LocalModification flag not properly restored when opening a cloud project prior successfully logging into the server

src/core/CMakeLists.txt, src/core/gridmodel.cpp, src/core/gridmodel.h, src/core/projectinfo.cpp, src/core/projectinfo.h, src/core/qgismobileapp.cpp, src/qml/GridRenderer.qml, src/qml/qgismobileapp.qml, src/qml/qml.qrc
This pull request adds grid decoration functionality to QField:
https://github.com/user-attachments/assets/97097ce5-0815-425b-8dfb-6f7244fd1bb7
QField will enable the grid based on the currently opened project's grid decoration settings, which is configured when preparing a project in QGIS. Implementation note: as with other decorations implemented in QField, we do not do a 1-to-1 implementation; in this case, we will take the line or maker color defined in QGIS but we will render the line and marker style our own way (namely non-dashed lines and cross markers).
Quite interestingly, relying on QML Shape rendering ended up being _much faster_ than relying on a QQuickPaintedItem and doing the rendering completely on the C++ side of things. That was surprising to me, and serves as a good …
=> Support grid decoration

src/core/qgismobileapp.cpp
Also aligns usage of geospatial PDF with what's been picked by gdal & QGIS.
=> Remove use of trademark wording

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
Unconditionally calling save() of a parent feature when adding children can be needlessly costly on online datasets, let's only do it when we absolutely need it (i.e. when a parent feature isn't created yet).
=> Avoid needless save when adding a child to a parent that is already part of its dataset

src/core/featuremodel.cpp
When we initially released this functionality, we turned out to be a bit too rigid on our handling of expression-driven attribute. 
This PR relaxes things a bit by applying the prohibition on transfer of attribute values on attributes with default value expression to those that _don't_ update their value on feature updates. The updated logic continues to protect users from overwriting UUID / unique value / timestamp attributes  that would have been generated _once_ on feature creation while allowing for expression-drive attributes set to refresh on feature update to have values transferred.
=> Improve feature attribute transfer by allowing copying _some_ expression-driven attributes

src/core/featuremodel.cpp
=> [Backport release-3_4] Improve feature attribute transfer by allowing copying _some_ expression-driven attributes

src/core/CMakeLists.txt, src/core/positioning/abstractgnssreceiver.cpp, src/core/positioning/abstractgnssreceiver.h, src/core/positioning/bluetoothreceiver.cpp, src/core/positioning/bluetoothreceiver.h, src/core/positioning/egenioussreceiver.cpp, src/core/positioning/egenioussreceiver.h, src/core/positioning/internalgnssreceiver.cpp, src/core/positioning/internalgnssreceiver.h, src/core/positioning/nmeagnssreceiver.cpp, src/core/positioning/nmeagnssreceiver.h, src/core/positioning/serialportreceiver.cpp, src/core/positioning/serialportreceiver.h, src/core/positioning/tcpreceiver.cpp, src/core/positioning/tcpreceiver.h, src/core/positioning/udpreceiver.cpp, src/core/positioning/udpreceiver.h, src/qml/PositioningDeviceSettings.qml
In this PR we are going to address these: 
* Refactor 1: https://github.com/opengisch/QField/pull/5637#discussion_r1767657714
* Refactor 2: https://github.com/opengisch/QField/pull/5637#discussion_r1767666659
---
This pattern is been used in: 
https://github.com/opengisch/QField/blob/3a1586f83605a886531bf996600e63063ac6ef28/src/core/positioning/bluetoothreceiver.cpp#L30
https://github.com/opengisch/QField/blob/3a1586f83605a886531bf996600e63063ac6ef28/src/core/positioning/tcpreceiver.cpp#L25
https://github.com/opengisch/QField/blob/3a1586f83605a886531bf996600e63063ac6ef28/src/core/positioning/udpreceiver.cpp#L38
--- 
> @domi4484: It feels a bit strange to me that subclasses of postioning device have to manage mSocketState that way. mSocketState and mSocketStateString have a quite risk to …
=> Positioning device refactoring

src/core/qfieldappauthrequesthandler.cpp, src/core/qfieldappauthrequesthandler.h, src/qml/qgismobileapp.qml
The goal of this change is to avoid having QField focus on a layer, triggering a feature form rebuild that might be halted halfway due to authentication being submitted and QField then force reloading the project.
On top of saving a few CPU cycles, it has the potential to avoid obscure threading crashes.
=> When loading a project with pending authentication requests, do not set an active layer to avoid potential crash

src/qml/qgismobileapp.qml
When users are in the algorithm design mode and attempt to navigate to the measurement section, the preview feature remains active, which is an unauthorized behavior. This pull request addresses and resolves that issue.
To prevent users from entering the measurement section while still in the algorithm design mode, we will implement a confirmation dialog. This dialog will prompt the user with the question: “Do you want to discard the algorithm to enter the measurement section?”
> If the user accepts, the algorithm will be discarded, allowing for a proper transition to the measurement section. 
This change aims to enhance user experience by ensuring that the application behaves predictably and maintains the integrity of the design process.
Added a confirmation dialog for transitioning from …
=> Processing / measuring tool bug fix

src/qml/BluetoothDeviceChooser.qml, src/qml/BookmarkProperties.qml, src/qml/DigitizingToolbar.qml, src/qml/FeatureForm.qml, src/qml/FeatureListForm.qml, src/qml/MessageLog.qml, src/qml/PluginManagerSettings.qml, src/qml/QFieldCloudPackageLayersFeedback.qml, src/qml/QFieldCloudPopup.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml, src/qml/geometryeditors/FillRing.qml, src/qml/imports/Theme/QfDialog.qml, src/qml/imports/Theme/qmldir, src/qml/qgismobileapp.qml, src/qml/qml.qrc
Cleaner dialog codes + we can have our custom dialog later. remove lots of duplication.
=> Add QfDialog.

CMakeLists.txt, cmake/qgis-cmake-wrapper.cmake, src/core/CMakeLists.txt, src/qml/Dummy.qml, src/qml/qgismobileapp.qml, src/qml/qml.qrc, vcpkg.json, vcpkg/ports/qgis/meshoptimizer.patch, vcpkg/ports/qgis/portfile.cmake, vcpkg/ports/qgis/vcpkg.json, vcpkg/ports/qtquick3d/0001-devendor-meshoptimizer.patch, vcpkg/ports/qtquick3d/portfile.cmake, vcpkg/ports/qtquick3d/vcpkg.json
=> Enable Qt Quick3D support

src/core/qfieldcloudprojectsmodel.cpp, src/core/utils/fileutils.cpp, src/core/utils/fileutils.h
@suricactus , as discussed.
I'm inclined to release 3.4.5 as soon as this is backported!
=> Avoid constantly re-downloading same large files from the cloud by fixing checksum

src/qml/MapCanvas.qml, src/qml/qgismobileapp.qml
At present, when the canvas location is locked and the user zooms in or out with a mouse, the lock will break.
Using same approach in `zoomInButton` and `zoomOutButton`:
```QML
if (gnssButton.followActive)
gnssButton.followActiveSkipExtentChanged = true;
```
Now zooming in/out wont break lock.   
[Screencast from 2024-10-19 16-49-36.webm](https://github.com/user-attachments/assets/dffa4b78-986c-4f3c-8344-fe48dd094245)
=> Canvas location lock improvement.

src/core/digitizinglogger.cpp, src/core/layertreemodel.cpp, src/core/multifeaturelistmodelbase.cpp, vcpkg/ports/qgis/meshoptimizer.patch, vcpkg/ports/qgis/portfile.cmake, vcpkg/ports/qgis/processing.patch
I'm excited about this one, 3.40 is a really good release.
=> Update QGIS to 3.40.0 final

src/core/qfieldappauthrequesthandler.cpp, src/qml/qgismobileapp.qml
Without this in, makes it really hard to click on the top [ X ] button to dismiss the login popup.
=> Fix layer login popup getting into the top / bottom system OS margins

src/core/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloudprojectsmodel.h, src/qml/qgismobileapp.qml
As discussed with Didier, Michael, and Johnny
=> Fix attachments not uploaded immediately when hitting the synchronize button

src/qml/RelationCombobox.qml
Fixes https://github.com/opengisch/QField/issues/5766 in a less intrusive fashion than patching QtDeclarative source code for now.
It's definitively a workaround here, but I think we can be happy with it for now.
Discussion upstream continues here: https://bugreports.qt.io/browse/QTBUG-130819
=> Work around an upstream Qt crash when a relation editor combobox leads to its attribute item to be hidden

src/qml/RelationCombobox.qml
=> [Backport release-3_4] Work around an upstream Qt crash when a relation editor combobox leads to its attribute item to be hidden

src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
This PR fixes https://github.com/opengisch/QField/issues/5610 by insuring that the relation editor widgets respect the setupOnly feature form property. 
This means that people will be able to add a number of children prior to starting a track _as long as unique constraints on the data provider side doesn't prohibit it_.
=> When setting up our tracking feature, we avoid saving at all times, make relations accept that reality

src/qml/qgismobileapp.qml
This PR fixes https://github.com/opengisch/QField/issues/5661 . Long story short, when we digitize a new geometry using a mouse or stylus and we hit confirm, we would often lose snapped feature information as the coordinate cursor would reset to the screen center _prior to_ the feature form having calculated its default value. By resetting onto the middle of the screen, any snapped feature context would be lost.
It isn't really a problem when people uses fingers to interface with the interface since the cursor always stays in the middle of the screen.
=> To avoid interference with snapping results when creating features using a mouse/stylus, do not reset coordinate cursor when rubber band is frozen

src/qml/RelationCombobox.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
This PR fixes https://github.com/opengisch/QField/issues/5662 whereas the bits required to digitize a geometry when adding a parent / child feature in a relationship was missing from the relation combobox item.
=> Fix geometry digitizing step missing when adding a relationship parent via the relation combobox

src/qml/CoordinateLocator.qml
This PR introduces support for the backward snapping feature, allowing snapping to common angles both backward (to the starting point) and forward (last digitized point).
1. **Replacing Shape with Repeater for Snapping Lines:** Instead of using a static `Shape {}` element, we now use a `Repeater {}` with dynamic model data to display the snapping lines. This approach provides flexibility and allows for more efficient handling of multiple snapping lines.
**Props of each list element:**
```QML
ListElement {
beginCoordX: 0
beginCoordY: 0
endCoordX: 0
endCoordY: 0
snappedToAngle: false
}
```
The snapping line is only visible if `snappedToAngle` is true or if valid `endCoords` are provided.
2. **Adding the `forwardMode` Parameter:** We introduced a `forwardMode` parameter to three key …
=> Support backward and forward snapping lines.

.github/workflows/windows.yml, fastlane/Fastfile
This automatically pushes releases to S3 and creates an update on the ms store.
This reduces manual maintenance work.
Risk: when we republish too quickly (<3d), it will fail because "there's already an update in progress". We might be able to cancel an update, not yet done.
Room for improvement: add more languages, a link to release notes, ...
=> Autopublish to ms store

src/core/appinterface.cpp
This PR introduces the use of a temporary file to progressively save data as a file is being downloaded during the import URL process. 
This should prevent QField from crashed caused by running out of memory when downloading large files in this process.
=> Fix import URL eating tons of memory on large file downloads

test/qml/tst_qFieldGuide.qml
We can either do what I suggest in this PR, or don't upload the translation strings from the `test` dir. I think this is easier.
=> Don't translate strings used in tests only

src/core/CMakeLists.txt, src/core/appinterface.h, src/core/locator/activelayerfeatureslocatorfilter.cpp, src/core/locator/featureslocatorfilter.cpp, src/core/locator/locatormodelsuperbridge.cpp, src/core/locator/locatormodelsuperbridge.h, src/core/locator/qfieldlocatorfilter.cpp, src/core/locator/qfieldlocatorfilter.h, src/core/pluginmanager.cpp, src/core/pluginmanager.h, src/core/qgismobileapp.cpp, src/core/qgsquick/qgsquickmapsettings.h, src/core/utils/coordinatereferencesystemutils.h, src/core/utils/featureutils.cpp, src/core/utils/featureutils.h, src/core/utils/geometryutils.cpp, src/core/utils/geometryutils.h, src/qml/LocatorItem.qml, src/qml/LocatorSettings.qml, src/qml/qgismobileapp.qml, vcpkg/ports/qgis/locatorcontext.patch, vcpkg/ports/qgis/portfile.cmake, vcpkg/ports/qgis/rectangle.patch
_Much wisdom gained from these lines of code._
The PR adds a framework that allows for plugin authors to integrate into the search bar through a QML-driven locator filter.
Here's a sample plugin registering a QML locator filter being declared:
```qml
Item {
id: plugin
Component.onCompleted: {
locatorBridge.registerQFieldLocatorFilter(testLocatorFilter);
}
QFieldLocatorFilter {
id: testLocatorFilter
name: "testlocator"
displayName: "test locator!!!"
prefix: "123"
source: Qt.resolvedUrl('testlocator.qml')
function triggerResult(result) {
console.log(result)
}
}
}
```
The QFieldLocatorFilter item *lives in the same thread and context* as QField's mainWindow, and therefore can access the map canvas et al within the `triggerResult` function.
Notice the source property of QFieldLocatorFilter. …
=> QML locator filter framework for QField plugin

src/core/platforms/platformutilities.cpp, src/core/platforms/platformutilities.h, src/qml/editorwidgets/ExternalResource.qml
This is a relatively serious fix here as it was leading to failed saving of sketches over images, or even attempts at overwriting an image attachment for a given feature _provided the expression-driven filename resulted in the same filename as the previous one being replace_.
=> Fix sketching over image attachments sometimes not working

src/core/appinterface.cpp
=> [Backport release-3_4] Fix import URL eating tons of memory on large file downloads

src/core/featurelistmodel.cpp
Fixes https://github.com/opengisch/QField/issues/5859 , super happy about this one, I was seeing it often on sentry.
Big thanks to @Hikuritamete for having taken the time to answer questions and provide additional information which led to this fix.
=> Avoid infinite sort loop when gathering feature lists for the value relation editor widget

src/core/featurelistmodel.cpp
=> [Backport release-3_4] Avoid infinite sort loop when gathering feature lists for the value relation editor widget

images/images.qrc, src/qml/BusyOverlay.qml, src/qml/CodeReader.qml, src/qml/DashBoard.qml, src/qml/DigitizingToolbar.qml, src/qml/FeatureForm.qml, src/qml/GeometryEditorsToolbar.qml, src/qml/Legend.qml, src/qml/LocatorItem.qml, src/qml/NavigationBar.qml, src/qml/QFieldAudioRecorder.qml, src/qml/QFieldCamera.qml, src/qml/QFieldSketcher.qml, src/qml/ScaleBar.qml, src/qml/WelcomeScreen.qml, src/qml/editorwidgets/ExternalResource.qml, src/qml/geometryeditors/Erase.qml, src/qml/geometryeditors/VertexEditor.qml, src/qml/imports/Theme/QfButton.qml, src/qml/imports/Theme/QfCalendarPanel.qml, src/qml/imports/Theme/QfCloseButton.qml, src/qml/imports/Theme/QfPageHeader.qml, src/qml/imports/Theme/Theme.qml, src/qml/qgismobileapp.qml
This gets rid of a bunch of "white" (or non-declared) color in favor of Theme color properties.  The PR also declares a new set of properties for tool buttons to make it semantically easier to read / modify.
The PR also adds a main [color] overlay color (i.e. the color we can use as overlay to the main color). This is mostly QField green navigation bar's text + buttons (which were hard-coded as "white"), or selected items' text.
Finally, the PR allows for customizing individual (or all) appearance colors. I.e., say hello to color scheme plugins.
=> Improvements to theme color handling, allow customizing appearance colors

src/qml/QFieldCloudScreen.qml
On the project selection screen when opening QField, the tab switch with My projects and community was not translated.
In this PR is the (one-line) change necessary to get this also correctly translated in the app.
=> Add missing translations for tabbar on QFieldCloudScreen

src/core/qgismobileapp.cpp, src/qml/About.qml
Also small refactor on the `Label.text` implementation to bring it to the latest best practices in JavaScript:
- `var` -> `const`
- braces around `if`s
|-|-|
| ![image](https://github.com/user-attachments/assets/1a3a2589-2c52-44c5-b986-a87edfbaca08) | ![image](https://github.com/user-attachments/assets/b2ae4cf2-8c78-4fa1-8b4c-5177f7eb23bd) |
=> Refactor the About screen to show the QGIS and GDAL/OGR versions

src/qml/CoordinateLocator.qml, src/qml/qgismobileapp.qml
This PR fixes https://github.com/opengisch/QField/issues/5882
@suricactus , thanks for the report. I've also taken the opportunity to update the code to avoid referencing to the snapToCommonAngleButton item. That created an assumption it is always present in the parent scene, which makes it harder to test items in isolation afterwards.
=> Do not enable snapping to angle when cursor locked to position, improve code to avoid referencing to parent item

src/qml/QFieldSketcher.qml
Improvements include:
- Remove page padding (introduced in Qt6 I think)
- Improve height of the drawing templates area for landscape oriented screens
- Insure that template titles are confined to their own items
=> Improve looks of the drawing templates folder

doc/dev.md
Update the cmake-command in the docs for the iOS build, as a parameter is missing to get the build successfully passed. See also #5897.
=> Update IOS cmake command in docs

vcpkg/ports/sentry-cocoa/exception.patch, vcpkg/ports/sentry-cocoa/portfile.cmake
Missed a fix I had local which I didn't proposed here yet in a PR, related to XCode / iOS builds.
When using XCode 16, the build always fails due to an issue with the Sentry package. I checked if it was feasible to update the package, but as still version 7 of the package was used, and the fix only existed in 8 I decided to only apply the patch. Maybe in a future version the Sentry package can be updated, but I assume there is a reason why this hasn't been done yet?
The issue / PR from Sentry that describes the issue and why it is resolved is over here: https://github.com/getsentry/sentry-cocoa/pull/4051
=> Add sentry patch for XCode 16 support

.github/workflows/windows.yml
Within the Windows build workflow, Ruby is installed as one of the last steps. It is installed to facilitate the S3 upload and debug symbol upload. These steps however contains conditions, and are only executed when a release is created.
Herby a PR to add also the same condition to the Ruby setup. The task itself takes just 30 seconds in the workflow, but still it is every time 30 seconds in a workflow that takes already significant time to run.
=> Add condition to ruby install in Windows action

platform/android/src/ch/opengis/qfield/QFieldActivity.java, src/core/platforms/android/androidplatformutilities.cpp, src/core/platforms/android/androidplatformutilities.h, src/core/platforms/platformutilities.cpp, src/core/platforms/platformutilities.h, src/qml/WelcomeScreen.qml, src/qml/editorwidgets/ExternalResource.qml
This PR gets rid of the last permission-request-on-launch popup when installing QField on Android: storage access. Instead of throwing an intimidating / irritating permission request when launching QField, we adopt a much better practice of asking permission when actually needed. We adopted this behavior for all other permissions, and it makes a huge difference.
In this case, we will only request permission when users have clicked on the "open local files" button from the welcome screen, or when users use the "attach picture from gallery" or "attach file" actions within the feature form's attachment editor widget.
This means someone could install QField, log into QFieldCloud, fetch and consume a project without ever being asked for this permission, _unless_ they would end up triggering an …
=> Rework storage permission handling on Android to serve permission request in context

cmake/Package.cmake, platform/android/AndroidManifest.xml.in, src/core/platforms/android/androidplatformutilities.cpp
We rely on Android file/photo/video pickers these days.
=> Remove obsolete android permissions

src/core/networkreply.cpp, src/core/networkreply.h, src/core/platforms/android/androidplatformutilities.cpp, src/core/qfieldcloudconnection.cpp, src/core/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloudprojectsmodel.h, src/qml/NavigationBar.qml, src/qml/QFieldCloudScreen.qml
**PR Description:**  
This PR aims to handle the download progress of a network reply by writing the downloaded data incrementally to a temporary file. The key steps include:
- **Listening to Download Progress:** We connect the `downloadProgress` signal of the `NetworkReply` to a lambda function that processes the download as it progresses.
- **File Writing:** Inside the lambda, we open the temporary file in append mode `(QIODevice::Append)` and write the data to it each time new bytes are received.
- **Error Handling:** If any error occurs while opening the file or during the write operation, we log the error and abort the network reply `(rawReply->abort())`.
- **Reading Data:** For each progress update, we read all available data from the reply using `readAll()` and write it to the …
=> QF-1414-Download and writing data to a temporary file in QFieldCloudProjects.

src/core/focusstack.cpp, src/core/focusstack.h, src/qml/DashBoard.qml, src/qml/WelcomeScreen.qml, src/qml/imports/Theme/QfButton.qml, src/qml/imports/Theme/QfDialog.qml, src/qml/imports/Theme/QfToolButton.qml, src/qml/imports/Theme/QfToolButtonDrawer.qml, src/qml/qgismobileapp.qml
This mode is toggled using F12 on the above-mentioned platforms. It is an alternative to the fullscreen mode (toggle via F11) which provides the possibility to do nice windows arrangement, screenshots, and screencasts.
How it looks on linux:
The PR also adds a couple of additional keyboard shortcuts. What we have now is:
- `F11`: toggle fullscreen
- `F12`: toggle borderless mode
- `Ctrl+Plus`: toggle browse/digitize mode
- `Ctrl+M`: activate the measurement mode
- `Ctrl+O`: open the file picker to select a project/dataset to load
- `Ctrl+K`: expand/focus on the search bar
- `Ctrl+Space`: digitize vertex/point
=> Implement a borderless window mode for QField on windows/linux/macos and add a couple of additional keyboard shortcuts

src/core/focusstack.cpp, src/core/focusstack.h
After further debugging, using itemFocusChanged signal is really not ideal (e.g., it throws constant interference when focusing on feature form items!). Instead, we can rely on the visibleChanged signal.
=> Use visibility signal as driver for focus stack focus

src/qml/DashBoard.qml, src/qml/imports/Theme/QfScrollBar.qml, src/qml/qgismobileapp.qml
Screencast:
https://github.com/user-attachments/assets/41538308-fed7-49d5-bf49-a7f649c0adcd
Improvements are as follow:
- The return home label gets '...' when it can't fit in the available space
- The top row of buttons now has the back/close button and 3-dot menu button always anchored to left and right edges, with the remaining button contained within a flickable item so nano screens can have access to all content
- The cloud button has been relocated to insure that has visual priority over the project folder button
=> UI followup to have the improved dashboard behave better on tiny, minuscule screens

images/images.qrc, images/themes/qfield/nodpi/ic_qfield_black_24dp.svg, src/qml/qgismobileapp.qml
[ic_qfield_black_24dp.svg](https://github.com/opengisch/QField/blob/930e74fa7fc028f64879ff60f184692541e6e32e/images/themes/qfield/nodpi/ic_qfield_black_24dp.svg)
=> Add about qfield icon.

platform/android/AndroidManifest.xml.in, platform/android/res/values/strings.xml, platform/android/src/ch/opengis/qfield/QFieldCloudService.java, platform/android/src/ch/opengis/qfield/QFieldPositioningService.java, src/core/featuremodel.cpp, src/core/featuremodel.h, src/core/positioning/positioning.cpp, src/core/positioning/positioning.h, src/core/positioning/positioningsource.cpp, src/core/positioning/positioningsource.h, src/core/projectinfo.cpp, src/core/qgsquick/qgsquickcoordinatetransformer.cpp, src/core/qgsquick/qgsquickcoordinatetransformer.h, src/core/rubberbandmodel.cpp, src/core/tracker.cpp, src/core/tracker.h, src/core/trackingmodel.cpp, src/core/trackingmodel.h, src/core/utils/geometryutils.h, src/qml/Legend.qml, src/qml/TrackerSettings.qml, src/qml/TrackingSession.qml, src/qml/qgismobileapp.qml, src/service/qfieldpositioningservice.cpp, src/service/qfieldpositioningservice.h
This PR implements background tracking support in QField :partying_face: 
Implementation notes:
- Users must return to the QField app for the collected positions while QField was suspended to be saved into the vector layer tracks. This is a requirement to insure features will get proper expression context et al and avoid serious issues with vector layers co-existing in multiple processes.
- The improvements fix an interesting out-of-sync situation where the position information was not necessarily matching the projected position (which is used to add vertices to the track feature).
Plenty of code refactoring has happened, hope it doesn't make it too much harder to review this.
=> Background tracking support

src/core/tracker.cpp
Regression discovered while testing  the new background tracking capability.
=> Fix handling of constraints when starting a new track to avoid data loss

src/qml/qgismobileapp.qml
@m-kuhn , a long time ago, you added code in QField to avoid the application window going missing on dual monitor systems when, upon relaunch, one screen has been removed. While that's super useful, it also ends up forcing QField to be moved onto the first screen on every launch, which isn't super friendly for people who have a static dual monitor setup, or launch QField multiple times within the same dual monitor configuration.
This PR improves things by forcing the main window to fit within the first screen _only_ when the system's screens configuration has been changed from the last time QField was loaded. 
And all of a second, I can reliably launch QField onto my secondary monitor consistently! :partying_face:
=> Fix QField always forced back to first screen on launch

platform/android/src/ch/opengis/qfield/QFieldActivity.java, platform/android/src/ch/opengis/qfield/QFieldUtils.java, src/qml/qgismobileapp.qml
This PR gets rid of our custom fullscreen handling on Android in favor of relying on the QML Window's MaximizeUsingFullscreenGeometryHint flag (like we already do on iOS).
On top lifting the burden of maintaining custom code by moving to Qt project code itself, using the flag provides a context that other parts of Qt may rely on to pick behavior based on the presence/absence of the flag (e.g. handlers).
=> Rely on MaximizeUsingFullscreenGeometryHint flag to provide fullscreen experience on Android

src/core/appinterface.cpp, src/core/appinterface.h, src/qml/DashBoard.qml
Screenshot time, look at the beautiful Ask AI button here:
As seen above, the PR allows for plugins to gently place themselves into the new dashboard actions toolbar. I've also resurrected the iface.addItemToMainMenuActionsToolbar() function as a deprecated method that now stands as an alias to addItemToDashboardActionsToolbar(). While plugins are still in their first year of existence, I guess it's not bad to avoid outright breaking things :)
=> Implement a iface function for plugins to add actions to the new dashboard actions toolbar

src/core/pluginmanager.cpp, src/core/pluginmanager.h, src/qml/PluginManagerSettings.qml
Until now, plugins wanting to offer a configuration dialog had to rely on adding a button _somewhere_ in QField, which creates clutter for no real reason when configuration is a once in a blue moon.
To remedy to the situation, this PR empowers plugin authors into adding a mechanism to trigger a configuration dialog. When loading a plugin, the plugin manager will now check for a `function configure() {}` declaration in the root item of the plugin in main.qml.
Screencast:
https://github.com/user-attachments/assets/c7f6297b-4754-44bf-b0ca-1ae8b8f0c95b
@mbernasocchi , as discussed. We can now have a clutter-free Ask AI! :)
=> Add a UX for plugins to register a configuration dialog within the plugin manager popup

src/app/main.cpp, src/qml/BookmarkProperties.qml, src/qml/Changelog.qml, src/qml/CodeReader.qml, src/qml/EmbeddedFeatureForm.qml, src/qml/LayerLoginDialog.qml, src/qml/LayerTreeItemProperties.qml, src/qml/PluginManagerSettings.qml, src/qml/PositioningDeviceSettings.qml, src/qml/QFieldAudioRecorder.qml, src/qml/QFieldCloudDeltaHistory.qml, src/qml/QFieldCloudLogin.qml, src/qml/QFieldCloudPackageLayersFeedback.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/RelationCombobox.qml, src/qml/TcpDeviceChooser.qml, src/qml/TrackerSettings.qml, src/qml/UdpDeviceChooser.qml, src/qml/WelcomeScreen.qml, src/qml/editorwidgets/ValueMap.qml, src/qml/imports/Theme/QfButton.qml, src/qml/imports/Theme/QfTextField.qml, src/qml/qgismobileapp.qml
This PR improves the looks of a couple of dialogs as well as positioning device settings popup by moving away from QfTextField (still used in the feature form and a few other places) in favor of the default Material TextField implementation.
Beyond sitting better alongside Material ComboBox items, It comes with a couple of nice improvements:
- slightly bigger hit area
- nicer reactive appearance to mouse hovering
- allows us to replace some labels with placeholder text, providing a more modern UI/UX
I came to realize this was needed for us while developing the WebDAV stuff, and I just can't unsee this now.
E.g.:
=> Avoiding using QfTextField when we mix up other material controls & popup height fixes

src/qml/MessageLog.qml, src/qml/PluginManagerSettings.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/qgismobileapp.qml
On Android, the popup that appears when long pressing on text fields is mislocated way down the screen for all of our dialog popups, including our shiny new WebDAV dialogs.
I suspect it has to do with us manually setting up the y property. We don't actually need to do that, let Qt handle placement.
=> Remove custom position code, let Qt center dialogs

src/qml/editorwidgets/RelationReference.qml
This fixes #288 , whereas our relation reference widget had not yet plugged in the filter expression configuration (even though we've architecturally supported this for a while now).
Nice win.
=> Fix missing filter expression support in the relation reference editor widget

src/core/featurelistmodel.cpp, src/qml/editorwidgets/ValueRelation.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml
The value relation's feature list model had its current feature form binding broken when a feature attribute value was changed. This PR fixes that.
In addition, I've fixed multi-line handling within our relation editor widget, which was until now glitching.
Before:
PR:
=> Fix value relation filter breaking after changing attribute value(s), improve relation editor widget handling of multiline feature display names

src/core/trackingmodel.cpp, src/core/valuemapmodelbase.cpp, src/core/vertexmodel.cpp, src/core/vertexmodel.h
Makes this section of PR files changed go away:
It's been distracting me, and it's the right thing to do :)
=> Shutdown 'unchanged files' code warnings that show up in PRs

src/qml/RelationCombobox.qml
Fixes https://github.com/opengisch/QField/issues/4309 .
=> Fix text wrapping for the relation combobox popup's items list

src/core/webdavconnection.cpp, src/core/webdavconnection.h, src/qml/QFieldLocalDataPickerScreen.qml
This PR improves the import webdav functionality by adding a mechanism through which URLs, users, and their last imported path will be saved and restored via combo box items.
By default, opening the import webdav folder will pre-fill to the last import selection.
The PR also implements a tree view to navigate remote folders, which _greatly_ eases navigation on complex tree structures:
https://github.com/user-attachments/assets/3ee339a3-2512-4c0e-8232-167f3101ed50
=> Implement remembrance into the import webdav dialog

src/core/featuremodel.cpp, src/core/layertreemapcanvasbridge.cpp, src/core/rubberbandshape.cpp, src/core/rubberbandshape.h, src/core/tracker.cpp, src/core/tracker.h, src/core/trackingmodel.cpp, src/core/trackingmodel.h, src/qml/TrackingSession.qml, src/qml/qgismobileapp.qml
This PR implements a number of strategies to optimize tracking playback when returning from a long period of time when QField was set in the background or the phone was locked.
For line and polygon layers, this makes replaying hours of captured positions near instantaneous. 
For point layers, the speed is significantly improved, yet as every position will lead to a completely new feature being added (inc. unique value checks, default value expression calculation, etc), the time required to playback the position can take longer. To that end, we now have a busy indicator overlay to tell the user an ongoing operation is happening. 
Overall, it makes using background tracking for long period of time much, much more efficient.
=> Tracker optimisation focus 

src/qml/CoordinateLocator.qml, src/qml/qgismobileapp.qml
**PR Description**
The snapping to angles functionality was working, but the snapping tolerance (the distance within which the cursor would snap to an angle) was too low. This low tolerance made it difficult to snap accurately to angles, especially when digitizing without a mouse. The precision required to hit the right angles was cumbersome, causing a less intuitive experience for users.
**Solution:**
To address this, we added a new option that allows users to configure the snapping tolerance for angles. This change improves usability by giving users more flexibility in setting the snapping distance to their preference, making it easier to snap to angles accurately without requiring precise cursor placement.
**Changes Made:**
* Introduced a configurable snapping tolerance setting for …
=> Angle snapping tolerance functionality

src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
This PR cleans up the snapping to angle settings by moving away from raw settings.{setValue,value}() functions in favor of the much nicer QML Settings item.
This in turn allows us to only enable snapping to angle for line and polygon layers to fix visual glitches when digitizing against points and geometryless layers.
=> Snapping settings cleanup & geometry type-driven activation

src/core/locator/activelayerfeatureslocatorfilter.cpp, src/core/locator/bookmarklocatorfilter.cpp, src/core/locator/featureslocatorfilter.cpp, src/core/locator/finlandlocatorfilter.cpp, src/core/locator/gotolocatorfilter.cpp, src/core/locator/locatormodelsuperbridge.cpp, src/core/locator/locatormodelsuperbridge.h, src/qml/CodeReader.qml, src/qml/LocatorItem.qml, src/qml/editorwidgets/RelationReference.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml, src/qml/qgismobileapp.qml
Practically speaking, the PR is there for a client's plugin to be able to react to captured QR/NFC codes without having to manually accept the decoded string.
Since this now happens without confirmation, we need a way to provide some more visual feedback in the form of geometry highlight. This wasn't available to plugins until this PR, and it's a nice and simple functionality that many people will appreciate.
=> Additonal functionalities surrounding the code reader and geometry highlighter for plugins

vcpkg/ports/qtdeclarative/portfile.cmake, vcpkg/ports/qtdeclarative/vcpkg.json
Probably gives us 5-10ms boot time win by skipping half a dozen plugin .so being loaded ;)
=> Reduce APK size further by removing MBs of needless qtdeclarative plugins

src/core/legendimageprovider.cpp
=> Fix legend image corruption when jumping from subtree to another with a step greater than one

src/app/main.cpp, src/core/platforms/platformutilities.cpp, src/core/platforms/platformutilities.h, src/core/qgismobileapp.cpp
This PR reworks the way we handle the presence of a pg_service.conf in the QField data directory (i.e. on Android <storage root>/Android/data/ch.opengis.qfield/files/QField) to allow for immediate and future improvements.
The big change: instead of having postgres consume that service configuration file (most often drag and dropped via USB cable), QField will copy its content into a new pg_service.conf file living within the QField app's writable system directory. By doing this, we unlock the ability by QField to modify that pg_service.conf file at will (think QFieldCloud-provided services being written into that file when successfully logging into QFC).
Back to the present, the new handling is meant to unlock support for SSL keys authentication through the following logic:
- when a …
=> Rework pg_service.conf handling to support SSL keys authentication

vcpkg.json, vcpkg/ports/qgis/vcpkg.json
Small picture lesson learned: AppImage environment doesn't like gles3.
Big picture lesson learned here is: local vcpkg-based Linux builds != Linux AppImage. One successfully executing does not mean the other will.
=> What is causing our AppImage to die?

src/core/networkreply.cpp
=> Only ignore SSL errors on non qfield.cloud endpoints

src/core/networkreply.cpp
=> [Backport release-3_5] Only ignore SSL errors on non qfield.cloud endpoints

src/qml/qgismobileapp.qml
**Description**
This PR addresses issue [#5296](https://github.com/opengisch/QField/issues/5296), which concerns a broken stylus binding to the coordinate locator.
The stylus binding is reliably broken by the following steps:
1.  Add a point using the stylus.
2.  Discard the point using your finger.
After this sequence, the stylus no longer functions correctly with the coordinate locator.
**Solution:**
It turned out that the `dummyHoverHandler`'s enabled property should be synchronized with the `hoverHandler` at all times.
**Known Limitation:**
There is a remaining edge case: If a user pans the map with their finger and then switches to using the stylus *within* 500 milliseconds, the stylus binding to the `CoordinateLocator` might be temporarily disrupted.  This is a known area for future …
=> Restore Stylus Binding to CoordinateLocator

src/qml/CoordinateLocator.qml
**Description**:
This PR addresses a usability issue related to adding vertices when the coordinate cursor is locked and is off-screen.  (#5883 ).
**Problem:**
When the coordinate cursor is locked, new vertices should be added at the current location point. However, if the user moves the map canvas so the current location (and thus the crosshair) is no longer visible, the user receives no visual confirmation of vertex addition. This creates uncertainty as to whether the vertex has been added or not.
**Solution:**
This PR implements a solution that automatically recenters the map when a vertex is added under the described condition. Specifically:
When the positionLocked setting is enabled and a vertex is being added.
The code checks if the crosshair circle (representing the current …
=> Center Map on Vertex Addition When Position Locked & Off-Screen

.github/ISSUE_TEMPLATE/10_bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
=> Add issue template when reporting a bug

src/core/localfilesmodel.cpp, src/core/localfilesmodel.h, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/imports/Theme/QfPageHeader.qml
**Description:**
In this PR we are implementing multi-selection functionality in the local project and dataset view.
**Changes Implemented:**
1- Selection mode triggers with **long press** on file / folder.
2- It is not possible to trigger selection mode in **root** (Home).   
3- In selection mode, **3 dot menu** for each item is invisible.  
4- In selection mode, back button will turn in to **cancel button** that clear selection.
**Main C++ Changes:**
1- Adding `inSelectionMode` Q_PROPERTY which indicates is in selection mode or not.   
2- Add `ItemCheckedRole`.
3- Add `clearSelection` function that `uncheck` selected mode for all items.  
**Screen cast:**
[Screencast From 2025-02-18 20-50-42.webm](https://github.com/user-attachments/assets/f449d458-14a3-4e86-a6a1-565499e50ebf)
=> Implement Multi-Selection for Local Data Picker Screen

src/qml/DashBoard.qml
The "Project Folder" is an unwanted leftover from the time this action was in the main menu. It's not visible by default _but_ if you change the font size of the app, you'll end up with this glitch:
Not ideal :wink:
=> Remove text label from the show project folder button in the dashboard

src/qml/QFieldCloudLogin.qml
QFieldSync allows for a custom server URL that ends with '/', QField doesn't and fails to communicate with the endpoint. This PR fixes the situation by being tolerant of that final '/'.
@suricactus , all good with you?
Fixes https://github.com/opengisch/QField/issues/6044
=> If '/' is the last character of a custom QFieldCloud server URL, slice it out

src/qml/QFieldCloudLogin.qml
=> [Backport release-3_5] If '/' is the last character of a custom QFieldCloud server URL, slice it out

vcpkg/ports/qgis/oauth-headers.patch, vcpkg/ports/qgis/portfile.cmake
This applies the changes from https://github.com/qgis/QGIS/pull/60668 on top of QGIS 3.40.
These changes allow to configure QGIS OAuth authentication configs to also include additional tokens from the token payload as HTTP headers in the requests. This allows us to also include a potential OpenID Connect ID Token in the requests, and will be needed to implement SSO using OpenID Connect in QField.
=> Add OAuth headers patch

src/core/qfieldcloudprojectsmodel.cpp, src/core/utils/qfieldcloudutils.cpp, src/core/utils/qfieldcloudutils.h, src/core/webdavconnection.cpp, src/core/webdavconnection.h, src/qml/QFieldLocalDataPickerScreen.qml
**Description:**
This pull request implements enhancements based on issue #6005, enabling the ability to push multiple files to both `QFieldCloud` and `WebDAV`.
**Enhancements for Pushing Multiple Files to QFieldCloud:**
We have updated the `addPendingAttachment` function to `addPendingAttachments`, which now accepts `const QStringList &fileNames` instead of `const QString &fileName` as its input. Additionally, we have refactored all instances where this function is used.
**Enhancements for Pushing Multiple Files to WebDAV:**
Similarly, we have revised the `uploadPath` function to `uploadPaths`, which now utilizes `const QStringList &localPaths` instead of `const QString &localPath`. Consequently, we have also refactored all related usages of this method.
**UI Notes:**
1. A menu button …
=> Upload multiple files to webDav or QFC

.github/workflows/ios.yml
Background on why this is needed in the form of a message from Apple's App Store:
_ITMS-90725: SDK version issue - This app was built with the iOS 17.5 SDK. Starting April 24, 2025, all iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution._
=> Trying to upgrade to Xcode 16 to build against iOS SDK 18

src/service/qfieldpositioningservice.cpp, src/service/qfieldpositioningservice.h
ATM, when we turn positioning off (long press on the positioning button -> uncheck [x] enable positioning), Android users might be mislead into thinking the positioning is still on as the service's notification isn't updated. Let's do that so users feel like they are achieving what they want.
=> When the user de-activate positioning within a session, let the positioning service notification reflect that

src/core/rubberbandmodel.cpp
Fixes issue https://github.com/opengisch/QField/issues/6068 (and likely a few more unreported issues).
This essentially reverts a change that was made to accommodate our trackers' use of the rubber band model, but other changes made it safe to revert (based on multiple tests I've done today).
=> Do not hard-wipe the last rubberband coordinate when resetting

src/core/qgsquick/qgsquickmapcanvasmap.cpp, src/core/qgsquick/qgsquickmapcanvasmap.h, src/qml/MapCanvas.qml, src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
Similar to what we have in QGIS. End result:
https://github.com/user-attachments/assets/2605f100-be80-40d3-9fb3-6962453f623b
This is actually quite nice as it doubles as a mean to prefetch XYZ tiles around the visible map extent, making browsing around the map that much nicer.
This is a requirement to a followup PR that will improve UX of map canvas located to position. 
Implements the following enhancement requested in 2020: https://github.com/opengisch/QField/issues/1532
=> Add preview rentering to map canvas

src/core/qgsquick/qgsquickmapcanvasmap.cpp, src/core/qgsquick/qgsquickmapcanvasmap.h, src/qml/MapCanvas.qml, src/qml/qgismobileapp.qml
This PR reworks the map canvas' "follow positioning" mode by insuring that the position stays in the middle of the screen while the map slips around. This makes for a much, _much_ better experience.
Before:
https://github.com/user-attachments/assets/7b8fa766-041e-4581-adb6-93e3cc1025da
PR:
https://github.com/user-attachments/assets/70243e78-4720-4db3-a32c-d35186b877f1
The PR leverages our newly-found ability at rendering content beyond the screen edge to be able to pan around while not triggering re-renders _all the time_. While I could not demonstrate this on my computer, the same logic has been applied to the device's compass when the map canvas is set to auto rotate along compass values.
In addition, the map canvas has a new smooth behavior, where panning, rotation, and zooming changes …
=> "Smooth ride", revamping the map canvas' "follow positioning" mode

src/qml/editorwidgets/RelationEditorBase.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml, src/qml/qml.qrc
This PR adds the possibility to print an atlas PDF tied to children of a parent within the parent feature form through the addition of actions within the relation editor widget's list. Here's how it looks like:
As the screenshot shows, the work here led to the delete button being relocated _into_ the 3-dot menu. Since it has become far less easy to accidentally tap on the delete button, it's now enabled all the time (irrespective of the feature form's editing state), just like we can delete the parent through its feature form all the time.
For good taste, I've also added a copy feature attributes to clipboard action. Interesting possibilities ahead of us! Thanks to Vevey for supporting this development. 
Note that I've taken the time to de-duplicate _tons_ of code shared across the …
=> Relation editor widget's print child feature atlas layout to PDF

src/qml/FeatureListForm.qml, src/qml/QFieldSketcher.qml, src/qml/qgismobileapp.qml
Now that our ESC/back key behavior works reliably, the missing parts stand out that much more. This one _deserves_ fixing.
=> Fix esc/back key not closing the QFieldCloud push/synchronize popup

src/qml/BusyOverlay.qml
This pull request introduces a `MouseArea` overlay within the `BusyOverlay.qml` component to prevent user interaction with the UI while a busy overlay is displayed. The overlay is specifically designed to block interactions during critical operations, such as file uploads to webDAV, ensuring a seamless and error-free user experience.
- Added a `MouseArea` called `busyOverlayCatcher` that fills the parent area of the `BusyOverlay.qml`.
- The `enabled` property of `MouseArea` is set to `busyOverlay.visible`, ensuring that it only activates when the busy overlay is visible.
- Implemented an `onClicked` signal handler that effectively suppresses any interaction by returning early when the overlay is active. This disallows users from selecting other files or navigating to different pages …
=> Overlay to Block UI Interaction During Busy State.

vcpkg/ports/qtbase/android_cursor_location.patch, vcpkg/ports/qtbase/bluetooth_mouse_fix.patch, vcpkg/ports/qtbase/portfile.cmake, vcpkg/ports/qtmultimedia/portfile.cmake, vcpkg/ports/qtmultimedia/video_recording_fix.patch
The PR fixes https://github.com/opengisch/QField/issues/5779 (Using Qfield with bluetooth mouse does not seem to work properly in the newest version) using a patch developed by Qt. (reported by our friends at National Land Survey of Finland).
The PR also fixes the copy/paste and selection handle not showing up at the right location on Android (reported by our friends at Oslandia). _This should have a nice positive impact of people wanting to use app-wide plugins._
Finally, the PR fixes a video recording issue with our QField camera.
=> Backport crucial Qt 6.8.3 fixes to our overlay Qt ports

src/core/pluginmanager.cpp, src/qml/PluginManagerSettings.qml
The PR polishes app-wide plugin experience in two ways: 
First, plugin manager's the list of installed plugins is now sorted, making it much easier to locate a plugin that's been installed.
More importantly, installing a plugin from a zipped archive now tolerates the following structure: 
- plugin_directory/main.qml;
- plugin_directory/metadata.txt;
- plugin_directory/.... 
When first launching the plugin framework, we required the plugin archive to have the main.qml in the _root_ of the zipppe archive, e.g.:
- main.qml;
- metadata.txt;
- ...
That form is a bit problematic for incoming plugin authors with prior experience authoring QGIS plugin as our big brother QGIS expects the plugin directory to be inside the zipped archive. We now support both styles. Win-win.
=> A bit of plugins polishing

src/core/qfieldcloudprojectsmodel.cpp
=> [Backport release-3_5] Fix windows errors removing temporary files when downloading a cloud project

src/qml/About.qml, src/qml/LayerTreeItemProperties.qml, src/qml/NavigationBar.qml, src/qml/PluginManagerSettings.qml, src/qml/QFieldCamera.qml, src/qml/QFieldCloudScreen.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/WelcomeScreen.qml, src/qml/editorwidgets/EditorWidgetBase.qml, src/qml/editorwidgets/RelationEditorBase.qml, src/qml/imports/Theme/QfMenu.qml, src/qml/imports/Theme/qmldir, src/qml/qgismobileapp.qml, src/qml/qml.qrc
This pull request introduces the `QfMenu` QML item, which consolidates and simplifies the implementation of multiple menus across the application. By replacing redundant code in various menu components, we have streamlined the menu structure and improved code maintainability.
- Created `QfMenu` component to encapsulate menu width.
The previous menu implementation required extensive code to calculate properties such as width. For example:
```qml
Menu {
id: linksMenu
title: qsTr("Links Menu")
width: {
var result = 0;
var padding = 0;
for (var i = 0; i < count; ++i) {
var item = itemAt(i);
result = Math.max(item.contentItem.implicitWidth, result);
padding = Math.max(item.padding, padding);
}
return result + padding * 2;
}
}
```
Menus can now be defined simply with:
```qml
QfMenu {
id: …
```
=> Refactor Menu Implementation with `QfMenu` Component

platform/android/AndroidManifest.xml.in, platform/android/src/ch/opengis/qfield/QFieldActivity.java
These Android-specific changes dramatically increase the reliability of opening files (datasets, projects, zipped projects) from apps such as telegram.
Until now, if a QField session was already launched , opening a file sent via telegram would fail (QField would open, die, then restart). This made for some bad UX when someone first installs QField, launches it, then goes to telegram to open a file.
I've tried these changes *a lot*, and I can't find a combinaison now that fails to open files. I'm *really* happy about this one. Makes giving instructions to people being on-boarded fail-proof.
@mbernasocchi , ties to what we discussed over the weekend :)
=> Fix reliability of file association on Android

.github/workflows/macos.yml, src/core/utils/layerutils.h
Fixes https://github.com/opengisch/QField/issues/6141
The long story short here is that the garbage collection of var iterator = LayerUtils.createFeatureIteratorFromExpression(...) isn't happening in due time, and we therefore need a way to close the feature iterator to free up the associated dataset connection. 
The PR adds an invokable close() function as well as bit of documentation to that affect.
=> Add a mechanism to explicitly close a feature iterator

src/core/qfieldcloudprojectsmodel.cpp, src/core/utils/qfieldcloudutils.cpp, src/core/utils/qfieldcloudutils.h, src/qml/QFieldLocalDataPickerScreen.qml
This pull request introduces several improvements to the file upload functionality, specifically for enhancing efficiency and extending support for pushing entire directories to QFieldCloud. The changes introduced include checksum verification to ensure that unchanged files are not uploaded again, reducing unnecessary data transfer, as well as enabling directory uploads.
1. **Checksum Verification for File Uploads**:
The file upload process has been optimized by introducing checksum verification. This ensures that files that have not been modified are not uploaded again, leading to significant efficiency improvements and reduced data transfer. The checksum verification mechanism is implemented using ETags for file comparison.
2. **Support for Uploading Entire Directories**:
A new …
=> Add Checksum Verification and Directory Upload Support for QFieldCloud

src/core/qgsquick/qgsquickmapcanvasmap.cpp
We should probably use logical DPI full stop, but we once tried it and our Android users didn't like the change. We can revisit for QField 4.0.
For the time being, we need it when testing scaling on Linux dev machines.
=> If users have explicitly set QT_SCALE_FACTOR environment variable, use logical DPI for map canvas rendering

src/core/CMakeLists.txt, src/core/appinterface.cpp, src/core/appinterface.h, src/core/externalstorage.cpp, src/core/externalstorage.h, src/core/qgismobileapp.cpp, src/qml/editorwidgets/ExternalResource.qml
This PR implements a fetch-only (i.e. read-only) support for external storage-driven attachment editor widget, i.e. when a given attribute's editor widget is configured like this in QGIS:
This is a nice step towards on-demand content for attachments, and increase our (already quite high) attribute form interoperability between QField and QGIS.
=> Fetch-only support for external storage (WebDAV/AWS 3) within the attachment editor widget

src/qml/QFieldCloudLogin.qml
@gounux , @lukasgraf , this PR implement authentication provider styling (as implemented in QFC PR https://github.com/opengisch/QFieldCloud/pull/1192)
=> Use QFC authentication details to style SSO buttons

.github/workflows/macos.yml
This PR fixes the MACOS build by using lipomerge by pip.
ping @m-kuhn
https://github.com/faaxm/lipomerge/issues/10
=> [Fixes: #6156] OSX Build script uses outdated path to lipomerge.py

src/qml/NavigationBar.qml
Basically the title, all prepositions are lower case, but somehow this one slipped to be capitalized and it looks alien.
=> Change the preposition to be lower case in "Update Attributes from Feature" string

src/qml/editorwidgets/RelationReference.qml
This PR fixes https://github.com/opengisch/QField/issues/6152 -- long story short here, in QGIS, the equivalent editor widget _always_ sorts its list by display name. Users expecting a sorted list in QField should have their expectations met.
=> Fix relation reference editor widget not sorting its list

src/qml/QFieldLocalDataPickerScreen.qml
ATM, the import WebDAV folder dialog can be a bit misleading as it allows users to click on OK after entering their credentials but _before_ selecting a folder (which results in the dialog being closed and nothing happening).
To make it extra clear to the user that they need to click on the Fetch remote folder button, let's disable the OK button until the user has selected an actual folder. That'll better communicate the required steps.
=> Disable the OK button ok the Import WebDAV folder dialog until a folder has been selected

src/qml/editorwidgets/RelationReference.qml
=> [Backport release-3_5] Fix relation reference editor widget not sorting its list

src/core/utils/fileutils.cpp, src/core/utils/fileutils.h, test/test_fileutils.cpp
**Problem**
While developing QField extensions, I discovered that the codebase lacks functions to read and write file content directly from QML. This absence makes several common extension scenarios difficult to implement:
- Reading file content to send via POST requests to APIs
- Storing local data when offline
- Implementing custom file-based caching with validation
- Processing local files (CSV, JSON, etc.) directly in QML
After examining FileUtils, PlatformUtilities, and QFieldCloudConnection, I found no existing functions that expose file content reading/writing capabilities to QML.
**Solution**
I've added three utility functions to the FileUtils class:
```
// Read entire file content as a byte array
Q_INVOKABLE static QByteArray readFileContent(const QString &filePath);
// Write …
```
=> Add file content read/write utilities for QML extensions

src/core/CMakeLists.txt, src/core/qfieldcloudproject.cpp, src/core/qfieldcloudproject.h, src/core/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloudprojectsmodel.h, src/core/qgismobileapp.cpp, src/qml/DashBoard.qml, src/qml/QFieldCloudPopup.qml, src/qml/QFieldCloudScreen.qml, src/qml/qgismobileapp.qml
(This is built on top of https://github.com/opengisch/QField/pull/6168 ; I'll leave the other one open to easily review the localized dataset addition)
This PR applies a massive refactoring to the cloud-related aspects of QField by pulling out virtually all of the cloud project-specific code that was added over time into the QFieldCloudProjectsModel class, which had become really difficult to manage and understand (for both newcomers to the code as well as veterans! :wink:). As a result of the work, a new QFieldCloudProject class has been added. We've moved away from a struct into a proper QObject class, with Q_PROPERTY, Q_INVOKABLE functions, signals, et al.
One of the most significant win here is that we can finally expose cloud project objects within QML itself. Until now, we were …
=> QFieldCloud-related classes revamp and improvements

src/app/main.cpp, src/core/appinterface.cpp, src/core/qfieldcloudconnection.cpp, src/core/qgismobileapp.cpp, src/core/webdavconnection.cpp, src/service/qfieldcloudservice.cpp, src/service/qfieldcloudservice.h, vcpkg/ports/qtkeychain-qt6/portfile.cmake, vcpkg/ports/qtkeychain-qt6/vcpkg.json
We can rely on new API in QGIS 3.42 to strengthen our authentication manager's database security/safety.
Since we're now (righteously :wink:)  storing QFieldCloud authentication details in the QgsAuthManager, we need to initiate QgsApplication when launching the attachment upload service on Android.
=> Improve security of the authentication manager's database + Fix QFieldCloud attachment upload on Android

src/qml/qgismobileapp.qml
The DragHandler driving freehand digitizing had a small threshold which meant that a stylus starting to draw would end up panning the map around a bit, leading to imprecise freehand digitizing motions. This PR fixes it.
Discovered by our very own @suricactus
=> Set stylus freehand digitizing start threshold to _zero_ so we have a precise start

src/core/qfieldcloudconnection.cpp, src/core/qfieldcloudproject.cpp, src/core/utils/qfieldcloudutils.cpp, src/core/utils/qfieldcloudutils.h, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/qgismobileapp.qml
(Temporarily includes https://github.com/opengisch/QField/pull/6190)
This PR fixes https://github.com/opengisch/QField/issues/6169 , and in doing so does a better job at compartmentalizing pending attachments into distinct users.
Long story short, we used to add all pending attachments into a single queue. That queue would end up "stuck" when users would log into a different user within the same QField instance / device.
The PR breaks that queue into one queue _per user_, and only tries to upload files from the logged in user.
=> Fix attachment upload on devices within which multiple cloud users are logging in

src/core/positioning/gnsspositioninformation.cpp, src/core/positioning/gnsspositioninformation.h, src/core/positioning/nmeagnssreceiver.cpp, src/core/positioning/positioningsource.cpp, src/core/utils/expressioncontextutils.cpp, test/qml/tst_positioning.qml
This PR exposes a couple of IMU-specific details to the positioning expression scope, namely @gnss_imu_roll, @gnss_imu_pitch, @gnss_imu_heading, and @gnss_imu_steering.
@mbernasocchi , as discussed.
=> Keep track of a couple of IMU details in the GNSS position information, expose them as expression variables

src/qml/editorwidgets/Range.qml, test/qml/tst_editorwidgets.qml
When a range editor widget's min / max has _not_ been defined, it was not possible to enter an integer other than 1 :scream:  This fixes it.
=> Fix range editor widget's undefined min/max for integer field type

.github/workflows/android.yml, .github/workflows/code_layout.yml, .github/workflows/linux.yml, .github/workflows/script_checks.yml
Minimal efforts to return to a functional CI on the release-3_5 branch.
We'll get a bunch of cppcheck warnings on _pre-existing_ code which we've fixed on master but I don't think we should spend time backporting. We'll be on QField 3.6 soon enough.
=> Fix CI builds on release-3_5 branch

src/qml/editorwidgets/Range.qml, test/qml/tst_editorwidgets.qml
=> [Backport release-3_5] Fix range editor widget's undefined min/max for integer field type

src/qml/editorwidgets/TextEdit.qml
Fixes https://github.com/opengisch/QField/issues/6207 .
=> Properly remove newline when a text editor widget is set to non-multiline

src/qml/editorwidgets/TextEdit.qml
=> [Backport release-3_5] Properly remove newline when a text editor widget is set to non-multiline

src/core/CMakeLists.txt, src/core/barcodeimageprovider.cpp, src/core/barcodeimageprovider.h, src/core/qgismobileapp.cpp, src/core/qgismobileapp.h
This allows us to do stuff like at zero cost (since we already ship the underlying library used here):
```
Image {
width: 400
height: 200
source: "image://barcode/?text=check-this-cool-code&color=green"
sourceSize.width: 400
sourceSize.height: 200
}
```
It'll be useful for us, and I can imagine it's an interesting functionality to have for plugin developers too.
=> Add an image provider dedicated to generating QR codes

src/core/identifytool.cpp, src/core/identifytool.h, src/qml/QFieldSettings.qml, src/qml/qgismobileapp.qml
This pull request introduces a new feature: **Automatically Open Form for Single Feature Identification**. The purpose of this feature is to streamline the user experience when identifying features on the map.
Currently, when users identify a single feature, they are required to go through a two-step process: first, selecting the feature from a list, and then clicking to open the feature form. This can feel redundant, as the list serves no purpose in cases where there's only one feature identified. With this update, users can enable a setting to skip the list and directly open the feature form when a single feature is identified. 
1. **Settings Update**:
- A new setting `autoOpenFormSingleIdentify` has been introduced in the application settings. This setting allows users to enable or …
=> Auto open form for single feature result

platform/android/AndroidManifest.xml.in, platform/android/src/ch/opengis/qfield/QFieldActivity.java, src/core/appinterface.cpp, src/core/appinterface.h, src/core/platforms/android/androidplatformutilities.cpp, src/core/platforms/android/androidplatformutilities.h, src/core/platforms/platformutilities.cpp, src/core/platforms/platformutilities.h, src/core/qgismobileapp.cpp, src/core/utils/urlutils.cpp, src/core/utils/urlutils.h, src/qml/qgismobileapp.qml, test/CMakeLists.txt, test/test_appinterface.cpp, test/test_urlutils.cpp
This PR implements a qfield:// scheme to allow for URL-driven actions on Android. ATM, there is only one action:
`qfield://local?import=https://docs.qfield.org/assets/projects/bee_farming_project.zip`
When using Android's camera, users can scan a QR code that decodes into the above URL scheme, which will lead them to import the project/dataset URL.
Project QR code example:
In action:
https://github.com/user-attachments/assets/d4a71aa6-a13d-44b9-af7e-c17958b37085
_When this PR (https://github.com/opengisch/QField/pull/6212) will be merged, the scheme will also handle cloud project details action._
=> Introduction of an android scheme to allow for URL-driven actions (inc. QR code decoded URLs)

images/themes/qfield/nodpi/ic_cloud_project_localonly_48dp.svg, src/core/appinterface.cpp, src/core/appinterface.h, src/core/barcodeimageprovider.cpp, src/core/qfieldcloud/qfieldcloudproject.cpp, src/core/qfieldcloud/qfieldcloudproject.h, src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp, src/core/qfieldcloud/qfieldcloudprojectsmodel.h, src/core/utils/urlutils.cpp, src/core/utils/urlutils.h, src/qml/QFieldCloudScreen.qml, src/qml/qgismobileapp.qml, test/test_appinterface.cpp, test/test_urlutils.cpp
Now that we have refactored the QFieldCloud-related classes, it's time to leverage the new possibilities it opened up. This PR implements a QFieldCloud project details view, which looks like this:
This does a couple of things really well which we were not doing before now:
- Project descriptions have gained relevance and usefulness by moving the project description away from the projects list into the project detail view. We can now write long descriptions without making the projects list look super odd, and the descriptions support markdown syntax which means hyperlinks to additional context et al.
- Project thumbnails are really nice, and the project details view embrace them.
- Project creation date and updated date details were missing altogether, they are there now.
As for UX, when …
=> Brand new QFieldCloud project details view + QR code project details fetching

src/core/utils/fileutils.cpp, src/core/utils/fileutils.h, src/qml/editorwidgets/ExternalResource.qml, test/test_fileutils.cpp
QFieldCloud recently added a restriction for file names so they can work on all popular operating systems. However, the attachment naming expressions have no restrictions to what they are going to evaluate.
Therefore the new `FileUtils::sanitizeFilePath` function has been added that will convert the disallowed chars into underscores and return an empty string when the file path cannot be fixed, for example when it is too long.
If an empty string is returned,then the default naming kicks in to guarantee the filename can be saved and can be uploaded to QFieldCloud.
---
QFieldSync config:
Resulting values:
=> Sanitize attachment filenames before saving so they are acceptable by QFieldCloud

src/qml/NavigationBar.qml
Issue identified as part of https://github.com/opengisch/QField/issues/6229
=> Avoid showing geometry editing button for datasets that do not support editing (e.g. file system permission prohibiting it

src/qml/Legend.qml, src/qml/qgismobileapp.qml
Fixes https://github.com/opengisch/QField/issues/6231 as well as adding additional safeguards against digitizing on a read-only layer through stylus and mouse.
=> Allow selecting a read-only vector layer to provide layer searches

src/core/featuremodel.cpp, src/core/identifytool.cpp, src/core/identifytool.h, src/core/multifeaturelistmodelbase.cpp, src/core/multifeaturelistmodelbase.h, src/qml/NavigationBar.qml
This PR implements feature identification fetching from WMS/ArcGIS MapServer/etc. raster layers, provided they are capable of returning features. Alongside our recent copy feature attributes to clipboard, it makes for a really nice enhancement.
For providers - such as ArcGIS MapServer - which provides geometries, we display a nice geometry highlight on top of the map (as we'd do with a vector layer:
The PR also cleans up handling of feature form for read-only layers.
=> Unlock feature identification on raster layers capable of returning features (WMS, ArcGIS Map Server, etc.)

test/qml/tst_editorwidgets.qml
We had 
```
QWARN  : test_qml::EditorWidgets::test_01_dateTime() "Could not convert argument 0 at"
QWARN  : test_qml::EditorWidgets::test_01_dateTime() 	 "expression for fieldIsString@file:///home/runner/work/QField/QField/src/qml/editorwidgets/DateTime.qml:35"
QWARN  : test_qml::EditorWidgets::test_01_dateTime() 	 "test_01_dateTime@file:///home/runner/work/QField/QField/test/qml/tst_editorwidgets.qml:216"
QWARN  : test_qml::EditorWidgets::test_01_dateTime() 	 "qtest_runInternal@qrc:/qt-project.org/imports/QtTest/TestCase.qml:1931"
QWARN  : test_qml::EditorWidgets::test_01_dateTime() 	 "qtest_runFunction@qrc:/qt-project.org/imports/QtTest/TestCase.qml:1947"
QWARN  : test_qml::EditorWidgets::test_01_dateTime() 	 "qtest_run@qrc:/qt-project.org/imports/QtTest/TestCase.qml:2127"
QWARN  : …
```
=> Fix warnings in test_01_dateTime().

src/qml/editorwidgets/Range.qml, test/qml/tst_editorwidgets.qml
Title says it all. This was problematic when QGIS projects would have a range editor widget for an integer64/longlong field with the default min/max. That min/max was not compatible with intvalidator, leading to an unuseable editor widget in QField.
=> Get rid of IntValidator in favor of DoubleValidator to fix integer64/longlong compatibility

src/core/attributeformmodelbase.cpp, src/core/attributeformmodelbase.h
This PR implements the two available data-defined properties tied to fields within feature forms, namely:
- field alias
- field's read-only/editable state
Both rely on an expression context that _includes_ QFieldCloud variables (@cloud_username and @cloud_useremail), which means we can now allow/disallow editing of certain fields based on which logged in QFieldCloud user is consuming a given cloud project.
As for the field alias, it can be useful to deliver multilingual forms when associated with e.g. a project-level variable that'd drive map canvas labels _as well as_ feature form attributes.
Implements https://github.com/opengisch/QField/issues/2417
=> Implement data defined feature form properties (field aliases and field editable state)

src/qml/Toast.qml, src/qml/qgismobileapp.qml
This pull request aims to implement a more robust mechanism to maintain the "lock on position" mode for users, particularly those driving and requiring the ability to zoom, pan, or rotate the map while preserving tracking functionality.
- Introduced a 5-second auto-relock mechanism after map panning, ensuring that the map automatically re-centers on the user's position unless explicitly unlocked.
- Added a visual progress bar within the toaster message to indicate the relock timer. This provides users with feedback about the relock countdown.
- Included an "Unlock" button within the toaster message for users to permanently disable auto-relocking if needed.
- Updated the `Toast.qml` component:
- Added a new `animationEnabled` property to support animations like the relock countdown.
- …
=> Hard-lock on positions

src/qml/QFieldGuide.qml
This pull request fixes the incorrect positioning of the indicator in `QFieldGuide`.
**Issue**
The indicator was misaligned, resulting in a poor visual experience.   
[Screencast From 2025-05-13 16-36-51.webm](https://github.com/user-attachments/assets/7d915564-ed8f-425c-8545-b57a62365ef2)
**Fix**
Made minor geometry adjustments to correctly position the indicator.   
[Screencast From 2025-05-13 16-32-21.webm](https://github.com/user-attachments/assets/19d04355-a2c3-4abd-a33c-e416fd7073ee)
=> QFieldGuide: fix indicator position.

src/core/referencingfeaturelistmodel.h, src/qml/editorwidgets/relationeditors/relation_editor.qml
Hoping this fixes the crash reported in https://github.com/opengisch/QField/issues/6261 . I've been able to replicate the crash (which does not happen all the time), and the gdb stack trace led me to realize our FeatureGatherer class was not thread safe.
=> Insure the referencing feature list model's feature gatherer is thread-safe

src/core/locator/featureslocatorfilter.cpp
By using .arg twice when creating the filter expression string, we were messing with any %1 present in the display expression (e.g. `format('room %1', "roomName")` )
=> Fix all features locator's bad expression creation

src/core/qgsquick/qgsquickmapsettings.cpp, src/core/utils/expressioncontextutils.cpp, src/qml/editorwidgets/RelationEditorBase.qml, src/qml/editorwidgets/ValueMap.qml, src/qml/editorwidgets/ValueRelation.qml
The logic got lost along the way it seems.
When someone saves a temporally-aware project with temporal navigation disabled, QField was meant to not activate its own temporal filtering. Upstream seems to have changed some of its behavior, whereas setting the map settings' temporal range (re-)enables temporal state. This PR addresses the behavior change to get us back to a sane behavior.
Fixes #6271
=> Fix temporal filtering not respecting default project temporal navigation state

platform/android/src/ch/opengis/qfield/QFieldPositioningService.java
I was misreading the documentation, the Build.VERSION_CODES.UPSIDE_DOWN_CAKE minimum has to do with the manifest, not the function parameter.
=> Fix minimum API level for foreground service type

src/core/clipboardmanager.cpp, src/core/clipboardmanager.h
This message scares people, let's get rid of it: 
The one downside is that, on app launch, if someone had copied a feature string data from an email or message (a 0.1% chance of ever being the case), QField wouldn't be aware of this on launch. I think it's a fair trade to avoid scaring people.
=> Avoid scary clipboard message when launching the app

src/core/qgsquick/qgsquickmapsettings.cpp, src/qml/geometryeditors/VertexEditor.qml
When clicking the "next feature" button in geometry editing mode, the map center position was incorrect when:
1. The map was rotated
2. The information drawer was open
This happened because the margin adjustments for the information drawer weren't properly accounting for map rotation.
The fix modifies the `setCenter` function in `QgsQuickMapSettings` to properly handle margin adjustments with rotation. Here's how it works:
```cpp
const double baseXAdjustment = mRightMargin * devicePixelRatio() * mMapSettings.mapUnitsPerPixel() / 2;
const double baseYAdjustment = mBottomMargin * devicePixelRatio() * mMapSettings.mapUnitsPerPixel() / 2;
```
- We calculate the base margin adjustments in map units
- The division by 2 is crucial because the margin needs to be split between both sides of the …
=> Fix map center positioning with rotation and information drawer

src/qml/FeatureListForm.qml, src/qml/NavigationBar.qml, src/qml/qgismobileapp.qml
This PR introduces the ability to process individual features directly from the feature form. Previously, processing actions were mainly available in multi-selection or list contexts. With this enhancement, users can now trigger processing algorithms on a single feature without having to leave the feature form, streamlining the workflow and improving usability.
- Added a new `Process Feature` menu item within the feature form options.
- Introduced the `singleFeatureIdentified` property and related logic to track and handle single feature identification.
- Updated `NavigationBar.qml`, `FeatureListForm.qml` and `qgismobileapp.qml` to wire up the new behavior and UI elements.
- When a single feature is identified and opened in the feature form, users will see the new **Process Feature** …
=> Add feature processing capability to individual features.

src/core/featuremodel.cpp, src/core/vertexmodel.cpp, src/core/vertexmodel.h
Screencast time:
https://github.com/user-attachments/assets/4a6e02af-adce-49b5-8b86-6b560c08cd13
The PR adds a missing bit in our vertex editor tool whereas _addition of new vertices_ were never injected into topological relationships across layers.
=> Handle topological addition of vertices across layers when using the vertex editor tool

src/qml/QFieldLocalDataPickerScreen.qml
Simply wrapping on word boundaries is not proper/enough when looking a filenames. Matches a similar fix we applied for QFieldCloud projects list view.
This now properly reflows:
=> Improve wrapping of local data view's filenames

src/qml/MapCanvas.qml
A regression was conveyed on the play store about "sluggish" behavior with QField 3.6, I suspect it has to do with us not stopping rendering while panning / zooming / rotating. We can go back to the previous behavior while leaving the new behavior on when locked to canvas (aka 'follow').
=> Stop rendering when freezing canvas for anything but follow events

src/core/changelogcontents.cpp, src/qml/Changelog.qml
This PR fixes an issue where large images in the changelog view could overflow the screen on smaller devices.
- Ensured images are responsive using `style="max-width:100%; height:auto;"`
| Before                                                         | After                                                         |
| -------------------------------------------------------------- | ------------------------------------------------------------- |
|![image](https://github.com/user-attachments/assets/6f421035-2e50-4d7c-9e74-8c062138b575) |![image](https://github.com/user-attachments/assets/6dbfc394-e145-430d-bbf4-48b22e07d85b)
=> Make Markdown images responsive in changelog viewer.

platform/ios/Info.plist.in
=> [Backport release-3_6] Allow non-HTTPS connections on iOS to connect to GNSS NMEA streams over HTTP TCP sockets

src/core/CMakeLists.txt, src/core/featurechecklistproxymodel.cpp, src/core/featurechecklistproxymodel.h, src/core/featurelistmodel.cpp, src/core/featurelistmodel.h, src/core/qgismobileapp.cpp, src/qml/RelationCombobox.qml, src/qml/editorwidgets/RelationReference.qml, src/qml/editorwidgets/ValueRelation.qml
This PR introduces several improvements to the ValueRelation editor widget, enhancing its usability and flexibility:
- **Search Functionality:**  
Added a search bar to the `ValueRelation` list, allowing users to quickly filter and find items based on their input.
- **Conditional Sorting (Checked Items First):**  
Introduced a `FeatureCheckListProxyModel` which enables sorting of checked items to appear at the top of the list. This sorting is active only in reading mode (i.e., when the widget is not enabled for editing).
- **UI Improvements:**  
- Adjusted padding and margins for better visual alignment and spacing.
- Fixed height calculation for the widget to ensure proper sizing with the new search bar and component structure.
- Implemented a new proxy model …
=> Value Relation: Search, Sort, Looks

src/core/navigation.cpp
Original fix provided by @AntoElCrackito here (https://github.com/opengisch/QField/pull/6378).
=> Insure navigation bearing serves a value between 0 to 360 degree

src/core/utils/fileutils.cpp, test/test_fileutils.cpp
=> [Backport release-3_6] fix: accidentally killed `+` support in attachments filenames due to windows insane slashes

src/core/navigation.cpp
=> [Backport release-3_6] Insure navigation bearing serves a value between 0 to 360 degree

.devcontainer/devcontainer.json, doc/dev.md
This PR adds a devcontainer support to get started with the development in an easy way. I also added some instructions of how to use it with CLion and VSCode. 
For now it supports only linux based hosts (because of X11 mounts), but a separate devcontainer could be made for Windows-WSL later on.
=> Add devcontainer support for QField

src/qml/DashBoard.qml, src/qml/QFieldGuide.qml, src/qml/qgismobileapp.qml
This PR upgrades the in-app guide system to provide contextual hints on more dashboard buttons in QField!
- **More Button Hints:**  
Added `objectName` properties to key dashboard buttons—`Measurement`, `Print`, `Cloud`, `Project Folder`, and `Mode Switch`—so they can be targeted with guide overlays.
- **Interactive Guide Steps:**  
Introduced "action" steps in the guide system, allowing the guide to open/close the dashboard automatically and highlight elements even if hidden at first.
- **👀 Better Onboarding:**  
Users now see helpful explanations and highlights for all major dashboard features, making QField easier to learn and use!
---  
[Screencast From 2025-06-30 21-28-20.webm](https://github.com/user-attachments/assets/230ad6e3-ab84-4035-a55e-1e193557a71f)
=> Add Contextual Hints for Dashboard Buttons and Interactive Guide Actions

src/core/webdavconnection.cpp, src/core/webdavconnection.h, src/qml/QFieldLocalDataPickerScreen.qml
This PR implements the ability for users to customize the name of the folder containing imported content from a remote WebDAV folder.
Here's a screenshot of the new UI:
Since we now allow for customized names, the tree showing the remote WebDAV folders now indicates the name of the local folder when already imported:
Since we now let user control the folder name, an additional safeguard was added to insure name collisions are avoided to prevent worlds colliding :)
Finally, to make room for the new label and text input, the refresh remote folders button was relocated to sit above the remote folders list, in a more muted fashion. This move makes a lot of sense as the button was not likely to be used frequently to begin with. It makes for a nicer UX overall.
Bonus, some tiny UI styling …
=> Implement imported folder naming customization

src/qml/NavigationBar.qml
Title says it all. While it brings me satisfaction to point out that there is meaning in rotating multipart points, it's not worth people going "err, rotating a _point_?!" :wink:
=> Hide rotate feature for singlepart point geometries

src/core/featurelistextentcontroller.cpp, src/core/qgsquick/qgsquickmapsettings.cpp, src/core/utils/featureutils.cpp
Before PR:
https://github.com/user-attachments/assets/de96dd8d-ba6e-4689-abba-520e0799d1c8
With PR:
https://github.com/user-attachments/assets/fabbfb53-988d-4806-a077-9fd0e6338993
:heart_eyes: 
The two changes here are:
- reworking how we modify extent when bottom/right margin are present to make it more robust (and maybe slightly easier to understand as we're combining the map canvas + the extent being passed)
- to insure we're spot on the center of the rotated extent, we use setCenter() after passing on the extent
I think the end result works quite nicely here and I'm hoping this is the last time we revisit this :)
=> Fix margin handling of rotated extent to fix zoom to feature et al

src/qml/qgismobileapp.qml
@mohsenD98 , I missed this when reviewing your dashboard guide code: when you use invokable settings value functions, they will not be properties but rather a static value. 
In this case, it means the dashboard connection would *not* get disabled when you changed the settings value (via setValue), which in turn means the guides would re-open any time you open the dashboard within the same initial app launch.
Fixes https://github.com/opengisch/QField/issues/6451
=> Fix dashboard guides re-appearing all the time during the first app launch

src/qml/qgismobileapp.qml
=> [Backport release-3_6] Fix dashboard guides re-appearing all the time during the first app launch

src/core/locator/activelayerfeatureslocatorfilter.h, src/core/locator/bookmarklocatorfilter.h, src/core/locator/expressioncalculatorlocatorfilter.h, src/core/locator/featureslocatorfilter.h, src/core/locator/gotolocatorfilter.h, src/core/locator/helplocatorfilter.h, src/core/locator/locatormodelsuperbridge.cpp, src/core/locator/qfieldlocatorfilter.cpp, src/core/locator/qfieldlocatorfilter.h
Because a blank space really doesn't make our search bar integration shine.
Before:
PR:
=> Allow for plugins to add a description to search bar locator filters

src/core/pluginmanager.cpp, src/core/pluginmanager.h, src/core/pluginmodel.cpp, src/core/pluginmodel.h, src/qml/PluginItem.qml, src/qml/PluginManagerSettings.qml
This PR implements a basic trusted state for plugins served/installed through the remotely available plugin endpoint JSON. 
The logic is quite simple ATM: if a given plugin UUID - at the moment the unique folder name - is listed in the remote plugin endpoint JSON, we consider the plugin to be trusted. To insure that this can't be abused easily, the manual installation of a plugin via URL now does a check against the remotely fetched plugin list and if the plugin to be install has the same UUID/folder name as what is listed remotely, we block the manual URL installation in favor of the list.
To make for the best possible experience, the remote plugin JSON is cached in the app's configuration directory and used on app launch to re-populate the trust status. If that location is compromised …
=> Implement remote plugin information cache and add a "trusted" state

src/core/utils/fileutils.cpp, src/core/utils/fileutils.h, src/qml/QFieldCamera.qml
This PR adds image stamping customization functionality to QField, configured via a brand new subpanel in the project properties' QField panel on QGIS:
The image stamping customization allows for users to:
- customize the details being stamped via the crafting of an expression-based multiline string
- customize the font color/size/drop shadow/etc. used to render the details
- customize the position (left / center / right) of the details
- add an image decoration overlay on top of the image being stamped
- force stamping of images irrespective of QField's own setting (useful for manager distributing over QFC)
As a result, people can come up with this kind of customized stamping with just a little bit of configuration:
_Note the top-left logo and the QFC username detail_
=> Implement image stamping customization functionality

vcpkg/ports/qtbase/hang.patch, vcpkg/ports/qtbase/portfile.cmake
@beanzmo , I'm low-to-medium hopeful this will fix the hang you've been seeing. 
Upstream issues:
- [QTBUG-136077: Android apps hang with black screen or splash screen](https://bugreports.qt.io/browse/QTBUG-136077)
- [QTBUG-135961: Blank screen when app is woken up from background](https://bugreports.qt.io/browse/QTBUG-135961)
=> Cherry pick Qt fix that might well fix Android hangs

src/qml/FeatureForm.qml, src/qml/FeatureListForm.qml, src/qml/OverlayFeatureFormDrawer.qml
This PR addresses several UI/UX issues to improve consistency and user interaction with the feature form.
1. **Feature Form Layout on Square Screens**
* Fixed an issue where, on perfectly square screens, opening a new feature via digitizing would render the feature form with an awkward half-screen layout.
* The form now properly utilizes available space.
2. **Prevent Overscroll Flicking**
* Added `Flickable.StopAtBounds` to the feature list view to avoid unnecessary movement when reaching scroll boundaries.
3. **Scroll Wheel Behavior**
* Fixed a problem where mouse wheel events would bypass the feature form when it had no scroll, unintentionally triggering map zooms.
* Mouse wheel interaction is now properly contained within the form when expected.
=> UI polish: Fix feature form layout, scroll behavior, and overscroll flicking

src/qml/imports/Theme/QfBadge.qml, src/qml/imports/Theme/QfToolButton.qml, src/qml/imports/Theme/qmldir, src/qml/qgismobileapp.qml, src/qml/qml.qrc
This PR introduces a reusable `QfBadge` component and integrates it into the UI to improve consistency and maintainability. It also enhances the user experience by showing a badge indicator when a project has local changes that can be synced or pushed to `QFieldCloud`.
- Added a new `QfBadge` component to standardize badge rendering across the app.
- Replaced previous inline badge implementations with `QfBadge`.
- Displayed a badge on the main menu button when the project has changes that are ready to be synced or pushed to QFieldCloud.
[Screencast From 2025-07-16 12-23-53.webm](https://github.com/user-attachments/assets/e3e433fc-c1b8-40e2-93a1-cd5df459210f)
=> Show the cloud "notification" logo on the canvas when it has notifications

src/core/utils/geometryutils.cpp, src/core/utils/geometryutils.h, src/core/utils/layerutils.cpp, src/core/utils/layerutils.h, src/qml/qgismobileapp.qml
Should have been done in 3.6! Better later than never.
With this in, plugins can register an handler and do stuff like:
```
const pointHandler = iface.findItemByObjectName("pointHandler")
const mapCanvas = iface.mapCanvas()
pointHandler.registerHandler("my_plugin", (point, type, interactionType) => {
if (interactionType === "clicked") {
// create a pair of point that'll represent a buffer area within which features are to be searched
let tl = mapCanvas.mapSettings.screenToCoordinate(Qt.point(point.x - 4, point.y - 4))
let br = mapCanvas.mapSettings.screenToCoordinate(Qt.point(point.x + 4, point.y + 4))
let expression = "intersects(geom_from_wkt('POLYGON(("+tl.x+" "+tl.y+", "+br.x+" "+tl.y+", "+br.x+" "+br.y+", "+tl.x+" "+br.y+", "+tl.x+" "+tl.y+"))'), $geometry)"
let it = …
```
=> Expose map canvas point handler item to plugins

src/core/clipboardmanager.cpp
=> [Backport release-3_7] Fix clipboard holds feature property not emitting signal when going from true to false

src/core/attributeformmodelbase.cpp, test/test_attributeformmodel.cpp
@beanzmo , client fix as discussed on chat.
We were not initializing the expression context with the feature model's expression and layer fields, leading to bogus expression evaluations.
I've strengthened us with an additional test case to cover this.
=> Fix data-defined feature form properties (such as editable) not initializing properly

src/core/attributeformmodelbase.cpp, test/test_attributeformmodel.cpp
=> [Backport release-3_7] Fix data-defined feature form properties (such as editable) not initializing properly

src/core/qfieldcloud/qfieldcloudproject.h, src/qml/QFieldCamera.qml
As reported by Daniel while building a feature showcase.
=> Fix image stamping when the project property is not null but an empty string

CMakeLists.txt, src/core/CMakeLists.txt, src/core/featuremodel.cpp, src/core/featuremodel.h, src/core/positioning/filereceiver.cpp, src/core/positioning/filereceiver.h, src/core/positioning/positioningdevicemodel.cpp, src/core/positioning/positioningdevicemodel.h, src/core/positioning/positioningsource.cpp, src/core/rubberbandmodel.cpp, src/core/rubberbandmodel.h, src/qml/FileDeviceChooser.qml, src/qml/PositioningDeviceSettings.qml, src/qml/QFieldSettings.qml, src/qml/qml.qrc, test/CMakeLists.txt, test/test_tracking.cpp
This PR adds a new positioning receiver type that allows for the replay of NMEA logs (without the need for a faux nmeaserver). It simplifies testing positioning-related functionalities among other things.
It also allows us to build a bunch of C++ test cases covering positioning functionalities. This PR adds basic tracking test cases, which tests a bunch of classes that drives tracking. This was motivated by a regression that went unreported for a few versions, and we just can't afford that kind of breakage.
=> Postioning's logs file receiver to replay NMEA logs and tracking test cases

src/qml/FeatureForm.qml, src/qml/editorwidgets/ValueRelation.qml
Addresses UX issue raised in https://github.com/opengisch/QField/issues/6564
While we now respect the nb of columns configured for value relation editor widgets, due to the nature of the devices running QField it might not be a realistic proposition :) the PR improves things by adopting a flexible nb. of column (maxed out to the user configured nb) based on available space. This matches the behavior we adopted for tab / group's column count.
=> Reduce the number of column for the value relation editor widget when space missing

src/qml/FeatureForm.qml, src/qml/editorwidgets/ValueRelation.qml
=> [Backport release-3_7] Reduce the number of column for the value relation editor widget when space missing

src/core/qfieldcloud/qfieldcloudproject.cpp, src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp, src/qml/QFieldCloudPopup.qml
This should reduce user confusion whereas we were previously advertising a cloud project as being locally available yet would lead to a [ download project ] button.
=> Fix misrepresenting a cloud project as locally available when download was not completed

src/core/featurehistory.cpp, src/core/featurehistory.h
@beanzmo , one more fix for you. It properly disable undo/redo when manipulating layers that are part of a buffered transaction group.
=> Insure that feature history plays well with buffered transaction groups' project transaction mode

.pre-commit-config.yaml, src/core/positioning/gnsspositioninformation.h, src/core/positioning/positioning.cpp, src/core/positioning/positioning.h, src/core/positioning/positioningsource.cpp, src/core/positioning/positioningsource.h, src/core/qgismobileapp.cpp, src/core/tracker.cpp, src/core/tracker.h, src/core/utils/positioningutils.cpp, src/core/utils/positioningutils.h, src/qml/QFieldSettings.qml, src/qml/TrackingSession.qml, src/qml/qgismobileapp.qml
This PR introduces a new `AccuracyQuality` classification to enhance filtering of GNSS position data
* **`GnssPositionInformation`:**
* Added `AccuracyQuality` enum (`AccuracyBad`, `AccuracyOk`, `AccuracyExcellent`) with `Q_PROPERTY` support.
* New member `mAccuracyQuality` and corresponding getter/setter.
* **`Positioning`:**
* Added `badAccuracyThreshold` and `excellentAccuracyThreshold` as configurable properties with signals.
* `processGnssPositionInformation()` now evaluates and assigns an appropriate `AccuracyQuality`.
* **`PositioningSource`:**
* Averaging now only includes positions with `AccuracyOk` or better.
* **`PositioningUtils`:**
* Low-quality positions are excluded from averaging logic.
* **`Tracker`:**
* Ignores positions marked as `AccuracyBad`.
=> Implement GNSS accuracy quality classification requirement for averaged positioning and tracker sessions

src/core/CMakeLists.txt, src/core/processing/processingalgorithmparametersmodel.cpp, src/core/processing/processingalgorithmsmodel.cpp, src/core/qgismobileapp.cpp, src/core/utils/processingutils.cpp, src/core/utils/processingutils.h, src/qml/processingparameterwidgets/area.qml, src/qml/qml.qrc
While we shipped with the super useful delete holes algorithm when we first released our processing toolbox support in QField, we since then lost support as the algorithm moved away from (ab)using the distance parameter to represent an area. 
By implementing support for the area parameter in QField, we regain the algorithm out of the box. 
Proof of life:
=> Implement the area parameter to recover delete holes algorithm into the processing toolbox

src/core/deltafilewrapper.cpp, src/core/deltafilewrapper.h
Prior to this commit the data was stored as:
// { localLayerId: { localPk: indexInTheDeltafile } }
QMap<QString, QMap<QString, int>> mLocalPkDeltaIdx;
However, in `DeltaFileWrapper::mergeDeleteDelta` we have `mDeltas.removeAt`, which can potentially change all delta indices in the deltafile, but never update them in `mLocalPkDeltaIdx`.
This change removes the dependency of the positions in the deltafile and adds replaces it with the uuids of the deltas:
// { localLayerId: { localPk: deltaUuid } }
QMap<QString, QMap<QString, QString>> mLocalPkToDeltaUuid;
As the UUIDs does not have a direct mapping, a new method is also added:
/**
* Retuns the index position of a delta with given \a uuid in the deltas list or -1 if missing. *
* @param uuid the uuid we are looking for */ int …
=> fix(qfc): potential problem where a deleted delta scrambles the delta ids

src/core/deltafilewrapper.cpp, src/core/deltafilewrapper.h
`QgsFeature.attribute` returns a `QVariant` with specific meta type. If the meta type is double and the value is null, then `QVariant.toString()` returns 0, which is plain wrong.
Therefore this commit introduces a check if the value is null, and only then tries to call `toString()`.
=> fix: prevent the local/source PK to contain fake `0` values when it should be empty

src/qml/QFieldSettings.qml
Fixes https://github.com/opengisch/QField/issues/6471 
Two issues in there, including a wrong flags check as well as an assumption device capacities updates immediately after the device combobox index changes, which it does not these days.
=> Fix visiblity of the orthometric vertical adjustment combobox item visibility

src/qml/imports/Theme/QfButton.qml, src/qml/imports/Theme/QfProgrerssRing.qml, src/qml/qgismobileapp.qml
This PR refactors the dropdown arrow in the QfButton component. The previous Canvas-based implementation was replaced with a vector ShapePath, making the arrow scalable, responsive to theme color changes, and visually cleaner.
- Replaced `Canvas` with `Shape` for the arrow.
- Arrow automatically adapts to theme changes (color).
- Scales correctly with different button sizes.
- Visual appearance is cleaner and more consistent with Material/modern UI patterns.
---
---
=> Redesign dropdown arrow with scalable ShapePath

src/core/layertreemodel.cpp, src/core/layertreemodel.h, src/core/legendimageprovider.cpp, src/core/legendimageprovider.h, src/core/qgismobileapp.cpp, src/core/qgismobileapp.h, src/qml/DashBoard.qml, src/qml/LayerTreeItemProperties.qml, src/qml/Legend.qml, src/qml/imports/Theme/Theme.qml
This PR implements legend graphic fetching for WMS and ArcMapService layers (as well as any QGIS provider in the future that'll implement the required functions over there).
Screenshot time:
This can provide crucial information to users consuming WMS layers, where the symbology can often be complex and without a legend simply undecipherable. 
While in this part of the code, it was easy to add support for the little-known legend placeholder image option in QGIS. Here's how it looks in QField:
Here's where users set this up in QGIS:
=> Implement WMS/AMS legend graphics as well as legend placeholder images

src/core/qfieldcloud/qfieldcloudproject.cpp, src/core/qfieldcloud/qfieldcloudproject.h, src/qml/QFieldCloudScreen.qml, src/qml/imports/Theme/QfButton.qml
Improves the robustness of partial file downloads by handling HTTP 416 (Range Not Satisfiable) responses.  
When a server returns HTTP 416, the client now restarts the download from scratch.
- Detects HTTP 416 response during partial downloads.
- Removes any invalid or outdated partial files.
- Initiates a full download without the Range header to ensure data integrity.
[Screencast From 2025-09-07 19-48-52.webm](https://github.com/user-attachments/assets/55e021c3-bdae-46c2-894f-41108f03044a)
=> Whenever a HTTP 416 is received when partially downloading a file, restart the download from scratch.

src/qml/QFieldCloudScreen.qml, src/qml/imports/Theme/QfButton.qml
This PR introduces an `IndeterminateProgressComponent` to `QfButton`, enhancing the feedback options available to users. In addition to the existing determinate progress indicator, this component allows for undetermined (indeterminate) progress feedback where the exact completion percentage is unknown.
There are scenarios where a determinate progress value is not available, but users should still be informed that a process is ongoing. Adding undetermined progress feedback improves UX by providing visual cues even when the completion percentage cannot be calculated.
https://github.com/opengisch/QField/pull/6629#discussion_r2330161397
[Screencast From 2025-09-14 15-57-52.webm](https://github.com/user-attachments/assets/eaa79220-31f9-4f65-9772-e0f9e209f832)
=> Add `IndeterminateProgressComponent` to QfButton.

src/app/main.cpp, src/core/localfilesmodel.cpp, src/qml/QFieldSettings.qml
This PR implements support for localized / translated project files so that QField can speak a lot of languages too (background reading: https://www.opengis.ch/2018/09/11/qgis-speaks-a-lot-of-languages/). This also works with cloud projects, which is reallly nice. 
Contrary to QGIS, we will always display a localized project if the _XX.qm file is present (i.e., we don't require users to overwrite / specify a locale). It will respect the phone / device's OS locale, or the one specified in QField settings panel.
Implements / fixes https://github.com/opengisch/QField/issues/5670
=> Project localization/translation support

src/core/layertreemapcanvasbridge.cpp, src/core/layertreemapcanvasbridge.h, src/core/layertreemodel.cpp, src/core/layertreemodel.h, src/core/qgismobileapp.cpp, src/core/utils/layerutils.cpp, src/core/utils/layerutils.h, src/core/utils/projectutils.cpp, src/core/utils/projectutils.h
These new APIs provide plugin authors with additional powers to inject layers within the currently opened project (for the duration of the project session).
The new APIs are documented within the .h[eaders].
Should be super interesting to see what people do with this. 
Here's a simple example that'd load a new memory layer showing the content of a GeoJSON string:
```
let layer = LayerUtils.memoryLayerFromJsonString("my_results", fetched_json_string, CoordinareReferenceSystemUtils.wgs84Crs())
ProjectUtils.addMapLayer(qgisProject, layer)
```
To subsequently remove the layer:
```
let layer = qgisProject.getMapLayersByName("my_results")[0];
ProjectUtils.removeMapLayer(layer);
```
Hint: the layers loading functions can lead to really cool stuff when paired with gdal's vsicurl prefix. This …
=> Memory layer creation and vector/raster layer loading APIs

src/qml/BookmarkProperties.qml, src/qml/BrowserPanel.qml, src/qml/Changelog.qml, src/qml/CodeReader.qml, src/qml/EmbeddedFeatureForm.qml, src/qml/FeatureForm.qml, src/qml/LayerTreeItemProperties.qml, src/qml/LocatorSettings.qml, src/qml/NavigationBar.qml, src/qml/NotesItem.qml, src/qml/PluginManagerSettings.qml, src/qml/PositioningDeviceSettings.qml, src/qml/QFieldAudioRecorder.qml, src/qml/QFieldCloudDeltaHistory.qml, src/qml/QFieldCloudPackageLayersFeedback.qml, src/qml/QFieldSettings.qml, src/qml/RelationCombobox.qml, src/qml/TemporalProperties.qml, src/qml/TrackerSettings.qml, src/qml/editorwidgets/ValueMap.qml, src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml, src/qml/editorwidgets/relationeditors/relation_editor.qml, src/qml/imports/Theme/QfPopup.qml, src/qml/imports/Theme/Theme.qml, src/qml/imports/Theme/qmldir, src/qml/qgismobileapp.qml, src/qml/qml.qrc
The days of 90 degree angled corners are gone. Adding a bit of roundness to our popups makes us look a lot better in circa 2025 OSes.
The PR also reworks horizontal margins for popups to get us a bit of extra content space, and makes the feature form constraints feedback look a lot nicer.
=> Rounded popup for nice visual improvement and harmony

src/core/qfieldcloud/qfieldcloudconnection.cpp, src/core/qfieldcloud/qfieldcloudconnection.h, src/core/utils/qfieldcloudutils.cpp, src/core/utils/qfieldcloudutils.h, src/qml/QFieldCloudScreen.qml, src/qml/QFieldLocalDataPickerScreen.qml, src/qml/qgismobileapp.qml
This pull request enhances **QFieldCloud** by enabling access to the Project folder view without opening the project. It also adds **confirmation** when deleting projects and introduces **file viewing** directly from the folder view.
* **Folder view:** Added support for accessing the folder view independently of the project's open state.
* **Confirmation:** Implemented a delete confirmation dialog to prevent accidental deletions.
* **File viewing:** Introduced a "View file" option for directly previewing files.
[Screencast From 2025-09-13 16-46-47.webm](https://github.com/user-attachments/assets/6484a58f-ab1a-400c-8df7-67d56d1399de)
=> Allow QFieldCloud to access Project folder view without opening Project

src/qml/PluginManagerSettings.qml
Fixes an issue where the available plugins are not refreshed when switching to the "Available" tab in the plugin manager. It ensures the plugin list is refreshed only when the "Available" tab is selected and the plugins haven't been fetched yet.
[Screencast From 2025-10-03 19-08-33.webm](https://github.com/user-attachments/assets/cb18b78b-205c-43ff-9cf1-9b9719cef37c)
=> Fixes plugin refresh on tab switch

src/core/qfieldcloud/deltafilewrapper.cpp
@suricactus , spotted a typo that caused consecutive geometry-only delta patches to kill the merged patch. 
Context: https://github.com/opengisch/QField/issues/6583#issuecomment-3364517069
=> Fix delta file wrapper typo leading to failure to merge geometry-only patches

src/core/utils/qfieldcloudutils.cpp
Ensures that the project ID is correctly extracted from the file path by using the canonical file path for the cloud directory. This resolves potential issues caused by symbolic links or relative paths, ensuring accurate project identification.
Previously, project ID detection could fail on Android devices because the same directory could be referenced via different paths (e.g., `/data/user/0/...` vs `/data/data/...`) due to symbolic links. By canonicalizing both the input file path and the cloud directory, we ensure consistent matching and reliable extraction of the project ID.
-   Uses `QFileInfo::canonicalFilePath()` to obtain the absolute path of the cloud directory, ensuring consistent and correct path comparison.
=> Ensures correct project ID extraction

src/core/qfieldcloud/qfieldcloudproject.cpp
For the "hey, there are changes on the server, synchronize!" indicator to be useful for most use cases, we should *not* fall into an outdated state when we were up-to-date and have just pushed _our own changes_ onto the server.
=> Avoid falling into an outdated state when up-to-date and pushing changes onto the sever

src/core/pluginmanager.cpp
=> Fix crash when installing from an invalid plugin URL
